MLIR: lib/Dialect/Affine/Analysis/AffineStructures.cpp File Reference
AffineStructures.cpp File Reference
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Analysis/Presburger/LinearTransform.h"
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Analysis/Presburger/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "affine-structures"
Functions
static LogicalResult getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineValueConstraints *localVarCst)
static bool areIdsAligned (const FlatAffineValueConstraints &a, const FlatAffineValueConstraints &b)
Checks if two constraint systems are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints &cst, unsigned start, unsigned end)
Checks if the SSA values associated with cst's identifiers in range [start, end) are unique.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints &cst)
Checks if the SSA values associated with cst's identifiers are unique.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints &cst, IdKind kind)
Checks if the SSA values associated with cst's identifiers of kind kind are unique.
static void mergeAndAlignIds (unsigned offset, FlatAffineValueConstraints *a, FlatAffineValueConstraints *b)
Merge and align the identifiers of A and B starting at 'offset', so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with A's original identifiers appearing first followed by any of B's identifiers that didn't appear in A.
static void turnSymbolIntoDim (FlatAffineValueConstraints *cst, Value id)
static bool detectAsMod (const FlatAffineValueConstraints &cst, unsigned pos, int64_t lbConst, int64_t ubConst, SmallVectorImpl< AffineExpr > &memo, MLIRContext *context)
static bool detectAsFloorDiv (const FlatAffineValueConstraints &cst, unsigned pos, MLIRContext *context, SmallVectorImpl< AffineExpr > &exprs)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant) given the initial set of expressions in exprs.
static LogicalResult computeLocalVars (const FlatAffineValueConstraints &cst, SmallVectorImpl< AffineExpr > &memo, MLIRContext *context)
Compute an explicit representation for local vars.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-structures"
Definition at line 30 of file AffineStructures.cpp.
Function Documentation
areIdsAligned()
static bool areIdsAligned (const FlatAffineValueConstraints & a, const FlatAffineValueConstraints & b) static
Checks if two constraint systems are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
Definition at line 325 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::getMaybeValues(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::presburger::IntegerRelation::getNumIds(), and mlir::presburger::IntegerRelation::getNumSymbolIds().
Referenced by mlir::FlatAffineValueConstraints::areIdsAlignedWithOther(), mergeAndAlignIds(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
areIdsUnique() [1/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints & cst, unsigned start, unsigned end) static
Checks if the SSA values associated with cst's identifiers in range [start, end) are unique.
Definition at line 342 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::getMaybeValues(), and mlir::presburger::IntegerRelation::getNumIds().
Referenced by areIdsUnique(), mergeAndAlignIds(), and mlir::FlatAffineValueConstraints::mergeSymbolIds().
areIdsUnique() [2/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints & cst) static
Checks if the SSA values associated with cst's identifiers are unique.
Definition at line 362 of file AffineStructures.cpp.
References areIdsUnique(), and mlir::presburger::IntegerRelation::getNumIds().
areIdsUnique() [3/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints & cst, IdKind kind) static
Checks if the SSA values associated with cst's identifiers of kind kind are unique.
Definition at line 369 of file AffineStructures.cpp.
computeLocalVars()
static LogicalResult computeLocalVars (const FlatAffineValueConstraints & cst, SmallVectorImpl< AffineExpr > & memo, MLIRContext * context) static
Compute an explicit representation for local vars.
For all systems coming from MLIR integer sets, maps, or expressions where local vars were introduced to model floordivs and mods, this always succeeds.
Definition at line 1408 of file AffineStructures.cpp.
References detectAsFloorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::presburger::IntegerRelation::getNumLocalIds(), mlir::presburger::IntegerRelation::getNumSymbolIds(), and mlir::success().
Referenced by mlir::FlatAffineValueConstraints::getAsIntegerSet(), and mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap().
detectAsFloorDiv()
static bool detectAsFloorDiv (const FlatAffineValueConstraints & cst, unsigned pos, MLIRContext * context, SmallVectorImpl< AffineExpr > & exprs) static
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant) given the initial set of expressions in exprs.
If it can be, the corresponding position in exprs is set as the detected affine expr. For eg: 4q <= i + j <= 4q + 3 <=> q = (i + j) floordiv 4. An equality can also yield a floordiv: eg. 4q = i + j <=> q = (i + j) floordiv 4. 32q + 28 <= i <= 32q + 31 => q = i floordiv 32.
Definition at line 847 of file AffineStructures.cpp.
References mlir::presburger::computeSingleVarRepr(), mlir::getAffineConstantExpr(), and mlir::presburger::IntegerRelation::getNumIds().
Referenced by computeLocalVars(), and mlir::FlatAffineValueConstraints::getSliceBounds().
detectAsMod()
static bool detectAsMod (const FlatAffineValueConstraints & cst, unsigned pos, int64_t lbConst, int64_t ubConst, SmallVectorImpl< AffineExpr > & memo, MLIRContext * context) static
Definition at line 736 of file AffineStructures.cpp.
References mlir::presburger::IntegerRelation::atEq(), mlir::AffineExpr::dyn_cast(), mlir::floorDiv(), mlir::getAffineConstantExpr(), mlir::presburger::IntegerRelation::getConstantBound(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumDimAndSymbolIds(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumIds(), mlir::presburger::IntegerRelation::getNumSymbolIds(), and mlir::simplifyAffineExpr().
Referenced by mlir::FlatAffineValueConstraints::getSliceBounds().
getFlattenedAffineExprs()
static LogicalResult getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineValueConstraints * localVarCst) static
Definition at line 72 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::clearAndCopyFrom(), mlir::failure(), mlir::FlatAffineValueConstraints::reset(), and mlir::success().
Referenced by mlir::getFlattenedAffineExprs().
mergeAndAlignIds()
static void mergeAndAlignIds (unsigned offset, FlatAffineValueConstraints * a, FlatAffineValueConstraints * b) static
Merge and align the identifiers of A and B starting at 'offset', so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with A's original identifiers appearing first followed by any of B's identifiers that didn't appear in A.
Local identifiers in B that have the same division representation as local identifiers in A are merged into one.
Definition at line 389 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::appendDimId(), areIdsAligned(), areIdsUnique(), mlir::FlatAffineValueConstraints::findId(), mlir::FlatAffineValueConstraints::getMaybeValues(), mlir::presburger::IntegerRelation::getNumDimAndSymbolIds(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::FlatAffineValueConstraints::getValue(), mlir::FlatAffineValueConstraints::getValues(), mlir::FlatAffineValueConstraints::insertDimId(), mlir::presburger::IntegerRelation::mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::FlatAffineValueConstraints::mergeAndAlignIdsWithOther(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
turnSymbolIntoDim()
static void turnSymbolIntoDim (FlatAffineValueConstraints * cst, Value id) static
Definition at line 502 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::findId(), mlir::presburger::IntegerRelation::getNumDimAndSymbolIds(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::presburger::IntegerRelation::getNumSymbolIds(), mlir::presburger::IntegerRelation::setDimSymbolSeparation(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims().