MLIR: lib/Analysis/Presburger/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Analysis/Presburger/Utils.h"
#include "mlir/Analysis/Presburger/IntegerRelation.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/MathExtras.h"
Functions
static void normalizeDivisionByGCD (SmallVectorImpl< int64_t > &dividend, unsigned &divisor)
Normalize a division's dividend and the divisor by their GCD.
static LogicalResult getDivRepr (const IntegerRelation &cst, unsigned pos, unsigned ubIneq, unsigned lbIneq, SmallVector< int64_t, 8 > &expr, unsigned &divisor)
Check if the pos^th identifier can be represented as a division using upper bound inequality at position ubIneq and lower bound inequality at position lbIneq.
static LogicalResult getDivRepr (const IntegerRelation &cst, unsigned pos, unsigned eqInd, SmallVector< int64_t, 8 > &expr, unsigned &divisor)
Check if the pos^th identifier can be represented as a division using equality at position eqInd.
static bool checkExplicitRepresentation (const IntegerRelation &cst, ArrayRef< bool > foundRepr, ArrayRef< int64_t > dividend, unsigned pos)
Function Documentation
checkExplicitRepresentation()
static bool checkExplicitRepresentation (const IntegerRelation & cst, ArrayRef< bool > foundRepr, ArrayRef< int64_t > dividend, unsigned pos) static
Definition at line 185 of file Utils.cpp.
References mlir::presburger::IntegerRelation::getNumIds().
Referenced by mlir::presburger::computeSingleVarRepr().
getDivRepr() [1/2]
static LogicalResult getDivRepr (const IntegerRelation & cst, unsigned pos, unsigned ubIneq, unsigned lbIneq, SmallVector< int64_t, 8 > & expr, unsigned & divisor) static
Check if the pos^th identifier can be represented as a division using upper bound inequality at position ubIneq and lower bound inequality at position lbIneq.
Let id be the pos^th identifier, then id is equivalent to expr floordiv divisor if there are constraints of the form: 0 <= expr - divisor * id <= divisor - 1 Rearranging, we have: divisor * id - expr + (divisor - 1) >= 0 <– Lower bound for 'id' -divisor * id + expr >= 0 <– Upper bound for 'id'
For example: 32*k >= 16*i + j - 31 <– Lower bound for 'k' 32*k <= 16*i + j <– Upper bound for 'k' expr = 16*i + j, divisor = 32 k = (16*i + j) floordiv 32
4q >= i + j - 2 <– Lower bound for 'q' 4q <= i + j + 1 <– Upper bound for 'q' expr = i + j + 1, divisor = 4 q = (i + j + 1) floordiv 4 This function also supports detecting divisions from bounds that are strictly tighter than the division bounds described above, since tighter bounds imply the division bounds. For example: 4q - i - j + 2 >= 0 <– Lower bound for 'q' -4q + i + j >= 0 <– Tight upper bound for 'q'
To extract floor divisions with tighter bounds, we assume that that the constraints are of the form: c <= expr - divisior * id <= divisor - 1, where 0 <= c <= divisor - 1 Rearranging, we have: divisor * id - expr + (divisor - 1) >= 0 <– Lower bound for 'id' -divisor * id + expr - c >= 0 <– Upper bound for 'id'
If successful, expr is set to dividend of the division and divisor is set to the denominator of the division. The final division expression is normalized by GCD.
Definition at line 90 of file Utils.cpp.
References mlir::presburger::IntegerRelation::atIneq(), mlir::failure(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumIds(), mlir::presburger::IntegerRelation::getNumInequalities(), normalizeDivisionByGCD(), and mlir::success().
Referenced by mlir::presburger::computeSingleVarRepr().
getDivRepr() [2/2]
static LogicalResult getDivRepr (const IntegerRelation & cst, unsigned pos, unsigned eqInd, SmallVector< int64_t, 8 > & expr, unsigned & divisor) static
Check if the pos^th identifier can be represented as a division using equality at position eqInd.
For example: 32*k == 16*i + j - 31 <– eqInd for 'k' expr = 16*i + j - 31, divisor = 32 k = (16*i + j - 31) floordiv 32
If successful, expr is set to dividend of the division and divisor is set to the denominator of the division. The final division expression is normalized by GCD.
Definition at line 154 of file Utils.cpp.
References mlir::presburger::IntegerRelation::atEq(), mlir::failure(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumIds(), normalizeDivisionByGCD(), and mlir::success().
normalizeDivisionByGCD()
static void normalizeDivisionByGCD (SmallVectorImpl< int64_t > & dividend, unsigned & divisor) static
Normalize a division's dividend and the divisor by their GCD.
For example: if the dividend and divisor are [2,0,4] and 4 respectively, they get normalized to [1,0,2] and 2.
Definition at line 24 of file Utils.cpp.
References mlir::floorDiv().
Referenced by getDivRepr().