MLIR: lib/Dialect/Arithmetic/IR/ArithmeticOps.cpp File Reference
ArithmeticOps.cpp File Reference
#include <utility>
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/APSInt.h"
#include "ArithmeticCanonicalization.inc"
#include "mlir/Dialect/Arithmetic/IR/ArithmeticOps.cpp.inc"
#include "mlir/Dialect/Arithmetic/IR/ArithmeticOpsEnums.cpp.inc"
Classes
class CmpFIntToFPConst
struct SelectI1Simplify
struct SelectToExtUI
Macros
#define GET_OP_CLASSES
Typedefs
template<typename... Types>
using type_list = std::tuple< Types... > *
Functions
static IntegerAttr addIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static IntegerAttr subIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred)
static APInt signedCeilNonnegInputs (const APInt &a, const APInt &b, bool &overflow)
template<typename... ShapedTypes, typename... ElementTypes>
static Type getUnderlyingType (Type type, type_list< ShapedTypes... >, type_list< ElementTypes... >)
Returns a non-null type only if the provided type is one of the allowed types or one of the allowed shaped types of the allowed types.
template<typename... ElementTypes>
static Type getTypeIfLike (Type type)
Get allowed underlying types for vectors and tensors.
template<typename... ElementTypes>
static Type getTypeIfLikeOrMemRef (Type type)
Get allowed underlying types for vectors, tensors, and memrefs.
static bool areValidCastInputsAndOutputs (TypeRange inputs, TypeRange outputs)
template<typename ValType , typename Op >
static LogicalResult verifyExtOp (Op op)
template<typename ValType , typename Op >
static LogicalResult verifyTruncateOp (Op op)
template<template< typename > class WidthComparator, typename... ElementTypes>
static bool checkWidthChangeCast (TypeRange inputs, TypeRange outputs)
Validate a cast that changes the width of a type.
template<typename From , typename To >
static bool checkIntFloatCast (TypeRange inputs, TypeRange outputs)
static Type getI1SameShape (Type type)
Return the type of the same shape (scalar, vector or tensor) containing i1.
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate)
Returns true if the predicate is true for two equal operands.
static Attribute getBoolAttribute (Type type, MLIRContext *ctx, bool value)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1999 of file ArithmeticOps.cpp.
Typedef Documentation
type_list
template<typename... Types> using type_list = std::tuple<Types...> *
Definition at line 761 of file ArithmeticOps.cpp.
Function Documentation
addIntegerAttrs()
static IntegerAttr addIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 29 of file ArithmeticOps.cpp.
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate) static
Returns true if the predicate is true for two equal operands.
Definition at line 1259 of file ArithmeticOps.cpp.
Referenced by getBoolAttribute().
areValidCastInputsAndOutputs()
static bool areValidCastInputsAndOutputs (TypeRange inputs, TypeRange outputs) static
Definition at line 794 of file ArithmeticOps.cpp.
References mlir::succeeded(), and mlir::verifyCompatibleShapes().
Referenced by checkIntFloatCast(), and checkWidthChangeCast().
checkIntFloatCast()
template<typename From , typename To > static bool checkIntFloatCast (TypeRange inputs, TypeRange outputs) static
Definition at line 1013 of file ArithmeticOps.cpp.
References mlir::RewritePatternSet::add(), areValidCastInputsAndOutputs(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::FloatType::getFloatSemantics(), and mlir::FloatType::getWidth().
checkWidthChangeCast()
template<template< typename > class WidthComparator, typename... ElementTypes> static bool checkWidthChangeCast (TypeRange inputs, TypeRange outputs) static
Validate a cast that changes the width of a type.
Definition at line 831 of file ArithmeticOps.cpp.
References areValidCastInputsAndOutputs(), and getTypeIfLike().
getBoolAttribute()
static Attribute getBoolAttribute (Type type, MLIRContext * ctx, bool value) static
Definition at line 1277 of file ArithmeticOps.cpp.
References applyCmpPredicateToEqualOperands(), mlir::Type::dyn_cast_or_null(), mlir::DenseElementsAttr::get(), mlir::BoolAttr::get(), mlir::m_Zero(), and mlir::matchPattern().
getI1SameShape()
static Type getI1SameShape (Type type) static
Return the type of the same shape (scalar, vector or tensor) containing i1.
Definition at line 1213 of file ArithmeticOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getContext(), mlir::Type::isa(), and vectorType().
Referenced by SelectToExtUI::matchAndRewrite().
getTypeIfLike()
template<typename... ElementTypes> static Type getTypeIfLike (Type type) static
Get allowed underlying types for vectors and tensors.
Definition at line 781 of file ArithmeticOps.cpp.
References getUnderlyingType().
Referenced by checkWidthChangeCast().
getTypeIfLikeOrMemRef()
template<typename... ElementTypes> static Type getTypeIfLikeOrMemRef (Type type) static
Get allowed underlying types for vectors, tensors, and memrefs.
Definition at line 788 of file ArithmeticOps.cpp.
References getUnderlyingType().
getUnderlyingType()
template<typename... ShapedTypes, typename... ElementTypes> static Type getUnderlyingType (Type type, type_list< ShapedTypes... > , type_list< ElementTypes... >) static
Returns a non-null type only if the provided type is one of the allowed types or one of the allowed shaped types of the allowed types.
Returns the element type if a valid shaped type is provided.
Definition at line 767 of file ArithmeticOps.cpp.
References mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by getTypeIfLike(), and getTypeIfLikeOrMemRef().
invertPredicate()
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred) static
Definition at line 70 of file ArithmeticOps.cpp.
References mlir::Type::cast(), mlir::Attribute::getType(), mlir::arith::invertPredicate(), mlir::Attribute::isa(), mlir::Type::isa(), mlir::success(), value, and mlir::verify().
signedCeilNonnegInputs()
static APInt signedCeilNonnegInputs (const APInt & a, const APInt & b, bool & overflow) static
Definition at line 310 of file ArithmeticOps.cpp.
References mlir::RewritePatternSet::add(), mlir::presburger::ceil(), mlir::Builder::getZeroAttr(), mlir::m_ConstantInt(), mlir::m_NegInfFloat(), mlir::m_NegZeroFloat(), mlir::m_One(), mlir::m_OneFloat(), mlir::m_PosInfFloat(), mlir::m_PosZeroFloat(), mlir::m_Zero(), and mlir::matchPattern().
subIntegerAttrs()
static IntegerAttr subIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 36 of file ArithmeticOps.cpp.
verifyExtOp()
template<typename ValType , typename Op > static LogicalResult verifyExtOp (Op op) static
Definition at line 805 of file ArithmeticOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), and mlir::success().
verifyTruncateOp()
template<typename ValType , typename Op > static LogicalResult verifyTruncateOp (Op op) static
Definition at line 818 of file ArithmeticOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), and mlir::success().