MLIR: lib/Conversion/ArithmeticToSPIRV/ArithmeticToSPIRV.cpp File Reference
ArithmeticToSPIRV.cpp File Reference
#include "mlir/Conversion/ArithmeticToSPIRV/ArithmeticToSPIRV.h"
#include "../PassDetail.h"
#include "../SPIRVCommon/Pattern.h"
#include "mlir/Conversion/FuncToSPIRV/FuncToSPIRV.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "arith-to-spirv-pattern"
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder)
Converts the given srcAttr into a boolean attribute if it holds an integral value.
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static bool isBoolScalarOrVector (Type type)
Returns true if the given type is a boolean scalar or vector type.
template<typename SignedAbsOp >
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder &builder)
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arith-to-spirv-pattern"
Definition at line 19 of file ArithmeticToSPIRV.cpp.
DISPATCH [1/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(op, op.getResult().getType(),         \
                                         adaptor.getLhs(), adaptor.getRhs());  \
    return success();
DISPATCH [2/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    if (spirvOp::template hasTrait<OpTrait::spirv::UnsignedOp>() &&            \
        operandType != this->getTypeConverter()->convertType(operandType)) {   \
      return op.emitError(                                                     \
          "bitwidth emulation is not implemented yet on unsigned op");         \
    }                                                                          \
    rewriter.replaceOpWithNewOp<spirvOp>(op, op.getResult().getType(),         \
                                         adaptor.getLhs(), adaptor.getRhs());  \
    return success();
DISPATCH [3/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(op, op.getResult().getType(),         \
                                         adaptor.getLhs(), adaptor.getRhs());  \
    return success();
Function Documentation
convertBoolAttr()
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder) static
Converts the given srcAttr into a boolean attribute if it holds an integral value.
Returns null attribute if conversion fails.
Definition at line 211 of file ArithmeticToSPIRV.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Builder::getBoolAttr().
Referenced by isBoolScalarOrVector().
convertFloatAttr()
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if dstType is not 32-bit or conversion fails.
Definition at line 248 of file ArithmeticToSPIRV.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::Type::isF32().
Referenced by isBoolScalarOrVector().
convertIntegerAttr()
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if conversion fails.
Definition at line 221 of file ArithmeticToSPIRV.cpp.
References mlir::Builder::getIntegerAttr().
Referenced by isBoolScalarOrVector().
emulateSignedRemainder()
template<typename SignedAbsOp > static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder & builder) static
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Note that this is needed for Vulkan. Per the Vulkan's SPIR-V environment spec, "for the OpSRem and OpSMod instructions, if either operand is negative the result is undefined." So we cannot directly use spv.SRem/spv.SMod if either operand can be negative. Emulate it via spv.UMod.
Definition at line 439 of file ArithmeticToSPIRV.cpp.
isBoolScalarOrVector()
static bool isBoolScalarOrVector (Type type) static
Returns true if the given type is a boolean scalar or vector type.
Definition at line 270 of file ArithmeticToSPIRV.cpp.
References mlir::Attribute::cast(), mlir::Type::cast(), convertBoolAttr(), convertFloatAttr(), convertIntegerAttr(), mlir::Type::dyn_cast(), mlir::failure(), mlir::DenseElementsAttr::get(), getElementType(), mlir::Attribute::getType(), mlir::Type::isa(), mlir::Type::isInteger(), mlir::Type::isIntOrIndexOrFloat(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().