MLIR: lib/Conversion/ArithmeticToLLVM/ArithmeticToLLVM.cpp File Reference
ArithmeticToLLVM.cpp File Reference
#include "mlir/Conversion/ArithmeticToLLVM/ArithmeticToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/VectorPattern.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/TypeUtilities.h"
Functions
template<typename LLVMPredType , typename PredType >
static LLVMPredType convertCmpPredicate (PredType pred)
Function Documentation
convertCmpPredicate()
template<typename LLVMPredType , typename PredType > static LLVMPredType convertCmpPredicate (PredType pred) static
Definition at line 159 of file ArithmeticToLLVM.cpp.
References mlir::applyPartialConversion(), mlir::OpBuilder::create(), mlir::failed(), mlir::LLVM::detail::handleMultidimensionalVectors(), mlir::kDeriveIndexBitwidthFromDataLayout, mlir::ConversionPatternRewriter::notifyMatchFailure(), options, mlir::LowerToLLVMOptions::overrideIndexBitwidth(), mlir::arith::populateArithmeticToLLVMConversionPatterns(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and vectorType().