MLIR: lib/Dialect/Async/Transforms/AsyncParallelFor.cpp File Reference
AsyncParallelFor.cpp File Reference
#include <utility>
#include "PassDetail.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/Async/Passes.h"
#include "mlir/Dialect/Async/Transforms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/RegionUtils.h"
Macros
#define DEBUG_TYPE "async-parallel-for"
Functions
template<typename ValueRange >
static SmallVector< IntegerAttr > integerConstants (ValueRange values)
static SmallVector< Value > delinearize (ImplicitLocOpBuilder &b, Value index, ArrayRef< Value > tripCounts)
static ParallelComputeFunctionType getParallelComputeFunctionType (scf::ParallelOp op, PatternRewriter &rewriter)
static ParallelComputeFunction createParallelComputeFunction (scf::ParallelOp op, const ParallelComputeFunctionBounds &bounds, unsigned numBlockAlignedInnerLoops, PatternRewriter &rewriter)
static func::FuncOp createAsyncDispatchFunction (ParallelComputeFunction &computeFunc, PatternRewriter &rewriter)
static void doAsyncDispatch (ImplicitLocOpBuilder &b, PatternRewriter &rewriter, ParallelComputeFunction &parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > &tripCounts)
static void doSequentialDispatch (ImplicitLocOpBuilder &b, PatternRewriter &rewriter, ParallelComputeFunction &parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > &tripCounts)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "async-parallel-for"
Definition at line 33 of file AsyncParallelFor.cpp.
Function Documentation
createAsyncDispatchFunction()
static func::FuncOp createAsyncDispatchFunction (ParallelComputeFunction & computeFunc, PatternRewriter & rewriter) static
Definition at line 459 of file AsyncParallelFor.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Builder::getContext(), mlir::Builder::getFunctionType(), mlir::Builder::getIndexType(), mlir::OpBuilder::getListener(), mlir::SymbolTable::insert(), mlir::OpBuilder::Listener::notifyOperationInserted(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by doAsyncDispatch().
createParallelComputeFunction()
static ParallelComputeFunction createParallelComputeFunction (scf::ParallelOp op, const ParallelComputeFunctionBounds & bounds, unsigned numBlockAlignedInnerLoops, PatternRewriter & rewriter) static
Definition at line 249 of file AsyncParallelFor.cpp.
References mlir::OpBuilder::clone(), mlir::Operation::create(), mlir::ImplicitLocOpBuilder::create(), mlir::delinearize(), mlir::Block::getArguments(), mlir::OpBuilder::getListener(), getParallelComputeFunctionType(), mlir::SymbolTable::insert(), mlir::BlockAndValueMapping::map(), and mlir::OpBuilder::Listener::notifyOperationInserted().
Referenced by doSequentialDispatch().
delinearize()
static SmallVector<Value> delinearize (ImplicitLocOpBuilder & b, Value index, ArrayRef< Value > tripCounts) static
Definition at line 195 of file AsyncParallelFor.cpp.
References mlir::ImplicitLocOpBuilder::create().
doAsyncDispatch()
static void doAsyncDispatch (ImplicitLocOpBuilder & b, PatternRewriter & rewriter, ParallelComputeFunction & parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > & tripCounts) static
Definition at line 575 of file AsyncParallelFor.cpp.
References mlir::ImplicitLocOpBuilder::create(), and createAsyncDispatchFunction().
Referenced by doSequentialDispatch().
doSequentialDispatch()
static void doSequentialDispatch (ImplicitLocOpBuilder & b, PatternRewriter & rewriter, ParallelComputeFunction & parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > & tripCounts) static
Definition at line 649 of file AsyncParallelFor.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::async::cloneConstantsIntoTheRegion(), mlir::ImplicitLocOpBuilder::create(), mlir::OpBuilder::create(), createParallelComputeFunction(), doAsyncDispatch(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::Builder::getF32Type(), mlir::Builder::getI32Type(), mlir::Builder::getIndexType(), integerConstants(), mlir::async::populateAsyncParallelForPatterns(), and mlir::success().
getParallelComputeFunctionType()
static ParallelComputeFunctionType getParallelComputeFunctionType (scf::ParallelOp op, PatternRewriter & rewriter) static
Definition at line 212 of file AsyncParallelFor.cpp.
References mlir::Builder::getFunctionType(), mlir::Builder::getIndexType(), and mlir::getUsedValuesDefinedAbove().
Referenced by createParallelComputeFunction().
integerConstants()
template<typename ValueRange > static SmallVector<IntegerAttr> integerConstants (ValueRange values) static
Definition at line 186 of file AsyncParallelFor.cpp.
References mlir::m_Constant(), and mlir::matchPattern().
Referenced by doSequentialDispatch().