MLIR: lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp File Reference
BufferizableOpInterface.cpp File Reference
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define DEBUG_TYPE "bufferizable-op-interface"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << (X))
Functions
static void setInsertionPointAfter (OpBuilder &b, Value value)
static void ensureToMemrefOpIsValid (Value tensor, Type memrefType)
static FailureOr< Value > createAlloc (OpBuilder &b, Location loc, MemRefType type, ValueRange dynShape, const BufferizationOptions &options)
Create a memref allocation with the given type and dynamic extents.
static MemRefType getAllocationTypeAndShape (OpBuilder &b, Location loc, Value shapedValue, SmallVectorImpl< Value > &dynShape)
Compute the type of the memref to use for allocating the buffer for shapedValue.
static Value createBufferAllocation (OpBuilder &b, Location loc, MemRefType type, ValueRange dynShape, bool skipDealloc)
Variables
static const char * kBufferAllocationAttr = "bufferization.allocation"
Attribute name used to mark allocs that are created by the bufferization.
static const char * kSkipDeallocAttr = "bufferization.skip_dealloc"
Attribute name used to mark allocs that should not be deallocated.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 30 of file BufferizableOpInterface.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "bufferizable-op-interface"
Definition at line 29 of file BufferizableOpInterface.cpp.
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << (X))
Definition at line 31 of file BufferizableOpInterface.cpp.
Function Documentation
createAlloc()
static FailureOr<Value> createAlloc (OpBuilder & b, Location loc, MemRefType type, ValueRange dynShape, const BufferizationOptions & options) static
Create a memref allocation with the given type and dynamic extents.
Definition at line 422 of file BufferizableOpInterface.cpp.
References mlir::bufferization::BufferizationOptions::allocationFn, mlir::bufferization::BufferizationOptions::bufferAlignment, mlir::OpBuilder::create(), and mlir::Builder::getI64IntegerAttr().
Referenced by mlir::bufferization::BufferizationState::BufferizationState(), mlir::bufferization::createAllocDeallocOps(), and mlir::bufferization::BufferizationState::getBuffer().
createBufferAllocation()
static Value createBufferAllocation (OpBuilder & b, Location loc, MemRefType type, ValueRange dynShape, bool skipDealloc) static
Definition at line 486 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getUnitAttr(), kBufferAllocationAttr, kSkipDeallocAttr, and mlir::Operation::setAttr().
Referenced by mlir::bufferization::BufferizationState::createAlloc().
ensureToMemrefOpIsValid()
static void ensureToMemrefOpIsValid (Value tensor, Type memrefType) static
Definition at line 243 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), and mlir::Value::getType().
Referenced by mlir::bufferization::lookupBuffer().
getAllocationTypeAndShape()
static MemRefType getAllocationTypeAndShape (OpBuilder & b, Location loc, Value shapedValue, SmallVectorImpl< Value > & dynShape) static
Compute the type of the memref to use for allocating the buffer for shapedValue.
Also returns (by reference in dynShape), the value for the dynamic dimensions in the returned memref type.
Definition at line 451 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), mlir::bufferization::getContiguousMemRefType(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::Type::isa(), and mlir::succeeded().
Referenced by mlir::bufferization::BufferizationState::createAlloc().
setInsertionPointAfter()
static void setInsertionPointAfter (OpBuilder & b, Value value) static
Definition at line 104 of file BufferizableOpInterface.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::bufferization::BufferizationState::getBuffer(), mlir::bufferization::lookupBuffer(), and mlir::OpBuilder::setInsertionPointAfterValue().
Variable Documentation
kBufferAllocationAttr
const char* kBufferAllocationAttr = "bufferization.allocation" static
Attribute name used to mark allocs that are created by the bufferization.
Definition at line 42 of file BufferizableOpInterface.cpp.
Referenced by mlir::bufferization::createAllocDeallocOps(), createBufferAllocation(), and mlir::bufferization::hoistBufferAllocations().
kSkipDeallocAttr
const char* kSkipDeallocAttr = "bufferization.skip_dealloc" static
Attribute name used to mark allocs that should not be deallocated.
Definition at line 45 of file BufferizableOpInterface.cpp.
Referenced by mlir::bufferization::createAllocDeallocOps(), and createBufferAllocation().