MLIR: lib/Dialect/Bufferization/Transforms/BufferResultsToOutParams.cpp File Reference
BufferResultsToOutParams.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
Functions
static void updateFuncOp (func::FuncOp func, SmallVectorImpl< BlockArgument > &appendedEntryArgs)
static void updateReturnOps (func::FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs)
static LogicalResult updateCalls (ModuleOp module)
Function Documentation
updateCalls()
static LogicalResult updateCalls (ModuleOp module) static
Definition at line 85 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Value::getType(), updateFuncOp(), and updateReturnOps().
updateFuncOp()
static void updateFuncOp (func::FuncOp func, SmallVectorImpl< BlockArgument > & appendedEntryArgs) static
Definition at line 21 of file BufferResultsToOutParams.cpp.
References mlir::detail::enumerate().
Referenced by updateCalls().
updateReturnOps()
static void updateReturnOps (func::FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs) static
Definition at line 63 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), and mlir::Operation::erase().
Referenced by updateCalls().