MLIR: include/mlir-c/Interfaces.h File Reference
Interfaces.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Typedefs
typedef void(* MlirTypesCallback) (intptr_t, MlirType *, void *)
These callbacks are used to return multiple types from functions while transferring ownership to the caller.
Functions
MLIR_CAPI_EXPORTED bool mlirOperationImplementsInterface (MlirOperation operation, MlirTypeID interfaceTypeID)
Returns true if the given operation implements an interface identified by its TypeID.
MLIR_CAPI_EXPORTED bool mlirOperationImplementsInterfaceStatic (MlirStringRef operationName, MlirContext context, MlirTypeID interfaceTypeID)
Returns true if the operation identified by its canonical string name implements the interface identified by its TypeID in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirInferTypeOpInterfaceTypeID ()
Returns the interface TypeID of the InferTypeOpInterface.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirInferTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue *operands, MlirAttribute attributes, intptr_t nRegions, MlirRegion *regions, MlirTypesCallback callback, void *userData)
Infers the return types of the operation identified by its canonical given the arguments that will be supplied to its generic builder.
Typedef Documentation
MlirTypesCallback
typedef void(* MlirTypesCallback) (intptr_t, MlirType *, void *)
These callbacks are used to return multiple types from functions while transferring ownership to the caller.
The first argument is the number of consecutive elements pointed to by the second argument. The third argument is an opaque pointer forwarded to the callback by the caller.
Definition at line 51 of file Interfaces.h.
Function Documentation
mlirInferTypeOpInterfaceInferReturnTypes()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirInferTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue * operands, MlirAttribute attributes, intptr_t nRegions, MlirRegion * regions, MlirTypesCallback callback, void * userData)
Infers the return types of the operation identified by its canonical given the arguments that will be supplied to its generic builder.
Calls callback with the types of inferred arguments, potentially several times, on success. Returns failure otherwise.
Definition at line 38 of file Interfaces.cpp.
References MlirStringRef::data, mlir::failed(), MlirStringRef::length, mlir::RegisteredOperationName::lookup(), mlirAttributeIsNull(), mlirLocationIsNull(), mlirLogicalResultFailure(), mlirLogicalResultSuccess(), unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyInferTypeOpInterface::inferReturnTypes().
mlirInferTypeOpInterfaceTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirInferTypeOpInterfaceTypeID ()
Returns the interface TypeID of the InferTypeOpInterface.
Definition at line 34 of file Interfaces.cpp.
References wrap().
mlirOperationImplementsInterface()
MLIR_CAPI_EXPORTED bool mlirOperationImplementsInterface (MlirOperation operation, MlirTypeID interfaceTypeID)
Returns true if the given operation implements an interface identified by its TypeID.
Definition at line 19 of file Interfaces.cpp.
References unwrap().
Referenced by mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::PyConcreteOpInterface().
mlirOperationImplementsInterfaceStatic()
MLIR_CAPI_EXPORTED bool mlirOperationImplementsInterfaceStatic (MlirStringRef operationName, MlirContext context, MlirTypeID interfaceTypeID)
Returns true if the operation identified by its canonical string name implements the interface identified by its TypeID in the given context.
Note that interfaces may be attached to operations in some contexts and not others.
Definition at line 26 of file Interfaces.cpp.
References MlirStringRef::data, MlirStringRef::length, mlir::RegisteredOperationName::lookup(), and unwrap().
Referenced by mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::PyConcreteOpInterface().