MLIR: include/mlir-c/Registration.h File Reference
Registration.h File Reference
#include "mlir-c/IR.h"
Classes
struct MlirDialectHandle
Macros
#define MLIR_DECLARE_CAPI_DIALECT_REGISTRATION(Name, Namespace) MLIR_CAPI_EXPORTED MlirDialectHandle mlirGetDialectHandle__##Namespace##__()
Typedefs
typedef struct MlirDialectHandle MlirDialectHandle
Functions
MLIR_CAPI_EXPORTED MlirStringRef mlirDialectHandleGetNamespace (MlirDialectHandle)
Returns the namespace associated with the provided dialect handle.
MLIR_CAPI_EXPORTED void mlirDialectHandleInsertDialect (MlirDialectHandle, MlirDialectRegistry)
Inserts the dialect associated with the provided dialect handle into the provided dialect registry.
MLIR_CAPI_EXPORTED void mlirDialectHandleRegisterDialect (MlirDialectHandle, MlirContext)
Registers the dialect associated with the provided dialect handle.
MLIR_CAPI_EXPORTED MlirDialect mlirDialectHandleLoadDialect (MlirDialectHandle, MlirContext)
Loads the dialect associated with the provided dialect handle.
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
MLIR_CAPI_EXPORTED void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
MLIR_CAPI_EXPORTED void mlirRegisterAllPasses ()
Register all compiler passes of MLIR.
Macro Definition Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION
#define MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Name, Namespace) MLIR_CAPI_EXPORTED MlirDialectHandle mlirGetDialectHandle__##Namespace##__()
Definition at line 40 of file Registration.h.
Typedef Documentation
MlirDialectHandle
typedef struct MlirDialectHandle MlirDialectHandle
Definition at line 38 of file Registration.h.
Function Documentation
mlirDialectHandleGetNamespace()
MLIR_CAPI_EXPORTED MlirStringRef mlirDialectHandleGetNamespace (MlirDialectHandle)
Returns the namespace associated with the provided dialect handle.
Definition at line 16 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::getNamespaceHook, and unwrap().
mlirDialectHandleInsertDialect()
MLIR_CAPI_EXPORTED void mlirDialectHandleInsertDialect (MlirDialectHandle , MlirDialectRegistry)
Inserts the dialect associated with the provided dialect handle into the provided dialect registry.
Definition at line 20 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::insertHook, and unwrap().
Referenced by mlir::ExternalPass::getDependentDialects(), and mlirDialectHandleRegisterDialect().
mlirDialectHandleLoadDialect()
MLIR_CAPI_EXPORTED MlirDialect mlirDialectHandleLoadDialect (MlirDialectHandle , MlirContext)
Loads the dialect associated with the provided dialect handle.
Definition at line 32 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::loadHook, and unwrap().
mlirDialectHandleRegisterDialect()
MLIR_CAPI_EXPORTED void mlirDialectHandleRegisterDialect (MlirDialectHandle , MlirContext)
Registers the dialect associated with the provided dialect handle.
Definition at line 25 of file DialectHandle.cpp.
References mlirDialectHandleInsertDialect(), unwrap(), and wrap().
mlirRegisterAllDialects()
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
This is needed before creating IR for these Dialects. TODO: Remove this function once the real registration API is finished.
Definition at line 16 of file Registration.cpp.
References mlir::registerAllDialects(), and unwrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().
mlirRegisterAllLLVMTranslations()
MLIR_CAPI_EXPORTED void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
Definition at line 22 of file Registration.cpp.
References mlir::registerLLVMDialectTranslation(), and unwrap().
mlirRegisterAllPasses()
MLIR_CAPI_EXPORTED void mlirRegisterAllPasses ()
Register all compiler passes of MLIR.
Definition at line 26 of file Registration.cpp.
References mlir::registerAllPasses().
Referenced by PYBIND11_MODULE().