MLIR: lib/CAPI/ExecutionEngine/ExecutionEngine.cpp File Reference
ExecutionEngine.cpp File Reference
#include "mlir-c/ExecutionEngine.h"
#include "mlir/CAPI/ExecutionEngine.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/ExecutionEngine/OptUtils.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "llvm/ExecutionEngine/Orc/Mangling.h"
#include "llvm/Support/TargetSelect.h"
Functions
MlirExecutionEngine mlirExecutionEngineCreate (MlirModule op, int optLevel, int numPaths, const MlirStringRef *sharedLibPaths)
Creates an ExecutionEngine for the provided ModuleOp.
void mlirExecutionEngineDestroy (MlirExecutionEngine jit)
Destroy an ExecutionEngine instance.
MlirLogicalResult mlirExecutionEngineInvokePacked (MlirExecutionEngine jit, MlirStringRef name, void **arguments)
Invoke a native function in the execution engine by name with the arguments and result of the invoked function passed as an array of pointers.
void * mlirExecutionEngineLookupPacked (MlirExecutionEngine jit, MlirStringRef name)
Lookup the wrapper of the native function in the execution engine with the given name, returns nullptr if the function can't be looked-up.
void * mlirExecutionEngineLookup (MlirExecutionEngine jit, MlirStringRef name)
Lookup a native function in the execution engine by name, returns nullptr if the name can't be looked-up.
void mlirExecutionEngineRegisterSymbol (MlirExecutionEngine jit, MlirStringRef name, void *sym)
Register a symbol with the jit: this symbol will be accessible to the jitted code.
void mlirExecutionEngineDumpToObjectFile (MlirExecutionEngine jit, MlirStringRef name)
Dump as an object in fileName.
Function Documentation
mlirExecutionEngineCreate()
MlirExecutionEngine mlirExecutionEngineCreate (MlirModule op, int optLevel, int numPaths, const MlirStringRef * sharedLibPaths)
Creates an ExecutionEngine for the provided ModuleOp.
The ModuleOp is expected to be "translatable" to LLVM IR (only contains operations in dialects that implement the LLVMTranslationDialectInterface). The module ownership stays with the client and can be destroyed as soon as the call returns. optLevel is the optimization level to be used for transformation and code generation. LLVM passes at optLevel are run before code generation. The number and array of paths corresponding to shared libraries that will be loaded are specified via numPaths and sharedLibPaths respectively. TODO: figure out other options.
Definition at line 21 of file ExecutionEngine.cpp.
References mlir::ExecutionEngine::create(), MlirStringRef::data, mlir::makeOptimizingTransformer, mlir::registerLLVMDialectTranslation(), mlir::ExecutionEngineOptions::transformer, unwrap(), and wrap().
Referenced by PYBIND11_MODULE().
mlirExecutionEngineDestroy()
void mlirExecutionEngineDestroy (MlirExecutionEngine jit)
Destroy an ExecutionEngine instance.
Definition at line 65 of file ExecutionEngine.cpp.
References unwrap().
mlirExecutionEngineDumpToObjectFile()
void mlirExecutionEngineDumpToObjectFile (MlirExecutionEngine jit, MlirStringRef name)
Dump as an object in fileName.
Definition at line 107 of file ExecutionEngine.cpp.
References unwrap().
Referenced by mlirExecutionEngineIsNull().
mlirExecutionEngineInvokePacked()
MlirLogicalResult mlirExecutionEngineInvokePacked (MlirExecutionEngine jit, MlirStringRef name, void ** arguments)
Invoke a native function in the execution engine by name with the arguments and result of the invoked function passed as an array of pointers.
The function must have been tagged with the llvm.emit_c_interface attribute. Returns a failure if the execution fails for any reason (the function name can't be resolved for instance).
Definition at line 70 of file ExecutionEngine.cpp.
References mlir::Error, mlir::failure(), mlir::success(), unwrap(), and wrap().
Referenced by mlirExecutionEngineIsNull().
mlirExecutionEngineLookup()
void* mlirExecutionEngineLookup (MlirExecutionEngine jit, MlirStringRef name)
Lookup a native function in the execution engine by name, returns nullptr if the name can't be looked-up.
Definition at line 88 of file ExecutionEngine.cpp.
References unwrap().
Referenced by mlirExecutionEngineIsNull().
mlirExecutionEngineLookupPacked()
void* mlirExecutionEngineLookupPacked (MlirExecutionEngine jit, MlirStringRef name)
Lookup the wrapper of the native function in the execution engine with the given name, returns nullptr if the function can't be looked-up.
Definition at line 80 of file ExecutionEngine.cpp.
References unwrap().
Referenced by mlirExecutionEngineIsNull().
mlirExecutionEngineRegisterSymbol()
void mlirExecutionEngineRegisterSymbol (MlirExecutionEngine jit, MlirStringRef name, void * sym)
Register a symbol with the jit: this symbol will be accessible to the jitted code.
Definition at line 96 of file ExecutionEngine.cpp.
References unwrap().
Referenced by mlirExecutionEngineIsNull().