MLIR: mlir::tblgen::Pred Class Reference
mlir::tblgen::Pred Class Reference
#include "mlir/TableGen/Predicate.h"
Public Member Functions
Pred ()
Pred (const llvm::Record *record)
Pred (const llvm::Init *init)
bool isNull () const
std::string getCondition () const
bool isCombined () const
ArrayRef< SMLoc > getLoc () const
bool operator== (const Pred &other) const
operator bool () const
Protected Attributes
const llvm::Record * def {nullptr}
Friends
llvm::hash_code hash_value (Pred pred)
Detailed Description
Definition at line 34 of file Predicate.h.
Constructor & Destructor Documentation
Pred() [1/3]
mlir::tblgen::Pred::Pred () inline explicit
Definition at line 37 of file Predicate.h.
Referenced by buildPredicateTree().
Pred() [2/3]
Pred::Pred (const llvm::Record * record) explicit
Definition at line 26 of file Predicate.cpp.
References def.
Pred() [3/3]
Pred::Pred (const llvm::Init * init) explicit
Definition at line 32 of file Predicate.cpp.
References def.
Member Function Documentation
getCondition()
std::string Pred::getCondition () const
Definition at line 37 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), mlir::tblgen::Constraint::getConditionTemplate(), and mlir::tblgen::PredTrait::getPredTemplate().
getLoc()
ArrayRef< SMLoc > Pred::getLoc () const
Definition at line 50 of file Predicate.cpp.
References def.
isCombined()
bool Pred::isCombined () const
Definition at line 46 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), and getPredCombinerKind().
isNull()
bool mlir::tblgen::Pred::isNull () const inline
Definition at line 46 of file Predicate.h.
Referenced by mlir::tblgen::CPred::getConditionImpl(), and mlir::tblgen::NamedTypeConstraint::hasPredicate().
operator bool()
mlir::tblgen::Pred::operator bool () const inline
Definition at line 63 of file Predicate.h.
operator==()
bool mlir::tblgen::Pred::operator== (const Pred & other) const inline
Definition at line 60 of file Predicate.h.
References def.
Friends And Related Function Documentation
hash_value
llvm::hash_code hash_value (Pred pred) friend
Definition at line 66 of file Predicate.h.
Member Data Documentation
def
const llvm::Record* mlir::tblgen::Pred::def {nullptr} protected
Definition at line 72 of file Predicate.h.
Referenced by mlir::tblgen::CombinedPred::CombinedPred(), mlir::tblgen::CPred::CPred(), mlir::tblgen::CombinedPred::getChildren(), mlir::tblgen::CombinedPred::getCombinerDef(), getCondition(), mlir::tblgen::CPred::getConditionImpl(), getLoc(), mlir::tblgen::SubstLeavesPred::getPattern(), mlir::tblgen::ConcatPred::getPrefix(), mlir::tblgen::SubstLeavesPred::getReplacement(), mlir::tblgen::ConcatPred::getSuffix(), isCombined(), operator==(), and Pred().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Predicate.h
lib/TableGen/Predicate.cpp