MLIR: lib/TableGen/Class.cpp File Reference
Class.cpp File Reference
#include "mlir/TableGen/Class.h"
#include "mlir/TableGen/Format.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Include the generated interface declarations.
mlir::tblgen
Functions
static StringRef getSpaceAfterType (StringRef type)
Returns space to be emitted after the given C++ type.
raw_ostream & mlir::tblgen::operator<< (raw_ostream &os, Visibility visibility)
Write "public", "protected", or "private".
Method * insertAndPruneMethods (std::vector< std::unique_ptr< Method >> &methods, std::unique_ptr< Method > newMethod)
Function Documentation
getSpaceAfterType()
static StringRef getSpaceAfterType (StringRef type) static
Returns space to be emitted after the given C++ type.
return "" if the ends with '&' or '*', or is empty, else returns " ".
Definition at line 20 of file Class.cpp.
Referenced by mlir::tblgen::MethodParameter::writeDeclTo(), mlir::tblgen::MethodSignature::writeDeclTo(), mlir::tblgen::MethodParameter::writeDefTo(), and mlir::tblgen::MethodSignature::writeDefTo().
insertAndPruneMethods()
Method* insertAndPruneMethods (std::vector< std::unique_ptr< Method >> & methods, std::unique_ptr< Method > newMethod)
Definition at line 347 of file Class.cpp.
Referenced by mlir::tblgen::Class::addConstructorAndPrune(), and mlir::tblgen::Class::addMethodAndPrune().