MLIR: mlir::pdll::Lexer Class Reference
mlir::pdll::Lexer Class Reference
#include "Tools/PDLL/Parser/Lexer.h"
Public Member Functions
Lexer (llvm::SourceMgr &mgr, ast::DiagnosticEngine &diagEngine, CodeCompleteContext *codeCompleteContext)
~Lexer ()
llvm::SourceMgr & getSourceMgr ()
Return a reference to the source manager used by the lexer.
ast::DiagnosticEngine & getDiagEngine ()
Return a reference to the diagnostic engine used by the lexer.
LogicalResult pushInclude (StringRef filename, SMRange includeLoc)
Push an include of the given file.
Token lexToken ()
Lex the next token and return it.
void resetPointer (const char *newPointer)
Change the position of the lexer cursor.
Token emitError (SMRange loc, const Twine &msg)
Emit an error to the lexer with the given location and message.
Token emitError (const char *loc, const Twine &msg)
Token emitErrorAndNote (SMRange loc, const Twine &msg, SMRange noteLoc, const Twine &note)
Detailed Description
Definition at line 169 of file Lexer.h.
Constructor & Destructor Documentation
Lexer()
Lexer::Lexer (llvm::SourceMgr & mgr, ast::DiagnosticEngine & diagEngine, CodeCompleteContext * codeCompleteContext)
Definition at line 75 of file Lexer.cpp.
References diag(), mlir::pdll::CodeCompleteContext::getCodeCompleteLoc(), mlir::pdll::ast::DiagnosticEngine::getHandlerFn(), mlir::pdll::ast::Diagnostic::getLocation(), mlir::pdll::ast::Diagnostic::getMessage(), mlir::pdll::ast::Diagnostic::getNotes(), mlir::pdll::ast::Diagnostic::getSeverity(), and mlir::pdll::ast::DiagnosticEngine::setHandlerFn().
~Lexer()
Lexer::~Lexer ()
Definition at line 103 of file Lexer.cpp.
References mlir::pdll::ast::DiagnosticEngine::setHandlerFn().
Member Function Documentation
emitError() [1/2]
Token Lexer::emitError (SMRange loc, const Twine & msg)
Emit an error to the lexer with the given location and message.
Definition at line 120 of file Lexer.cpp.
References mlir::pdll::ast::DiagnosticEngine::emitError(), and mlir::pdll::Token::error.
Referenced by emitErrorAndNote().
emitError() [2/2]
Token mlir::pdll::Lexer::emitError (const char * loc, const Twine & msg)
emitErrorAndNote()
Token Lexer::emitErrorAndNote (SMRange loc, const Twine & msg, SMRange noteLoc, const Twine & note)
Definition at line 124 of file Lexer.cpp.
References mlir::pdll::Token::arrow, mlir::pdll::ast::Diagnostic::attachNote(), mlir::pdll::Token::code_complete, mlir::pdll::Token::colon, mlir::pdll::Token::comma, mlir::pdll::Token::directive, mlir::pdll::Token::dot, mlir::pdll::ast::DiagnosticEngine::emitError(), emitError(), mlir::pdll::Token::eof, mlir::pdll::Token::equal, mlir::pdll::Token::equal_arrow, mlir::pdll::Token::error, mlir::pdll::Token::greater, mlir::pdll::Token::l_brace, mlir::pdll::Token::l_paren, mlir::pdll::Token::l_square, mlir::pdll::Token::less, lexToken(), mlir::pdll::Token::r_brace, mlir::pdll::Token::r_paren, mlir::pdll::Token::r_square, and mlir::pdll::Token::semicolon.
getDiagEngine()
ast::DiagnosticEngine& mlir::pdll::Lexer::getDiagEngine () inline
Return a reference to the diagnostic engine used by the lexer.
Definition at line 179 of file Lexer.h.
getSourceMgr()
llvm::SourceMgr& mlir::pdll::Lexer::getSourceMgr () inline
Return a reference to the source manager used by the lexer.
Definition at line 176 of file Lexer.h.
lexToken()
Token mlir::pdll::Lexer::lexToken ()
Lex the next token and return it.
Referenced by emitErrorAndNote().
pushInclude()
LogicalResult Lexer::pushInclude (StringRef filename, SMRange includeLoc)
Push an include of the given file.
This will cause the lexer to start processing the provided file. Returns failure if the file could not be opened, success otherwise.
Definition at line 107 of file Lexer.cpp.
References mlir::failure(), and mlir::success().
resetPointer()
void mlir::pdll::Lexer::resetPointer (const char * newPointer) inline
Change the position of the lexer cursor.
The next token we lex will start at the designated point in the input.
Definition at line 191 of file Lexer.h.
References mlir::emitError().
The documentation for this class was generated from the following files:
lib/Tools/PDLL/Parser/Lexer.h
lib/Tools/PDLL/Parser/Lexer.cpp