MLIR: mlir::pdll::ast::Decl Class Reference
mlir::pdll::ast::Decl Class Reference
This class represents the base Decl node.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This class represents the base Decl node.
Definition at line 629 of file Nodes.h.
Constructor & Destructor Documentation
Decl()
mlir::pdll::ast::Decl::Decl (TypeID typeID, SMRange loc, const Name * name = nullptr) inline protected
Definition at line 638 of file Nodes.h.
Member Function Documentation
classof()
bool mlir::pdll::ast::Decl::classof (const Node * node) inline static
Provide type casting support.
Definition at line 1238 of file Nodes.h.
getName()
const Name* mlir::pdll::ast::Decl::getName () const inline
Return the name of the decl, or nullptr if it doesn't have one.
Definition at line 632 of file Nodes.h.
Referenced by mlir::pdll::ast::DeclScope::add(), checkAndNestUnderRewriteOp(), getLspDiagnoticFromDiag(), mlir::pdll::ast::UserConstraintDecl::getName(), mlir::pdll::ast::NamedAttributeDecl::getName(), mlir::pdll::ast::OpNameDecl::getName(), mlir::pdll::ast::UserRewriteDecl::getName(), and mlir::pdll::ast::VariableDecl::getName().
The documentation for this class was generated from the following file:
include/mlir/Tools/PDLL/AST/Nodes.h