MLIR: mlir::python::PyOpView Class Reference
mlir::python::PyOpView Class Reference
A PyOpView is equivalent to the C++ "Op" wrappers: these are the basis for providing more instance-specific accessors and serve as the base class for custom ODS-style operation classes.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyOpView (const pybind11::object &operationObject)
PyOperation & getOperation () override
Each must provide access to the raw Operation.
pybind11::object getOperationObject ()
Public Member Functions inherited from mlir::python::PyOperationBase
virtual ~PyOperationBase ()=default
void print (pybind11::object fileObject, bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
Implements the bound 'print' method and helps with others.
pybind11::object getAsm (bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
void moveAfter (PyOperationBase &other)
Moves the operation before or after the other operation.
void moveBefore (PyOperationBase &other)
Static Public Member Functions
static pybind11::object createRawSubclass (const pybind11::object &userClass)
static pybind11::object buildGeneric (const pybind11::object &cls, pybind11::list resultTypeList, pybind11::list operandList, llvm::Optional< pybind11::dict > attributes, llvm::Optional< std::vector< PyBlock *>> successors, llvm::Optional< int > regions, DefaultingPyLocation location, const pybind11::object &maybeIp)
Detailed Description
A PyOpView is equivalent to the C++ "Op" wrappers: these are the basis for providing more instance-specific accessors and serve as the base class for custom ODS-style operation classes.
Since this class is subclass on the python side, it must present an init method that operates in pure python types.
Definition at line 617 of file IRModule.h.
Constructor & Destructor Documentation
PyOpView()
PyOpView::PyOpView (const pybind11::object & operationObject)
Definition at line 1516 of file IRCore.cpp.
Member Function Documentation
buildGeneric()
py::object PyOpView::buildGeneric (const pybind11::object & cls, pybind11::list resultTypeList, pybind11::list operandList, llvm::Optional< pybind11::dict > attributes, llvm::Optional< std::vector< PyBlock *>> successors, llvm::Optional< int > regions, DefaultingPyLocation location, const pybind11::object & maybeIp) static
Definition at line 1259 of file IRCore.cpp.
References mlir::python::PyOperation::create(), mlir::detail::enumerate(), mlir::python::PyMlirContext::get(), mlirDenseElementsAttrUInt32Get(), mlirIntegerTypeGet(), and mlirVectorTypeGet().
Referenced by mlir::python::PySymbolTable::walkSymbolTables().
createRawSubclass()
py::object PyOpView::createRawSubclass (const pybind11::object & userClass) static
Definition at line 1522 of file IRCore.cpp.
Referenced by PYBIND11_MODULE().
getOperation()
PyOperation& mlir::python::PyOpView::getOperation () inline override virtual
Each must provide access to the raw Operation.
Implements mlir::python::PyOperationBase.
Definition at line 620 of file IRModule.h.
getOperationObject()
pybind11::object mlir::python::PyOpView::getOperationObject () inline
Definition at line 624 of file IRModule.h.
Referenced by mlir::python::PySymbolTable::walkSymbolTables().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp