MLIR: mlir::presburger::PresburgerRelation Class Reference
mlir::presburger::PresburgerRelation Class Reference
A PresburgerRelation represents a union of IntegerRelations that live in the same PresburgerSpace with support for union, intersection, subtraction, and complement operations, as well as sampling.
#include "mlir/Analysis/Presburger/PresburgerRelation.h"
Public Member Functions
PresburgerRelation (const IntegerRelation &disjunct)
unsigned getNumDomainIds () const
unsigned getNumRangeIds () const
unsigned getNumSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumIds () const
unsigned getNumDisjuncts () const
Return the number of disjuncts in the union.
const PresburgerSpace & getSpace () const
ArrayRef< IntegerRelation > getAllDisjuncts () const
Return a reference to the list of disjuncts.
const IntegerRelation & getDisjunct (unsigned index) const
Return the disjunct at the specified index.
void unionInPlace (const IntegerRelation &disjunct)
Mutate this set, turning it into the union of this set and the given disjunct.
void unionInPlace (const PresburgerRelation &set)
Mutate this set, turning it into the union of this set and the given set.
PresburgerRelation unionSet (const PresburgerRelation &set) const
Return the union of this set and the given set.
PresburgerRelation intersect (const PresburgerRelation &set) const
Return the intersection of this set and the given set.
bool containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
PresburgerRelation complement () const
Return the complement of this set.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
bool isSubsetOf (const PresburgerRelation &set) const
Return true if this set is a subset of the given set, and false otherwise.
bool isEqual (const PresburgerRelation &set) const
Return true if this set is equal to the given set, and false otherwise.
bool isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
bool findIntegerSample (SmallVectorImpl< int64_t > &sample)
Find an integer sample from the given set.
Optional< uint64_t > computeVolume () const
Compute an overapproximation of the number of integer points in the disjunct.
PresburgerRelation coalesce () const
Simplifies the representation of a PresburgerRelation.
void print (raw_ostream &os) const
Print the set's internal state.
void dump () const
Static Public Member Functions
static PresburgerRelation getUniverse (const PresburgerSpace &space)
Return a universe set of the specified type that contains all points.
static PresburgerRelation getEmpty (const PresburgerSpace &space)
Return an empty set of the specified type that contains no points.
Protected Member Functions
PresburgerRelation (const PresburgerSpace &space)
Construct an empty PresburgerRelation with the specified number of dimension and symbols.
Protected Attributes
PresburgerSpace space
SmallVector< IntegerRelation, 2 > disjuncts
The list of disjuncts that this set is the union of.
Friends
class SetCoalescer
Detailed Description
A PresburgerRelation represents a union of IntegerRelations that live in the same PresburgerSpace with support for union, intersection, subtraction, and complement operations, as well as sampling.
The IntegerRelations (disjuncts) are stored in a vector, and the set represents the union of these relations. An empty list corresponds to the empty set.
Note that there are no invariants guaranteed on the list of disjuncts other than that they are all in the same PresburgerSpace. For example, the relations may overlap with each other.
Definition at line 37 of file PresburgerRelation.h.
Constructor & Destructor Documentation
PresburgerRelation() [1/2]
PresburgerRelation::PresburgerRelation (const IntegerRelation & disjunct) explicit
Definition at line 19 of file PresburgerRelation.cpp.
References unionInPlace().
Referenced by getEmpty().
PresburgerRelation() [2/2]
mlir::presburger::PresburgerRelation::PresburgerRelation (const PresburgerSpace & space) inline explicit protected
Construct an empty PresburgerRelation with the specified number of dimension and symbols.
Definition at line 127 of file PresburgerRelation.h.
References mlir::presburger::PresburgerSpace::getNumLocalIds().
Member Function Documentation
coalesce()
PresburgerRelation PresburgerRelation::coalesce () const
Simplifies the representation of a PresburgerRelation.
In particular, removes all disjuncts which are subsets of other disjuncts in the union.
Definition at line 756 of file PresburgerRelation.cpp.
References mlir::presburger::SetCoalescer::SetCoalescer().
Referenced by mlir::presburger::PresburgerSet::coalesce(), and getSpace().
complement()
PresburgerRelation PresburgerRelation::complement () const
Return the complement of this set.
All local variables in the set must correspond to floor divisions.
Definition at line 371 of file PresburgerRelation.cpp.
References getSetDifference(), getSpace(), and mlir::presburger::IntegerRelation::getUniverse().
Referenced by mlir::presburger::PresburgerSet::complement(), and getSpace().
computeVolume()
Optional< uint64_t > PresburgerRelation::computeVolume () const
Compute an overapproximation of the number of integer points in the disjunct.
Symbol ids are currently not supported. If the computed overapproximation is infinite, an empty optional is returned.
This currently just sums up the overapproximations of the volumes of the disjuncts, so the approximation might be far from the true volume in the case when there is a lot of overlap between disjuncts.
Definition at line 418 of file PresburgerRelation.cpp.
References disjuncts, and getNumSymbolIds().
Referenced by getSpace().
containsPoint()
bool PresburgerRelation::containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
A point is contained in the union iff any of the parts contain the point.
Definition at line 64 of file PresburgerRelation.cpp.
References mlir::presburger::IntegerRelation::containsPoint(), and disjuncts.
Referenced by getSpace().
dump()
void PresburgerRelation::dump () const
Definition at line 768 of file PresburgerRelation.cpp.
References print().
Referenced by getSpace().
findIntegerSample()
bool PresburgerRelation::findIntegerSample (SmallVectorImpl< int64_t > & sample)
Find an integer sample from the given set.
This should not be called if any of the disjuncts in the union are unbounded.
Definition at line 407 of file PresburgerRelation.cpp.
References disjuncts.
Referenced by getSpace().
getAllDisjuncts()
ArrayRef< IntegerRelation > PresburgerRelation::getAllDisjuncts () const
Return a reference to the list of disjuncts.
Definition at line 28 of file PresburgerRelation.cpp.
References disjuncts.
Referenced by getSpace().
getDisjunct()
const IntegerRelation & PresburgerRelation::getDisjunct (unsigned index) const
Return the disjunct at the specified index.
Definition at line 32 of file PresburgerRelation.cpp.
References disjuncts.
Referenced by getSetDifference(), and getSpace().
getEmpty()
PresburgerRelation PresburgerRelation::getEmpty (const PresburgerSpace & space) static
Return an empty set of the specified type that contains no points.
Definition at line 77 of file PresburgerRelation.cpp.
References PresburgerRelation().
Referenced by getSetDifference().
getNumDisjuncts()
unsigned PresburgerRelation::getNumDisjuncts () const
Return the number of disjuncts in the union.
Definition at line 24 of file PresburgerRelation.cpp.
References disjuncts.
Referenced by getNumIds(), getSetDifference(), and mlir::presburger::SetCoalescer::SetCoalescer().
getNumDomainIds()
unsigned mlir::presburger::PresburgerRelation::getNumDomainIds () const inline
Definition at line 47 of file PresburgerRelation.h.
References mlir::presburger::PresburgerSpace::getNumDomainIds().
getNumIds()
unsigned mlir::presburger::PresburgerRelation::getNumIds () const inline
Definition at line 51 of file PresburgerRelation.h.
References getNumDisjuncts(), and mlir::presburger::PresburgerSpace::getNumIds().
getNumLocalIds()
unsigned mlir::presburger::PresburgerRelation::getNumLocalIds () const inline
Definition at line 50 of file PresburgerRelation.h.
References mlir::presburger::PresburgerSpace::getNumLocalIds().
getNumRangeIds()
unsigned mlir::presburger::PresburgerRelation::getNumRangeIds () const inline
Definition at line 48 of file PresburgerRelation.h.
References mlir::presburger::PresburgerSpace::getNumRangeIds().
getNumSymbolIds()
unsigned mlir::presburger::PresburgerRelation::getNumSymbolIds () const inline
Definition at line 49 of file PresburgerRelation.h.
References mlir::presburger::PresburgerSpace::getNumSymbolIds().
Referenced by computeVolume().
getSpace()
const PresburgerSpace& mlir::presburger::PresburgerRelation::getSpace () const inline
Definition at line 56 of file PresburgerRelation.h.
References coalesce(), complement(), computeVolume(), containsPoint(), dump(), findIntegerSample(), getAllDisjuncts(), getDisjunct(), intersect(), isEqual(), isIntegerEmpty(), isSubsetOf(), print(), space, subtract(), unionInPlace(), and unionSet().
Referenced by complement(), getSetDifference(), intersect(), and subtract().
getUniverse()
PresburgerRelation PresburgerRelation::getUniverse (const PresburgerSpace & space) static
Return a universe set of the specified type that contains all points.
Definition at line 71 of file PresburgerRelation.cpp.
References mlir::presburger::IntegerRelation::getUniverse(), and unionInPlace().
intersect()
PresburgerRelation PresburgerRelation::intersect (const PresburgerRelation & set) const
Return the intersection of this set and the given set.
Definition at line 89 of file PresburgerRelation.cpp.
References disjuncts, getSpace(), mlir::presburger::IntegerRelation::intersect(), mlir::presburger::PresburgerSpace::isCompatible(), mlir::presburger::IntegerRelation::isEmpty(), space, and unionInPlace().
Referenced by getSpace(), and mlir::presburger::PresburgerSet::intersect().
isEqual()
bool PresburgerRelation::isEqual (const PresburgerRelation & set) const
Return true if this set is equal to the given set, and false otherwise.
Two sets are equal iff they are subsets of each other.
All local variables in both sets must correspond to floor divisions.
Definition at line 395 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerSpace::isCompatible(), isSubsetOf(), and space.
Referenced by getSpace(), mlir::presburger::MultiAffineFunction::isEqual(), mlir::presburger::IntegerRelation::isEqual(), and mlir::presburger::PWMAFunction::isEqual().
isIntegerEmpty()
bool PresburgerRelation::isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
Return true if all the sets in the union are known to be integer empty, false otherwise.
Definition at line 402 of file PresburgerRelation.cpp.
References disjuncts, and mlir::presburger::IntegerRelation::isIntegerEmpty().
Referenced by mlir::presburger::PWMAFunction::addPiece(), getSpace(), mlir::ComputationSliceState::isMaximal(), mlir::ComputationSliceState::isSliceValid(), and isSubsetOf().
isSubsetOf()
bool PresburgerRelation::isSubsetOf (const PresburgerRelation & set) const
Return true if this set is a subset of the given set, and false otherwise.
T is a subset of S iff T \ S is empty, since if T \ S contains a point then this is a point that is contained in T but not S, and if T contains a point that is not in S, this also lies in T \ S.
Definition at line 390 of file PresburgerRelation.cpp.
References isIntegerEmpty(), and subtract().
Referenced by getSpace(), isEqual(), and mlir::presburger::IntegerRelation::isSubsetOf().
print()
void PresburgerRelation::print (raw_ostream & os) const
Print the set's internal state.
Definition at line 760 of file PresburgerRelation.cpp.
References mlir::presburger::IntegerRelation::print().
Referenced by getSpace().
subtract()
PresburgerRelation PresburgerRelation::subtract (const PresburgerRelation & set) const
Return the set difference of this set and the given set, i.e., return this \ set.
Return the result of subtract the given set from this set, i.e., return this \ set.
All local variables in set must correspond to floor divisions, but local variables in this need not correspond to divisions.
Definition at line 378 of file PresburgerRelation.cpp.
References disjuncts, getSetDifference(), getSpace(), mlir::presburger::PresburgerSpace::isCompatible(), space, and unionInPlace().
Referenced by getSpace(), isSubsetOf(), and mlir::presburger::PresburgerSet::subtract().
unionInPlace() [1/2]
void PresburgerRelation::unionInPlace (const IntegerRelation & disjunct)
Mutate this set, turning it into the union of this set and the given disjunct.
Mutate this set, turning it into the union of this set and the given IntegerRelation.
Definition at line 39 of file PresburgerRelation.cpp.
References disjuncts, mlir::presburger::IntegerRelation::getSpace(), mlir::presburger::PresburgerSpace::isCompatible(), and space.
Referenced by mlir::presburger::SetCoalescer::coalesce(), mlir::presburger::PWMAFunction::getDomain(), getSetDifference(), getSpace(), getUniverse(), mlir::presburger::PresburgerSet::getUniverse(), intersect(), isRangeDivisibleBy(), PresburgerRelation(), subtract(), unionInPlace(), and unionSet().
unionInPlace() [2/2]
void PresburgerRelation::unionInPlace (const PresburgerRelation & set)
Mutate this set, turning it into the union of this set and the given set.
This is accomplished by simply adding all the disjuncts of the given set to this set.
Definition at line 48 of file PresburgerRelation.cpp.
References disjuncts, mlir::presburger::PresburgerSpace::isCompatible(), space, and unionInPlace().
unionSet()
PresburgerRelation PresburgerRelation::unionSet (const PresburgerRelation & set) const
Return the union of this set and the given set.
Definition at line 56 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerSpace::isCompatible(), space, and unionInPlace().
Referenced by getSpace(), and mlir::presburger::PresburgerSet::unionSet().
Friends And Related Function Documentation
SetCoalescer
friend class SetCoalescer friend
Definition at line 137 of file PresburgerRelation.h.
Member Data Documentation
disjuncts
SmallVector<IntegerRelation, 2> mlir::presburger::PresburgerRelation::disjuncts protected
The list of disjuncts that this set is the union of.
Definition at line 135 of file PresburgerRelation.h.
Referenced by computeVolume(), containsPoint(), findIntegerSample(), getAllDisjuncts(), getDisjunct(), getNumDisjuncts(), intersect(), isIntegerEmpty(), mlir::presburger::SetCoalescer::SetCoalescer(), subtract(), and unionInPlace().
space
PresburgerSpace mlir::presburger::PresburgerRelation::space protected
Definition at line 132 of file PresburgerRelation.h.
Referenced by getSpace(), intersect(), isEqual(), subtract(), unionInPlace(), and unionSet().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerRelation.h
lib/Analysis/Presburger/PresburgerRelation.cpp