MLIR: mlir::lsp::CompilationDatabase Class Reference
mlir::lsp::CompilationDatabase Class Reference
This class contains a collection of compilation information for files provided to the language server, such as the available include directories.
#include "Tools/mlir-pdll-lsp-server/CompilationDatabase.h"
Classes
struct FileInfo
Compilation information for a specific file within the database.
Public Member Functions
CompilationDatabase (ArrayRef< std::string > databases)
Construct a compilation database from the provided files containing YAML descriptions of the database.
const FileInfo * getFileInfo (StringRef filename) const
Get the compilation information for the provided file, or nullptr if the database doesn't include information for filename.
Detailed Description
This class contains a collection of compilation information for files provided to the language server, such as the available include directories.
This database acts as an aggregate in-memory form of compilation databases used by the current language client. The textual form of a compilation database is a YAML file containing documents of the following form:
— !FileInfo: filepath: <string> - Absolute file path of the file. includes: <string> - Semi-colon delimited list of include directories.
Definition at line 29 of file CompilationDatabase.h.
Constructor & Destructor Documentation
CompilationDatabase()
CompilationDatabase::CompilationDatabase (ArrayRef< std::string > databases)
Construct a compilation database from the provided files containing YAML descriptions of the database.
Definition at line 52 of file CompilationDatabase.cpp.
Member Function Documentation
getFileInfo()
const CompilationDatabase::FileInfo * CompilationDatabase::getFileInfo (StringRef filename) const
Get the compilation information for the provided file, or nullptr if the database doesn't include information for filename.
Definition at line 58 of file CompilationDatabase.cpp.
References mlir::lsp::Logger::error(), mlir::lsp::Logger::info(), and mlir::openInputFile().
The documentation for this class was generated from the following files:
lib/Tools/mlir-pdll-lsp-server/CompilationDatabase.h
lib/Tools/mlir-pdll-lsp-server/CompilationDatabase.cpp