MLIR: mlir::pdll::ast::ValueRangeConstraintDecl Class Reference
mlir::pdll::ast::ValueRangeConstraintDecl Class Reference
The class represents a ValueRange constraint, and constrains a variable to be a ValueRange.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Expr * getTypeExpr ()
Return the optional type the value range is constrained to.
const Expr * getTypeExpr () const
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static ValueRangeConstraintDecl * create (Context &ctx, SMRange loc, Expr *typeExpr=nullptr)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< ValueRangeConstraintDecl, CoreConstraintDecl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::ConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
ValueRangeConstraintDecl (SMRange loc, Expr *typeExpr)
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< ValueRangeConstraintDecl, CoreConstraintDecl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
CoreConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::ConstraintDecl
ConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Protected Attributes
Expr * typeExpr
An optional type that the value range is constrained to.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< ValueRangeConstraintDecl, CoreConstraintDecl >
using Base = NodeBase< ValueRangeConstraintDecl, CoreConstraintDecl >
Detailed Description
The class represents a ValueRange constraint, and constrains a variable to be a ValueRange.
Definition at line 797 of file Nodes.h.
Constructor & Destructor Documentation
ValueRangeConstraintDecl()
mlir::pdll::ast::ValueRangeConstraintDecl::ValueRangeConstraintDecl (SMRange loc, Expr * typeExpr) inline protected
Definition at line 808 of file Nodes.h.
Member Function Documentation
create()
ValueRangeConstraintDecl * ValueRangeConstraintDecl::create (Context & ctx, SMRange loc, Expr * typeExpr = nullptr) static
Definition at line 418 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), mlir::pdll::ast::UserConstraintDecl::getInputs(), and mlir::pdll::ast::UserConstraintDecl::getResults().
getTypeExpr() [1/2]
Expr* mlir::pdll::ast::ValueRangeConstraintDecl::getTypeExpr () inline
Return the optional type the value range is constrained to.
Definition at line 804 of file Nodes.h.
Referenced by mlir::pdll::ast::Name::create().
getTypeExpr() [2/2]
const Expr* mlir::pdll::ast::ValueRangeConstraintDecl::getTypeExpr () const inline
Definition at line 805 of file Nodes.h.
Member Data Documentation
typeExpr
Expr* mlir::pdll::ast::ValueRangeConstraintDecl::typeExpr protected
An optional type that the value range is constrained to.
Definition at line 812 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp