MLIR: mlir::detail::AsmStateImpl Class Reference
mlir::detail::AsmStateImpl Class Reference
Public Member Functions
AsmStateImpl (Operation *op, const OpPrintingFlags &printerFlags, AsmState::LocationMap *locationMap)
void initializeAliases (Operation *op)
Initialize the alias state to enable the printing of aliases.
AliasState & getAliasState ()
Get the state used for aliases.
SSANameState & getSSANameState ()
Get the state used for SSA names.
const OpPrintingFlags & getPrinterFlags () const
Get the printer flags.
void registerOperationLocation (Operation *op, unsigned line, unsigned col)
Register the location, line and column, within the buffer that the given operation was printed at.
Detailed Description
Definition at line 1260 of file AsmPrinter.cpp.
Constructor & Destructor Documentation
AsmStateImpl()
mlir::detail::AsmStateImpl::AsmStateImpl (Operation * op, const OpPrintingFlags & printerFlags, AsmState::LocationMap * locationMap) inline explicit
Definition at line 1262 of file AsmPrinter.cpp.
Member Function Documentation
getAliasState()
AliasState& mlir::detail::AsmStateImpl::getAliasState () inline
Get the state used for aliases.
Definition at line 1273 of file AsmPrinter.cpp.
getPrinterFlags()
const OpPrintingFlags& mlir::detail::AsmStateImpl::getPrinterFlags () const inline
Get the printer flags.
Definition at line 1279 of file AsmPrinter.cpp.
Referenced by mlir::AsmPrinter::Impl::printIntegerSet().
getSSANameState()
SSANameState& mlir::detail::AsmStateImpl::getSSANameState () inline
Get the state used for SSA names.
Definition at line 1276 of file AsmPrinter.cpp.
Referenced by mlir::Value::printAsOperand(), and mlir::AsmPrinter::Impl::printIntegerSet().
initializeAliases()
void mlir::detail::AsmStateImpl::initializeAliases (Operation * op) inline
Initialize the alias state to enable the printing of aliases.
Definition at line 1268 of file AsmPrinter.cpp.
Referenced by mlir::Operation::print().
registerOperationLocation()
void mlir::detail::AsmStateImpl::registerOperationLocation (Operation * op, unsigned line, unsigned col) inline
Register the location, line and column, within the buffer that the given operation was printed at.
Definition at line 1283 of file AsmPrinter.cpp.
The documentation for this class was generated from the following file:
lib/IR/AsmPrinter.cpp