MLIR: mlir::presburger::PWMAFunction Class Reference
mlir::presburger::PWMAFunction Class Reference
This class represents a piece-wise MultiAffineFunction.
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
PWMAFunction (const PresburgerSpace &space, unsigned numOutputs)
const PresburgerSpace & getSpace () const
void addPiece (const MultiAffineFunction &piece)
void addPiece (const IntegerPolyhedron &domain, const Matrix &output)
const MultiAffineFunction & getPiece (unsigned i) const
unsigned getNumPieces () const
unsigned getNumOutputs () const
unsigned getNumInputs () const
MultiAffineFunction & getPiece (unsigned i)
PresburgerSet getDomain () const
Return the domain of this piece-wise MultiAffineFunction.
Optional< SmallVector< int64_t, 8 > > valueAt (ArrayRef< int64_t > point) const
Return the value at the specified point and an empty optional if the point does not lie in the domain.
bool isEqual (const PWMAFunction &other) const
Return whether this and other are equal as PWMAFunctions, i.e.
void truncateOutput (unsigned count)
Truncate the output dimensions to the first count dimensions.
void print (raw_ostream &os) const
void dump () const
Detailed Description
This class represents a piece-wise MultiAffineFunction.
This can be thought of as a list of MultiAffineFunction with disjoint domains, with each having their own affine expressions for their output tuples. For example, we could have a function with two input variables (x, y), defined as
f(x, y) = (2*x + y, y - 4) if x >= 0, y >= 0 = (-2*x + y, y + 4) if x < 0, y < 0 = (4, 1) if x < 0, y >= 0
Note that the domains all have to be disjoint. Otherwise, the behaviour of this class is undefined. The domains need not cover all possible points; this represents a partial function and so could be undefined at some points.
As in PresburgerSets, the input ids are partitioned into dimension ids and symbolic ids.
Support is provided to compare equality of two such functions as well as finding the value of the function at a point.
Definition at line 126 of file PWMAFunction.h.
Constructor & Destructor Documentation
PWMAFunction()
mlir::presburger::PWMAFunction::PWMAFunction (const PresburgerSpace & space, unsigned numOutputs) inline
Definition at line 128 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getNumDomainIds(), and mlir::presburger::PresburgerSpace::getNumLocalIds().
Member Function Documentation
addPiece() [1/2]
void PWMAFunction::addPiece (const MultiAffineFunction & piece)
Definition at line 198 of file PWMAFunction.cpp.
References mlir::presburger::MultiAffineFunction::getDomain(), getDomain(), mlir::presburger::MultiAffineFunction::getDomainSpace(), mlir::presburger::PresburgerSpace::isCompatible(), mlir::presburger::MultiAffineFunction::isConsistent(), and mlir::presburger::PresburgerRelation::isIntegerEmpty().
Referenced by addPiece(), and isRangeDivisibleBy().
addPiece() [2/2]
void PWMAFunction::addPiece (const IntegerPolyhedron & domain, const Matrix & output)
Definition at line 209 of file PWMAFunction.cpp.
References addPiece().
dump()
void PWMAFunction::dump () const
Definition at line 220 of file PWMAFunction.cpp.
References print().
getDomain()
PresburgerSet PWMAFunction::getDomain () const
Return the domain of this piece-wise MultiAffineFunction.
This is the union of the domains of all the pieces.
Definition at line 29 of file PWMAFunction.cpp.
References mlir::presburger::PresburgerSet::getEmpty(), getSpace(), and mlir::presburger::PresburgerRelation::unionInPlace().
Referenced by addPiece(), mlir::presburger::MultiAffineFunction::isEqual(), isEqual(), and mlir::presburger::MultiAffineFunction::valueAt().
getNumInputs()
unsigned mlir::presburger::PWMAFunction::getNumInputs () const inline
Definition at line 145 of file PWMAFunction.h.
Referenced by valueAt().
getNumOutputs()
unsigned mlir::presburger::PWMAFunction::getNumOutputs () const inline
Definition at line 144 of file PWMAFunction.h.
Referenced by mlir::presburger::IntegerPolyhedron::findSymbolicIntegerLexMin(), mlir::presburger::MultiAffineFunction::isEqualWhereDomainsOverlap(), isRangeDivisibleBy(), and mlir::presburger::MultiAffineFunction::valueAt().
getNumPieces()
unsigned mlir::presburger::PWMAFunction::getNumPieces () const inline
Definition at line 143 of file PWMAFunction.h.
getPiece() [1/2]
const MultiAffineFunction& mlir::presburger::PWMAFunction::getPiece (unsigned i) const inline
Definition at line 142 of file PWMAFunction.h.
getPiece() [2/2]
MultiAffineFunction& mlir::presburger::PWMAFunction::getPiece (unsigned i) inline
Definition at line 146 of file PWMAFunction.h.
References mlir::presburger::MultiAffineFunction::dump(), mlir::presburger::MultiAffineFunction::getDomain(), mlir::presburger::MultiAffineFunction::isEqual(), mlir::presburger::MultiAffineFunction::print(), mlir::presburger::MultiAffineFunction::truncateOutput(), and mlir::presburger::MultiAffineFunction::valueAt().
getSpace()
const PresburgerSpace& mlir::presburger::PWMAFunction::getSpace () const inline
Definition at line 137 of file PWMAFunction.h.
Referenced by getDomain().
isEqual()
bool PWMAFunction::isEqual (const PWMAFunction & other) const
Return whether this and other are equal as PWMAFunctions, i.e.
Two PWMAFunctions are equal if they have the same dimensionalities, the same domain, and take the same value at every point in the domain.
whether they have the same dimensions, the same domain and they take the same value at every point in the domain.
Definition at line 180 of file PWMAFunction.cpp.
References getDomain(), mlir::presburger::PresburgerSpace::isCompatible(), and mlir::presburger::PresburgerRelation::isEqual().
print()
void PWMAFunction::print (raw_ostream & os) const
Definition at line 214 of file PWMAFunction.cpp.
Referenced by mlir::presburger::MultiAffineFunction::dump(), and dump().
truncateOutput()
void PWMAFunction::truncateOutput (unsigned count)
Truncate the output dimensions to the first count dimensions.
TODO: refactor so that this can be accomplished through removeIdRange.
Definition at line 111 of file PWMAFunction.cpp.
Referenced by mlir::presburger::IntegerPolyhedron::findSymbolicIntegerLexMin().
valueAt()
Optional< SmallVector< int64_t, 8 > > PWMAFunction::valueAt (ArrayRef< int64_t > point) const
Return the value at the specified point and an empty optional if the point does not lie in the domain.
Definition at line 66 of file PWMAFunction.cpp.
References getNumInputs().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PWMAFunction.h
lib/Analysis/Presburger/PWMAFunction.cpp