MLIR: mlir::PassInstrumentor Class Reference
mlir::PassInstrumentor Class Reference
This class holds a collection of PassInstrumentation objects, and invokes their respective call backs.
#include "mlir/Pass/PassInstrumentation.h"
Public Member Functions
PassInstrumentor ()
PassInstrumentor (PassInstrumentor &&)=delete
PassInstrumentor (const PassInstrumentor &)=delete
~PassInstrumentor ()
void runBeforePipeline (StringAttr name, const PassInstrumentation::PipelineParentInfo &parentInfo)
See PassInstrumentation::runBeforePipeline for details.
void runAfterPipeline (StringAttr name, const PassInstrumentation::PipelineParentInfo &parentInfo)
See PassInstrumentation::runAfterPipeline for details.
void runBeforePass (Pass *pass, Operation *op)
See PassInstrumentation::runBeforePass for details.
void runAfterPass (Pass *pass, Operation *op)
See PassInstrumentation::runAfterPass for details.
void runAfterPassFailed (Pass *pass, Operation *op)
See PassInstrumentation::runAfterPassFailed for details.
void runBeforeAnalysis (StringRef name, TypeID id, Operation *op)
See PassInstrumentation::runBeforeAnalysis for details.
void runAfterAnalysis (StringRef name, TypeID id, Operation *op)
See PassInstrumentation::runAfterAnalysis for details.
void addInstrumentation (std::unique_ptr< PassInstrumentation > pi)
Add the given instrumentation to the collection.
Detailed Description
This class holds a collection of PassInstrumentation objects, and invokes their respective call backs.
Definition at line 84 of file PassInstrumentation.h.
Constructor & Destructor Documentation
PassInstrumentor() [1/3]
PassInstrumentor::PassInstrumentor ()
Definition at line 807 of file Pass.cpp.
References ~PassInstrumentor().
PassInstrumentor() [2/3]
mlir::PassInstrumentor::PassInstrumentor (PassInstrumentor &&) delete
PassInstrumentor() [3/3]
mlir::PassInstrumentor::PassInstrumentor (const PassInstrumentor &) delete
~PassInstrumentor()
PassInstrumentor::~PassInstrumentor () default
Referenced by PassInstrumentor().
Member Function Documentation
addInstrumentation()
void PassInstrumentor::addInstrumentation (std::unique_ptr< PassInstrumentation > pi)
Add the given instrumentation to the collection.
Definition at line 866 of file Pass.cpp.
Referenced by mlir::PassManager::addInstrumentation().
runAfterAnalysis()
void PassInstrumentor::runAfterAnalysis (StringRef name, TypeID id, Operation * op)
See PassInstrumentation::runAfterAnalysis for details.
Definition at line 858 of file Pass.cpp.
Referenced by mlir::detail::AnalysisMap::invalidate().
runAfterPass()
void PassInstrumentor::runAfterPass (Pass * pass, Operation * op)
See PassInstrumentation::runAfterPass for details.
Definition at line 836 of file Pass.cpp.
Referenced by mlir::OpPassManager::getNesting().
runAfterPassFailed()
void PassInstrumentor::runAfterPassFailed (Pass * pass, Operation * op)
See PassInstrumentation::runAfterPassFailed for details.
Definition at line 843 of file Pass.cpp.
Referenced by mlir::OpPassManager::getNesting().
runAfterPipeline()
void PassInstrumentor::runAfterPipeline (StringAttr name, const PassInstrumentation::PipelineParentInfo & parentInfo)
See PassInstrumentation::runAfterPipeline for details.
Definition at line 820 of file Pass.cpp.
Referenced by mlir::OpPassManager::getNesting().
runBeforeAnalysis()
void PassInstrumentor::runBeforeAnalysis (StringRef name, TypeID id, Operation * op)
See PassInstrumentation::runBeforeAnalysis for details.
Definition at line 850 of file Pass.cpp.
Referenced by mlir::detail::AnalysisMap::invalidate().
runBeforePass()
void PassInstrumentor::runBeforePass (Pass * pass, Operation * op)
See PassInstrumentation::runBeforePass for details.
Definition at line 829 of file Pass.cpp.
Referenced by mlir::OpPassManager::getNesting().
runBeforePipeline()
void PassInstrumentor::runBeforePipeline (StringAttr name, const PassInstrumentation::PipelineParentInfo & parentInfo)
See PassInstrumentation::runBeforePipeline for details.
Definition at line 811 of file Pass.cpp.
Referenced by mlir::OpPassManager::getNesting().
The documentation for this class was generated from the following files:
include/mlir/Pass/PassInstrumentation.h
lib/Pass/Pass.cpp