MLIR: mlir::AffineBound Class Reference
mlir::AffineBound Class Reference
AffineBound represents a lower or upper bound in the for operation.
#include "mlir/Dialect/Affine/IR/AffineOps.h"
Public Types
using operand_iterator = AffineForOp::operand_iterator
using operand_range = AffineForOp::operand_range
Public Member Functions
AffineForOp getAffineForOp ()
AffineMap getMap ()
unsigned getNumOperands ()
Value getOperand (unsigned idx)
operand_iterator operandBegin ()
operand_iterator operandEnd ()
operand_range getOperands ()
Friends
class AffineForOp
Detailed Description
AffineBound represents a lower or upper bound in the for operation.
This class does not own the underlying operands. Instead, it refers to the operands stored in the AffineForOp. Its life span should not exceed that of the for operation it refers to.
Definition at line 449 of file AffineOps.h.
Member Typedef Documentation
operand_iterator
using mlir::AffineBound::operand_iterator = AffineForOp::operand_iterator
Definition at line 457 of file AffineOps.h.
operand_range
using mlir::AffineBound::operand_range = AffineForOp::operand_range
Definition at line 458 of file AffineOps.h.
Member Function Documentation
getAffineForOp()
AffineForOp mlir::AffineBound::getAffineForOp () inline
Definition at line 451 of file AffineOps.h.
getMap()
AffineMap mlir::AffineBound::getMap () inline
Definition at line 452 of file AffineOps.h.
Referenced by mlir::coalesceLoops(), constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getNumOperands()
unsigned mlir::AffineBound::getNumOperands () inline
Definition at line 454 of file AffineOps.h.
Referenced by constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperand()
Value mlir::AffineBound::getOperand (unsigned idx) inline
Definition at line 455 of file AffineOps.h.
Referenced by constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperands()
operand_range mlir::AffineBound::getOperands () inline
Definition at line 462 of file AffineOps.h.
Referenced by mlir::coalesceLoops(), and mlir::normalizeAffineFor().
operandBegin()
operand_iterator mlir::AffineBound::operandBegin () inline
Definition at line 460 of file AffineOps.h.
operandEnd()
operand_iterator mlir::AffineBound::operandEnd () inline
Definition at line 461 of file AffineOps.h.
Friends And Related Function Documentation
AffineForOp
friend class AffineForOp friend
Definition at line 476 of file AffineOps.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Affine/IR/AffineOps.h