MLIR: mlir::presburger::LinearTransform Class Reference
mlir::presburger::LinearTransform Class Reference
#include "mlir/Analysis/Presburger/LinearTransform.h"
Public Member Functions
LinearTransform (Matrix &&oMatrix)
LinearTransform (const Matrix &oMatrix)
IntegerRelation applyTo (const IntegerRelation &rel) const
SmallVector< int64_t, 8 > preMultiplyWithRow (ArrayRef< int64_t > rowVec) const
SmallVector< int64_t, 8 > postMultiplyWithColumn (ArrayRef< int64_t > colVec) const
Static Public Member Functions
static std::pair< unsigned, LinearTransform > makeTransformToColumnEchelon (Matrix m)
Detailed Description
Definition at line 23 of file LinearTransform.h.
Constructor & Destructor Documentation
LinearTransform() [1/2]
LinearTransform::LinearTransform (Matrix && oMatrix) explicit
Definition at line 15 of file LinearTransform.cpp.
Referenced by makeTransformToColumnEchelon().
LinearTransform() [2/2]
LinearTransform::LinearTransform (const Matrix & oMatrix) explicit
Definition at line 16 of file LinearTransform.cpp.
Member Function Documentation
applyTo()
IntegerRelation LinearTransform::applyTo (const IntegerRelation & rel) const
Definition at line 115 of file LinearTransform.cpp.
References mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::IntegerRelation::getSpace(), and preMultiplyWithRow().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
makeTransformToColumnEchelon()
std::pair< unsigned, LinearTransform > LinearTransform::makeTransformToColumnEchelon (Matrix m) static
Definition at line 34 of file LinearTransform.cpp.
References mlir::presburger::Matrix::getNumColumns(), mlir::presburger::Matrix::getNumRows(), mlir::presburger::Matrix::identity(), LinearTransform(), modEntryColumnOperation(), mlir::presburger::Matrix::negateColumn(), and mlir::presburger::Matrix::swapColumns().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
postMultiplyWithColumn()
SmallVector<int64_t, 8> mlir::presburger::LinearTransform::postMultiplyWithColumn (ArrayRef< int64_t > colVec) const inline
Definition at line 50 of file LinearTransform.h.
References mlir::presburger::Matrix::postMultiplyWithColumn().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
preMultiplyWithRow()
SmallVector<int64_t, 8> mlir::presburger::LinearTransform::preMultiplyWithRow (ArrayRef< int64_t > rowVec) const inline
Definition at line 43 of file LinearTransform.h.
References mlir::presburger::Matrix::preMultiplyWithRow().
Referenced by applyTo().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/LinearTransform.h
lib/Analysis/Presburger/LinearTransform.cpp