MLIR: mlir::linalg::TileLoopNest Class Reference
mlir::linalg::TileLoopNest Class Reference
A struct to manage the tile loop nest specific information.
#include "mlir/Dialect/Linalg/Utils/Utils.h"
Public Member Functions
TileLoopNest (LinalgOp rootOp)
LogicalResult tileRootOp (OpBuilder &b, ArrayRef< int64_t > tileSizes, ArrayRef< int64_t > tileInterchange, Optional< LinalgLoopDistributionOptions > tileDistribution)
Tile the root operation using the given tileSizes and tileInterchange, and tileDistribution.
FailureOr< LinalgOp > fuseProducer (OpBuilder &b, OpOperand *consumerOpOperand)
Fuse the producer of consumerOpOperand into the tile loop nest.
ValueRange getRootOpReplacementResults ()
Returns the replacement results for the original untiled root operation.
LinalgOp getRootOp ()
Returns the tiled root operation.
SmallVector< LinalgOp > getAllTiledAndFusedOps ()
Returns the tiled root operation and the fused producers.
ArrayRef< scf::ForOp > getLoopOps ()
Returns the loop ops generated from tiling.
bool isEmpty ()
Returns true if the tile loop nest has no tile loops.
Detailed Description
A struct to manage the tile loop nest specific information.
Definition at line 333 of file Utils.h.
Constructor & Destructor Documentation
TileLoopNest()
mlir::linalg::TileLoopNest::TileLoopNest (LinalgOp rootOp) inline
Definition at line 335 of file Utils.h.
Member Function Documentation
fuseProducer()
FailureOr< LinalgOp > TileLoopNest::fuseProducer (OpBuilder & b, OpOperand * consumerOpOperand)
Fuse the producer of consumerOpOperand into the tile loop nest.
Returns the fused producer or fails if fusion is not possible.
Definition at line 328 of file FusionOnTensors.cpp.
References mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::Operation::getResult(), getTiledProducer(), getTiledProducerLoops(), getTiledSliceDims(), mlir::Value::getType(), mlir::Value::getUses(), isEmpty(), mlir::Value::replaceAllUsesExcept(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by mlir::linalg::tileConsumerAndFuseProducers().
getAllTiledAndFusedOps()
SmallVector< LinalgOp > TileLoopNest::getAllTiledAndFusedOps ()
Returns the tiled root operation and the fused producers.
Definition at line 409 of file FusionOnTensors.cpp.
getLoopOps()
ArrayRef<scf::ForOp> mlir::linalg::TileLoopNest::getLoopOps () inline
Returns the loop ops generated from tiling.
Definition at line 358 of file Utils.h.
References mlir::linalg::tileConsumerAndFuseProducers().
getRootOp()
LinalgOp mlir::linalg::TileLoopNest::getRootOp () inline
Returns the tiled root operation.
Definition at line 352 of file Utils.h.
Referenced by mlir::linalg::tileConsumerAndFuseProducers().
getRootOpReplacementResults()
ValueRange TileLoopNest::getRootOpReplacementResults ()
Returns the replacement results for the original untiled root operation.
Definition at line 404 of file FusionOnTensors.cpp.
References isEmpty().
isEmpty()
bool TileLoopNest::isEmpty ()
Returns true if the tile loop nest has no tile loops.
Definition at line 198 of file FusionOnTensors.cpp.
References mlir::Value::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getBackwardSlice(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Operation::getParentOp(), mlir::Value::getUsers(), and mlir::Value::hasOneUse().
Referenced by fuseProducer(), getRootOpReplacementResults(), mlir::linalg::tileConsumerAndFuseProducers(), and tileRootOp().
tileRootOp()
LogicalResult TileLoopNest::tileRootOp (OpBuilder & b, ArrayRef< int64_t > tileSizes, ArrayRef< int64_t > tileInterchange, Optional< LinalgLoopDistributionOptions > tileDistribution)
Tile the root operation using the given tileSizes and tileInterchange, and tileDistribution.
Definition at line 275 of file FusionOnTensors.cpp.
References mlir::detail::enumerate(), mlir::failed(), mlir::failure(), isEmpty(), mlir::linalg::Loops, mlir::linalg::LinalgTilingOptions::setDistributionOptions(), mlir::linalg::LinalgTilingOptions::setInterchange(), mlir::linalg::LinalgTilingOptions::setLoopType(), mlir::linalg::LinalgTilingOptions::setTileSizes(), mlir::success(), and mlir::linalg::tileLinalgOp().
Referenced by mlir::linalg::tileConsumerAndFuseProducers().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Utils/Utils.h
lib/Dialect/Linalg/Transforms/FusionOnTensors.cpp