MLIR: mlir::presburger::Matrix Class Reference
mlir::presburger::Matrix Class Reference
This is a class to represent a resizable matrix.
#include "mlir/Analysis/Presburger/Matrix.h"
Public Member Functions
Matrix ()=delete
Matrix (unsigned rows, unsigned columns, unsigned reservedRows=0, unsigned reservedColumns=0)
Construct a matrix with the specified number of rows and columns.
int64_t & at (unsigned row, unsigned column)
Access the element at the specified row and column.
int64_t at (unsigned row, unsigned column) const
int64_t & operator() (unsigned row, unsigned column)
int64_t operator() (unsigned row, unsigned column) const
void swapColumns (unsigned column, unsigned otherColumn)
Swap the given columns.
void swapRows (unsigned row, unsigned otherRow)
Swap the given rows.
unsigned getNumRows () const
unsigned getNumColumns () const
unsigned getNumReservedRows () const
Return the maximum number of rows/columns that can be added without incurring a reallocation.
unsigned getNumReservedColumns () const
void reserveRows (unsigned rows)
Reserve enough space to resize to the specified number of rows without reallocations.
MutableArrayRef< int64_t > getRow (unsigned row)
Get a [Mutable]ArrayRef corresponding to the specified row.
ArrayRef< int64_t > getRow (unsigned row) const
void insertColumns (unsigned pos, unsigned count)
Insert columns having positions pos, pos + 1, ...
void insertColumn (unsigned pos)
void insertRows (unsigned pos, unsigned count)
Insert rows having positions pos, pos + 1, ...
void insertRow (unsigned pos)
void removeColumns (unsigned pos, unsigned count)
Remove the columns having positions pos, pos + 1, ...
void removeColumn (unsigned pos)
void removeRows (unsigned pos, unsigned count)
Remove the rows having positions pos, pos + 1, ...
void removeRow (unsigned pos)
void copyRow (unsigned sourceRow, unsigned targetRow)
void fillRow (unsigned row, int64_t value)
void addToRow (unsigned sourceRow, unsigned targetRow, int64_t scale)
Add scale multiples of the source row to the target row.
void addToColumn (unsigned sourceColumn, unsigned targetColumn, int64_t scale)
Add scale multiples of the source column to the target column.
void negateColumn (unsigned column)
Negate the specified column.
void negateRow (unsigned row)
Negate the specified row.
int64_t normalizeRow (unsigned row, unsigned nCols)
Divide the first nCols of the specified row by their GCD.
int64_t normalizeRow (unsigned row)
Divide the columns of the specified row by their GCD.
SmallVector< int64_t, 8 > preMultiplyWithRow (ArrayRef< int64_t > rowVec) const
The given vector is interpreted as a row vector v.
SmallVector< int64_t, 8 > postMultiplyWithColumn (ArrayRef< int64_t > colVec) const
The given vector is interpreted as a column vector v.
void resize (unsigned newNRows, unsigned newNColumns)
Resize the matrix to the specified dimensions.
void resizeHorizontally (unsigned newNColumns)
void resizeVertically (unsigned newNRows)
unsigned appendExtraRow ()
Add an extra row at the bottom of the matrix and return its position.
unsigned appendExtraRow (ArrayRef< int64_t > elems)
Same as above, but copy the given elements into the row.
void print (raw_ostream &os) const
Print the matrix.
void dump () const
bool hasConsistentState () const
Return whether the Matrix is in a consistent state with all its invariants satisfied.
Static Public Member Functions
static Matrix identity (unsigned dimension)
Return the identity matrix of the specified dimension.
Detailed Description
This is a class to represent a resizable matrix.
More columns and rows can be reserved than are currently used. The data is stored as a single 1D array, viewed as a 2D matrix with nRows rows and nReservedColumns columns, stored in row major form. Thus the element at (i, j) is stored at data[i*nReservedColumns + j]. The reserved but unused columns always have all zero values. The reserved rows are just reserved space in the underlying SmallVector's capacity.
Definition at line 34 of file Matrix.h.
Constructor & Destructor Documentation
Matrix() [1/2]
mlir::presburger::Matrix::Matrix () delete
Matrix() [2/2]
Matrix::Matrix (unsigned rows, unsigned columns, unsigned reservedRows = 0, unsigned reservedColumns = 0)
Construct a matrix with the specified number of rows and columns.
The number of reserved rows and columns will be at least the number specified, and will always be sufficient to accomodate the number of rows and columns specified.
Initially, the entries are initialized to ero.
Definition at line 16 of file Matrix.cpp.
References max().
Member Function Documentation
addToColumn()
void Matrix::addToColumn (unsigned sourceColumn, unsigned targetColumn, int64_t scale)
Add scale multiples of the source column to the target column.
Definition at line 220 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::presburger::IntegerRelation::eliminateRedundantLocalId(), mlir::presburger::MultiAffineFunction::mergeLocalIds(), modEntryColumnOperation(), and mlir::presburger::IntegerRelation::setAndEliminate().
addToRow()
void Matrix::addToRow (unsigned sourceRow, unsigned targetRow, int64_t scale)
Add scale multiples of the source row to the target row.
Definition at line 213 of file Matrix.cpp.
References at().
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
appendExtraRow() [1/2]
unsigned Matrix::appendExtraRow ()
Add an extra row at the bottom of the matrix and return its position.
Definition at line 65 of file Matrix.cpp.
References resizeVertically().
Referenced by mlir::presburger::IntegerRelation::addBound(), mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::addInequality(), and appendExtraRow().
appendExtraRow() [2/2]
unsigned Matrix::appendExtraRow (ArrayRef< int64_t > elems)
Same as above, but copy the given elements into the row.
The length of elems must be equal to the number of columns.
Definition at line 70 of file Matrix.cpp.
References appendExtraRow(), and at().
at() [1/2]
int64_t & Matrix::at (unsigned row, unsigned column)
Access the element at the specified row and column.
Definition at line 31 of file Matrix.cpp.
Referenced by addToColumn(), addToRow(), appendExtraRow(), copyRow(), fillRow(), insertRows(), negateColumn(), negateRow(), operator()(), postMultiplyWithColumn(), preMultiplyWithRow(), print(), removeColumns(), swapColumns(), and swapRows().
at() [2/2]
int64_t Matrix::at (unsigned row, unsigned column) const
Definition at line 37 of file Matrix.cpp.
copyRow()
void Matrix::copyRow (unsigned sourceRow, unsigned targetRow)
Definition at line 201 of file Matrix.cpp.
References at().
Referenced by insertRows(), mlir::presburger::IntegerRelation::removeRedundantConstraints(), mlir::presburger::IntegerRelation::removeRedundantInequalities(), removeRows(), and mlir::presburger::IntegerRelation::removeTrivialRedundancy().
dump()
void Matrix::dump () const
Definition at line 277 of file Matrix.cpp.
References print().
fillRow()
void Matrix::fillRow (unsigned row, int64_t value)
Definition at line 208 of file Matrix.cpp.
References at(), and value.
Referenced by mlir::presburger::SimplexBase::addZeroRow(), and mlir::presburger::IntegerRelation::removeRedundantInequalities().
getNumColumns()
unsigned Matrix::getNumColumns () const
Definition at line 53 of file Matrix.cpp.
Referenced by mlir::presburger::MultiAffineFunction::isConsistent(), mlir::presburger::LinearTransform::makeTransformToColumnEchelon(), negateRow(), normalizeRow(), postMultiplyWithColumn(), preMultiplyWithRow(), and swapColumns().
getNumReservedColumns()
unsigned Matrix::getNumReservedColumns () const
Definition at line 55 of file Matrix.cpp.
getNumReservedRows()
unsigned Matrix::getNumReservedRows () const
Return the maximum number of rows/columns that can be added without incurring a reallocation.
Definition at line 57 of file Matrix.cpp.
Referenced by mlir::presburger::IntegerRelation::getNumReservedEqualities(), and mlir::presburger::IntegerRelation::getNumReservedInequalities().
getNumRows()
unsigned Matrix::getNumRows () const
Definition at line 51 of file Matrix.cpp.
Referenced by mlir::presburger::IntegerRelation::addBound(), addToColumn(), mlir::presburger::SimplexBase::addZeroRow(), mlir::presburger::IntegerRelation::append(), mlir::presburger::Simplex::findIntegerSample(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::MultiAffineFunction::getNumOutputs(), mlir::presburger::LinearTransform::makeTransformToColumnEchelon(), negateColumn(), postMultiplyWithColumn(), preMultiplyWithRow(), mlir::presburger::GBRSimplex::removeLastEquality(), and swapRows().
getRow() [1/2]
MutableArrayRef< int64_t > Matrix::getRow (unsigned row)
Get a [Mutable]ArrayRef corresponding to the specified row.
Definition at line 113 of file Matrix.cpp.
Referenced by mlir::presburger::Simplex::findIntegerSample(), mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::MultiAffineFunction::isEqualWhereDomainsOverlap(), isRangeDivisibleBy(), normalizeRow(), and mlir::presburger::GBRSimplex::removeLastEquality().
getRow() [2/2]
ArrayRef< int64_t > Matrix::getRow (unsigned row) const
Definition at line 117 of file Matrix.cpp.
hasConsistentState()
bool Matrix::hasConsistentState () const
Return whether the Matrix is in a consistent state with all its invariants satisfied.
Definition at line 279 of file Matrix.cpp.
Referenced by mlir::presburger::IntegerRelation::hasConsistentState().
identity()
Matrix Matrix::identity (unsigned dimension) static
Return the identity matrix of the specified dimension.
Definition at line 24 of file Matrix.cpp.
Referenced by mlir::presburger::Simplex::findIntegerSample(), and mlir::presburger::LinearTransform::makeTransformToColumnEchelon().
insertColumn()
void Matrix::insertColumn (unsigned pos)
Definition at line 121 of file Matrix.cpp.
References insertColumns().
insertColumns()
void Matrix::insertColumns (unsigned pos, unsigned count)
Insert columns having positions pos, pos + 1, ...
pos + count - 1. Columns that were at positions 0 to pos - 1 will stay where they are; columns that were at positions pos to nColumns - 1 will be pushed to the right. pos should be at most nColumns.
Definition at line 122 of file Matrix.cpp.
Referenced by insertColumn(), mlir::presburger::MultiAffineFunction::mergeLocalIds(), and resizeHorizontally().
insertRow()
void Matrix::insertRow (unsigned pos)
Definition at line 177 of file Matrix.cpp.
References insertRows().
insertRows()
void Matrix::insertRows (unsigned pos, unsigned count)
Insert rows having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; rows that were at positions pos to nColumns - 1 will be pushed to the right. pos should be at most nRows.
Definition at line 178 of file Matrix.cpp.
References at(), copyRow(), and resizeVertically().
Referenced by insertRow().
negateColumn()
void Matrix::negateColumn (unsigned column)
Negate the specified column.
Definition at line 228 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::presburger::LinearTransform::makeTransformToColumnEchelon().
negateRow()
void Matrix::negateRow (unsigned row)
Negate the specified row.
Definition at line 233 of file Matrix.cpp.
References at(), and getNumColumns().
Referenced by mlir::presburger::IntegerRelation::removeRedundantInequalities().
normalizeRow() [1/2]
int64_t Matrix::normalizeRow (unsigned row, unsigned nCols)
Divide the first nCols of the specified row by their GCD.
Returns the GCD of the first nCols of the specified row.
Definition at line 238 of file Matrix.cpp.
References getRow(), and mlir::presburger::normalizeRange().
Referenced by mlir::presburger::SimplexBase::addRow(), mlir::presburger::IntegerRelation::gaussianEliminateIds(), mlir::presburger::IntegerRelation::gcdTightenInequalities(), mlir::presburger::IntegerRelation::normalizeConstraintsByGCD(), normalizeRow(), mlir::presburger::SimplexBase::pivot(), and mlir::presburger::IntegerRelation::removeRedundantLocalVars().
normalizeRow() [2/2]
int64_t Matrix::normalizeRow (unsigned row)
Divide the columns of the specified row by their GCD.
Returns the GCD of the columns of the specified row.
Definition at line 242 of file Matrix.cpp.
References getNumColumns(), and normalizeRow().
operator()() [1/2]
int64_t & Matrix::operator() (unsigned row, unsigned column)
Definition at line 43 of file Matrix.cpp.
References at().
operator()() [2/2]
int64_t Matrix::operator() (unsigned row, unsigned column) const
Definition at line 47 of file Matrix.cpp.
References at().
postMultiplyWithColumn()
SmallVector< int64_t, 8 > Matrix::postMultiplyWithColumn (ArrayRef< int64_t > colVec) const
The given vector is interpreted as a column vector v.
Pre-multiply v with this matrix, say M, and return Mv.
Definition at line 258 of file Matrix.cpp.
References at(), getNumColumns(), and getNumRows().
Referenced by mlir::presburger::LinearTransform::postMultiplyWithColumn().
preMultiplyWithRow()
SmallVector< int64_t, 8 > Matrix::preMultiplyWithRow (ArrayRef< int64_t > rowVec) const
The given vector is interpreted as a row vector v.
Post-multiply v with this matrix, say M, and return vM.
Definition at line 247 of file Matrix.cpp.
References at(), getNumColumns(), and getNumRows().
Referenced by mlir::presburger::LinearTransform::preMultiplyWithRow().
print()
void Matrix::print (raw_ostream & os) const
Print the matrix.
Definition at line 269 of file Matrix.cpp.
References at().
Referenced by dump().
removeColumn()
void Matrix::removeColumn (unsigned pos)
Definition at line 163 of file Matrix.cpp.
References removeColumns().
Referenced by mlir::presburger::MultiAffineFunction::mergeLocalIds().
removeColumns()
void Matrix::removeColumns (unsigned pos, unsigned count)
Remove the columns having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; columns that were at positions pos + count - 1 or later will be pushed to the right. The columns to be deleted must be valid rows: pos + count - 1 must be at most nColumns - 1.
Definition at line 164 of file Matrix.cpp.
References at().
Referenced by removeColumn(), and resizeHorizontally().
removeRow()
void Matrix::removeRow (unsigned pos)
Definition at line 191 of file Matrix.cpp.
References removeRows().
Referenced by mlir::presburger::IntegerRelation::removeEquality(), and mlir::presburger::IntegerRelation::removeInequality().
removeRows()
void Matrix::removeRows (unsigned pos, unsigned count)
Remove the rows having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; rows that were at positions pos + count - 1 or later will be pushed to the right. The rows to be deleted must be valid rows: pos + count - 1 must be at most nRows - 1.
Definition at line 192 of file Matrix.cpp.
References copyRow(), and resizeVertically().
Referenced by mlir::presburger::IntegerRelation::removeEqualityRange(), mlir::presburger::IntegerRelation::removeInequalityRange(), and removeRow().
reserveRows()
void Matrix::reserveRows (unsigned rows)
Reserve enough space to resize to the specified number of rows without reallocations.
Definition at line 61 of file Matrix.cpp.
Referenced by mlir::presburger::IntegerRelation::append(), and isRangeDivisibleBy().
resize()
void Matrix::resize (unsigned newNRows, unsigned newNColumns)
Resize the matrix to the specified dimensions.
If a dimension is smaller, the values are truncated; if it is bigger, the new values are initialized to zero.
Due to the representation of the matrix, resizing vertically (adding rows) is less expensive than increasing the number of columns beyond nReservedColumns.
Definition at line 85 of file Matrix.cpp.
References resizeHorizontally(), and resizeVertically().
resizeHorizontally()
void Matrix::resizeHorizontally (unsigned newNColumns)
Definition at line 78 of file Matrix.cpp.
References insertColumns(), and removeColumns().
Referenced by mlir::presburger::SimplexBase::appendVariable(), resize(), and mlir::presburger::SimplexBase::undo().
resizeVertically()
void Matrix::resizeVertically (unsigned newNRows)
Definition at line 90 of file Matrix.cpp.
Referenced by mlir::presburger::SimplexBase::addZeroRow(), appendExtraRow(), mlir::presburger::IntegerRelation::clearConstraints(), insertRows(), mlir::presburger::Simplex::makeProduct(), mlir::presburger::SimplexBase::removeLastConstraintRowOrientation(), mlir::presburger::IntegerRelation::removeRedundantConstraints(), mlir::presburger::IntegerRelation::removeRedundantInequalities(), removeRows(), mlir::presburger::IntegerRelation::removeTrivialRedundancy(), and resize().
swapColumns()
void Matrix::swapColumns (unsigned column, unsigned otherColumn)
Swap the given columns.
Definition at line 104 of file Matrix.cpp.
References at(), and getNumColumns().
Referenced by mlir::presburger::LinearTransform::makeTransformToColumnEchelon(), mlir::presburger::SimplexBase::swapColumns(), and mlir::presburger::IntegerRelation::swapId().
swapRows()
void Matrix::swapRows (unsigned row, unsigned otherRow)
Swap the given rows.
Definition at line 95 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::presburger::GBRSimplex::removeLastEquality(), and mlir::presburger::SimplexBase::swapRows().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Matrix.h
lib/Analysis/Presburger/Matrix.cpp