MLIR: mlir::RewriterBase Class Reference
mlir::RewriterBase Class Reference
This class coordinates the application of a rewrite on a set of IR, providing a way for clients to track mutations and create new operations.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
virtual void inlineRegionBefore (Region &region, Region &parent, Region::iterator before)
Move the blocks that belong to "region" before the given position in another region "parent".
void inlineRegionBefore (Region &region, Block *before)
virtual void cloneRegionBefore (Region &region, Region &parent, Region::iterator before, BlockAndValueMapping &mapping)
Clone the blocks that belong to "region" before the given position in another region "parent".
void cloneRegionBefore (Region &region, Region &parent, Region::iterator before)
void cloneRegionBefore (Region &region, Block *before)
virtual void replaceOpWithIf (Operation *op, ValueRange newValues, bool *allUsesReplaced, llvm::unique_function< bool(OpOperand &) const > functor)
This method replaces the uses of the results of op with the values in newValues when the provided functor returns true for a specific use.
void replaceOpWithIf (Operation *op, ValueRange newValues, llvm::unique_function< bool(OpOperand &) const > functor)
void replaceOpWithinBlock (Operation *op, ValueRange newValues, Block *block, bool *allUsesReplaced=nullptr)
This method replaces the uses of the results of op with the values in newValues when a use is nested within the given block.
virtual void replaceOp (Operation *op, ValueRange newValues)
This method replaces the results of the operation with the specified list of values.
template<typename OpTy , typename... Args>
OpTy replaceOpWithNewOp (Operation *op, Args &&...args)
Replaces the result op with a new op that is created without verification.
virtual void eraseOp (Operation *op)
This method erases an operation that is known to have no uses.
virtual void eraseBlock (Block *block)
This method erases all operations in a block.
virtual void mergeBlocks (Block *source, Block *dest, ValueRange argValues=llvm::None)
Merge the operations of block 'source' into the end of block 'dest'.
void mergeBlockBefore (Block *source, Operation *op, ValueRange argValues=llvm::None)
virtual Block * splitBlock (Block *block, Block::iterator before)
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
virtual void startRootUpdate (Operation *op)
This method is used to notify the rewriter that an in-place operation modification is about to happen.
virtual void finalizeRootUpdate (Operation *op)
This method is used to signal the end of a root update on the given operation.
virtual void cancelRootUpdate (Operation *op)
This method cancels a pending root update.
template<typename CallableT >
void updateRootInPlace (Operation *root, CallableT &&callable)
This method is a utility wrapper around a root update of an operation.
template<typename CallbackT >
std::enable_if_t<!std::is_convertible< CallbackT, Twine >::value, LogicalResult > notifyMatchFailure (Location loc, CallbackT &&reasonCallback)
Used to notify the rewriter that the IR failed to be rewritten because of a match failure, and provide a callback to populate a diagnostic with the reason why the failure occurred.
template<typename CallbackT >
std::enable_if_t<!std::is_convertible< CallbackT, Twine >::value, LogicalResult > notifyMatchFailure (Operation *op, CallbackT &&reasonCallback)
template<typename ArgT >
LogicalResult notifyMatchFailure (ArgT &&arg, const Twine &msg)
template<typename ArgT >
LogicalResult notifyMatchFailure (ArgT &&arg, const char *msg)
Public Member Functions inherited from mlir::OpBuilder
OpBuilder (MLIRContext *ctx, Listener *listener=nullptr)
Create a builder with the given context.
OpBuilder (Region *region, Listener *listener=nullptr)
Create a builder and set the insertion point to the start of the region.
OpBuilder (Region &region, Listener *listener=nullptr)
OpBuilder (Operation *op, Listener *listener=nullptr)
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
OpBuilder (Block *block, Block::iterator insertPoint, Listener *listener=nullptr)
void setListener (Listener *newListener)
Sets the listener of this builder to the one provided.
Listener * getListener () const
Returns the current listener of this builder, or nullptr if this builder doesn't have a listener.
void clearInsertionPoint ()
Reset the insertion point to no location.
InsertPoint saveInsertionPoint () const
Return a saved insertion point.
void restoreInsertionPoint (InsertPoint ip)
Restore the insert point to a previously saved point.
void setInsertionPoint (Block *block, Block::iterator insertPoint)
Set the insertion point to the specified location.
void setInsertionPoint (Operation *op)
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
void setInsertionPointAfter (Operation *op)
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
void setInsertionPointAfterValue (Value val)
Sets the insertion point to the node after the specified value.
void setInsertionPointToStart (Block *block)
Sets the insertion point to the start of the specified block.
void setInsertionPointToEnd (Block *block)
Sets the insertion point to the end of the specified block.
Block * getInsertionBlock () const
Return the block the current insertion point belongs to.
Block::iterator getInsertionPoint () const
Returns the current insertion point of the builder.
Block * getBlock () const
Returns the current block of the builder.
Block * createBlock (Region *parent, Region::iterator insertPt={}, TypeRange argTypes=llvm::None, ArrayRef< Location > locs=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Block * createBlock (Block *insertBefore, TypeRange argTypes=llvm::None, ArrayRef< Location > locs=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Operation * insert (Operation *op)
Insert the given operation at the current insertion point and return it.
Operation * create (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
Operation * create (Location loc, StringAttr opName, ValueRange operands, TypeRange types={}, ArrayRef< NamedAttribute > attributes={}, BlockRange successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
Creates an operation with the given fields.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&...args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&...args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::OneResult >), Value >::type createOrFold (Location location, Args &&...args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::ZeroResult >), OpTy >::type createOrFold (Location location, Args &&...args)
Overload to create or fold a zero result operation.
LogicalResult tryFold (Operation *op, SmallVectorImpl< Value > &results)
Attempts to fold the given operation and places new results within 'results'.
Operation * clone (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (Operation &op)
Operation * cloneWithoutRegions (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of this operation but keep the operation regions empty.
Operation * cloneWithoutRegions (Operation &op)
template<typename OpT >
OpT cloneWithoutRegions (OpT op)
Public Member Functions inherited from mlir::Builder
Builder (MLIRContext *context)
Builder (Operation *op)
MLIRContext * getContext () const
Location getUnknownLoc ()
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getF32Type ()
FloatType getF64Type ()
FloatType getF80Type ()
FloatType getF128Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getI8Type ()
IntegerType getI32Type ()
IntegerType getI64Type ()
IntegerType getIntegerType (unsigned width)
IntegerType getIntegerType (unsigned width, bool isSigned)
FunctionType getFunctionType (TypeRange inputs, TypeRange results)
TupleType getTupleType (TypeRange elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args... args)
Get or construct an instance of the type 'ty' with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (const Twine &bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
Attribute getZeroAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
IntegerAttr getIndexAttr (int64_t value)
IntegerAttr getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
IntegerAttr getUI32IntegerAttr (uint32_t value)
DenseIntElementsAttr getBoolVectorAttr (ArrayRef< bool > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
DenseIntElementsAttr getI64VectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexVectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
DenseIntElementsAttr getI64TensorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexTensorAttr (ArrayRef< int64_t > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getBoolArrayAttr (ArrayRef< bool > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
ArrayAttr getTypeArrayAttr (TypeRange values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Public Member Functions inherited from mlir::OpBuilder::Listener
virtual ~Listener ()
virtual void notifyOperationInserted (Operation *op)
Notification handler for when an operation is inserted into the builder.
virtual void notifyBlockCreated (Block *block)
Notification handler for when a block is created using the builder.
Protected Member Functions
RewriterBase (MLIRContext *ctx)
Initialize the builder with this rewriter as the listener.
RewriterBase (const OpBuilder &otherBuilder)
~RewriterBase () override
virtual void notifyRootReplaced (Operation *op)
These are the callback methods that subclasses can choose to implement if they would like to be notified about certain types of mutations.
virtual void notifyOperationRemoved (Operation *op)
This is called on an operation that a rewrite is removing, right before the operation is deleted.
virtual LogicalResult notifyMatchFailure (Location loc, function_ref< void(Diagnostic &)> reasonCallback)
Notify the rewriter that the pattern failed to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
Additional Inherited Members
Static Public Member Functions inherited from mlir::OpBuilder
static OpBuilder atBlockBegin (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static OpBuilder atBlockEnd (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static OpBuilder atBlockTerminator (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Protected Attributes inherited from mlir::Builder
MLIRContext * context
Detailed Description
This class coordinates the application of a rewrite on a set of IR, providing a way for clients to track mutations and create new operations.
This class serves as a common API for IR mutation between pattern rewrites and non-pattern rewrites, and facilitates the development of shared IR transformation utilities.
Definition at line 398 of file PatternMatch.h.
Constructor & Destructor Documentation
RewriterBase() [1/2]
mlir::RewriterBase::RewriterBase (MLIRContext * ctx) inline explicit protected
Initialize the builder with this rewriter as the listener.
Definition at line 538 of file PatternMatch.h.
RewriterBase() [2/2]
mlir::RewriterBase::RewriterBase (const OpBuilder & otherBuilder) inline explicit protected
Definition at line 539 of file PatternMatch.h.
~RewriterBase()
RewriterBase::~RewriterBase () override protected
Definition at line 204 of file PatternMatch.cpp.
Member Function Documentation
cancelRootUpdate()
virtual void mlir::RewriterBase::cancelRootUpdate (Operation * op) inline virtual
This method cancels a pending root update.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 493 of file PatternMatch.h.
Referenced by collapseGenericOpIterationDims(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), and mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
cloneRegionBefore() [1/3]
void RewriterBase::cloneRegionBefore (Region & region, Region & parent, Region::iterator before, BlockAndValueMapping & mapping) virtual
Clone the blocks that belong to "region" before the given position in another region "parent".
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 351 of file PatternMatch.cpp.
References mlir::Region::cloneInto().
Referenced by mlir::ConversionPatternRewriter::cloneRegionBefore(), collapseGenericOpIterationDims(), fuseWithReshapeByExpansion(), mlir::scf::getParallelForInductionVarOwner(), inlineIfCase(), and inlineWhileCase().
cloneRegionBefore() [2/3]
void RewriterBase::cloneRegionBefore (Region & region, Region & parent, Region::iterator before)
Definition at line 356 of file PatternMatch.cpp.
cloneRegionBefore() [3/3]
void RewriterBase::cloneRegionBefore (Region & region, Block * before)
Definition at line 361 of file PatternMatch.cpp.
References mlir::Block::getParent().
eraseBlock()
void RewriterBase::eraseBlock (Block * block) virtual
This method erases all operations in a block.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 265 of file PatternMatch.cpp.
References mlir::Block::erase(), and mlir::Operation::use_empty().
Referenced by ableToUpdatePredOperands(), mlir::eraseUnreachableBlocks(), inlineIfCase(), inlineWhileCase(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::lowerAffineLowerBound(), and mlir::replaceForOpWithNewYields().
eraseOp()
void RewriterBase::eraseOp (Operation * op) virtual
This method erases an operation that is known to have no uses.
The uses of the given operation must be known to be dead.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 259 of file PatternMatch.cpp.
References mlir::Operation::erase(), and mlir::Operation::use_empty().
Referenced by mlir::scf::buildLoopNest(), deleteDeadness(), doSequentialDispatch(), eachHasOnlyOneOfTypes(), findAncestorOpInRegion(), foldMemRefCast(), mlir::bufferization::foldToMemrefToTensorPair(), foldTransferInBoundsAttribute(), fuseElementwiseOpsImpl(), mlir::linalg::generateLibraryCallName(), getGenericEffectsImpl(), getTargetShape(), inlineIfCase(), inlineWhileCase(), mlir::sparse_tensor::insertYieldOp(), mlir::scf::insideMutuallyExclusiveBranches(), isComputeOperation(), linalgOpToLoopsImpl(), MultiBlockExecuteInliner::matchAndRewrite(), AllocaScopeInliner::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), VectorizeConvolution::matchAndRewrite(), mlir::outlineSingleBlockRegion(), processParallelLoop(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), simplifyBrToBlockWithSinglePred(), mlir::linalg::vectorize(), and verifyAllocLikeOp().
finalizeRootUpdate()
virtual void mlir::RewriterBase::finalizeRootUpdate (Operation * op) inline virtual
This method is used to signal the end of a root update on the given operation.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 489 of file PatternMatch.h.
Referenced by mlir::scf::buildLoopNest(), collapseGenericOpIterationDims(), mlir::scf::getParallelForInductionVarOwner(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::linalg::interchangeGenericOp(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::replaceForOpWithNewYields(), and replaceUnitDimIndexOps().
inlineRegionBefore() [1/2]
void RewriterBase::inlineRegionBefore (Region & region, Region & parent, Region::iterator before) virtual
Move the blocks that belong to "region" before the given position in another region "parent".
Move the blocks that belong to "region" before the given position in another region.
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
The two regions must be different. The caller is in charge to update create the operation transferring the control flow to the region and pass it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 339 of file PatternMatch.cpp.
References mlir::Region::getBlocks().
Referenced by createDecl(), declareReduction(), eachHasOnlyOneOfTypes(), mlir::linalg::generalizeNamedOp(), getGenericEffectsImpl(), mlir::scf::getParallelForInductionVarOwner(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::scf::insideMutuallyExclusiveBranches(), joinShapes(), mlir::lowerAffineLowerBound(), MultiBlockExecuteInliner::matchAndRewrite(), parseInferType(), and mlir::linalg::splitReduction().
inlineRegionBefore() [2/2]
void RewriterBase::inlineRegionBefore (Region & region, Block * before)
Definition at line 343 of file PatternMatch.cpp.
References mlir::Block::getParent().
mergeBlockBefore()
void RewriterBase::mergeBlockBefore (Block * source, Operation * op, ValueRange argValues = llvm::None)
Definition at line 298 of file PatternMatch.cpp.
References mlir::Operation::getBlock(), mlir::Block::hasNoPredecessors(), and mlir::Block::hasNoSuccessors().
Referenced by mlir::scf::buildLoopNest(), mlir::sparse_tensor::insertYieldOp(), AllocaScopeInliner::matchAndRewrite(), mlir::replaceForOpWithNewYields(), and replaceOpWithRegion().
mergeBlocks()
void RewriterBase::mergeBlocks (Block * source, Block * dest, ValueRange argValues = llvm::None) virtual
Merge the operations of block 'source' into the end of block 'dest'.
'source's predecessors must either be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
'source's predecessors must be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 277 of file PatternMatch.cpp.
References mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Block::end(), mlir::Block::erase(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getOperations(), and mlir::Block::getPredecessors().
Referenced by mlir::scf::buildLoopNest(), collapseGenericOpIterationDims(), declareReduction(), eachHasOnlyOneOfTypes(), mlir::scf::getParallelForInductionVarOwner(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::outlineSingleBlockRegion(), and simplifyBrToBlockWithSinglePred().
notifyMatchFailure() [1/5]
template<typename CallbackT > std::enable_if_t<!std::is_convertible<CallbackT, Twine>::value, LogicalResult> mlir::RewriterBase::notifyMatchFailure (Location loc, CallbackT && reasonCallback) inline
Used to notify the rewriter that the IR failed to be rewritten because of a match failure, and provide a callback to populate a diagnostic with the reason why the failure occurred.
This method allows for derived rewriters to optionally hook into the reason why a rewrite failed, and display it to users.
Definition at line 512 of file PatternMatch.h.
References mlir::failure(), and value.
Referenced by mlir::linalg::LinalgTransformationFilter::checkAndNotify(), mlir::tosa::checkHasDynamicBatchDims(), collapseGenericOpIterationDims(), createLinalgBodyCalculationForElementwiseOp(), createReassociationMapsForCollapse(), elementwiseMatchAndRewriteHelper(), extractVector(), foldTransferInBoundsAttribute(), fuseWithReshapeByExpansion(), mlir::linalg::generalizeNamedOp(), getGenericEffectsImpl(), hasaUniqueDim(), inferDynamicDimsForConv(), insertCasts(), mlir::linalg::interchangeGenericOp(), isGenericOpExpandable(), mlir::lowerAffineLowerBound(), mlir::math::ErfPolynomialApproximation::matchAndRewrite(), TransposeOpLowering::matchAndRewrite(), MaterializePadValue::matchAndRewrite(), parseInferType(), processParallelLoop(), reduceMatchAndRewriteHelper(), mlir::linalg::LinalgTileAndFuseTensorOpsPattern::returningMatchAndRewrite(), mlir::linalg::splitReduction(), and mlir::detail::pdl_function_builder::verifyAsArgs().
notifyMatchFailure() [2/5]
template<typename CallbackT > std::enable_if_t<!std::is_convertible<CallbackT, Twine>::value, LogicalResult> mlir::RewriterBase::notifyMatchFailure (Operation * op, CallbackT && reasonCallback) inline
Definition at line 522 of file PatternMatch.h.
References mlir::Operation::getLoc().
notifyMatchFailure() [3/5]
template<typename ArgT > LogicalResult mlir::RewriterBase::notifyMatchFailure (ArgT && arg, const Twine & msg) inline
Definition at line 527 of file PatternMatch.h.
References diag().
notifyMatchFailure() [4/5]
template<typename ArgT > LogicalResult mlir::RewriterBase::notifyMatchFailure (ArgT && arg, const char * msg) inline
Definition at line 532 of file PatternMatch.h.
notifyMatchFailure() [5/5]
virtual LogicalResult mlir::RewriterBase::notifyMatchFailure (Location loc, function_ref< void(Diagnostic &)> reasonCallback) inline protected virtual
Notify the rewriter that the pattern failed to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
This method allows for derived rewriters to optionally hook into the reason why a rewrite failed, and display it to users.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 562 of file PatternMatch.h.
References mlir::failure(), and mlir::PatternBenefit::operator=().
notifyOperationRemoved()
virtual void mlir::RewriterBase::notifyOperationRemoved (Operation * op) inline protected virtual
This is called on an operation that a rewrite is removing, right before the operation is deleted.
At this point, the operation has zero uses.
Definition at line 555 of file PatternMatch.h.
Referenced by mlir::bufferization::bufferizeOp().
notifyRootReplaced()
virtual void mlir::RewriterBase::notifyRootReplaced (Operation * op) inline protected virtual
These are the callback methods that subclasses can choose to implement if they would like to be notified about certain types of mutations.
Notify the rewriter that the specified operation is about to be replaced with another set of operations. This is called before the uses of the operation have been changed.
Definition at line 551 of file PatternMatch.h.
replaceOp()
void RewriterBase::replaceOp (Operation * op, ValueRange newValues) virtual
This method replaces the results of the operation with the specified list of values.
The number of provided values must match the number of results of the operation.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 245 of file PatternMatch.cpp.
References mlir::Operation::erase(), mlir::Operation::getNumResults(), and mlir::Operation::replaceAllUsesWith().
Referenced by mlir::scf::buildLoopNest(), canonicalizeLoopBounds(), collapseGenericOpIterationDims(), computeMemRefRankReductionMask(), createReassociationMapsForCollapse(), eachHasOnlyOneOfTypes(), elementwiseMatchAndRewriteHelper(), mlir::linalg::eliminateInitTensors(), executeGetOperandsResults(), extractVector(), foldInsertAfterInsertSlice(), foldMemRefCast(), mlir::bufferization::foldToMemrefToTensorPair(), foldTransferInBoundsAttribute(), fuseElementwiseOps(), fuseWithReshapeByExpansion(), mlir::linalg::generalizeNamedOp(), generateCollapsedIndexingRegion(), mlir::linalg::generateLibraryCallName(), getGenericEffectsImpl(), mlir::scf::getParallelForInductionVarOwner(), getTargetShape(), mlir::vector::getVectorReductionOp(), inferDynamicDimsForConv(), inlineWhileCase(), insertCasts(), mlir::scf::insideMutuallyExclusiveBranches(), isSumOfMul(), isTrivialSubViewOp(), joinShapes(), linalgOpToLoopsImpl(), mlir::lowerAffineLowerBound(), ConcatOptimization::matchAndRewrite(), ReduceMultiDimReductionRank::matchAndRewrite(), ConvertSameRankInsertStridedSliceIntoShuffle::matchAndRewrite(), TwoDimMultiReductionToElementWise::matchAndRewrite(), NoOpOptimization::matchAndRewrite(), TwoDimMultiReductionToReduction::matchAndRewrite(), AddZeroOptimization::matchAndRewrite(), MulOneOptimization::matchAndRewrite(), AllocaScopeInliner::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::vector::ContractionOpToOuterProductOpLowering::matchAndRewrite(), MaxPool2dIsNoOp::matchAndRewrite(), ClampIsNoOp::matchAndRewrite(), mlir::vector::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), VectorizeConvolution::matchAndRewrite(), TransferReadToVectorLoadLowering::matchAndRewrite(), VectorCreateMaskOpConversion::matchAndRewrite(), SliceCanonicalizer::operator()(), parseInferType(), mlir::replaceForOpWithNewYields(), replaceIndexOpsByInductionVariables(), mlir::bufferization::replaceOpWithBufferizedValues(), replaceOpWithRegion(), mlir::linalg::LinalgPaddingPattern::returningMatchAndRewrite(), PadOpVectorizationWithTransferWritePattern::rewriteUser(), tilePadOp(), updateExpandedGenericOpRegion(), mlir::linalg::vectorize(), mlir::linalg::vectorizeCopy(), and verifyAllocLikeOp().
replaceOpWithIf() [1/2]
void RewriterBase::replaceOpWithIf (Operation * op, ValueRange newValues, bool * allUsesReplaced, llvm::unique_function< bool(OpOperand &) const > functor) virtual
This method replaces the uses of the results of op with the values in newValues when the provided functor returns true for a specific use.
The number of values in newValues is required to match the number of results of op. allUsesReplaced, if non-null, is set to true if all of the uses of op were replaced. Note that in some rewriters, the given 'functor' may be stored beyond the lifetime of the rewrite being applied. As such, the function should not capture by reference and instead use value capture as necessary.
The number of values in newValues is required to match the number of results of op.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 212 of file PatternMatch.cpp.
References mlir::Operation::getNumResults(), and mlir::Operation::getResults().
Referenced by mlir::scf::buildLoopNest().
replaceOpWithIf() [2/2]
void mlir::RewriterBase::replaceOpWithIf (Operation * op, ValueRange newValues, llvm::unique_function< bool(OpOperand &) const > functor) inline
Definition at line 430 of file PatternMatch.h.
replaceOpWithinBlock()
void RewriterBase::replaceOpWithinBlock (Operation * op, ValueRange newValues, Block * block, bool * allUsesReplaced = nullptr)
This method replaces the uses of the results of op with the values in newValues when a use is nested within the given block.
The number of values in newValues is required to match the number of results of op. If all uses of this operation are replaced, the operation is erased.
Definition at line 235 of file PatternMatch.cpp.
References mlir::detail::IROperandBase::getOwner(), mlir::Block::getParentOp(), and mlir::Operation::isProperAncestor().
replaceOpWithNewOp()
template<typename OpTy , typename... Args> OpTy mlir::RewriterBase::replaceOpWithNewOp (Operation * op, Args &&... args) inline
Replaces the result op with a new op that is created without verification.
The result values of the two ops must be the same types.
Definition at line 451 of file PatternMatch.h.
References mlir::Operation::getLoc().
Referenced by addResumeFunction(), mlir::scf::buildLoopNest(), canonicalizeMinMaxOp(), mlir::canonicalizeSetAndOperands(), castBoolToIntN(), castDataPtr(), convertCmpPredicate(), convertStructType(), convertTanhOp(), createConst(), createDecl(), createReassociationMapsForCollapse(), declareReduction(), mlir::ValueDecomposer::decomposeValue(), dropSwitchCasesThatMatchDefault(), eachHasOnlyOneOfTypes(), encodeKernelName(), extractCompositeElement(), extractVector(), findAncestorOpInRegion(), foldExtractStridedOpFromInsertChain(), foldInsertAfterInsertSlice(), foldSwitch(), mlir::bufferization::foldToMemrefToTensorPair(), foldTransferInBoundsAttribute(), getAsValue(), getCanonicalSliceResultType(), getDefaultABIAttrs(), getFirstIntValue(), getGenericEffectsImpl(), mlir::scf::getParallelForInductionVarOwner(), getPermutationMapAttr(), getPtrToElementType(), getReassociationMapForFoldingUnitDims(), getSrcVectorElementType(), hasaUniqueDim(), mlir::ComplexStructBuilder::imaginary(), inferDynamicDimsForConv(), insertCasts(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::linalg::interchangeGenericOp(), isBoolScalarOrVector(), mlir::vector::isBroadcastableTo(), isTrivialSubViewOp(), joinShapes(), linalgOpToLoopsImpl(), mlir::lowerAffineLowerBound(), matchAndReplaceDepthwiseConv(), mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite(), InnerOuterDimReductionConversion::matchAndRewrite(), TransferReadPermutationLowering::matchAndRewrite(), DecomposeDifferentRankInsertStridedSlice::matchAndRewrite(), mlir::GPUReturnOpLowering::matchAndRewrite(), ConcatOptimization::matchAndRewrite(), ReduceMultiDimReductionRank::matchAndRewrite(), ReshapeReshapeOptimization::matchAndRewrite(), ReshapeConstOptimization::matchAndRewrite(), TransferWritePermutationLowering::matchAndRewrite(), mlir::ComposeReassociativeReshapeOps< ReshapeOpTy >::matchAndRewrite(), ConstantTransposeOptimization::matchAndRewrite(), Convert1DExtractStridedSliceIntoShuffle::matchAndRewrite(), TransferOpReduceRank::matchAndRewrite(), mlir::ComposeCollapseOfExpandOp< CollapseOpTy, ExpandOpTy >::matchAndRewrite(), mlir::ComposeExpandOfCollapseOp< ExpandOpTy, CollapseOpTy >::matchAndRewrite(), ConvertAddressOf::matchAndRewrite(), OneDimMultiReductionToTwoDim::matchAndRewrite(), ConvertAccessChain::matchAndRewrite(), MaterializePadValue::matchAndRewrite(), ConvertStore::matchAndRewrite(), ClampClampOptimization::matchAndRewrite(), YieldOpLowering::matchAndRewrite(), mlir::linalg::PadOpTransformationPattern::matchAndRewrite(), mlir::linalg::GeneralizePadOpPattern::matchAndRewrite(), SelectI1Simplify::matchAndRewrite(), SelectToExtUI::matchAndRewrite(), TransferReadToVectorLoadLowering::matchAndRewrite(), VectorLoadToMemrefLoadLowering::matchAndRewrite(), VectorStoreToMemrefStoreLowering::matchAndRewrite(), TransferWriteToVectorStoreLowering::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), BubbleDownVectorBitCastForExtract::matchAndRewrite(), BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), BubbleUpBitCastForStridedSliceInsert::matchAndRewrite(), DeduplicateAffineMinMaxExpressions< T >::matchAndRewrite(), MergeAffineMinMaxOp< T >::matchAndRewrite(), CanonicalizeAffineMinMaxOpExprAndTermOrder< T >::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), SubViewCanonicalizer::operator()(), outlineExecuteOp(), parseInferType(), reduceMatchAndRewriteHelper(), replaceTransferOpWithMubuf(), replaceUnitDimIndexOps(), replaceWithLoadOrStore(), reshapeLowerToHigher(), PadOpVectorizationWithTransferWritePattern::rewriteUser(), PadOpVectorizationWithInsertSlicePattern::rewriteUser(), mlir::DataDescriptor::setSize(), simplifyPassThroughBr(), simplifyPassThroughSwitch(), simplifySwitchFromDefaultSwitchOnSameCondition(), simplifySwitchFromSwitchOnSameCondition(), simplifySwitchWithOnlyDefault(), splatZero(), GenericPadOpVectorizationPattern::tryVectorizeCopy(), verifyTensorReshapeOp(), and wrapExternalFunction().
splitBlock()
Block * RewriterBase::splitBlock (Block * block, Block::iterator before) virtual
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 320 of file PatternMatch.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResults(), and mlir::Block::splitBlock().
Referenced by declareReduction(), eachHasOnlyOneOfTypes(), MultiBlockExecuteInliner::matchAndRewrite(), and mlir::ConversionPatternRewriter::splitBlock().
startRootUpdate()
virtual void mlir::RewriterBase::startRootUpdate (Operation * op) inline virtual
This method is used to notify the rewriter that an in-place operation modification is about to happen.
A call to this function must be followed by a call to either finalizeRootUpdate or cancelRootUpdate. This is a minor efficiency win (it avoids creating a new operation and removing the old one) but also often allows simpler code in the client.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 484 of file PatternMatch.h.
Referenced by mlir::scf::buildLoopNest(), collapseGenericOpIterationDims(), mlir::scf::getParallelForInductionVarOwner(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::linalg::interchangeGenericOp(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::replaceForOpWithNewYields(), and replaceUnitDimIndexOps().
updateRootInPlace()
template<typename CallableT > void mlir::RewriterBase::updateRootInPlace (Operation * root, CallableT && callable) inline
This method is a utility wrapper around a root update of an operation.
It wraps calls to startRootUpdate and finalizeRootUpdate around the given callable.
Definition at line 499 of file PatternMatch.h.
References value.
Referenced by mlir::TypeConverter::convertBlockSignature(), mlir::ValueDecomposer::decomposeValue(), foldTransferInBoundsAttribute(), mlir::scf::insideMutuallyExclusiveBranches(), isComputeOperation(), isGpuAsyncTokenType(), isShapePreserving(), lowerEntryPointABIAttr(), ReshapeConstOptimization::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), MaterializeTransferMask< ConcreteOp >::matchAndRewrite(), parseInferType(), peelForLoop(), mlir::populateCallOpTypeConversionPattern(), PadOpVectorizationWithTransferReadPattern::rewriteUser(), and simplifyPassThroughBr().
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp