MLIR: mlir::presburger::IntegerPolyhedron Class Reference
mlir::presburger::IntegerPolyhedron Class Reference
An IntegerPolyhedron represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
#include "mlir/Analysis/Presburger/IntegerRelation.h"
Public Member Functions
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a set reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
Kind getKind () const override
Return the kind of this IntegerRelation.
std::unique_ptr< IntegerPolyhedron > clone () const
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1) override
Insert num identifiers of the specified kind at position pos.
SymbolicLexMin findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the polyhedron.
Public Member Functions inherited from mlir::presburger::IntegerRelation
IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a relation reserving memory for the specified number of constraints and identifiers.
IntegerRelation (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
virtual ~IntegerRelation ()=default
std::unique_ptr< IntegerRelation > clone () const
const PresburgerSpace & getSpace () const
Returns a reference to the underlying space.
PresburgerSpace getSpaceWithoutLocals () const
Returns a copy of the space without locals.
void append (const IntegerRelation &other)
Appends constraints from other into this.
IntegerRelation intersect (IntegerRelation other) const
Return the intersection of the two sets.
bool isEqual (const IntegerRelation &other) const
Return whether this and other are equal.
bool isSubsetOf (const IntegerRelation &other) const
Return whether this is a subset of the given IntegerRelation.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumDomainIds () const
unsigned getNumRangeIds () const
unsigned getNumSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumDimIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIds () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
IdKind getIdKindAt (unsigned pos) const
Return the IdKind of the id at the specified position.
CountsSnapshot getCounts () const
void truncate (const CountsSnapshot &counts)
unsigned appendId (IdKind kind, unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
virtual void eliminateRedundantLocalId (unsigned posA, unsigned posB)
Eliminate the posB^th local identifier, replacing every instance of it with the posA^th local identifier.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
virtual void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
MaybeOptimum< SmallVector< Fraction, 8 > > findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
MaybeOptimum< SmallVector< int64_t, 8 > > findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
virtual void swapId (unsigned posA, unsigned posB)
Swap the posA^th identifier with the posB^th identifier.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
virtual void clearAndCopyFrom (const IntegerRelation &other)
Replaces the contents of this IntegerRelation with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Optional< uint64_t > computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
Optional< SmallVector< int64_t, 8 > > containsPointNoLocal (ArrayRef< int64_t > point) const
Given the values of non-local ids, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< MaybeLocalRepr > &repr) const
Find equality and pairs of inequality contraints identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< MaybeLocalRepr > &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const IntegerRelation &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void removeDuplicateDivs ()
void convertIdKind (IdKind srcKind, unsigned idStart, unsigned idLimit, IdKind dstKind)
Converts identifiers of kind srcKind in the range [idStart, idLimit) to variables of kind dstKind and placed after all the other variables of kind dstKind.
void convertToLocal (IdKind kind, unsigned idStart, unsigned idLimit)
unsigned mergeLocalIds (IntegerRelation &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static IntegerPolyhedron getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Static Public Member Functions inherited from mlir::presburger::IntegerRelation
static IntegerRelation getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Additional Inherited Members
Public Types inherited from mlir::presburger::IntegerRelation
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints, Kind::IntegerRelation, Kind::IntegerPolyhedron }
All derived classes of IntegerRelation.
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Protected Member Functions inherited from mlir::presburger::IntegerRelation
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void printSpace (raw_ostream &os) const
Prints the number of constraints, dimensions, symbols and locals in the IntegerRelation.
void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void truncateIdKind (IdKind kind, unsigned num)
Truncate the ids of the specified kind to the specified number by dropping some ids at the end.
void truncateIdKind (IdKind kind, const CountsSnapshot &counts)
Truncate the ids to the number in the space of the specified CountsSnapshot.
Protected Attributes inherited from mlir::presburger::IntegerRelation
PresburgerSpace space
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes inherited from mlir::presburger::IntegerRelation
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
An IntegerPolyhedron represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
Affine constraints can be inequalities or equalities in the form:
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n >= 0 Equality : c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n == 0
where c_0, c_1, ..., c_n are integers and n is the total number of identifiers in the space.
An IntegerPolyhedron is similar to an IntegerRelation but it does not make a distinction between Domain and Range identifiers. Internally, IntegerPolyhedron is implemented as a IntegerRelation with zero domain ids.
Since IntegerPolyhedron does not make a distinction between kinds of dimensions, IdKind::SetDim should be used to refer to dimension identifiers.
Definition at line 626 of file IntegerRelation.h.
Constructor & Destructor Documentation
IntegerPolyhedron() [1/2]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace & space) inline
Constructs a set reserving memory for the specified number of constraints and identifiers.
Definition at line 630 of file IntegerRelation.h.
References mlir::presburger::PresburgerSpace::getNumDomainIds().
Referenced by mlir::FlatAffineValueConstraints::FlatAffineValueConstraints().
IntegerPolyhedron() [2/2]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (const PresburgerSpace & space) inline explicit
Constructs a relation with the specified number of dimensions and symbols.
Definition at line 641 of file IntegerRelation.h.
Member Function Documentation
classof()
static bool mlir::presburger::IntegerPolyhedron::classof (const IntegerRelation * cst) inline static
Definition at line 655 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::clone(), mlir::presburger::IntegerRelation::getKind(), mlir::presburger::IntegerRelation::insertId(), and mlir::presburger::IntegerRelation::IntegerPolyhedron.
clone()
std::unique_ptr< IntegerPolyhedron > IntegerPolyhedron::clone () const
Definition at line 37 of file IntegerRelation.cpp.
findSymbolicIntegerLexMin()
SymbolicLexMin IntegerPolyhedron::findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the polyhedron.
This finds, for every assignment to the symbols, the lexicographically minimum value attained by the dimensions. For example, the symbolic lexmin of the set
(x, y)[a, b, c] : (a <= x, b <= x, x <= c)
can be written as
x = a if b <= a, a <= c x = b if a < b, b <= c
This function is stored in the lexmin function in the result. Some assignments to the symbols might make the set empty. Such points are not part of the function's domain. In the above example, this happens when max(a, b) > c.
For some values of the symbols, the lexmin may be unbounded. SymbolicLexMin stores these parts of the symbolic domain in a separate PresburgerSet, unboundedDomain.
Definition at line 155 of file IntegerRelation.cpp.
References mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), mlir::presburger::IntegerRelation::getNumLocalIds(), mlir::presburger::PWMAFunction::getNumOutputs(), mlir::presburger::IntegerRelation::getNumSymbolIds(), mlir::presburger::PresburgerSpace::getSetSpace(), mlir::presburger::SymbolicLexMin::lexmin, and mlir::presburger::PWMAFunction::truncateOutput().
getKind()
Kind mlir::presburger::IntegerPolyhedron::getKind () const inline override virtual
Return the kind of this IntegerRelation.
Reimplemented from mlir::presburger::IntegerRelation.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 653 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerPolyhedron.
getUniverse()
static IntegerPolyhedron mlir::presburger::IntegerPolyhedron::getUniverse (const PresburgerSpace & space) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 648 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerPolyhedron.
insertId()
unsigned IntegerPolyhedron::insertId (IdKind kind, unsigned pos, unsigned num = 1) override virtual
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Reimplemented from mlir::presburger::IntegerRelation.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 2103 of file IntegerRelation.cpp.
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/IntegerRelation.h
lib/Analysis/Presburger/IntegerRelation.cpp