MLIR: mlir::AsmParser Class Reference
mlir::AsmParser Class Reference abstract
This base class exposes generic asm parser hooks, usable across the various derived parsers.
#include "mlir/IR/OpImplementation.h"
Public Types
enum Delimiter {
Delimiter::None, Delimiter::Paren, Delimiter::Square, Delimiter::LessGreater,
Delimiter::Braces, Delimiter::OptionalParen, Delimiter::OptionalSquare, Delimiter::OptionalLessGreater,
Delimiter::OptionalBraces
}
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList.
template<typename AttrType >
using has_parse_method = decltype(AttrType::parse(std::declval< AsmParser & >(), std::declval< Type >()))
Trait to check if AttrType provides a parse method.
template<typename AttrType >
using detect_has_parse_method = llvm::is_detected< has_parse_method, AttrType >
template<typename TypeT >
using type_has_parse_method = decltype(TypeT::parse(std::declval< AsmParser & >()))
Trait to check if TypeT provides a parse method.
template<typename TypeT >
using detect_type_has_parse_method = llvm::is_detected< type_has_parse_method, TypeT >
Public Member Functions
AsmParser ()=default
virtual ~AsmParser ()
MLIRContext * getContext () const
virtual SMLoc getNameLoc () const =0
Return the location of the original name token.
virtual InFlightDiagnostic emitError (SMLoc loc, const Twine &message={})=0
Emit a diagnostic at the specified location and return failure.
virtual Builder & getBuilder () const =0
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
virtual SMLoc getCurrentLocation ()=0
Get the location of the next token and store it into the argument.
ParseResult getCurrentLocation (SMLoc *loc)
virtual Location getEncodedSourceLoc (SMLoc loc)=0
Re-encode the given source location as an MLIR location and return it.
virtual ParseResult parseArrow ()=0
Parse a '->' token.
virtual ParseResult parseOptionalArrow ()=0
Parse a '->' token if present.
virtual ParseResult parseLBrace ()=0
Parse a { token.
virtual ParseResult parseOptionalLBrace ()=0
Parse a { token if present.
virtual ParseResult parseRBrace ()=0
Parse a } token.
virtual ParseResult parseOptionalRBrace ()=0
Parse a } token if present.
virtual ParseResult parseColon ()=0
Parse a : token.
virtual ParseResult parseOptionalColon ()=0
Parse a : token if present.
virtual ParseResult parseComma ()=0
Parse a , token.
virtual ParseResult parseOptionalComma ()=0
Parse a , token if present.
virtual ParseResult parseEqual ()=0
Parse a = token.
virtual ParseResult parseOptionalEqual ()=0
Parse a = token if present.
virtual ParseResult parseLess ()=0
Parse a '<' token.
virtual ParseResult parseOptionalLess ()=0
Parse a '<' token if present.
virtual ParseResult parseGreater ()=0
Parse a '>' token.
virtual ParseResult parseOptionalGreater ()=0
Parse a '>' token if present.
virtual ParseResult parseQuestion ()=0
Parse a '?' token.
virtual ParseResult parseOptionalQuestion ()=0
Parse a '?' token if present.
virtual ParseResult parsePlus ()=0
Parse a '+' token.
virtual ParseResult parseOptionalPlus ()=0
Parse a '+' token if present.
virtual ParseResult parseStar ()=0
Parse a '*' token.
virtual ParseResult parseOptionalStar ()=0
Parse a '*' token if present.
virtual ParseResult parseVerticalBar ()=0
Parse a '|' token.
virtual ParseResult parseOptionalVerticalBar ()=0
Parse a '|' token if present.
ParseResult parseString (std::string *string)
Parse a quoted string token.
virtual ParseResult parseOptionalString (std::string *string)=0
Parse a quoted string token if present.
ParseResult parseKeyword (StringRef keyword, const Twine &msg="")
Parse a given keyword.
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef keyword)=0
Parse the given keyword if present.
virtual ParseResult parseOptionalKeyword (StringRef *keyword)=0
Parse a keyword, if present, into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef *keyword, ArrayRef< StringRef > allowedValues)=0
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
ParseResult parseKeywordOrString (std::string *result)
Parse a keyword or a quoted string.
virtual ParseResult parseOptionalKeywordOrString (std::string *result)=0
Parse an optional keyword or string.
virtual ParseResult parseLParen ()=0
Parse a (token.
virtual ParseResult parseOptionalLParen ()=0
Parse a (token if present.
virtual ParseResult parseRParen ()=0
Parse a) token.
virtual ParseResult parseOptionalRParen ()=0
Parse a) token if present.
virtual ParseResult parseLSquare ()=0
Parse a [ token.
virtual ParseResult parseOptionalLSquare ()=0
Parse a [ token if present.
virtual ParseResult parseRSquare ()=0
Parse a ] token.
virtual ParseResult parseOptionalRSquare ()=0
Parse a ] token if present.
virtual ParseResult parseOptionalEllipsis ()=0
Parse a ... token if present;.
virtual ParseResult parseFloat (double &result)=0
Parse a floating point value from the stream.
template<typename IntT >
ParseResult parseInteger (IntT &result)
Parse an integer value from the stream.
virtual OptionalParseResult parseOptionalInteger (APInt &result)=0
Parse an optional integer value from the stream.
template<typename IntT >
OptionalParseResult parseOptionalInteger (IntT &result)
virtual ParseResult parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElementFn, StringRef contextMessage=StringRef())=0
Parse a list of comma-separated items with an optional delimiter.
ParseResult parseCommaSeparatedList (function_ref< ParseResult()> parseElementFn)
Parse a comma separated list of elements that must have at least one entry in it.
template<typename T , typename... ParamsT>
T getChecked (SMLoc loc, ParamsT &&...params)
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
template<typename T , typename... ParamsT>
T getChecked (ParamsT &&...params)
A variant of getChecked that uses the result of getNameLoc to emit errors.
virtual ParseResult parseAttribute (Attribute &result, Type type={})=0
Parse an arbitrary attribute of a given type and return it in result.
virtual ParseResult parseCustomAttributeWithFallback (Attribute &result, Type type, function_ref< ParseResult(Attribute &result, Type type)> parseAttribute)=0
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type={})
Parse an attribute of a specific kind and type.
ParseResult parseAttribute (Attribute &result, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an attribute of a specific kind and type.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute of a given type and populate it in result.
template<typename AttrType >
std::enable_if_t< detect_has_parse_method< AttrType >::value, ParseResult > parseCustomAttributeWithFallback (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse a custom attribute of a given type unless the next token is #, in which case the generic parser is invoked.
template<typename AttrType >
std::enable_if_t<!detect_has_parse_method< AttrType >::value, ParseResult > parseCustomAttributeWithFallback (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
SFINAE parsing method for Attribute that don't implement a parse method.
template<typename AttrType >
std::enable_if_t< detect_has_parse_method< AttrType >::value, ParseResult > parseCustomAttributeWithFallback (AttrType &result)
Parse a custom attribute of a given type unless the next token is #, in which case the generic parser is invoked.
template<typename AttrType >
std::enable_if_t<!detect_has_parse_method< AttrType >::value, ParseResult > parseCustomAttributeWithFallback (AttrType &result)
SFINAE parsing method for Attribute that don't implement a parse method.
virtual OptionalParseResult parseOptionalAttribute (Attribute &result, Type type={})=0
Parse an arbitrary optional attribute of a given type and return it in result.
virtual OptionalParseResult parseOptionalAttribute (ArrayAttr &result, Type type={})=0
Parse an optional array attribute and return it in result.
virtual OptionalParseResult parseOptionalAttribute (StringAttr &result, Type type={})=0
Parse an optional string attribute and return it in result.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
virtual ParseResult parseOptionalAttrDict (NamedAttrList &result)=0
Parse a named dictionary into 'result' if it is present.
virtual ParseResult parseOptionalAttrDictWithKeyword (NamedAttrList &result)=0
Parse a named dictionary into 'result' if the attributes keyword is present.
virtual ParseResult parseAffineMap (AffineMap &map)=0
Parse an affine map instance into 'map'.
virtual ParseResult printIntegerSet (IntegerSet &set)=0
Parse an integer set instance into 'set'.
ParseResult parseSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)=0
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseType (Type &result)=0
Parse a type.
virtual ParseResult parseCustomTypeWithFallback (Type &result, function_ref< ParseResult(Type &result)> parseType)=0
Parse a custom type with the provided callback, unless the next token is #, in which case the generic parser is invoked.
virtual OptionalParseResult parseOptionalType (Type &result)=0
Parse an optional type.
template<typename TypeT >
ParseResult parseType (TypeT &result)
Parse a type of a specific type.
template<typename TypeT >
std::enable_if_t< detect_type_has_parse_method< TypeT >::value, ParseResult > parseCustomTypeWithFallback (TypeT &result)
Parse a custom Type of a given type unless the next token is #, in which case the generic parser is invoked.
template<typename TypeT >
std::enable_if_t<!detect_type_has_parse_method< TypeT >::value, ParseResult > parseCustomTypeWithFallback (TypeT &result)
SFINAE parsing method for Type that don't implement a parse method.
ParseResult parseTypeList (SmallVectorImpl< Type > &result)
Parse a type list.
virtual ParseResult parseArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an arrow followed by a type list.
virtual ParseResult parseOptionalArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional arrow followed by a type list.
virtual ParseResult parseColonType (Type &result)=0
Parse a colon followed by a type.
template<typename TypeType >
ParseResult parseColonType (TypeType &result)
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
virtual ParseResult parseColonTypeList (SmallVectorImpl< Type > &result)=0
Parse a colon followed by a type list, which must have at least one type.
virtual ParseResult parseOptionalColonTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional colon followed by a type list, which if present must have at least one type.
ParseResult parseKeywordType (const char *keyword, Type &result)
Parse a keyword followed by a type.
ParseResult addTypeToList (Type type, SmallVectorImpl< Type > &result)
Add the specified type to the end of the specified type list and return success.
ParseResult addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > &result)
Add the specified types to the end of the specified type list and return success.
virtual ParseResult parseDimensionList (SmallVectorImpl< int64_t > &dimensions, bool allowDynamic=true)=0
Parse a 'x' separated dimension list.
virtual ParseResult parseXInDimensionList ()=0
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
Detailed Description
This base class exposes generic asm parser hooks, usable across the various derived parsers.
Definition at line 362 of file OpImplementation.h.
Member Typedef Documentation
detect_has_parse_method
template<typename AttrType > using mlir::AsmParser::detect_has_parse_method = llvm::is_detected<has_parse_method, AttrType>
Definition at line 720 of file OpImplementation.h.
detect_type_has_parse_method
template<typename TypeT > using mlir::AsmParser::detect_type_has_parse_method = llvm::is_detected<type_has_parse_method, TypeT>
Definition at line 898 of file OpImplementation.h.
has_parse_method
template<typename AttrType > using mlir::AsmParser::has_parse_method = decltype(AttrType::parse(std::declval<AsmParser &>(), std::declval<Type>()))
Trait to check if AttrType provides a parse method.
Definition at line 718 of file OpImplementation.h.
type_has_parse_method
template<typename TypeT > using mlir::AsmParser::type_has_parse_method = decltype(TypeT::parse(std::declval<AsmParser &>()))
Trait to check if TypeT provides a parse method.
Definition at line 895 of file OpImplementation.h.
Member Enumeration Documentation
Delimiter
enum mlir::AsmParser::Delimiter strong
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList.
Enumerator
None
Zero or more operands with no delimiters.
Paren
Parens surrounding zero or more operands.
Square
Square brackets surrounding zero or more operands.
LessGreater
<> brackets surrounding zero or more operands.
Braces
{} brackets surrounding zero or more operands.
OptionalParen
Parens supporting zero or more operands, or nothing.
OptionalSquare
Square brackets supporting zero or more ops, or nothing.
OptionalLessGreater
<> brackets supporting zero or more ops, or nothing.
OptionalBraces
{} brackets surrounding zero or more operands, or nothing.
Definition at line 588 of file OpImplementation.h.
Constructor & Destructor Documentation
AsmParser()
mlir::AsmParser::AsmParser () default
~AsmParser()
AsmParser::~AsmParser () virtual default
Referenced by mlir::OperationName::dump().
Member Function Documentation
addTypesToList()
ParseResult mlir::AsmParser::addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > & result) inline
Add the specified types to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 993 of file OpImplementation.h.
References mlir::success().
Referenced by verifyAtomicCompareExchangeImpl().
addTypeToList()
ParseResult mlir::AsmParser::addTypeToList (Type type, SmallVectorImpl< Type > & result) inline
Add the specified type to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 985 of file OpImplementation.h.
References mlir::success().
Referenced by foldTransferInBoundsAttribute(), parseAffineMinMaxOp(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), parseGroupNonUniformArithmeticOp(), parseOneResultSameOperandTypeOp(), printNVVMIntrinsicOp(), printTransferAttrs(), mlir::replaceForOpWithNewYields(), and verifyAtomicCompareExchangeImpl().
emitError()
virtual InFlightDiagnostic mlir::AsmParser::emitError (SMLoc loc, const Twine & message = {}) pure virtual
Emit a diagnostic at the specified location and return failure.
Referenced by acceptBitWidth(), applyTilingToAll(), buildLLVMFunctionType(), mlir::pdl::PDLType::classof(), computeMemRefRankReductionMask(), eachHasOnlyOneOfTypes(), foldTransferInBoundsAttribute(), mlir::DynamicOpDefinition::get(), getElementType(), getInsertExtractValueElementType(), getLoadStoreElementType(), getOption(), mlir::scf::getParallelForInductionVarOwner(), hasOneBranchOpTo(), isZeroAttribute(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAllReduceOperation(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), parseAsyncDependencies(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), mlir::Dialect::parseAttribute(), parseAttributions(), parseBound(), parseCalibratedType(), parseClauseAttr(), parseCooperativeMatrixType(), parseEnumStrAttr(), parseExpressedTypeAndRange(), parseFunctionArgumentList(), mlir::function_interface_impl::parseFunctionOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseInterfaceVarABIAttr(), parseMatrixType(), parseNamedStructuredOpRegion(), parseOneResultSameOperandTypeOp(), parseOptionalArrayStride(), parseOptionalLLVMKeyword(), parsePDLType(), parsePointerType(), parseScheduleClause(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseStructType(), parseSynchronizationHint(), parseTargetEnvAttr(), mlir::Dialect::parseType(), parseUniformType(), parseVerCapExtAttr(), mlir::DataLayoutSpecAttr::print(), printInitializationList(), printTransferAttrs(), mlir::replaceForOpWithNewYields(), verifyAtomicCompareExchangeImpl(), verifyConstantType(), verifyDimAndSymbolIdentifiers(), and verifyScheduleModifiers().
getBuilder()
virtual Builder& mlir::AsmParser::getBuilder () const pure virtual
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
Referenced by applyTilingToAll(), buildLLVMFunctionType(), computeMemRefRankReductionMask(), eachHasOnlyOneOfTypes(), foldTransferInBoundsAttribute(), getLoadStoreElementType(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), isComputeOperation(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineMinMaxOp(), parseAsyncDependencies(), parseAttributions(), parseBound(), parseCmpOp(), parseCommonStructuredOpParts(), parseControlAttribute(), parseCreateOperationOpAttributes(), parseCreateOperationOpResults(), mlir::parseDimAndSymbolList(), parseEnumKeywordAttr(), parseEnumStrAttr(), mlir::function_interface_impl::parseFunctionOp(), parseGEPIndices(), parseGlobalMemrefOpTypeAndInitialValue(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseMemoryAccessAttributes(), parseOperandsOrIntegersImpl(), parseOperationOpAttributes(), parseOptionalLLVMKeyword(), mlir::impl::parseOptionalVisibilityKeyword(), parseResultsValueType(), parseScheduleClause(), parseSizeAssignment(), parseSourceMemoryAccessAttributes(), parseStorageType(), parseSynchronizationHint(), parseVariableDecorations(), parseVerCapExtAttr(), parseWsLoopControl(), printInitializationList(), printTransferAttrs(), printWsLoopControl(), mlir::replaceForOpWithNewYields(), verifyAllocLikeOp(), verifyAtomicCompareExchangeImpl(), verifyAttributions(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyDimAndSymbolIdentifiers(), verifyMemoryOpIndexing(), verifyPointerAndCoopMatrixType(), and verifyVectorMemoryOp().
getChecked() [1/2]
template<typename T , typename... ParamsT> T mlir::AsmParser::getChecked (SMLoc loc, ParamsT &&... params) inline
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
Note that unlike OpBuilder::getType, this method does not implicitly insert a context parameter.
Definition at line 636 of file OpImplementation.h.
References mlir::emitError().
Referenced by acceptBitWidth(), mlir::DynamicAttr::parse(), mlir::DynamicType::parse(), parseAnyType(), parseCalibratedType(), and parseUniformType().
getChecked() [2/2]
template<typename T , typename... ParamsT> T mlir::AsmParser::getChecked (ParamsT &&... params) inline
A variant of getChecked that uses the result of getNameLoc to emit errors.
Definition at line 643 of file OpImplementation.h.
References mlir::emitError(), and mlir::parseAttribute().
getContext()
MLIRContext * AsmParser::getContext () const
Definition at line 63 of file AsmPrinter.cpp.
References mlir::DialectAsmPrinter::~DialectAsmPrinter(), and mlir::OpAsmPrinter::~OpAsmPrinter().
Referenced by acceptBitWidth(), buildLLVMFunctionType(), getOption(), mlir::DataLayoutSpecAttr::parse(), parseAllReduceOperation(), parseClauseAttr(), parseFunctionArgumentList(), parseGlobalMemrefOpTypeAndInitialValue(), parseImageOperands(), parseNamedStructuredOpRegion(), parseOptionalLLVMKeyword(), parseReductionVarList(), parseScheduleClause(), printNVVMIntrinsicOp(), and verifyCoopMatrixMulAdd().
getCurrentLocation() [1/2]
virtual SMLoc mlir::AsmParser::getCurrentLocation () pure virtual
Get the location of the next token and store it into the argument.
This always succeeds.
Referenced by applyTilingToAll(), mlir::pdl::PDLType::classof(), foldTransferInBoundsAttribute(), mlir::DynamicOpDefinition::get(), getElementPtrType(), getGenericEffectsImpl(), getInsertExtractValueElementType(), getLoadStoreElementType(), mlir::scf::getParallelForInductionVarOwner(), hasOneBranchOpTo(), isZeroAttribute(), mlir::DataLayoutEntryAttr::parse(), parseAllReduceOperation(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), parseAsyncDependencies(), parseAtomicBinOp(), parseAtomicCompareExchangeImpl(), parseAtomicOrdering(), parseAtomicUpdateOp(), parseAttributions(), parseBound(), parseClauseAttr(), parseCommonStructuredOpParts(), parseCooperativeMatrixType(), parseEnumStrAttr(), parseExpressedTypeAndRange(), parseFunctionArgumentList(), mlir::function_interface_impl::parseFunctionOp(), parseInterfaceVarABIAttr(), parseKeywordList(), parseMatrixType(), parseNamedStructuredOpRegion(), parseOneResultSameOperandTypeOp(), parseOperandList(), parseOptionalArrayStride(), parsePointerType(), parsePtrAccessChainOpImpl(), parseScheduleClause(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseSynchronizationHint(), parseTargetEnvAttr(), parseUniformType(), parseVerCapExtAttr(), printTransferAttrs(), verifyAtomicCompareExchangeImpl(), and verifyConstantType().
getCurrentLocation() [2/2]
ParseResult mlir::AsmParser::getCurrentLocation (SMLoc * loc) inline
Definition at line 387 of file OpImplementation.h.
References mlir::success().
getEncodedSourceLoc()
virtual Location mlir::AsmParser::getEncodedSourceLoc (SMLoc loc) pure virtual
Re-encode the given source location as an MLIR location and return it.
Note: This method should only be used when a Location is necessary, as the encoding process is not efficient.
getNameLoc()
virtual SMLoc mlir::AsmParser::getNameLoc () const pure virtual
Return the location of the original name token.
Referenced by acceptBitWidth(), computeMemRefRankReductionMask(), eachHasOnlyOneOfTypes(), getLoadStoreElementType(), getOption(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutSpecAttr::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), mlir::Dialect::parseAttribute(), parseBound(), parseCalibratedType(), parseGlobalMemrefOpTypeAndInitialValue(), parseOptionalLLVMKeyword(), parsePDLType(), parseScheduleClause(), parseStructType(), parseTargetEnvAttr(), mlir::Dialect::parseType(), mlir::DataLayoutSpecAttr::print(), printInitializationList(), printNVVMIntrinsicOp(), mlir::replaceForOpWithNewYields(), verifyAtomicCompareExchangeImpl(), verifyDimAndSymbolIdentifiers(), verifyPointerAndCoopMatrixType(), and verifyScheduleModifiers().
parseAffineMap()
virtual ParseResult mlir::AsmParser::parseAffineMap (AffineMap & map) pure virtual
Parse an affine map instance into 'map'.
parseArrow()
virtual ParseResult mlir::AsmParser::parseArrow () pure virtual
Parse a '->' token.
Referenced by getLoadStoreElementType(), parseAllocateAndAllocator(), parseReductionVarList(), parseResultsValueType(), and printCreateOperationOpResults().
parseArrowTypeList()
virtual ParseResult mlir::AsmParser::parseArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an arrow followed by a type list.
Referenced by parseBound(), and printInitializationList().
parseAttribute() [1/5]
virtual ParseResult mlir::AsmParser::parseAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary attribute of a given type and return it in result.
Referenced by acceptBitWidth(), eachHasOnlyOneOfTypes(), getInsertExtractValueElementType(), getLoadStoreElementType(), hasaUniqueDim(), hasOneBranchOpTo(), isZeroAttribute(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), parseAffineMinMaxOp(), parseBound(), parseCreateOperationOpAttributes(), parseEnumStrAttr(), parseGlobalMemrefOpTypeAndInitialValue(), parseMemoryAccessAttributes(), parseOperationOpAttributes(), parseOptionalLLVMKeyword(), parseReductionVarList(), parseSourceMemoryAccessAttributes(), parseTargetEnvAttr(), parseVariableDecorations(), mlir::replaceForOpWithNewYields(), typeOrAttrParser(), verifyAtomicCompareExchangeImpl(), verifyConstantType(), verifyCoopMatrixMulAdd(), and verifyDimAndSymbolIdentifiers().
parseAttribute() [2/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, Type type = {}) inline
Parse an attribute of a specific kind and type.
Definition at line 664 of file OpImplementation.h.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseAttribute(), and mlir::success().
parseAttribute() [3/5]
ParseResult mlir::AsmParser::parseAttribute (Attribute & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute and return it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 681 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [4/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an attribute of a specific kind and type.
Definition at line 688 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [5/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute of a given type and populate it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 697 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseAttribute(), and mlir::success().
parseColon()
virtual ParseResult mlir::AsmParser::parseColon () pure virtual
Parse a : token.
Referenced by getInsertExtractValueElementType(), getLoadStoreElementType(), hasOneBranchOpTo(), parseExpressedTypeAndRange(), parseOneResultSameOperandTypeOp(), parseStorageRange(), parseSwitchOpCases(), parseUniformType(), verifyConstantType(), verifyCoopMatrixMulAdd(), and verifyPointerAndCoopMatrixType().
parseColonType() [1/2]
virtual ParseResult mlir::AsmParser::parseColonType (Type & result) pure virtual
Parse a colon followed by a type.
Referenced by computeMemRefRankReductionMask(), eachHasOnlyOneOfTypes(), getElementPtrType(), getInsertExtractValueElementType(), getLoadStoreElementType(), mlir::scf::getParallelForInductionVarOwner(), isZeroAttribute(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::AffineDmaWaitOp::parse(), parseAllocateAndAllocator(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGroupNonUniformArithmeticOp(), parseLinearClause(), parseOneResultSameOperandTypeOp(), parseOperandAndType(), parseOperandList(), parsePtrAccessChainOpImpl(), parseReductionVarList(), parseScheduleClause(), parseWsLoopControl(), printNVVMIntrinsicOp(), printWsLoopControl(), mlir::replaceForOpWithNewYields(), verifyAtomicCompareExchangeImpl(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyMemoryOpIndexing(), and verifyVectorMemoryOp().
parseColonType() [2/2]
template<typename TypeType > ParseResult mlir::AsmParser::parseColonType (TypeType & result) inline
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
Definition at line 953 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), and mlir::success().
parseColonTypeList()
virtual ParseResult mlir::AsmParser::parseColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse a colon followed by a type list, which must have at least one type.
Referenced by computeMemRefRankReductionMask(), foldTransferInBoundsAttribute(), getGenericEffectsImpl(), mlir::AffineDmaStartOp::parse(), parseCommonStructuredOpParts(), parseCreateOperationOpResults(), parseSwitchOpCases(), and printTransferAttrs().
parseComma()
virtual ParseResult mlir::AsmParser::parseComma () pure virtual
Parse a , token.
Referenced by computeMemRefRankReductionMask(), foldTransferInBoundsAttribute(), getElementPtrType(), getInsertExtractValueElementType(), getLoadStoreElementType(), isZeroAttribute(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAndVerify< unsigned >(), parseCooperativeMatrixType(), parseGlobalMemrefOpTypeAndInitialValue(), parseInterfaceVarABIAttr(), parseMemoryAccessAttributes(), parsePointerType(), parsePtrAccessChainOpImpl(), parseSizeAssignment(), parseSourceMemoryAccessAttributes(), parseStructMemberDecorations(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), parseVariableDecorations(), parseVerCapExtAttr(), printTransferAttrs(), typeOrAttrParser(), verifyAtomicCompareExchangeImpl(), verifyCoopMatrixMulAdd(), verifyMemoryOpIndexing(), verifyPointerAndCoopMatrixType(), and verifyVectorMemoryOp().
parseCommaSeparatedList() [1/2]
virtual ParseResult mlir::AsmParser::parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElementFn, StringRef contextMessage = StringRef()) pure virtual
Parse a list of comma-separated items with an optional delimiter.
If a delimiter is provided, then an empty list is allowed. If not, then at least one element will be parsed.
contextMessage is an optional message appended to "expected '('" sorts of diagnostics when parsing the delimeters.
Referenced by mlir::FieldParser< ContainerT, std::enable_if_t< std::is_member_function_pointer< decltype(&ContainerT::push_back)>::value, ContainerT > >::parse(), parseAllocateAndAllocator(), parseFunctionArgumentList(), parseFunctionResultList(), and verifyConstantType().
parseCommaSeparatedList() [2/2]
ParseResult mlir::AsmParser::parseCommaSeparatedList (function_ref< ParseResult()> parseElementFn) inline
Parse a comma separated list of elements that must have at least one entry in it.
Definition at line 623 of file OpImplementation.h.
References mlir::detail::pass_options::parseCommaSeparatedList().
parseCustomAttributeWithFallback() [1/5]
virtual ParseResult mlir::AsmParser::parseCustomAttributeWithFallback (Attribute & result, Type type, function_ref< ParseResult(Attribute &result, Type type)> parseAttribute) pure virtual
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
Referenced by mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > >::parse().
parseCustomAttributeWithFallback() [2/5]
template<typename AttrType > std::enable_if_t<detect_has_parse_method<AttrType>::value, ParseResult> mlir::AsmParser::parseCustomAttributeWithFallback (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse a custom attribute of a given type unless the next token is #, in which case the generic parser is invoked.
The parsed attribute is populated in result and also added to the specified attribute list with the specified name.
Definition at line 728 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::success(), and value.
parseCustomAttributeWithFallback() [3/5]
template<typename AttrType > std::enable_if_t<!detect_has_parse_method<AttrType>::value, ParseResult> mlir::AsmParser::parseCustomAttributeWithFallback (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
SFINAE parsing method for Attribute that don't implement a parse method.
Definition at line 755 of file OpImplementation.h.
References mlir::parseAttribute(), and value.
parseCustomAttributeWithFallback() [4/5]
template<typename AttrType > std::enable_if_t<detect_has_parse_method<AttrType>::value, ParseResult> mlir::AsmParser::parseCustomAttributeWithFallback (AttrType & result) inline
Parse a custom attribute of a given type unless the next token is #, in which case the generic parser is invoked.
The parsed attribute is populated in result.
Definition at line 765 of file OpImplementation.h.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::success(), and value.
parseCustomAttributeWithFallback() [5/5]
template<typename AttrType > std::enable_if_t<!detect_has_parse_method<AttrType>::value, ParseResult> mlir::AsmParser::parseCustomAttributeWithFallback (AttrType & result) inline
SFINAE parsing method for Attribute that don't implement a parse method.
Definition at line 787 of file OpImplementation.h.
References mlir::parseAttribute().
parseCustomTypeWithFallback() [1/3]
virtual ParseResult mlir::AsmParser::parseCustomTypeWithFallback (Type & result, function_ref< ParseResult(Type &result)> parseType) pure virtual
Parse a custom type with the provided callback, unless the next token is #, in which case the generic parser is invoked.
Referenced by mlir::FieldParser< TypeT, std::enable_if_t< std::is_base_of< Type, TypeT >::value, TypeT > >::parse().
parseCustomTypeWithFallback() [2/3]
template<typename TypeT > std::enable_if_t<detect_type_has_parse_method<TypeT>::value, ParseResult> mlir::AsmParser::parseCustomTypeWithFallback (TypeT & result) inline
Parse a custom Type of a given type unless the next token is #, in which case the generic parser is invoked.
The parsed Type is populated in result.
Definition at line 905 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::success(), and value.
parseCustomTypeWithFallback() [3/3]
template<typename TypeT > std::enable_if_t<!detect_type_has_parse_method<TypeT>::value, ParseResult> mlir::AsmParser::parseCustomTypeWithFallback (TypeT & result) inline
SFINAE parsing method for Type that don't implement a parse method.
Definition at line 926 of file OpImplementation.h.
References mlir::parseType().
parseDimensionList()
virtual ParseResult mlir::AsmParser::parseDimensionList (SmallVectorImpl< int64_t > & dimensions, bool allowDynamic = true) pure virtual
Parse a 'x' separated dimension list.
This populates the dimension list, using -1 for the ? dimensions if allowDynamic is set and errors out on ? otherwise.
dimension-list ::= (dimension x)* dimension ::= ? | integer
When allowDynamic is not set, this is used to parse:
static-dimension-list ::= (integer x)*
Referenced by parseArrayType(), parseCooperativeMatrixType(), and parseMatrixType().
parseEqual()
virtual ParseResult mlir::AsmParser::parseEqual () pure virtual
Parse a = token.
Referenced by getOption(), hasaUniqueDim(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), parseBound(), parseCreateOperationOpAttributes(), parseLinearClause(), parseOperationOpAttributes(), parseOptionalArrayStride(), parserOptionalOperandAndTypeWithPrefix(), parseSizeAssignment(), parseWsLoopControl(), printInitializationList(), and printWsLoopControl().
parseFloat()
virtual ParseResult mlir::AsmParser::parseFloat (double & result) pure virtual
Parse a floating point value from the stream.
Referenced by parseExpressedTypeAndRange(), and parseQuantParams().
parseGreater()
virtual ParseResult mlir::AsmParser::parseGreater () pure virtual
Parse a '>' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseCreateOperationOpResults(), parseExpressedTypeAndRange(), parseGlobalMemrefOpTypeAndInitialValue(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parseRuntimeArrayType(), parseSampledImageType(), parseStorageRange(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseInteger()
template<typename IntT > ParseResult mlir::AsmParser::parseInteger (IntT & result) inline
Parse an integer value from the stream.
Definition at line 555 of file OpImplementation.h.
References mlir::emitError(), and mlir::OptionalParseResult::hasValue().
Referenced by getOption(), mlir::FieldParser< IntT, std::enable_if_t< std::is_integral< IntT >::value, IntT > >::parse(), parseAndVerifyInteger(), parseQuantParams(), parseStorageRange(), parseSwitchOpCases(), parseTargetEnvAttr(), and parseUniformType().
parseKeyword() [1/2]
ParseResult mlir::AsmParser::parseKeyword (StringRef keyword, const Twine & msg = "") inline
Parse a given keyword.
Definition at line 485 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by eachHasOnlyOneOfTypes(), getLoadStoreElementType(), getOption(), mlir::scf::getParallelForInductionVarOwner(), mlir::scf::insideMutuallyExclusiveBranches(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::vector::CombiningKindAttr::parse(), parseAndVerify(), parseAtomicBinOp(), parseAtomicOrdering(), parseBound(), parseCalibratedType(), parseClauseAttr(), parseCreateOperationOpResults(), parseGlobalMemrefOpTypeAndInitialValue(), parseInterfaceVarABIAttr(), parseKeywordList(), parseOptionalArrayStride(), parsePDLType(), parsePointerType(), parseScheduleClause(), parseSizeAssignment(), parseStorageType(), parseStructType(), parseSwitchOpCases(), parseSynchronizationHint(), parseTargetEnvAttr(), parseVerCapExtAttr(), parseWsLoopControl(), mlir::DataLayoutSpecAttr::print(), printCreateOperationOpResults(), printInitializationList(), printWsLoopControl(), and verifyCoopMatrixMulAdd().
parseKeyword() [2/2]
ParseResult mlir::AsmParser::parseKeyword (StringRef * keyword) inline
Parse a keyword into 'keyword'.
Definition at line 493 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
parseKeywordOrString()
ParseResult mlir::AsmParser::parseKeywordOrString (std::string * result) inline
Parse a keyword or a quoted string.
Definition at line 513 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), and mlir::success().
parseKeywordType()
ParseResult mlir::AsmParser::parseKeywordType (const char * keyword, Type & result) inline
Parse a keyword followed by a type.
Definition at line 978 of file OpImplementation.h.
References mlir::failure(), and mlir::parseType().
Referenced by hasOneBranchOpTo(), and verifyAtomicCompareExchangeImpl().
parseLBrace()
virtual ParseResult mlir::AsmParser::parseLBrace () pure virtual
Parse a { token.
Referenced by parseUniformType().
parseLess()
virtual ParseResult mlir::AsmParser::parseLess () pure virtual
Parse a '<' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseGlobalMemrefOpTypeAndInitialValue(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parseRuntimeArrayType(), parseSampledImageType(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseLParen()
virtual ParseResult mlir::AsmParser::parseLParen () pure virtual
Parse a (token.
Referenced by mlir::scf::getParallelForInductionVarOwner(), hasOneBranchOpTo(), parseCommonStructuredOpParts(), parseControlAttribute(), parseCreateOperationOpResults(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseOperandList(), parseOptionalLLVMKeyword(), parseOptionalOperand(), parseOptionalOperandAndType(), parseSizeAssignment(), parseStructType(), parseVariableDecorations(), verifyConstantType(), and verifyCoopMatrixMulAdd().
parseLSquare()
virtual ParseResult mlir::AsmParser::parseLSquare () pure virtual
Parse a [ token.
Referenced by getInsertExtractValueElementType(), getLoadStoreElementType(), parseKeywordList(), and parseOperandsOrIntegersImpl().
parseOptionalArrow()
virtual ParseResult mlir::AsmParser::parseOptionalArrow () pure virtual
Parse a '->' token if present.
Referenced by parseCreateOperationOpResults(), and mlir::function_interface_impl::parseFunctionSignature().
parseOptionalArrowTypeList()
virtual ParseResult mlir::AsmParser::parseOptionalArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional arrow followed by a type list.
Referenced by eachHasOnlyOneOfTypes(), mlir::scf::insideMutuallyExclusiveBranches(), isComputeOperation(), parseNamedStructuredOpResults(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), and verifyAllocLikeOp().
parseOptionalAttrDict()
virtual ParseResult mlir::AsmParser::parseOptionalAttrDict (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if it is present.
Referenced by applyTilingToAll(), computeMemRefRankReductionMask(), eachHasOnlyOneOfTypes(), foldTransferInBoundsAttribute(), getGenericEffectsImpl(), getInsertExtractValueElementType(), getLoadStoreElementType(), hasaUniqueDim(), mlir::scf::insideMutuallyExclusiveBranches(), isZeroAttribute(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), parseAffineMinMaxOp(), parseBound(), parseCommonStructuredOpParts(), parseFunctionArgumentList(), parseLLVMOpAttrs(), parseOneResultSameOperandTypeOp(), parseOptionalLLVMKeyword(), parseSizeAssignment(), parseVariableDecorations(), printCreateOperationOpResults(), printInitializationList(), printNVVMIntrinsicOp(), printTransferAttrs(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), verifyAllocLikeOp(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyDimAndSymbolIdentifiers(), verifyMemoryOpIndexing(), and verifyVectorMemoryOp().
parseOptionalAttrDictWithKeyword()
virtual ParseResult mlir::AsmParser::parseOptionalAttrDictWithKeyword (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if the attributes keyword is present.
Referenced by mlir::scf::getParallelForInductionVarOwner(), hasOneBranchOpTo(), isComputeOperation(), parseAttributions(), mlir::function_interface_impl::parseFunctionOp(), verifyAttributions(), and verifyConstantType().
parseOptionalAttribute() [1/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary optional attribute of a given type and return it in result.
parseOptionalAttribute() [2/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (ArrayAttr & result, Type type = {}) pure virtual
Parse an optional array attribute and return it in result.
parseOptionalAttribute() [3/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (StringAttr & result, Type type = {}) pure virtual
Parse an optional string attribute and return it in result.
parseOptionalAttribute() [4/5]
template<typename AttrType > OptionalParseResult mlir::AsmParser::parseOptionalAttribute (AttrType & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an optional attribute of a specific type and add it to the list with the specified name.
Definition at line 807 of file OpImplementation.h.
parseOptionalAttribute() [5/5]
template<typename AttrType > OptionalParseResult mlir::AsmParser::parseOptionalAttribute (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse an optional attribute of a specific type and add it to the list with the specified name.
Definition at line 816 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::OptionalParseResult::hasValue(), and mlir::succeeded().
parseOptionalColon()
virtual ParseResult mlir::AsmParser::parseOptionalColon () pure virtual
Parse a : token if present.
Referenced by parseAnyType(), parseQuantParams(), parseTargetEnvAttr(), and parseUniformType().
parseOptionalColonTypeList()
virtual ParseResult mlir::AsmParser::parseOptionalColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional colon followed by a type list, which if present must have at least one type.
Referenced by parseOptionalLLVMKeyword().
parseOptionalComma()
virtual ParseResult mlir::AsmParser::parseOptionalComma () pure virtual
Parse a , token if present.
Referenced by foldTransferInBoundsAttribute(), getLoadStoreElementType(), getOption(), isComputeOperation(), SelectToExtUI::matchAndRewrite(), mlir::DataLayoutSpecAttr::parse(), parseCreateOperationOpAttributes(), parseGEPIndices(), parseInterfaceVarABIAttr(), parseKeywordList(), parseLinearClause(), parseOperandList(), parseOperationOpAttributes(), parseOptionalArrayStride(), parseReductionVarList(), parseScheduleClause(), parseStructMemberDecorations(), parseStructType(), parseSwitchOpCases(), parseSynchronizationHint(), parseUniformType(), printTransferAttrs(), verifyConstantType(), and verifyCoopMatrixMulAdd().
parseOptionalEllipsis()
virtual ParseResult mlir::AsmParser::parseOptionalEllipsis () pure virtual
Parse a ... token if present;.
Referenced by parseFunctionArgumentList().
parseOptionalEqual()
virtual ParseResult mlir::AsmParser::parseOptionalEqual () pure virtual
Parse a = token if present.
Referenced by parseGlobalMemrefOpTypeAndInitialValue(), parseScheduleClause(), and parseStructMemberDecorations().
parseOptionalGreater()
virtual ParseResult mlir::AsmParser::parseOptionalGreater () pure virtual
Parse a '>' token if present.
Referenced by mlir::DataLayoutSpecAttr::parse(), parseStructType(), and typeOrAttrParser().
parseOptionalInteger() [1/2]
virtual OptionalParseResult mlir::AsmParser::parseOptionalInteger (APInt & result) pure virtual
Parse an optional integer value from the stream.
Referenced by parseGEPIndices(), parseInterfaceVarABIAttr(), parseStructMemberDecorations(), and parseSwitchOpCases().
parseOptionalInteger() [2/2]
template<typename IntT > OptionalParseResult mlir::AsmParser::parseOptionalInteger (IntT & result) inline
Definition at line 567 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::OptionalParseResult::hasValue(), and mlir::success().
parseOptionalKeyword() [1/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef keyword) pure virtual
Parse the given keyword if present.
Referenced by getLoadStoreElementType(), getOption(), hasaUniqueDim(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), isComputeOperation(), parseAllReduceOperation(), parseAsyncDependencies(), parseAtomicReductionRegion(), parseAttributions(), parseBound(), parseCommonStructuredOpParts(), parseControlAttribute(), parseGlobalMemrefOpTypeAndInitialValue(), parseGroupNonUniformArithmeticOp(), parseLaunchFuncOperands(), parseOperandList(), parseOptionalKeywordAlternative(), parseOptionalLLVMKeyword(), parseOptionalOperand(), parseOptionalOperandAndType(), mlir::impl::parseOptionalVisibilityKeyword(), parserOptionalOperandAndTypeWithPrefix(), parseSizeAssignment(), parseStructType(), parseSynchronizationHint(), parseTargetEnvAttr(), parseVariableDecorations(), parseWsLoopControl(), printInitializationList(), mlir::replaceForOpWithNewYields(), and verifyConstantType().
parseOptionalKeyword() [2/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef * keyword) pure virtual
Parse a keyword, if present, into 'keyword'.
parseOptionalKeyword() [3/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef * keyword, ArrayRef< StringRef > allowedValues) pure virtual
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
parseOptionalKeywordOrString()
virtual ParseResult mlir::AsmParser::parseOptionalKeywordOrString (std::string * result) pure virtual
Parse an optional keyword or string.
parseOptionalLBrace()
virtual ParseResult mlir::AsmParser::parseOptionalLBrace () pure virtual
Parse a { token if present.
Referenced by parseCreateOperationOpAttributes(), and parseOperationOpAttributes().
parseOptionalLess()
virtual ParseResult mlir::AsmParser::parseOptionalLess () pure virtual
Parse a '<' token if present.
Referenced by parseCreateOperationOpResults(), parseStorageRange(), and typeOrAttrParser().
parseOptionalLParen()
virtual ParseResult mlir::AsmParser::parseOptionalLParen () pure virtual
Parse a (token if present.
Referenced by getLoadStoreElementType(), isComputeOperation(), parseFunctionResultList(), parseOneResultSameOperandTypeOp(), parseOptionalOperandAndType(), and parseSwitchOpCases().
parseOptionalLSquare()
virtual ParseResult mlir::AsmParser::parseOptionalLSquare () pure virtual
Parse a [ token if present.
Referenced by parseImageOperands(), parseMemoryAccessAttributes(), parseSourceMemoryAccessAttributes(), parseStructType(), and verifyAtomicCompareExchangeImpl().
parseOptionalPlus()
virtual ParseResult mlir::AsmParser::parseOptionalPlus () pure virtual
Parse a '+' token if present.
parseOptionalQuestion()
virtual ParseResult mlir::AsmParser::parseOptionalQuestion () pure virtual
Parse a '?' token if present.
parseOptionalRBrace()
virtual ParseResult mlir::AsmParser::parseOptionalRBrace () pure virtual
Parse a } token if present.
parseOptionalRParen()
virtual ParseResult mlir::AsmParser::parseOptionalRParen () pure virtual
Parse a) token if present.
Referenced by parseFunctionResultList(), parseOperandList(), parseOptionalLLVMKeyword(), and parseStructType().
parseOptionalRSquare()
virtual ParseResult mlir::AsmParser::parseOptionalRSquare () pure virtual
Parse a ] token if present.
Referenced by parseKeywordList(), parseOperandsOrIntegersImpl(), and parseStructMemberDecorations().
parseOptionalStar()
virtual ParseResult mlir::AsmParser::parseOptionalStar () pure virtual
Parse a '*' token if present.
parseOptionalString()
virtual ParseResult mlir::AsmParser::parseOptionalString (std::string * string) pure virtual
Parse a quoted string token if present.
Referenced by mlir::DataLayoutEntryAttr::parse().
parseOptionalSymbolName()
virtual ParseResult mlir::AsmParser::parseOptionalSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) pure virtual
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Referenced by hasOneBranchOpTo().
parseOptionalType()
virtual OptionalParseResult mlir::AsmParser::parseOptionalType (Type & result) pure virtual
Parse an optional type.
Referenced by mlir::DataLayoutEntryAttr::parse(), and parseStorageType().
parseOptionalVerticalBar()
virtual ParseResult mlir::AsmParser::parseOptionalVerticalBar () pure virtual
Parse a '|' token if present.
parsePlus()
virtual ParseResult mlir::AsmParser::parsePlus () pure virtual
Parse a '+' token.
parseQuestion()
virtual ParseResult mlir::AsmParser::parseQuestion () pure virtual
Parse a '?' token.
parseRBrace()
virtual ParseResult mlir::AsmParser::parseRBrace () pure virtual
Parse a } token.
Referenced by parseCreateOperationOpAttributes(), parseOperationOpAttributes(), and parseUniformType().
parseRParen()
virtual ParseResult mlir::AsmParser::parseRParen () pure virtual
Parse a) token.
Referenced by getLoadStoreElementType(), mlir::scf::getParallelForInductionVarOwner(), hasOneBranchOpTo(), isComputeOperation(), parseCommonStructuredOpParts(), parseControlAttribute(), parseCreateOperationOpResults(), parseFunctionResultList(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseOneResultSameOperandTypeOp(), parseOperandList(), parseOptionalLLVMKeyword(), parseOptionalOperand(), parseOptionalOperandAndType(), parseSizeAssignment(), parseStructType(), parseSwitchOpCases(), parseVariableDecorations(), verifyConstantType(), and verifyCoopMatrixMulAdd().
parseRSquare()
virtual ParseResult mlir::AsmParser::parseRSquare () pure virtual
Parse a ] token.
Referenced by getInsertExtractValueElementType(), getLoadStoreElementType(), parseImageOperands(), parseKeywordList(), parseMemoryAccessAttributes(), parseSourceMemoryAccessAttributes(), parseStructMemberDecorations(), and verifyAtomicCompareExchangeImpl().
parseStar()
virtual ParseResult mlir::AsmParser::parseStar () pure virtual
Parse a '*' token.
parseString()
ParseResult mlir::AsmParser::parseString (std::string * string) inline
Parse a quoted string token.
Definition at line 474 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by mlir::FieldParser< std::string >::parse().
parseSymbolName()
ParseResult mlir::AsmParser::parseSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Definition at line 845 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::parseType(), and mlir::success().
Referenced by hasOneBranchOpTo(), parseAttributions(), mlir::function_interface_impl::parseFunctionOp(), parseOptionalLLVMKeyword(), verifyAttributions(), verifyConstantType(), and verifyCoopMatrixMulAdd().
parseType() [1/2]
virtual ParseResult mlir::AsmParser::parseType (Type & result) pure virtual
Parse a type.
Referenced by getInsertExtractValueElementType(), getLoadStoreElementType(), hasOneBranchOpTo(), isZeroAttribute(), SelectToExtUI::matchAndRewrite(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseAnyType(), parseAwaitResultType(), parseExpressedTypeAndRange(), parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalMemrefOpTypeAndInitialValue(), parseOneResultSameOperandTypeOp(), parseResultsValueType(), parseStorageType(), parseStructType(), parseUniformType(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyPointerAndCoopMatrixType(), and verifyVectorMemoryOp().
parseType() [2/2]
template<typename TypeT > ParseResult mlir::AsmParser::parseType (TypeT & result) inline
Parse a type of a specific type.
Definition at line 876 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseType(), and mlir::success().
parseTypeList()
ParseResult mlir::AsmParser::parseTypeList (SmallVectorImpl< Type > & result) inline
Parse a type list.
Definition at line 931 of file OpImplementation.h.
References mlir::failure(), mlir::parseType(), mlir::succeeded(), and mlir::success().
Referenced by getElementPtrType(), and parsePtrAccessChainOpImpl().
parseVerticalBar()
virtual ParseResult mlir::AsmParser::parseVerticalBar () pure virtual
Parse a '|' token.
parseXInDimensionList()
virtual ParseResult mlir::AsmParser::parseXInDimensionList () pure virtual
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
printIntegerSet()
virtual ParseResult mlir::AsmParser::printIntegerSet (IntegerSet & set) pure virtual
Parse an integer set instance into 'set'.
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/AsmPrinter.cpp