MLIR: mlir::pdll::ods::Dialect Class Reference
mlir::pdll::ods::Dialect Class Reference
This class represents an ODS dialect, and contains information on the constructs held within the dialect.
#include "mlir/Tools/PDLL/ODS/Dialect.h"
Public Member Functions
~Dialect ()
StringRef getName () const
Return the name of this dialect.
std::pair< Operation *, bool > insertOperation (StringRef name, StringRef summary, StringRef desc, SMLoc loc)
Insert a new operation with the dialect.
Operation * lookupOperation (StringRef name) const
Lookup an operation registered with the given name, or null if no operation with that name is registered.
const llvm::StringMap< std::unique_ptr< Operation > > & getOperations () const
Return a map of all of the operations registered to this dialect.
Friends
class Context
Allow access to the constructor.
Detailed Description
This class represents an ODS dialect, and contains information on the constructs held within the dialect.
Definition at line 26 of file Dialect.h.
Constructor & Destructor Documentation
~Dialect()
mlir::pdll::ods::Dialect::~Dialect ()
Member Function Documentation
getName()
StringRef Dialect::getName () const inline
Return the name of this dialect.
Definition at line 31 of file Dialect.h.
References insertOperation(), and lookupOperation().
getOperations()
const llvm::StringMap<std::unique_ptr<Operation> >& mlir::pdll::ods::Dialect::getOperations () const inline
Return a map of all of the operations registered to this dialect.
Definition at line 44 of file Dialect.h.
Referenced by getLspDiagnoticFromDiag().
insertOperation()
std::pair< Operation *, bool > Dialect::insertOperation (StringRef name, StringRef summary, StringRef desc, SMLoc loc)
Insert a new operation with the dialect.
Returns the inserted operation, and a boolean indicating if the operation newly inserted (false if the operation already existed).
Definition at line 24 of file Dialect.cpp.
Referenced by getName(), and mlir::pdll::ods::Context::insertOperation().
lookupOperation()
Operation * Dialect::lookupOperation (StringRef name) const
Lookup an operation registered with the given name, or null if no operation with that name is registered.
Definition at line 36 of file Dialect.cpp.
Referenced by getName().
Friends And Related Function Documentation
Context
friend class Context friend
Allow access to the constructor.
Definition at line 58 of file Dialect.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/ODS/Dialect.h
lib/TableGen/Dialect.cpp