MLIR: mlir::presburger::MultiAffineFunction Class Reference
mlir::presburger::MultiAffineFunction Class Reference
This class represents a multi-affine function whose domain is given by an IntegerPolyhedron.
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
MultiAffineFunction (const IntegerPolyhedron &domain, const Matrix &output)
MultiAffineFunction (const Matrix &output, const PresburgerSpace &space)
unsigned getNumInputs () const
unsigned getNumOutputs () const
bool isConsistent () const
const IntegerPolyhedron & getDomain () const
const PresburgerSpace & getDomainSpace () const
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Remove the specified range of ids.
void mergeLocalIds (MultiAffineFunction &other)
Given a MAF other, merges local identifiers such that both funcitons have union of local ids, without changing the set of points in domain or the output.
bool isEqualWhereDomainsOverlap (MultiAffineFunction other) const
Return whether the outputs of this and other agree wherever both functions are defined, i.e., the outputs should be equal for all points in the intersection of the domains.
bool isEqual (const MultiAffineFunction &other) const
Return whether the this and other are equal.
Optional< SmallVector< int64_t, 8 > > valueAt (ArrayRef< int64_t > point) const
Get the value of the function at the specified point.
void truncateOutput (unsigned count)
Truncate the output dimensions to the first count dimensions.
void print (raw_ostream &os) const
void dump () const
Detailed Description
This class represents a multi-affine function whose domain is given by an IntegerPolyhedron.
This can be thought of as an IntegerPolyhedron with a tuple of integer values attached to every point in the polyhedron, with the value of each element of the tuple given by an affine expression in the ids of the polyhedron. For example we could have the domain
(x, y) : (x >= 5, y >= x)
and a tuple of three integers defined at every point in the polyhedron:
(x, y) -> (x + 2, 2*x - 3y + 5, 2*x + y).
In this way every point in the polyhedron has a tuple of integers associated with it. If the integer polyhedron has local ids, then the output expressions can use them as well. The output expressions are represented as a matrix with one row for every element in the output vector one column for each id, and an extra column at the end for the constant term.
Checking equality of two such functions is supported, as well as finding the value of the function at a specified point.
Definition at line 45 of file PWMAFunction.h.
Constructor & Destructor Documentation
MultiAffineFunction() [1/2]
mlir::presburger::MultiAffineFunction::MultiAffineFunction (const IntegerPolyhedron & domain, const Matrix & output) inline
Definition at line 47 of file PWMAFunction.h.
MultiAffineFunction() [2/2]
mlir::presburger::MultiAffineFunction::MultiAffineFunction (const Matrix & output, const PresburgerSpace & space) inline
Definition at line 49 of file PWMAFunction.h.
Member Function Documentation
dump()
void MultiAffineFunction::dump () const
Definition at line 83 of file PWMAFunction.cpp.
References mlir::presburger::PWMAFunction::print().
Referenced by mlir::presburger::PWMAFunction::getPiece().
getDomain()
const IntegerPolyhedron& mlir::presburger::MultiAffineFunction::getDomain () const inline
Definition at line 57 of file PWMAFunction.h.
Referenced by mlir::presburger::PWMAFunction::addPiece(), mlir::presburger::PWMAFunction::getPiece(), isEqual(), and isEqualWhereDomainsOverlap().
getDomainSpace()
const PresburgerSpace& mlir::presburger::MultiAffineFunction::getDomainSpace () const inline
Definition at line 58 of file PWMAFunction.h.
References mlir::presburger::IntegerRelation::getSpace(), and insertId().
Referenced by mlir::presburger::PWMAFunction::addPiece(), isEqual(), and isEqualWhereDomainsOverlap().
getNumInputs()
unsigned mlir::presburger::MultiAffineFunction::getNumInputs () const inline
Definition at line 52 of file PWMAFunction.h.
References mlir::presburger::IntegerRelation::getNumDimAndSymbolIds().
getNumOutputs()
unsigned mlir::presburger::MultiAffineFunction::getNumOutputs () const inline
Definition at line 53 of file PWMAFunction.h.
References mlir::presburger::Matrix::getNumRows().
insertId()
unsigned MultiAffineFunction::insertId (IdKind kind, unsigned pos, unsigned num = 1)
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. The coefficient columns corresponding to the added identifiers are initialized to zero. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Definition at line 91 of file PWMAFunction.cpp.
Referenced by getDomainSpace().
isConsistent()
bool mlir::presburger::MultiAffineFunction::isConsistent () const inline
Definition at line 54 of file PWMAFunction.h.
References mlir::presburger::Matrix::getNumColumns(), and mlir::presburger::IntegerRelation::getNumIds().
Referenced by mlir::presburger::PWMAFunction::addPiece().
isEqual()
bool MultiAffineFunction::isEqual (const MultiAffineFunction & other) const
Return whether the this and other are equal.
This is the case if they lie in the same space, i.e. have the same dimensions, and their domains are identical and their outputs are equal on their domain.
Definition at line 85 of file PWMAFunction.cpp.
References getDomain(), mlir::presburger::PWMAFunction::getDomain(), getDomainSpace(), and mlir::presburger::PresburgerRelation::isEqual().
Referenced by mlir::presburger::PWMAFunction::getPiece().
isEqualWhereDomainsOverlap()
bool MultiAffineFunction::isEqualWhereDomainsOverlap (MultiAffineFunction other) const
Return whether the outputs of this and other agree wherever both functions are defined, i.e., the outputs should be equal for all points in the intersection of the domains.
Definition at line 146 of file PWMAFunction.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::append(), getDomain(), getDomainSpace(), mlir::presburger::PWMAFunction::getNumOutputs(), mlir::presburger::Matrix::getRow(), mlir::presburger::IntegerRelation::isSubsetOf(), mergeLocalIds(), and subtract().
mergeLocalIds()
void MultiAffineFunction::mergeLocalIds (MultiAffineFunction & other)
Given a MAF other, merges local identifiers such that both funcitons have union of local ids, without changing the set of points in domain or the output.
Definition at line 118 of file PWMAFunction.cpp.
References mlir::presburger::Matrix::addToColumn(), mlir::presburger::IntegerRelation::eliminateRedundantLocalId(), mlir::presburger::IntegerRelation::getIdKindOffset(), mlir::presburger::IntegerRelation::getNumLocalIds(), mlir::presburger::Matrix::insertColumns(), mlir::presburger::Local, mlir::presburger::mergeLocalIds(), and mlir::presburger::Matrix::removeColumn().
Referenced by isEqualWhereDomainsOverlap().
print()
void MultiAffineFunction::print (raw_ostream & os) const
Definition at line 75 of file PWMAFunction.cpp.
Referenced by mlir::presburger::PWMAFunction::getPiece().
removeIdRange()
void MultiAffineFunction::removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Remove the specified range of ids.
Definition at line 99 of file PWMAFunction.cpp.
truncateOutput()
void MultiAffineFunction::truncateOutput (unsigned count)
Truncate the output dimensions to the first count dimensions.
TODO: refactor so that this can be accomplished through removeIdRange.
Definition at line 106 of file PWMAFunction.cpp.
Referenced by mlir::presburger::PWMAFunction::getPiece().
valueAt()
Optional< SmallVector< int64_t, 8 > > MultiAffineFunction::valueAt (ArrayRef< int64_t > point) const
Get the value of the function at the specified point.
If the point lies outside the domain, an empty optional is returned.
Definition at line 37 of file PWMAFunction.cpp.
References mlir::presburger::PWMAFunction::getDomain(), and mlir::presburger::PWMAFunction::getNumOutputs().
Referenced by mlir::presburger::PWMAFunction::getPiece().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PWMAFunction.h
lib/Analysis/Presburger/PWMAFunction.cpp