MLIR: mlir::VectorType::Builder Class Reference
mlir::VectorType::Builder Class Reference
This is a builder type that keeps local references to arguments.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
Builder (VectorType other)
Build from another VectorType.
Builder (ArrayRef< int64_t > shape, Type elementType, unsigned numScalableDims=0)
Build from scratch.
Builder & setShape (ArrayRef< int64_t > newShape, unsigned newNumScalableDims=0)
Builder & setElementType (Type newElementType)
Builder & dropDim (unsigned pos)
Erase a dim from shape .
operator Type ()
In the particular case where the vector has a single dimension that we drop, return the scalar element type.
Detailed Description
This is a builder type that keeps local references to arguments.
Arguments that are passed into the builder must outlive the builder.
Definition at line 270 of file BuiltinTypes.h.
Constructor & Destructor Documentation
Builder() [1/2]
mlir::VectorType::Builder::Builder (VectorType other) inline explicit
Build from another VectorType.
Definition at line 273 of file BuiltinTypes.h.
Builder() [2/2]
mlir::VectorType::Builder::Builder (ArrayRef< int64_t > shape, Type elementType, unsigned numScalableDims = 0) inline
Build from scratch.
Definition at line 278 of file BuiltinTypes.h.
Member Function Documentation
dropDim()
Builder& mlir::VectorType::Builder::dropDim (unsigned pos) inline
Erase a dim from shape .
Definition at line 296 of file BuiltinTypes.h.
Referenced by reshapeLoad(), and reshapeStore().
operator Type()
mlir::VectorType::Builder::operator Type () inline
In the particular case where the vector has a single dimension that we drop, return the scalar element type.
Definition at line 310 of file BuiltinTypes.h.
References mlir::computeRankReductionMask().
setElementType()
Builder& mlir::VectorType::Builder::setElementType (Type newElementType) inline
Definition at line 290 of file BuiltinTypes.h.
setShape()
Builder& mlir::VectorType::Builder::setShape (ArrayRef< int64_t > newShape, unsigned newNumScalableDims = 0) inline
Definition at line 283 of file BuiltinTypes.h.
The documentation for this class was generated from the following file:
include/mlir/IR/BuiltinTypes.h