MLIR: mlir::TensorType Class Reference
mlir::TensorType Class Reference
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
Type getElementType () const
Returns the element type of this tensor type.
bool hasRank () const
Returns if this type is ranked, i.e. it has a known number of dimensions.
ArrayRef< int64_t > getShape () const
Returns the shape of this tensor type.
TensorType cloneWith (Optional< ArrayRef< int64_t >> shape, Type elementType) const
Clone this type with the given shape and element type.
operator ShapedType () const
Allow implicit conversion to ShapedType.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool isValidElementType (Type type)
Return true if the specified element type is ok in a tensor.
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Protected Attributes inherited from mlir::Type
ImplType * impl {nullptr}
Detailed Description
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
Note: This class attaches the ShapedType trait to act as a mixin to provide many useful utility functions. This inheritance has no effect on derived tensor types.
Definition at line 77 of file BuiltinTypes.h.
Member Function Documentation
classof()
bool mlir::TensorType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 398 of file BuiltinTypes.h.
References mlir::canonicalizeStridedLayout(), mlir::eraseStridedLayout(), mlir::getStridedLinearLayoutMap(), mlir::getStridesAndOffset(), mlir::Type::isa(), mlir::isStaticShapeAndContiguousRowMajor(), mlir::isStrided(), mlir::makeCanonicalStridedLayoutExpr(), and mlir::makeStridedLinearLayoutMap().
cloneWith()
TensorType TensorType::cloneWith (Optional< ArrayRef< int64_t >> shape, Type elementType) const
Clone this type with the given shape and element type.
If the provided shape is None, the current shape of the type is used.
Definition at line 281 of file BuiltinTypes.cpp.
getElementType()
Type TensorType::getElementType () const
Returns the element type of this tensor type.
Definition at line 269 of file BuiltinTypes.cpp.
Referenced by convertTensorType(), mlir::tensor::foldTensorCast(), getNumElements(), joinShapes(), and sourceMaterializationCallback().
getShape()
ArrayRef< int64_t > TensorType::getShape () const
Returns the shape of this tensor type.
Definition at line 277 of file BuiltinTypes.cpp.
References getShape().
hasRank()
bool TensorType::hasRank () const
Returns if this type is ranked, i.e. it has a known number of dimensions.
Definition at line 275 of file BuiltinTypes.cpp.
Referenced by joinShapes(), and sourceMaterializationCallback().
isValidElementType()
bool TensorType::isValidElementType (Type type) static
Return true if the specified element type is ok in a tensor.
Definition at line 307 of file BuiltinTypes.cpp.
References checkTensorElementType(), mlir::Attribute::dyn_cast_or_null(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Type::getDialect(), getElementType(), mlir::Type::isa(), and mlir::verify().
Referenced by checkTensorElementType(), and mlir::detail::Parser::parseTensorType().
operator ShapedType()
mlir::TensorType::operator ShapedType () const inline
Allow implicit conversion to ShapedType.
Definition at line 102 of file BuiltinTypes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp