MLIR: mlir::tblgen::ExtraClassDeclaration Class Reference
mlir::tblgen::ExtraClassDeclaration Class Reference
Unstructured extra class declarations and definitions, from TableGen definitions.
#include "mlir/TableGen/Class.h"
Public Member Functions
ExtraClassDeclaration (StringRef extraClassDeclaration, StringRef extraClassDefinition="")
Create an extra class declaration.
void writeDeclTo (raw_indented_ostream &os) const override
Write the extra class declarations.
void writeDefTo (raw_indented_ostream &os, StringRef namePrefix) const override
Write the extra class definitions.
Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::ExtraClassDeclaration >
ClassDeclarationBase ()
Public Member Functions inherited from mlir::tblgen::ClassDeclaration
virtual ~ClassDeclaration ()=default
ClassDeclaration (Kind kind)
Create a class declaration with a given kind.
Kind getKind () const
Get the class declaration kind.
Additional Inherited Members
Public Types inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::ExtraClassDeclaration >
using Base = ClassDeclarationBase< DeclKind >
Public Types inherited from mlir::tblgen::ClassDeclaration
enum Kind {
Method, UsingDeclaration, VisibilityDeclaration, Field,
ExtraClassDeclaration
}
Kinds for LLVM-style RTTI.
Static Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::ExtraClassDeclaration >
static bool classof (const ClassDeclaration *other)
Detailed Description
Unstructured extra class declarations and definitions, from TableGen definitions.
The default visibility of extra class declarations is up to the owning class.
Definition at line 538 of file Class.h.
Constructor & Destructor Documentation
ExtraClassDeclaration()
mlir::tblgen::ExtraClassDeclaration::ExtraClassDeclaration (StringRef extraClassDeclaration, StringRef extraClassDefinition = "") inline
Create an extra class declaration.
Definition at line 542 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo(), and mlir::tblgen::MethodParameter::writeDefTo().
Member Function Documentation
writeDeclTo()
void ExtraClassDeclaration::writeDeclTo (raw_indented_ostream & os) const override virtual
Write the extra class declarations.
Implements mlir::tblgen::ClassDeclaration.
Definition at line 259 of file Class.cpp.
References mlir::raw_indented_ostream::printReindented().
writeDefTo()
void ExtraClassDeclaration::writeDefTo (raw_indented_ostream & os, StringRef namePrefix) const override virtual
Write the extra class definitions.
Reimplemented from mlir::tblgen::ClassDeclaration.
Definition at line 263 of file Class.cpp.
References mlir::raw_indented_ostream::printReindented().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp