MLIR: mlir::presburger::PresburgerSpace Class Reference
mlir::presburger::PresburgerSpace Class Reference
PresburgerSpace is the space of all possible values of a tuple of integer valued variables/identifiers.
#include "mlir/Analysis/Presburger/PresburgerSpace.h"
Public Member Functions
unsigned getNumDomainIds () const
unsigned getNumRangeIds () const
unsigned getNumSetDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumDimIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIds () const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
IdKind getIdKindAt (unsigned pos) const
Return the IdKind of the id at the specified position.
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Removes identifiers of the specified kind in the column range [idStart, idLimit).
bool isCompatible (const PresburgerSpace &other) const
Returns true if both the spaces are compatible i.e.
bool isEqual (const PresburgerSpace &other) const
Returns true if both the spaces are equal including local identifiers i.e.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
void print (llvm::raw_ostream &os) const
void dump () const
Static Public Member Functions
static PresburgerSpace getRelationSpace (unsigned numDomain=0, unsigned numRange=0, unsigned numSymbols=0, unsigned numLocals=0)
static PresburgerSpace getSetSpace (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Protected Member Functions
PresburgerSpace (unsigned numDomain=0, unsigned numRange=0, unsigned numSymbols=0, unsigned numLocals=0)
Detailed Description
PresburgerSpace is the space of all possible values of a tuple of integer valued variables/identifiers.
Each identifier has one of the three types:
Dimension: Ordinary variables over which the space is represented.
Symbol: Symbol identifiers correspond to fixed but unknown values. Mathematically, a space with symbolic identifiers is like a family of spaces indexed by the symbolic identifiers.
Local: Local identifiers correspond to existentially quantified variables. For example, consider the space: (x, exists q) where x is a dimension identifier and q is a local identifier. Let us put the constraints: 1 <= x <= 7, x = 2q on this space to get the set: (x) : (exists q : q <= x <= 7, x = 2q). An assignment to symbolic and dimension variables is valid if there exists some assignment to the local variable q satisfying these constraints. For this example, the set is equivalent to {2, 4, 6}. Mathematically, existential quantification can be thought of as the result of projection. In this example, q is existentially quantified. This can be thought of as the result of projecting out q from the previous example, i.e. we obtained {2, 4, 6} by projecting out the second dimension from {(2, 1), (4, 2), (6, 2)}.
Dimension identifiers are further divided into Domain and Range identifiers to support building relations.
Identifiers are stored in the following order: [Domain, Range, Symbols, Locals]
A space with no distinction between types of dimension identifiers can be implemented as a space with zero domain. IdKind::SetDim should be used to refer to dimensions in such spaces.
Compatibility of two spaces implies that number of identifiers of each kind other than Locals are equal. Equality of two spaces implies that number of identifiers of each kind are equal.
Definition at line 65 of file PresburgerSpace.h.
Constructor & Destructor Documentation
PresburgerSpace()
mlir::presburger::PresburgerSpace::PresburgerSpace (unsigned numDomain = 0, unsigned numRange = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline protected
Definition at line 141 of file PresburgerSpace.h.
Member Function Documentation
dump()
void PresburgerSpace::dump () const
Definition at line 131 of file PresburgerSpace.cpp.
References print().
getIdKindAt()
IdKind PresburgerSpace::getIdKindAt (unsigned pos) const
Return the IdKind of the id at the specified position.
Definition at line 59 of file PresburgerSpace.cpp.
References mlir::presburger::Domain, getIdKindEnd(), getNumIds(), mlir::presburger::Local, mlir::presburger::Range, and mlir::presburger::Symbol.
Referenced by mlir::presburger::IntegerRelation::fourierMotzkinEliminate(), and mlir::presburger::IntegerRelation::getIdKindAt().
getIdKindEnd()
unsigned PresburgerSpace::getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
Definition at line 40 of file PresburgerSpace.cpp.
Referenced by getIdKindAt().
getIdKindOffset()
unsigned PresburgerSpace::getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
Definition at line 28 of file PresburgerSpace.cpp.
Referenced by mlir::presburger::IntegerRelation::fourierMotzkinEliminate().
getIdKindOverlap()
unsigned PresburgerSpace::getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
Definition at line 44 of file PresburgerSpace.cpp.
getNumDimAndSymbolIds()
unsigned mlir::presburger::PresburgerSpace::getNumDimAndSymbolIds () const inline
Definition at line 88 of file PresburgerSpace.h.
Referenced by mlir::presburger::IntegerRelation::getNumDimAndSymbolIds(), and setDimSymbolSeparation().
getNumDimIds()
unsigned mlir::presburger::PresburgerSpace::getNumDimIds () const inline
Definition at line 87 of file PresburgerSpace.h.
Referenced by mlir::presburger::IntegerRelation::getNumDimIds().
getNumDomainIds()
unsigned mlir::presburger::PresburgerSpace::getNumDomainIds () const inline
Definition at line 81 of file PresburgerSpace.h.
Referenced by mlir::presburger::PresburgerRelation::getNumDomainIds(), mlir::presburger::IntegerRelation::getNumDomainIds(), mlir::presburger::IntegerRelation::getSpaceWithoutLocals(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), isCompatible(), mlir::presburger::PresburgerSet::PresburgerSet(), print(), and mlir::presburger::PWMAFunction::PWMAFunction().
getNumIdKind()
unsigned PresburgerSpace::getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
Definition at line 16 of file PresburgerSpace.cpp.
getNumIds()
unsigned mlir::presburger::PresburgerSpace::getNumIds () const inline
Definition at line 91 of file PresburgerSpace.h.
Referenced by getIdKindAt(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::PresburgerRelation::getNumIds(), mlir::presburger::IntegerRelation::getNumIds(), and mlir::presburger::IntegerRelation::IntegerRelation().
getNumLocalIds()
unsigned mlir::presburger::PresburgerSpace::getNumLocalIds () const inline
Definition at line 85 of file PresburgerSpace.h.
Referenced by mlir::presburger::PresburgerRelation::getNumLocalIds(), mlir::presburger::IntegerRelation::getNumLocalIds(), getSetDifference(), isEqual(), mlir::presburger::PresburgerRelation::PresburgerRelation(), mlir::presburger::PresburgerSet::PresburgerSet(), print(), and mlir::presburger::PWMAFunction::PWMAFunction().
getNumRangeIds()
unsigned mlir::presburger::PresburgerSpace::getNumRangeIds () const inline
Definition at line 82 of file PresburgerSpace.h.
Referenced by mlir::presburger::PresburgerRelation::getNumRangeIds(), mlir::presburger::IntegerRelation::getNumRangeIds(), mlir::presburger::IntegerRelation::getSpaceWithoutLocals(), isCompatible(), and print().
getNumSetDimIds()
unsigned mlir::presburger::PresburgerSpace::getNumSetDimIds () const inline
Definition at line 83 of file PresburgerSpace.h.
getNumSymbolIds()
unsigned mlir::presburger::PresburgerSpace::getNumSymbolIds () const inline
Definition at line 84 of file PresburgerSpace.h.
Referenced by mlir::presburger::PresburgerRelation::getNumSymbolIds(), mlir::presburger::IntegerRelation::getNumSymbolIds(), mlir::presburger::IntegerRelation::getSpaceWithoutLocals(), isCompatible(), and print().
getRelationSpace()
static PresburgerSpace mlir::presburger::PresburgerSpace::getRelationSpace (unsigned numDomain = 0, unsigned numRange = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline static
Definition at line 67 of file PresburgerSpace.h.
Referenced by mlir::presburger::IntegerRelation::getSpaceWithoutLocals(), and mlir::presburger::IntegerRelation::unionBoundingBox().
getSetSpace()
static PresburgerSpace mlir::presburger::PresburgerSpace::getSetSpace (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline static
Definition at line 74 of file PresburgerSpace.h.
Referenced by mlir::presburger::IntegerPolyhedron::findSymbolicIntegerLexMin(), and mlir::FlatAffineValueConstraints::FlatAffineValueConstraints().
insertId()
unsigned PresburgerSpace::insertId (IdKind kind, unsigned pos, unsigned num = 1)
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Definition at line 72 of file PresburgerSpace.cpp.
isCompatible()
bool PresburgerSpace::isCompatible (const PresburgerSpace & other) const
Returns true if both the spaces are compatible i.e.
if both spaces have the same number of identifiers of each kind (excluding locals).
Definition at line 107 of file PresburgerSpace.cpp.
References getNumDomainIds(), getNumRangeIds(), and getNumSymbolIds().
Referenced by mlir::presburger::PWMAFunction::addPiece(), getSetDifference(), mlir::presburger::PresburgerRelation::intersect(), mlir::presburger::PresburgerRelation::isEqual(), isEqual(), mlir::presburger::PWMAFunction::isEqual(), mlir::presburger::mergeLocalIds(), mlir::presburger::PresburgerRelation::subtract(), mlir::presburger::PresburgerRelation::unionInPlace(), and mlir::presburger::PresburgerRelation::unionSet().
isEqual()
bool PresburgerSpace::isEqual (const PresburgerSpace & other) const
Returns true if both the spaces are equal including local identifiers i.e.
if both spaces have the same number of identifiers of each kind (including locals).
Definition at line 113 of file PresburgerSpace.cpp.
References getNumLocalIds(), and isCompatible().
Referenced by mlir::presburger::IntegerRelation::append(), mlir::presburger::IntegerRelation::isEqual(), mlir::presburger::IntegerRelation::isSubsetOf(), and mlir::presburger::IntegerRelation::unionBoundingBox().
print()
void PresburgerSpace::print (llvm::raw_ostream & os) const
Definition at line 124 of file PresburgerSpace.cpp.
References getNumDomainIds(), getNumLocalIds(), getNumRangeIds(), and getNumSymbolIds().
Referenced by dump(), and mlir::presburger::IntegerRelation::printSpace().
removeIdRange()
void PresburgerSpace::removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Removes identifiers of the specified kind in the column range [idStart, idLimit).
The range is relative to the kind of identifier.
Definition at line 89 of file PresburgerSpace.cpp.
Referenced by mlir::presburger::IntegerRelation::fourierMotzkinEliminate().
setDimSymbolSeparation()
void PresburgerSpace::setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Depending on the new symbol count, either a chunk of dimensional identifiers immediately before the split become symbols, or some of the symbols immediately after the split become dimensions.
Definition at line 117 of file PresburgerSpace.cpp.
References getNumDimAndSymbolIds().
Referenced by mlir::presburger::IntegerRelation::setDimSymbolSeparation().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerSpace.h
lib/Analysis/Presburger/PresburgerSpace.cpp