MLIR: mlir::tblgen::Class Class Reference
mlir::tblgen::Class Class Reference
A class used to emit C++ classes from Tablegen.
#include "mlir/TableGen/Class.h"
Public Member Functions
virtual ~Class ()=default
Class (const Class &)=delete
Explicitly delete the copy constructor.
template<typename NameT , typename = typename std::enable_if_t< !std::is_same<NameT, Class>::value>>
Class (NameT &&name, bool isStruct=false)
Create a class with a name, and whether it should be declared as a class or struct.
template<Method::Properties Properties = Method::None, typename... Args>
Constructor * addConstructor (Args &&...args)
Add a new constructor to this class and prune and constructors made redundant by it.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addMethod (RetTypeT &&retType, NameT &&name, Method::Properties properties, Args &&...args)
Add a new method to this class and prune any methods made redundant by it.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add a method with statically-known properties.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addStaticMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add a static method.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addStaticInlineMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add an inline static method.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addInlineMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add an inline method.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * addConstMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add a const method.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * declareMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add a declaration for a method.
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args>
Method * declareStaticMethod (RetTypeT &&retType, NameT &&name, Args &&...args)
Add a declaration for a static method.
template<typename TypeT , typename NameT >
void addField (TypeT &&type, NameT &&name)
Add a new field to the class.
ParentClass & addParent (ParentClass parent)
Add a parent class.
StringRef getClassName () const
Return the C++ name of the class.
void writeDeclTo (raw_ostream &rawOs) const
Write the declaration of this class, all declarations, and definitions of inline functions.
void writeDefTo (raw_ostream &rawOs) const
Write the definitions of thiss class's out-of-line constructors and methods.
void writeDeclTo (raw_indented_ostream &os) const
Write the declaration of this class, all declarations, and definitions of inline functions.
void writeDefTo (raw_indented_ostream &os) const
Write the definitions of thiss class's out-of-line constructors and methods.
template<typename DeclT , typename... Args>
DeclT * declare (Args &&...args)
Add a declaration.
virtual void finalize ()
The declaration of a class needs to be "finalized".
Protected Member Functions
Constructor * addConstructorAndPrune (Constructor &&newCtor)
Add a new constructor if it is not made redundant by any existing constructors and prune and existing constructors made redundant.
Method * addMethodAndPrune (Method &&newMethod)
Add a new method if it is not made redundant by any existing methods and prune and existing methods made redundant.
Visibility getLastVisibilityDecl () const
Get the last visibility declaration.
Protected Attributes
std::string className
The C++ class name.
SmallVector< ParentClass > parents
The list of parent classes.
std::vector< std::unique_ptr< Method > > methods
The pending list of methods and constructors.
SmallVector< Field > fields
The pending list of private class fields.
bool isStruct
Whether this is a class or a struct.
std::vector< std::unique_ptr< ClassDeclaration > > declarations
A list of declarations in the class, emitted in order.
Detailed Description
A class used to emit C++ classes from Tablegen.
Contains a list of public methods and a list of private fields to be emitted.
Definition at line 565 of file Class.h.
Constructor & Destructor Documentation
~Class()
virtual mlir::tblgen::Class::~Class () virtual default
Class() [1/2]
mlir::tblgen::Class::Class (const Class &) delete
Explicitly delete the copy constructor.
This is to work around a gcc-5 bug with std::is_trivially_move_constructible.
Class() [2/2]
template<typename NameT , typename = typename std::enable_if_t< !std::is_same<NameT, Class>::value>> mlir::tblgen::Class::Class (NameT && name, bool isStruct = false) inline
Create a class with a name, and whether it should be declared as a class or struct.
Also, prevent this from being mistaken as a move constructor candidate.
Definition at line 578 of file Class.h.
References mlir::tblgen::Method::None.
Member Function Documentation
addConstMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addConstMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add a const method.
Definition at line 642 of file Class.h.
References mlir::tblgen::Method::None.
addConstructor()
template<Method::Properties Properties = Method::None, typename... Args> Constructor* mlir::tblgen::Class::addConstructor (Args &&... args) inline
Add a new constructor to this class and prune and constructors made redundant by it.
Returns null if the constructor was not added. Else, returns a pointer to the new constructor.
Definition at line 585 of file Class.h.
References mlir::tblgen::Method::Constructor, and mlir::tblgen::Method::None.
addConstructorAndPrune()
Constructor * Class::addConstructorAndPrune (Constructor && newCtor) protected
Add a new constructor if it is not made redundant by any existing constructors and prune and existing constructors made redundant.
Definition at line 366 of file Class.cpp.
References insertAndPruneMethods().
addField()
template<typename TypeT , typename NameT > void mlir::tblgen::Class::addField (TypeT && type, NameT && name) inline
Add a new field to the class.
Class fields added this way are always private.
Definition at line 670 of file Class.h.
addInlineMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addInlineMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add an inline method.
Definition at line 633 of file Class.h.
References mlir::tblgen::Method::None.
addMethod() [1/2]
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addMethod (RetTypeT && retType, NameT && name, Method::Properties properties, Args &&... args) inline
Add a new method to this class and prune any methods made redundant by it.
Returns null if the method was not added (because an existing method would make it redundant). Else, returns a pointer to the new method.
Definition at line 596 of file Class.h.
References mlir::tblgen::Method::None.
addMethod() [2/2]
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add a method with statically-known properties.
Definition at line 606 of file Class.h.
References mlir::tblgen::Method::None.
addMethodAndPrune()
Method * Class::addMethodAndPrune (Method && newMethod) protected
Add a new method if it is not made redundant by any existing methods and prune and existing methods made redundant.
Definition at line 361 of file Class.cpp.
References insertAndPruneMethods().
addParent()
ParentClass & Class::addParent (ParentClass parent)
Add a parent class.
Definition at line 272 of file Class.cpp.
addStaticInlineMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addStaticInlineMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add an inline static method.
Definition at line 623 of file Class.h.
References mlir::tblgen::Method::None.
addStaticMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::addStaticMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add a static method.
Definition at line 614 of file Class.h.
References mlir::tblgen::Method::None.
declare()
template<typename DeclT , typename... Args> DeclT* mlir::tblgen::Class::declare (Args &&... args) inline
Add a declaration.
The declaration is appended directly to the list of class declarations.
Definition at line 703 of file Class.h.
declareMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::declareMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add a declaration for a method.
Definition at line 651 of file Class.h.
References mlir::tblgen::Method::None.
declareStaticMethod()
template<Method::Properties Properties = Method::None, typename RetTypeT , typename NameT , typename... Args> Method* mlir::tblgen::Class::declareStaticMethod (RetTypeT && retType, NameT && name, Args &&... args) inline
Add a declaration for a static method.
Definition at line 660 of file Class.h.
finalize()
void Class::finalize () virtual
The declaration of a class needs to be "finalized".
Class constructors, methods, and fields can be added in any order, regardless of whether they are public or private. These are stored in lists separate from list of declarations declarations.
So that the generated C++ code is somewhat organised, public methods are declared together, and so are private methods and class fields. This function iterates through all the added methods and fields and organises them into the list of declarations, adding visibility declarations as needed, as follows:
public methods and constructors
private methods and constructors
class fields – all are private
Class::finalize clears the lists of pending methods and fields, and can be called multiple times.
Definition at line 301 of file Class.cpp.
References mlir::tblgen::Private, and mlir::tblgen::Public.
getClassName()
StringRef mlir::tblgen::Class::getClassName () const inline
Return the C++ name of the class.
Definition at line 678 of file Class.h.
getLastVisibilityDecl()
Visibility Class::getLastVisibilityDecl () const protected
Get the last visibility declaration.
Definition at line 337 of file Class.cpp.
References mlir::tblgen::Private, and mlir::tblgen::Public.
writeDeclTo() [1/2]
void mlir::tblgen::Class::writeDeclTo (raw_ostream & rawOs) const inline
Write the declaration of this class, all declarations, and definitions of inline functions.
Wrap the output stream in an indented stream.
Definition at line 682 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo().
writeDeclTo() [2/2]
void Class::writeDeclTo (raw_indented_ostream & os) const
Write the declaration of this class, all declarations, and definitions of inline functions.
Definition at line 277 of file Class.cpp.
References mlir::raw_indented_ostream::scope().
writeDefTo() [1/2]
void mlir::tblgen::Class::writeDefTo (raw_ostream & rawOs) const inline
Write the definitions of thiss class's out-of-line constructors and methods.
Wrap the output stream in an indented stream.
Definition at line 688 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo(), and mlir::tblgen::MethodParameter::writeDefTo().
writeDefTo() [2/2]
void Class::writeDefTo (raw_indented_ostream & os) const
Write the definitions of thiss class's out-of-line constructors and methods.
Definition at line 295 of file Class.cpp.
Member Data Documentation
className
std::string mlir::tblgen::Class::className protected
The C++ class name.
Definition at line 742 of file Class.h.
declarations
std::vector<std::unique_ptr<ClassDeclaration> > mlir::tblgen::Class::declarations protected
A list of declarations in the class, emitted in order.
Definition at line 753 of file Class.h.
fields
SmallVector<Field> mlir::tblgen::Class::fields protected
The pending list of private class fields.
Definition at line 748 of file Class.h.
isStruct
bool mlir::tblgen::Class::isStruct protected
Whether this is a class or a struct.
Definition at line 750 of file Class.h.
methods
std::vector<std::unique_ptr<Method> > mlir::tblgen::Class::methods protected
The pending list of methods and constructors.
Definition at line 746 of file Class.h.
parents
SmallVector<ParentClass> mlir::tblgen::Class::parents protected
The list of parent classes.
Definition at line 744 of file Class.h.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp