MLIR: mlir::bufferization::OneShotAnalysisState Class Reference
mlir::bufferization::OneShotAnalysisState Class Reference
State for analysis-enabled bufferization.
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
Public Member Functions
OneShotAnalysisState (Operation *op, const OneShotBufferizationOptions &options)
OneShotAnalysisState (const OneShotAnalysisState &)=delete
virtual ~OneShotAnalysisState ()=default
BufferizationAliasInfo & getAliasInfo ()
Return a reference to the BufferizationAliasInfo.
bool isInPlace (OpOperand &opOperand) const override
Return true if the given OpResult has been decided to bufferize inplace.
bool areEquivalentBufferizedValues (Value v1, Value v2) const override
Return true if v1 and v2 bufferize to equivalent buffers.
bool isTensorYielded (Value tensor) const override
Return true if the given tensor (or an aliasing tensor) is yielded from the containing block.
void gatherYieldedTensors (Operation *op)
Find all tensors that are yielded/returned from a block and store them in yieldedTensors.
Public Member Functions inherited from mlir::bufferization::AnalysisState
SmallVector< OpOperand * > getAliasingOpOperand (OpResult result) const
Determine which OpOperand* will alias with result if the op is bufferized in place.
SmallVector< OpResult > getAliasingOpResult (OpOperand &opOperand) const
Determine which OpResult will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
SetVector< Value > findValueInReverseUseDefChain (Value value, llvm::function_ref< bool(Value)> condition) const
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
SetVector< Value > findLastPrecedingWrite (Value value) const
Find the Values of the last preceding write of a given Value.
bool hasDialectState (StringRef name) const
Return true if the given dialect state exists.
template<typename StateT >
Optional< const StateT * > getDialectState (StringRef name) const
Return dialect-specific bufferization state.
template<typename StateT >
StateT & getOrCreateDialectState (StringRef name)
Return dialect-specific analysis state or create one if none exists.
void insertDialectState (StringRef name, std::unique_ptr< DialectAnalysisState > state)
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
Additional Inherited Members
Protected Member Functions inherited from mlir::bufferization::AnalysisState
AnalysisState (const BufferizationOptions &options)
AnalysisState (const AnalysisState &)=delete
~AnalysisState ()=default
Detailed Description
State for analysis-enabled bufferization.
This class keeps track of alias (via BufferizationAliasInfo) to decide if tensor OpOperands should bufferize in-place.
Definition at line 151 of file OneShotAnalysis.h.
Constructor & Destructor Documentation
OneShotAnalysisState() [1/2]
OneShotAnalysisState::OneShotAnalysisState (Operation * op, const OneShotBufferizationOptions & options)
Definition at line 189 of file OneShotAnalysis.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationOptions::isOpAllowed(), mlir::bufferization::BufferizationAliasInfo::markInPlace(), mlir::WalkResult::skip(), mlir::bufferization::BufferizationAliasInfo::unionAliasSets(), and mlir::Operation::walk().
OneShotAnalysisState() [2/2]
mlir::bufferization::OneShotAnalysisState::OneShotAnalysisState (const OneShotAnalysisState &) delete
~OneShotAnalysisState()
virtual mlir::bufferization::OneShotAnalysisState::~OneShotAnalysisState () virtual default
Member Function Documentation
areEquivalentBufferizedValues()
bool OneShotAnalysisState::areEquivalentBufferizedValues (Value v1, Value v2) const override virtual
Return true if v1 and v2 bufferize to equivalent buffers.
Implements mlir::bufferization::AnalysisState.
Definition at line 214 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues().
gatherYieldedTensors()
void OneShotAnalysisState::gatherYieldedTensors (Operation * op)
Find all tensors that are yielded/returned from a block and store them in yieldedTensors.
Also include all aliasing tensors in the same block.
Definition at line 223 of file OneShotAnalysis.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Operation::getOpOperands(), mlir::bufferization::AnalysisState::getOptions(), mlir::Operation::getParentOp(), mlir::Value::getType(), mlir::Type::isa(), mlir::isRegionReturnLike(), and mlir::Operation::walk().
Referenced by mlir::bufferization::analyzeOp().
getAliasInfo()
BufferizationAliasInfo& mlir::bufferization::OneShotAnalysisState::getAliasInfo () inline
Return a reference to the BufferizationAliasInfo.
Definition at line 161 of file OneShotAnalysis.h.
References mlir::bufferization::analyzeOp(), isInPlace(), options, and mlir::bufferization::runOneShotBufferize().
Referenced by mlir::bufferization::analyzeOp().
isInPlace()
bool OneShotAnalysisState::isInPlace (OpOperand & opOperand) const override virtual
Return true if the given OpResult has been decided to bufferize inplace.
Implements mlir::bufferization::AnalysisState.
Definition at line 210 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::isInPlace().
isTensorYielded()
bool OneShotAnalysisState::isTensorYielded (Value tensor) const override virtual
Return true if the given tensor (or an aliasing tensor) is yielded from the containing block.
Also include all aliasing tensors in the same block.
Implements mlir::bufferization::AnalysisState.
Definition at line 252 of file OneShotAnalysis.cpp.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h
lib/Dialect/Bufferization/Transforms/OneShotAnalysis.cpp