MLIR: mlir::AttributeStorage Class Reference
mlir::AttributeStorage Class Reference
Base storage class appearing in an attribute.
#include "mlir/IR/AttributeSupport.h"
Public Member Functions
Type getType () const
Get the type of this attribute.
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Protected Member Functions
AttributeStorage (Type type=nullptr)
Construct a new attribute storage instance with the given type.
void setType (Type newType)
Set the type of this attribute.
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Base storage class appearing in an attribute.
Derived storage classes should only be constructed within the context of the AttributeUniquer.
Definition at line 127 of file AttributeSupport.h.
Constructor & Destructor Documentation
AttributeStorage()
mlir::AttributeStorage::AttributeStorage (Type type = nullptr) inline protected
Construct a new attribute storage instance with the given type.
Note: All attributes require a valid type. If no type is provided here, the type of the attribute will automatically default to NoneType upon initialization in the uniquer.
Definition at line 146 of file AttributeSupport.h.
Member Function Documentation
getAbstractAttribute()
const AbstractAttribute& mlir::AttributeStorage::getAbstractAttribute () const inline
Return the abstract descriptor for this attribute.
Definition at line 136 of file AttributeSupport.h.
getType()
Type mlir::AttributeStorage::getType () const inline
Get the type of this attribute.
Definition at line 133 of file AttributeSupport.h.
Referenced by mlir::MLIRContext::getAttributeUniquer(), mlir::detail::DenseIntOrFPElementsAttrStorage::operator==(), mlir::detail::DenseStringElementsAttrStorage::operator==(), and mlir::detail::StringAttrStorage::operator==().
initialize()
void mlir::AttributeStorage::initialize (MLIRContext * context) inline protected
Default initialization for attribute storage classes that require no additional initialization.
Definition at line 159 of file AttributeSupport.h.
Referenced by mlir::detail::StringAttrStorage::construct().
initializeAbstractAttribute()
void mlir::AttributeStorage::initializeAbstractAttribute (const AbstractAttribute & abstractAttr) inline protected
Set the abstract attribute for this storage instance.
This is used by the AttributeUniquer when initializing a newly constructed storage object.
Definition at line 153 of file AttributeSupport.h.
Referenced by mlir::MLIRContext::getAttributeUniquer().
setType()
void mlir::AttributeStorage::setType (Type newType) inline protected
Set the type of this attribute.
Definition at line 149 of file AttributeSupport.h.
Referenced by mlir::MLIRContext::getAttributeUniquer().
The documentation for this class was generated from the following file:
include/mlir/IR/AttributeSupport.h