MLIR: mlir::LLVM::LLVMPointerType Class Reference
mlir::LLVM::LLVMPointerType Class Reference
LLVM dialect pointer type.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
Type getElementType () const
Returns the pointed-to type. It may be null if the pointer is opaque.
bool isOpaque () const
Returns true if this type is the opaque pointer type, i.e., it has no pointed-to type.
unsigned getAddressSpace () const
Returns the address space of the pointer.
unsigned getTypeSizeInBits (const DataLayout &dataLayout, DataLayoutEntryListRef params) const
Hooks for DataLayoutTypeInterface.
unsigned getABIAlignment (const DataLayout &dataLayout, DataLayoutEntryListRef params) const
unsigned getPreferredAlignment (const DataLayout &dataLayout, DataLayoutEntryListRef params) const
bool areCompatible (DataLayoutEntryListRef oldLayout, DataLayoutEntryListRef newLayout) const
LogicalResult verifyEntries (DataLayoutEntryListRef entries, Location loc) const
Static Public Member Functions
static bool isValidElementType (Type type)
Checks if the given type can have a pointer type pointing to it.
static LLVMPointerType get (MLIRContext *context, unsigned addressSpace=0)
Gets or creates an instance of LLVM dialect pointer type pointing to an object of pointee type in the given address space.
static LLVMPointerType get (Type pointee, unsigned addressSpace=0)
static LLVMPointerType getChecked (function_ref< InFlightDiagnostic()> emitError, Type pointee, unsigned addressSpace=0)
static LLVMPointerType getChecked (function_ref< InFlightDiagnostic()> emitError, MLIRContext *context, unsigned addressSpace=0)
static LogicalResult verify (function_ref< InFlightDiagnostic()> emitError, Type pointee, unsigned)
Verifies that the type about to be constructed is well-formed.
static LogicalResult verify (function_ref< InFlightDiagnostic()> emitError, MLIRContext *context, unsigned)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verify (Args... args)
Default implementation that just returns success.
Detailed Description
LLVM dialect pointer type.
This type typically represents a reference to an object in memory. Pointers may be opaque or parameterized by the element type. Both opaque and non-opaque pointers are additionally parameterized by the address space.
Definition at line 182 of file LLVMTypes.h.
Member Function Documentation
areCompatible()
bool LLVMPointerType::areCompatible (DataLayoutEntryListRef oldLayout, DataLayoutEntryListRef newLayout) const
Definition at line 292 of file LLVMTypes.cpp.
References mlir::Attribute::cast(), extractPointerSpecValue(), getAddressSpace(), kDefaultPointerAlignment, and kDefaultPointerSizeBits.
get() [1/2]
LLVMPointerType LLVMPointerType::get (MLIRContext * context, unsigned addressSpace = 0) static
Gets or creates an instance of LLVM dialect pointer type pointing to an object of pointee type in the given address space.
The pointer type is created in the same context as pointee. If the pointee is not provided, creates an opaque pointer in the given context and address space.
Definition at line 173 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get().
Referenced by addAtomicRMW(), addResumeFunction(), mlir::LLVMTypeConverter::canConvertToBarePtr(), castDataPtr(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertPointerType(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), mlir::LLVM::createGlobalString(), declareReduction(), mlir::ConvertToLLVMPattern::getElementPtrType(), getLoadStoreElementType(), mlir::LLVMTypeConverter::getMemRefDescriptorSize(), mlir::LLVMTypeConverter::getPointerBitwidth(), getPtrToElementType(), mlir::ConvertToLLVMPattern::getSizeInBytes(), mlir::ConvertToLLVMPattern::getVoidPtrType(), isDefinedByCallTo(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::LLVM::lookupOrCreateAlignedAllocFn(), mlir::LLVM::lookupOrCreateFreeFn(), mlir::LLVM::lookupOrCreateMallocFn(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), mlirLLVMPointerTypeGet(), mlir::UnrankedMemRefDescriptor::offset(), mlir::populateGpuToLLVMConversionPatterns(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::MemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), mlir::UnrankedMemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::strideBasePtr(), mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType(), and wrapExternalFunction().
get() [2/2]
LLVMPointerType LLVMPointerType::get (Type pointee, unsigned addressSpace = 0) static
Definition at line 167 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), and mlir::Type::getContext().
getABIAlignment()
unsigned LLVMPointerType::getABIAlignment (const DataLayout & dataLayout, DataLayoutEntryListRef params) const
Definition at line 269 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMArrayType::getElementType(), getPointerDataLayoutEntry(), and mlir::DataLayout::getTypeABIAlignment().
getAddressSpace()
unsigned LLVMPointerType::getAddressSpace () const
Returns the address space of the pointer.
Definition at line 195 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by areCompatible(), getPointerDataLayoutEntry(), mlir::LLVMTypeConverter::LLVMTypeConverter(), lookupSymbolInModule(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getChecked() [1/2]
LLVMPointerType LLVMPointerType::getChecked (function_ref< InFlightDiagnostic()> emitError, Type pointee, unsigned addressSpace = 0) static
Definition at line 179 of file LLVMTypes.cpp.
References mlir::emitError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), and mlir::Type::getContext().
getChecked() [2/2]
LLVMPointerType LLVMPointerType::getChecked (function_ref< InFlightDiagnostic()> emitError, MLIRContext * context, unsigned addressSpace = 0) static
Definition at line 186 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked().
getElementType()
Type LLVMPointerType::getElementType () const
Returns the pointed-to type. It may be null if the pointer is opaque.
Definition at line 191 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by convertOmpAtomicUpdate(), mlir::LLVMTypeConverter::LLVMTypeConverter(), lookupSymbolInModule(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getPreferredAlignment()
unsigned LLVMPointerType::getPreferredAlignment (const DataLayout & dataLayout, DataLayoutEntryListRef params) const
Definition at line 281 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMArrayType::getElementType(), getPointerDataLayoutEntry(), and mlir::DataLayout::getTypePreferredAlignment().
getTypeSizeInBits()
unsigned LLVMPointerType::getTypeSizeInBits (const DataLayout & dataLayout, DataLayoutEntryListRef params) const
Hooks for DataLayoutTypeInterface.
Should not be called directly. Obtain a DataLayout instance and query it instead.
Definition at line 256 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMArrayType::getElementType(), getPointerDataLayoutEntry(), and mlir::DataLayout::getTypeSizeInBits().
isOpaque()
bool LLVMPointerType::isOpaque () const
Returns true if this type is the opaque pointer type, i.e., it has no pointed-to type.
Definition at line 193 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::LLVMTypeConverter::LLVMTypeConverter(), lookupSymbolInModule(), mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType(), and verifyOpaquePtr().
isValidElementType()
bool LLVMPointerType::isValidElementType (Type type) static
Checks if the given type can have a pointer type pointing to it.
Definition at line 158 of file LLVMTypes.cpp.
References mlir::Type::isa(), and mlir::LLVM::isCompatibleOuterType().
Referenced by isZeroAttribute().
verify() [1/2]
LogicalResult LLVMPointerType::verify (function_ref< InFlightDiagnostic()> emitError, Type pointee, unsigned) static
Verifies that the type about to be constructed is well-formed.
Definition at line 200 of file LLVMTypes.cpp.
References mlir::emitError(), mlir::LLVM::LLVMArrayType::isValidElementType(), and mlir::success().
verify() [2/2]
static LogicalResult mlir::LLVM::LLVMPointerType::verify (function_ref< InFlightDiagnostic()> emitError, MLIRContext * context, unsigned) inline static
Definition at line 218 of file LLVMTypes.h.
References mlir::success().
verifyEntries()
LogicalResult LLVMPointerType::verifyEntries (DataLayoutEntryListRef entries, Location loc) const
Definition at line 330 of file LLVMTypes.cpp.
References mlir::emitError(), extractPointerSpecValue(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp