MLIR: mlir::pdll::ast::OpConstraintDecl Class Reference
mlir::pdll::ast::OpConstraintDecl Class Reference
The class represents an Operation constraint, and constrains a variable to be an Operation.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Optional< StringRef > getName () const
Return the name of the operation, or None if there isn't one.
const OpNameDecl * getNameDecl () const
Return the declaration of the operation name.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static OpConstraintDecl * create (Context &ctx, SMRange loc, const OpNameDecl *nameDecl=nullptr)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OpConstraintDecl, CoreConstraintDecl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::ConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
OpConstraintDecl (SMRange loc, const OpNameDecl *nameDecl)
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OpConstraintDecl, CoreConstraintDecl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
CoreConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::ConstraintDecl
ConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Protected Attributes
const OpNameDecl * nameDecl
The operation name of this constraint.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< OpConstraintDecl, CoreConstraintDecl >
using Base = NodeBase< OpConstraintDecl, CoreConstraintDecl >
Detailed Description
The class represents an Operation constraint, and constrains a variable to be an Operation.
Definition at line 721 of file Nodes.h.
Constructor & Destructor Documentation
OpConstraintDecl()
mlir::pdll::ast::OpConstraintDecl::OpConstraintDecl (SMRange loc, const OpNameDecl * nameDecl) inline explicit protected
Definition at line 734 of file Nodes.h.
Member Function Documentation
create()
OpConstraintDecl * OpConstraintDecl::create (Context & ctx, SMRange loc, const OpNameDecl * nameDecl = nullptr) static
Definition at line 371 of file Nodes.cpp.
References mlir::pdll::ast::OpNameDecl::create(), and mlir::pdll::ast::Context::getAllocator().
getName()
Optional< StringRef > OpConstraintDecl::getName () const
Return the name of the operation, or None if there isn't one.
Definition at line 380 of file Nodes.cpp.
Referenced by getLspDiagnoticFromDiag().
getNameDecl()
const OpNameDecl* mlir::pdll::ast::OpConstraintDecl::getNameDecl () const inline
Return the declaration of the operation name.
Definition at line 731 of file Nodes.h.
Referenced by mlir::pdll::ast::Name::create().
Member Data Documentation
nameDecl
const OpNameDecl* mlir::pdll::ast::OpConstraintDecl::nameDecl protected
The operation name of this constraint.
Definition at line 738 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp