MLIR: mlir::Type Class Reference
mlir::Type Class Reference
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
#include "mlir/IR/Types.h"
Public Types
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Public Member Functions
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Protected Attributes
ImplType * impl {nullptr}
Friends
::llvm::hash_code hash_value (Type arg)
Detailed Description
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
They wrap a pointer to the storage object owned by MLIRContext. Therefore, instances of Type are passed around by value.
Some types are "primitives" meaning they do not have any parameters, for example the Index type. Parametric types have additional information that differentiates the types of the same class, for example the Integer type has bitwidth, making i8 and i16 belong to the same kind by be different instances of the IntegerType. Type parameters are part of the unique immutable key. The mutable component of the type can be modified after the type is created, but cannot affect the identity of the type.
Types are constructed and uniqued via the 'detail::TypeUniquer' class.
Derived type classes are expected to implement several required implementation hooks:
Optional:
static LogicalResult verify(function_ref<InFlightDiagnostic()> emitError, Args... args)
This method is invoked when calling the 'TypeBase::get/getChecked' methods to ensure that the arguments passed in are valid to construct a type instance with.
This method is expected to return failure if a type cannot be constructed with 'args', success otherwise.
'args' must correspond with the arguments passed into the 'TypeBase::get' call.
Type storage objects inherit from TypeStorage and contain the following:
The dialect that defined the type.
Any parameters of the type.
An optional mutable component. For non-parametric types, a convenience DefaultTypeStorage is provided. Parametric storage types must derive TypeStorage and respect the following:
Define a type alias, KeyTy, to a type that uniquely identifies the instance of the type.
The key type must be constructible from the values passed into the detail::TypeUniquer::get call.
If the KeyTy does not have an llvm::DenseMapInfo specialization, the storage class must define a hashing method: 'static unsigned hashKey(const KeyTy &)'
Provide a method, 'bool operator==(const KeyTy &) const', to compare the storage instance against an instance of the key type.
Provide a static construction method: 'DerivedStorage *construct(TypeStorageAllocator &, const KeyTy &key)' that builds a unique instance of the derived storage. The arguments to this function are an allocator to store any uniqued data within the context and the key type for this storage.
If they have a mutable component, this component must not be a part of
Definition at line 72 of file Types.h.
Member Typedef Documentation
AbstractTy
using mlir::Type::AbstractTy = AbstractType
Definition at line 82 of file Types.h.
ImplType
using mlir::Type::ImplType = TypeStorage
Definition at line 80 of file Types.h.
TypeBase
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits> using mlir::Type::TypeBase = detail::StorageUserBase<ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits...>
Utility class for implementing types.
Definition at line 78 of file Types.h.
Constructor & Destructor Documentation
Type() [1/3]
constexpr mlir::Type::Type () inline
Definition at line 84 of file Types.h.
Referenced by mlir::pdl::PDLType::classof(), getFromOpaquePointer(), and Type().
Type() [2/3]
mlir::Type::Type (const ImplType * impl) inline
Definition at line 85 of file Types.h.
References operator=(), and Type().
Type() [3/3]
mlir::Type::Type (const Type & other) default
Member Function Documentation
cast()
template<typename U > U mlir::Type::cast () const
Definition at line 250 of file Types.h.
Referenced by mlir::AllocLikeOpLLVMLowering::AllocLikeOpLLVMLowering(), applyPad(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::LLVMTypeConverter::canConvertToBarePtr(), castBoolToIntN(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::bufferization::castOrReallocMemRefValue(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), checkIntFloatCast(), mlir::DenseFPElementsAttr::classof(), mlir::DenseIntElementsAttr::classof(), collapseGenericOpIterationDims(), mlir::spirv::Deserializer::collect(), mlir::DenseElementsAttr::complex_float_value_begin(), mlir::DenseElementsAttr::complex_float_value_end(), computeCollapsedType(), computeExpandedType(), computeMemRefRankReductionMask(), computeTensorReshapeCollapsedType(), convertArrayType(), convertOmpAtomicRead(), convertScalarType(), mlir::tensor::createCanonicalRankReducingExtractSliceOp(), mlir::tensor::createCanonicalRankReducingInsertSliceOp(), createConstantAllBitsSet(), createFPConstant(), createGlobalVarForEntryPointArgument(), createInitialValueForReduceOp(), createLinalgBodyCalculationForElementwiseOp(), createReassociationMapsForCollapse(), createSubViewIntersection(), doubleBuffer(), ensureToMemrefOpIsValid(), extractOne(), mlir::StructBuilder::extractPtr(), findAncestorOpInRegion(), findDuplicateElement(), mlir::DenseElementsAttr::float_value_begin(), mlir::DenseElementsAttr::float_value_end(), foldExtractFromBroadcast(), foldExtractFromShapeCast(), foldExtractStridedOpFromInsertChain(), foldInsertAfterInsertSlice(), foldTransferInBoundsAttribute(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), generateCopy(), mlir::linalg::generateLibraryCallName(), generatePointWiseCopy(), genLoad(), mlir::DenseElementsAttr::get(), getAllocationTypeAndShape(), mlir::spirv::ArrayType::getCapabilities(), mlir::spirv::RuntimeArrayType::getCapabilities(), mlir::spirv::CooperativeMatrixNVType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::AffineDmaStartOp::getDstMemorySpace(), mlir::AffineDmaStartOp::getDstMemRefRank(), mlir::AffineDmaStartOp::getDstMemRefType(), mlir::linalg::getDynOperands(), mlir::MemRefDescriptor::getElementPtrType(), mlir::ShapeAdaptor::getElementType(), mlir::spirv::MatrixType::getElementType(), mlir::spirv::ArrayType::getExtensions(), mlir::spirv::RuntimeArrayType::getExtensions(), mlir::spirv::CooperativeMatrixNVType::getExtensions(), getFirstIntValue(), mlir::DenseElementsAttr::getFloatValues(), getFullMemRefAsRegion(), getLocalInvocationDimSize(), mlir::bufferization::getMemRefType(), getMultiLevelStrides(), getNumElements(), mlir::sparse_tensor::getOneAttr(), getPushConstantVariable(), mlir::quant::QuantizedType::getQuantizedElementType(), getReshapeOutputShapeFromInputShape(), mlir::spirv::ArrayType::getSizeInBytes(), mlir::AffineDmaStartOp::getSrcMemorySpace(), mlir::AffineDmaStartOp::getSrcMemRefType(), mlir::AffineDmaStartOp::getTagMemRefRank(), mlir::AffineDmaWaitOp::getTagMemRefRank(), mlir::AffineDmaStartOp::getTagMemRefType(), mlir::AffineDmaWaitOp::getTagMemRefType(), mlir::DenseElementsAttr::getType(), mlir::Builder::getZeroAttr(), mlir::LLVM::detail::handleMultidimensionalVectors(), hasAllocationScope(), hasSameBitwidthScalarType(), inferDynamicDimsForConv(), inferIntrinsicResultType(), inferStridedSliceOpResultType(), insertCopies(), insertCopyLoops(), insertOne(), invertPredicate(), isAsyncWithOneDependency(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isComplexOfIntType(), isInBounds(), isMatchingWidth(), isMemRefNormalizable(), mlir::LLVM::isScalableVectorType(), isZeroAttribute(), joinShapes(), mlir::linalg::makeMemRefCopyOp(), mlir::linalg::makeTransposeOp(), mlir::OperandElementTypeIterator::mapElement(), mlir::ResultElementTypeIterator::mapElement(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), ReshapeConstOptimization::matchAndRewrite(), MaxPool2dIsNoOp::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), mlir::MemRefDescriptor::MemRefDescriptor(), minMaxValueForFloat(), minMaxValueForSignedInt(), minMaxValueForUnsignedInt(), minusOneIntegerAttribute(), mlir::normalizeMemRef(), operator!(), SubViewCanonicalizer::operator()(), mlir::DenseElementsAttr::IntElementIterator::operator*(), outlineExecuteOp(), mlir::detail::Parser::parseElementsLiteralType(), parseGlobalMemrefOpTypeAndInitialValue(), parseInferType(), populateFromInt64AttrArray(), printCreateOperationOpResults(), printGEPIndices(), produceSliceErrorMsg(), produceSubViewErrorMsg(), mlir::replaceAllMemRefUsesWith(), mlir::replaceForOpWithNewYields(), replaceUsesAndPropagateType(), reshapeLoad(), reshapeLowerToHigher(), mlir::linalg::rewriteAsPaddedOp(), mlir::detail::sameOffsetsSizesAndStrides(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), splatZero(), mlir::vector::splitFullAndPartialTransfer(), unpackOperandVector(), vectorType(), mlir::spirv::MatrixType::verify(), verifyAtomicCompareExchangeImpl(), verifyAtomicUpdateOp(), verifyBlockReadWritePtrAndValTypes(), verifyCastOp(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyExtOp(), verifyLoadStorePtrAndValTypes(), verifyMemoryOpIndexing(), verifyPointerAndCoopMatrixType(), verifyReductionVarList(), verifyTensorReshapeOp(), verifyTruncateOp(), verifyVectorMemoryOp(), and wrapExternalFunction().
classof()
static bool mlir::Type::classof (Type) inline static
Definition at line 104 of file Types.h.
dump()
void Type::dump () const
Definition at line 3007 of file AsmPrinter.cpp.
References print().
Referenced by getDialect().
dyn_cast()
template<typename U > U mlir::Type::dyn_cast () const
Definition at line 244 of file Types.h.
Referenced by mlir::ValueDecomposer::addDecomposeValueConversion(), addResumeFunction(), appendMangledType(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), mlir::tosa::buildConvOpQuantizationAttr(), mlir::tosa::buildConvOpResultTypeInfo(), buildLogicalUnaryOp(), mlir::tosa::buildMatMulOpQuantizationAttr(), buildMatMulOpWithQuantInfo(), mlir::tosa::buildPadOpQuantizationAttr(), mlir::tosa::buildQTypeFromMinMax(), mlir::tosa::buildUnaryOpQuantizationAttr(), castBoolToIntN(), checkIntFloatCast(), mlir::spirv::SPIRVType::classof(), mlir::spirv::ScalarType::classof(), mlir::spirv::CompositeType::classof(), collapseGenericOpIterationDims(), mlir::spirv::Deserializer::collect(), computeMemRefRankReductionMask(), mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::LLVMTypeConverter::convertCallingConventionType(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertIntrinsicResult(), convertMemrefType(), convertScalarType(), convertTensorType(), createFPConstant(), mlir::VulkanLayoutUtils::decorateType(), defaultIsSmallAlloc(), mlir::vector::distributPointwiseVectorOp(), elementwiseMatchAndRewriteHelper(), ensureToMemrefOpIsValid(), extractVectorElementType(), findAncestorOpInRegion(), findDuplicateElement(), foldExtractFromBroadcast(), foldExtractStridedOpFromInsertChain(), mlir::tensor::foldTensorCast(), mlir::bufferization::foldToMemrefToTensorPair(), foldTransferInBoundsAttribute(), forwardPassthroughAttributes(), genAddress(), getBitWidth(), mlir::bufferization::func_ext::getBufferizedFunctionArgType(), mlir::bufferization::BufferizationState::getBufferType(), mlir::detail::getDefaultABIAlignment(), mlir::detail::getDefaultPreferredAlignment(), mlir::detail::getDefaultTypeSizeInBits(), mlir::detail::getDenseElementBitWidth(), getElementPtrType(), getElementType(), mlir::getElementTypeOrSelf(), getEnclosingforOps(), mlir::FloatType::getFPMantissaWidth(), getI1SameShape(), getInsertExtractValueElementType(), mlir::tosa::ValueKnowledge::getKnowledgeFromType(), getLoadStoreElementType(), mlir::bufferization::getMemRefType(), getNumElements(), mlir::sparse_tensor::getOneAttr(), mlir::quant::QuantizedType::getQuantizedElementType(), getRuntimeArrayElementType(), getShape(), mlir::sparse_tensor::getSparseTensorEncoding(), getTensorOrVectorElementType(), mlir::memref::getTensorTypeFromMemRefType(), getTypeNumBytes(), getUnaryOpResultType(), mlir::getValueOrCreateCastToIndexLike(), mlir::Builder::getZeroAttr(), hasaUniqueDim(), mlir::hasNonIdentityLayout(), hasOneBranchOpTo(), PadOpVectorizationWithTransferWritePattern::hasSameTensorSize(), insertCasts(), insertCopies(), isAllocationSupported(), isBoolScalarOrVector(), mlir::vector::isBroadcastableTo(), mlir::LLVM::isCompatibleOuterType(), mlir::LLVM::isCompatibleVectorType(), mlir::shape::isExtentTensorType(), mlir::VulkanLayoutUtils::isLegalType(), isMemRefNormalizable(), mlir::isOpaqueTypeWithName(), isSignedIntegerOrVector(), isUnsignedIntegerOrVector(), mlir::DataDescriptor::isValid(), mlir::spirv::MatrixType::isValidColumnType(), mlir::LLVM::LLVMScalableVectorType::isValidElementType(), isValidIntOrFloat(), isValidQuantizationSpec(), isZeroAttribute(), joinShapes(), mlir::bufferization::lookupBuffer(), mlir::linalg::makeTiledShape(), matchAndReplaceDepthwiseConv(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), mlir::TypeConverter::materializeTargetConversion(), minusOneIntegerAttribute(), operator!(), optionallyBroadcast(), mlir::sparse_tensor::overheadTypeEncoding(), parseAndVerifyMatrixType(), parseAndVerifyType(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), parseAwaitResultType(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCustomTypeWithFallback(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), parseGlobalMemrefOpTypeAndInitialValue(), parseOneResultSameOperandTypeOp(), mlir::AsmParser::parseType(), mlir::tensor::preservesStaticInformation(), printAwaitResultType(), printCalibratedQuantizedType(), mlir::ExtensibleDialect::printIfDynamicType(), printNVVMIntrinsicOp(), printOperation(), mlir::quant::quantizeAttr(), reduceIfNeeded(), replaceUnitExtents(), reshapeLowerToHigher(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), mlir::DataDescriptor::setSize(), mlir::ShapeAdaptor::ShapeAdaptor(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), splatZero(), mlir::structFuncArgTypeConverter(), mlir::TypeRange::TypeRange(), vectorShape(), mlir::quant::QuantizedType::verify(), verifyAtomicCompareExchangeImpl(), verifyCastOp(), mlir::verifyCompatibleShape(), verifyConstantType(), verifyCoopMatrixMulAdd(), and writeAPIntsToBuffer().
dyn_cast_or_null()
template<typename U > U mlir::Type::dyn_cast_or_null () const
Definition at line 247 of file Types.h.
Referenced by getBoolAttribute(), and operator!().
getAbstractType()
const AbstractTy& mlir::Type::getAbstractType () inline
Return the abstract type descriptor for this type.
Definition at line 179 of file Types.h.
Referenced by hasTrait().
getAsOpaquePointer()
const void* mlir::Type::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 165 of file Types.h.
References impl.
Referenced by llvm::PointerLikeTypeTraits< mlir::Type >::getAsVoidPointer().
getContext()
MLIRContext * Type::getContext () const
Return the MLIRContext in which this type was uniqued.
Definition at line 19 of file Types.cpp.
Referenced by addResumeFunction(), combineOneSpec(), mlir::quant::fakeQuantAttrsToType(), findDuplicateElement(), mlir::DataLayoutEntryAttr::get(), mlir::LLVM::LLVMArrayType::get(), mlir::spirv::ArrayType::get(), mlir::gpu::MMAMatrixType::get(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::spirv::PointerType::get(), mlir::quant::AnyQuantizedType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::spirv::SampledImageType::get(), mlir::quant::UniformQuantizedType::get(), mlir::quant::UniformQuantizedPerAxisType::get(), mlir::LLVM::LLVMFixedVectorType::get(), mlir::quant::CalibratedQuantizedType::get(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::LLVM::LLVMScalableVectorType::get(), mlir::spirv::MatrixType::get(), mlir::LLVM::LLVMArrayType::getChecked(), mlir::gpu::MMAMatrixType::getChecked(), mlir::LLVM::LLVMFunctionType::getChecked(), mlir::LLVM::LLVMPointerType::getChecked(), mlir::quant::AnyQuantizedType::getChecked(), mlir::spirv::SampledImageType::getChecked(), mlir::quant::UniformQuantizedType::getChecked(), mlir::quant::UniformQuantizedPerAxisType::getChecked(), mlir::LLVM::LLVMFixedVectorType::getChecked(), mlir::quant::CalibratedQuantizedType::getChecked(), mlir::LLVM::LLVMScalableVectorType::getChecked(), mlir::spirv::MatrixType::getChecked(), mlir::Value::getContext(), mlir::detail::getDefaultABIAlignment(), mlir::detail::getDefaultPreferredAlignment(), mlir::detail::getDefaultTypeSizeInBits(), getGetValueTypeOpValueType(), getI1SameShape(), mlir::memref::getTensorTypeFromMemRefType(), getTypeID(), getUnaryOpResultType(), inferIntrinsicResultType(), parseSymbol(), printNVVMIntrinsicOp(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), mlir::MemRefType::Builder::setMemorySpace(), and mlir::UnrankedMemRefDescriptor::sizeBasePtr().
getDialect()
Dialect Type::getDialect () const inline
Get the dialect this type is registered to.
Definition at line 114 of file Types.h.
References dump(), getIntOrFloatBitWidth(), hash_value, isBF16(), isF128(), isF16(), isF32(), isF64(), isF80(), isIndex(), isInteger(), isIntOrFloat(), isIntOrIndex(), isIntOrIndexOrFloat(), isSignedInteger(), isSignlessInteger(), isSignlessIntOrFloat(), isSignlessIntOrIndex(), isSignlessIntOrIndexOrFloat(), isUnsignedInteger(), and print().
Referenced by mlir::pdl::PDLType::classof(), mlir::spirv::SPIRVType::classof(), mlir::quant::QuantizedType::classof(), combineOneSpec(), mlir::TensorType::isValidElementType(), parseAndVerifyType(), mlir::AsmPrinter::Impl::printDialectType(), and verifyConstantType().
getFromOpaquePointer()
static Type mlir::Type::getFromOpaquePointer (const void * pointer) inline static
Definition at line 168 of file Types.h.
References Type().
Referenced by mlir::DiagnosticArgument::getAsType(), and llvm::PointerLikeTypeTraits< mlir::Type >::getFromVoidPointer().
getIntOrFloatBitWidth()
unsigned Type::getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
Definition at line 91 of file Types.cpp.
Referenced by buildAttributeAPInt(), castBoolToIntN(), createInitialValueForReduceOp(), createLinalgBodyCalculationForElementwiseOp(), createReassociationMapsForCollapse(), declareReduction(), mlir::VulkanLayoutUtils::decorateType(), genLoad(), getBitWidth(), mlir::detail::getDefaultTypeSizeInBits(), mlir::detail::getDenseElementBitWidth(), getDialect(), mlir::Builder::getIntegerAttr(), getSrcVectorElementType(), getTypeNumBytes(), isDefinedByCallTo(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), parseSwitchOpCases(), and verifyCastOp().
getTypeID()
TypeID mlir::Type::getTypeID () inline
Return a unique identifier for the concrete type.
This is used to support dynamic type casting.
Definition at line 108 of file Types.h.
References getContext().
Referenced by mlir::detail::filterEntriesForType(), mlir::DataLayout::getTypeABIAlignment(), mlir::DataLayout::getTypePreferredAlignment(), mlir::DataLayout::getTypeSize(), mlir::DataLayout::getTypeSizeInBits(), mlir::DynamicType::isa(), and mlir::OpTrait::impl::verifyElementwise().
hasTrait()
template<template< typename T > class Trait> bool mlir::Type::hasTrait () inline
Returns true if the type was registered with a particular trait.
Definition at line 174 of file Types.h.
References getAbstractType(), and mlir::AbstractType::hasTrait().
Referenced by mlir::DynamicType::classof().
isa() [1/2]
template<typename U > bool mlir::Type::isa () const
Definition at line 234 of file Types.h.
Referenced by addResumeFunction(), analyzeProfitability(), assertDestinationPassingStyle(), broadcast(), mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), buildLLVMFunctionType(), mlir::scf::buildLoopNest(), buildVectorWrite(), mlir::LLVMTypeConverter::canConvertToBarePtr(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), checkAndNestUnderRewriteOp(), mlir::pdl::PDLType::classof(), mlir::spirv::SPIRVType::classof(), mlir::FloatType::classof(), mlir::TensorType::classof(), mlir::spirv::CompositeType::classof(), mlir::BaseMemRefType::classof(), mlir::DenseFPElementsAttr::classof(), mlir::spirv::Deserializer::collect(), mlir::DenseElementsAttr::complex_float_value_begin(), mlir::DenseElementsAttr::complex_float_value_end(), convertStructType(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), mlir::bufferization::BufferizationState::createAlloc(), createConstantAllBitsSet(), createInitialValueForReduceOp(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), mlir::createLoopFusionPass(), mlir::vector::createOrFoldDimOp(), mlir::linalg::createOrFoldDimOp(), createOrFoldDimOp(), mlir::VulkanLayoutUtils::decorateType(), dispatchPrint(), eachHasOnlyOneOfTypes(), fillStructuredOpRegion(), findDuplicateElement(), foldExtractFromBroadcast(), foldExtractStridedOpFromInsertChain(), mlir::memref::foldMemRefCast(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), fuseOperations(), mlir::bufferization::OneShotAnalysisState::gatherYieldedTensors(), genIndexValue(), mlir::sparse_tensor::genIsNonzero(), genLoad(), genTensorLoad(), mlir::SPIRVConversionTarget::get(), getAllocationTypeAndShape(), getAssumedUniqueReturnOp(), getBitWidth(), mlir::OpTrait::util::getBroadcastedType(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::detail::getDefaultABIAlignment(), mlir::detail::getDefaultPreferredAlignment(), mlir::detail::getDefaultTypeSizeInBits(), getFirstIntValue(), getGetValueTypeOpValueType(), getI1SameShape(), getInsertExtractValueElementType(), getLoadStoreElementType(), mlir::sparse_tensor::getOneAttr(), getOperandTreePredicates(), mlir::LLVM::getPrimitiveTypeSizeInBits(), getProducerOfTensor(), mlir::quant::QuantizedType::getQuantizedElementType(), getTreePredicates(), getTypeNumBytes(), getUnderlyingType(), getVectorType(), mlir::Builder::getZeroAttr(), hasaUniqueDim(), hasTensorOrVectorType(), inferDynamicDimsForConv(), insertCasts(), invertPredicate(), isAccessIndexInvariant(), isaTensor(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isCompatibleExpressedType(), mlir::LLVM::isCompatibleFloatingPointType(), mlir::LLVM::isCompatibleOuterType(), mlir::LLVM::isCompatibleVectorType(), isComplexOfIntType(), isDefinedByCallTo(), isErrorPropagationPossible(), isGpuAsyncTokenType(), isMemRefNormalizable(), isQuantizablePrimitiveType(), mlir::async::isRefCounted(), mlir::LLVM::isScalableVectorType(), isSupportedCombiningKind(), mlir::LLVM::LLVMFunctionType::isValidArgumentType(), mlir::LLVM::LLVMArrayType::isValidElementType(), mlir::TensorType::isValidElementType(), mlir::BaseMemRefType::isValidElementType(), mlir::LLVM::LLVMPointerType::isValidElementType(), mlir::LLVM::LLVMStructType::isValidElementType(), mlir::LLVM::LLVMFixedVectorType::isValidElementType(), mlir::LLVM::LLVMScalableVectorType::isValidElementType(), isValidIntOrFloat(), isValidQuantizationSpec(), mlir::LLVM::LLVMFunctionType::isValidResultType(), mlir::bufferization::AnalysisState::isValueRead(), joinShapes(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), ConvertAccessChain::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), SelectToExtUI::matchAndRewrite(), operator!(), mlir::AffineDmaWaitOp::parse(), parseAndVerifySampledImageType(), mlir::detail::Parser::parseComplexType(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), mlir::detail::Parser::parseElementsLiteralType(), mlir::detail::Parser::parseFloatAttr(), parseInferType(), printAttributions(), printAwaitResultType(), mlir::AsmPrinter::Impl::printDenseIntOrFPElementsAttr(), mlir::OpAsmPrinter::printFunctionalType(), printNVVMIntrinsicOp(), mlir::bufferization::replaceOpWithBufferizedValues(), replaceUnitExtents(), mlir::spirv::Serializer::processOp< spirv::FunctionCallOp >(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), setInPlaceOpOperand(), mlir::DataDescriptor::setSize(), mlir::structFuncArgTypeConverter(), vectorizeOperand(), mlir::quant::AnyQuantizedType::verify(), mlir::spirv::SampledImageType::verify(), mlir::quant::UniformQuantizedType::verify(), mlir::quant::UniformQuantizedPerAxisType::verify(), mlir::quant::CalibratedQuantizedType::verify(), verifyAtomicCompareExchangeImpl(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyPointerAndCoopMatrixType(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), visitUpward(), walkReferenceCountedValues(), and wrapExternalFunction().
isa() [2/2]
template<typename First , typename Second , typename... Rest> bool mlir::Type::isa () const
Definition at line 240 of file Types.h.
isBF16()
bool Type::isBF16 () const
Definition at line 21 of file Types.cpp.
Referenced by fltSemanticsForType(), getDialect(), mlir::quant::QuantizedType::isSigned(), mlir::spirv::ScalarType::isValid(), parseAndVerifyType(), and verifyMultShape().
isF128()
bool Type::isF128 () const
Definition at line 26 of file Types.cpp.
Referenced by fltSemanticsForType(), and getDialect().
isF16()
bool Type::isF16 () const
Definition at line 22 of file Types.cpp.
Referenced by fltSemanticsForType(), foldTransferInBoundsAttribute(), getDialect(), mlir::quant::QuantizedType::isSigned(), mlir::gpu::MMAMatrixType::isValidElementType(), and printNVVMIntrinsicOp().
isF32()
bool Type::isF32 () const
Definition at line 23 of file Types.cpp.
Referenced by convertFloatAttr(), fltSemanticsForType(), foldTransferInBoundsAttribute(), getDialect(), mlir::quant::QuantizedType::isSigned(), mlir::gpu::MMAMatrixType::isValidElementType(), mlir::sparse_tensor::primaryTypeEncoding(), printNVVMIntrinsicOp(), and verifyMultShape().
isF64()
bool Type::isF64 () const
Definition at line 24 of file Types.cpp.
Referenced by fltSemanticsForType(), getDialect(), mlir::quant::QuantizedType::isSigned(), parseElementAttrHexValues(), mlir::sparse_tensor::primaryTypeEncoding(), and printNVVMIntrinsicOp().
isF80()
bool Type::isF80 () const
Definition at line 25 of file Types.cpp.
Referenced by fltSemanticsForType(), and getDialect().
isIndex()
bool Type::isIndex () const
Definition at line 28 of file Types.cpp.
Referenced by buildAttributeAPInt(), ceilDivPositive(), computeMemRefRankReductionMask(), mlir::detail::getDenseElementBitWidth(), getDialect(), mlir::Builder::getIntegerAttr(), mlir::linalg::getUpperBoundForIndex(), mlir::getValueOrCreateCastToIndexLike(), hasaUniqueDim(), isMatchingWidth(), mlir::quant::QuantizedType::isSigned(), mlir::isValidDim(), isValidIntOrFloat(), mlir::isValidSymbol(), joinShapes(), and mlir::sparse_tensor::overheadTypeEncoding().
isInteger()
bool Type::isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
Definition at line 31 of file Types.cpp.
Referenced by castBoolToIntN(), castIntNToBool(), createInitialValueForReduceOp(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), getDialect(), isBoolScalarOrVector(), isMatchingWidth(), mlir::quant::QuantizedType::isSigned(), parseElementAttrHexValues(), mlir::sparse_tensor::primaryTypeEncoding(), and verifyMultShape().
isIntOrFloat()
bool Type::isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
Definition at line 87 of file Types.cpp.
Referenced by mlir::spirv::Deserializer::collect(), getBitWidth(), getDialect(), isAllocationSupported(), isDefinedByCallTo(), ConvertAccessChain::matchAndRewrite(), and mlir::vector::ContractionOpToMatmulOpLowering::matchAndRewrite().
isIntOrIndex()
bool Type::isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
Definition at line 85 of file Types.cpp.
Referenced by mlir::DenseIntElementsAttr::classof(), mlir::sparse_tensor::genIsNonzero(), getDialect(), isSupportedCombiningKind(), and parseElementAttrHexValues().
isIntOrIndexOrFloat()
bool Type::isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
Definition at line 89 of file Types.cpp.
Referenced by getDialect(), isBoolScalarOrVector(), mlir::vector::isBroadcastableTo(), isSupportedCombiningKind(), mlir::BaseMemRefType::isValidElementType(), TwoDimMultiReductionToElementWise::matchAndRewrite(), parseElementAttrHexValues(), and verifyRegionAttribute().
isSignedInteger() [1/2]
bool Type::isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
Definition at line 49 of file Types.cpp.
Referenced by buildAttributeAPInt(), getDialect(), mlir::Builder::getIntegerAttr(), and isSignedIntegerOrVector().
isSignedInteger() [2/2]
bool Type::isSignedInteger (unsigned width) const
Definition at line 55 of file Types.cpp.
isSignlessInteger() [1/2]
bool Type::isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
Definition at line 37 of file Types.cpp.
Referenced by mlir::arith::ConstantIntOp::build(), getDialect(), and SelectToExtUI::matchAndRewrite().
isSignlessInteger() [2/2]
bool Type::isSignlessInteger (unsigned width) const
Definition at line 43 of file Types.cpp.
isSignlessIntOrFloat()
bool Type::isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
Definition at line 81 of file Types.cpp.
Referenced by getDialect(), and mlir::linalg::RegionMatcher::matchAsScalarBinaryOp().
isSignlessIntOrIndex()
bool Type::isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
Definition at line 73 of file Types.cpp.
Referenced by getDialect(), and mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike().
isSignlessIntOrIndexOrFloat()
bool Type::isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
Definition at line 77 of file Types.cpp.
Referenced by appendMangledType(), and getDialect().
isUnsignedInteger() [1/2]
bool Type::isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
Definition at line 61 of file Types.cpp.
Referenced by createLinalgBodyCalculationForElementwiseOp(), createReassociationMapsForCollapse(), getDialect(), isUnsignedIntegerOrVector(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), and mlir::AsmPrinter::Impl::printDenseIntOrFPElementsAttr().
isUnsignedInteger() [2/2]
bool Type::isUnsignedInteger (unsigned width) const
Definition at line 67 of file Types.cpp.
operator bool()
mlir::Type::operator bool () const inline explicit
Definition at line 93 of file Types.h.
References impl.
operator!()
bool mlir::Type::operator! () const inline
Definition at line 95 of file Types.h.
References cast(), dyn_cast(), dyn_cast_or_null(), and isa().
operator!=()
bool mlir::Type::operator!= (Type other) const inline
Definition at line 92 of file Types.h.
operator=()
Type& mlir::Type::operator= (const Type & other) default
Referenced by Type().
operator==()
bool mlir::Type::operator== (Type other) const inline
Definition at line 91 of file Types.h.
References impl.
print()
void Type::print (raw_ostream & os) const
Print the current type.
Definition at line 3003 of file AsmPrinter.cpp.
References mlir::AsmPrinter::Impl::printType().
Referenced by getDialect(), and mlir::operator<<().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (Type arg) friend
Definition at line 230 of file Types.h.
Referenced by getDialect().
Member Data Documentation
impl
ImplType* mlir::Type::impl {nullptr} protected
Definition at line 182 of file Types.h.
Referenced by getAsOpaquePointer(), mlir::hash_value(), operator bool(), and operator==().
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/AsmPrinter.cpp
lib/IR/Types.cpp
lib/TableGen/Type.cpp
lib/Tools/PDLL/AST/NodePrinter.cpp