MLIR: mlir::presburger::Simplex Class Reference
mlir::presburger::Simplex Class Reference
The Simplex class uses the Normal pivot rule and supports integer emptiness checks as well as detecting redundancies.
#include "mlir/Analysis/Presburger/Simplex.h"
Public Types
enum Direction { Direction::Up, Direction::Down }
enum IneqType { IneqType::Redundant, IneqType::Cut, IneqType::Separate }
Public Member Functions
Simplex ()=delete
Simplex (unsigned nVar)
Simplex (const IntegerRelation &constraints)
~Simplex () override=default
void addInequality (ArrayRef< int64_t > coeffs) final
Add an inequality to the tableau.
MaybeOptimum< Fraction > computeRowOptimum (Direction direction, unsigned row)
Compute the maximum or minimum value of the given row, depending on direction.
MaybeOptimum< Fraction > computeOptimum (Direction direction, ArrayRef< int64_t > coeffs)
Compute the maximum or minimum value of the given expression, depending on direction.
bool isBoundedAlongConstraint (unsigned constraintIndex)
Returns whether the perpendicular of the specified constraint is a is a direction along which the polytope is bounded.
bool isMarkedRedundant (unsigned constraintIndex) const
Returns whether the specified constraint has been marked as redundant.
void detectRedundant ()
Finds a subset of constraints that is redundant, i.e., such that the set of solutions does not change if these constraints are removed.
std::pair< MaybeOptimum< int64_t >, MaybeOptimum< int64_t > > computeIntegerBounds (ArrayRef< int64_t > coeffs)
Returns a (min, max) pair denoting the minimum and maximum integer values of the given expression.
bool isUnbounded ()
Returns true if the polytope is unbounded, i.e., extends to infinity in some direction.
Optional< SmallVector< int64_t, 8 > > findIntegerSample ()
Returns an integer sample point if one exists, or None otherwise.
IneqType findIneqType (ArrayRef< int64_t > coeffs)
Returns the type of the inequality with coefficients coeffs.
bool isRedundantInequality (ArrayRef< int64_t > coeffs)
Check if the specified inequality already holds in the polytope.
bool isRedundantEquality (ArrayRef< int64_t > coeffs)
Check if the specified equality already holds in the polytope.
bool isRationalSubsetOf (const IntegerRelation &rel)
Returns true if this Simplex's polytope is a rational subset of rel.
Optional< SmallVector< int64_t, 8 > > getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
Optional< SmallVector< Fraction, 8 > > getRationalSample () const
Returns the current sample point, which may contain non-integer (rational) coordinates.
Public Member Functions inherited from mlir::presburger::SimplexBase
SimplexBase ()=delete
virtual ~SimplexBase ()=default
bool isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
unsigned getNumVariables () const
Returns the number of variables in the tableau.
unsigned getNumConstraints () const
Returns the number of constraints in the tableau.
void addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
void appendVariable (unsigned count=1)
Add new variables to the end of the list of variables.
void addDivisionVariable (ArrayRef< int64_t > coeffs, int64_t denom)
Append a new variable to the simplex and constrain it such that its only integer value is the floor div of coeffs and denom.
void markEmpty ()
Mark the tableau as being empty.
unsigned getSnapshot () const
Get a snapshot of the current state.
unsigned getSnapshotBasis ()
Get a snapshot of the current state including the basis.
void rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
void intersectIntegerRelation (const IntegerRelation &rel)
Add all the constraints from the given IntegerRelation.
void print (raw_ostream &os) const
Print the tableau's internal state.
void dump () const
Static Public Member Functions
static Simplex makeProduct (const Simplex &a, const Simplex &b)
Make a tableau to represent a pair of points in the given tableaus, one in tableau A and one in B.
Friends
class GBRSimplex
Additional Inherited Members
Protected Types inherited from mlir::presburger::SimplexBase
enum Orientation { Orientation::Row, Orientation::Column }
enum UndoLogEntry {
UndoLogEntry::RemoveLastConstraint, UndoLogEntry::RemoveLastVariable, UndoLogEntry::UnmarkEmpty, UndoLogEntry::UnmarkLastRedundant,
UndoLogEntry::RestoreBasis
}
Enum to denote operations that need to be undone during rollback.
Protected Member Functions inherited from mlir::presburger::SimplexBase
SimplexBase (unsigned nVar, bool mustUseBigM, unsigned symbolOffset, unsigned nSymbol)
Construct a SimplexBase with the specified number of variables and fixed columns.
Optional< unsigned > findAnyPivotRow (unsigned col)
Return any row that this column can be pivoted with, ignoring tableau consistency.
void swapRowWithCol (unsigned row, unsigned col)
Swap the row with the column in the tableau's data structures but not the tableau itself.
void pivot (unsigned row, unsigned col)
Pivot the row with the column.
void pivot (Pivot pair)
const Unknown & unknownFromIndex (int index) const
Returns the unknown associated with index.
const Unknown & unknownFromColumn (unsigned col) const
Returns the unknown associated with col.
const Unknown & unknownFromRow (unsigned row) const
Returns the unknown associated with row.
Unknown & unknownFromIndex (int index)
Returns the unknown associated with index.
Unknown & unknownFromColumn (unsigned col)
Returns the unknown associated with col.
Unknown & unknownFromRow (unsigned row)
Returns the unknown associated with row.
unsigned addZeroRow (bool makeRestricted=false)
Add a new row to the tableau and the associated data structures.
unsigned addRow (ArrayRef< int64_t > coeffs, bool makeRestricted=false)
Add a new row to the tableau and the associated data structures.
void swapRows (unsigned i, unsigned j)
Swap the two rows/columns in the tableau and associated data structures.
void swapColumns (unsigned i, unsigned j)
void removeLastConstraintRowOrientation ()
Remove the last constraint, which must be in row orientation.
void undo (UndoLogEntry entry)
Undo the operation represented by the log entry.
unsigned getNumFixedCols () const
Return the number of fixed columns, as described in the constructor above, this is the number of columns beyond those for the variables in var.
Protected Attributes inherited from mlir::presburger::SimplexBase
bool usingBigM
Stores whether or not a big M column is present in the tableau.
unsigned nRow
The number of rows in the tableau.
unsigned nCol
The number of columns in the tableau, including the common denominator and the constant column.
unsigned nRedundant
The number of redundant rows in the tableau.
unsigned nSymbol
The number of parameters.
Matrix tableau
The matrix representing the tableau.
bool empty
This is true if the tableau has been detected to be empty, false otherwise.
SmallVector< UndoLogEntry, 8 > undoLog
Holds a log of operations, used for rolling back to a previous state.
SmallVector< SmallVector< int, 8 >, 8 > savedBases
Holds a vector of bases.
SmallVector< int, 8 > rowUnknown
These hold the indexes of the unknown at a given row or column position.
SmallVector< int, 8 > colUnknown
SmallVector< Unknown, 8 > con
These hold information about each unknown.
SmallVector< Unknown, 8 > var
Detailed Description
The Simplex class uses the Normal pivot rule and supports integer emptiness checks as well as detecting redundancies.
The Simplex class supports redundancy checking via detectRedundant and isMarkedRedundant. A redundant constraint is one which is never violated as long as the other constraints are not violated, i.e., removing a redundant constraint does not change the set of solutions to the constraints. As a heuristic, constraints that have been marked redundant can be ignored for most operations. Therefore, these constraints are kept in rows 0 to nRedundant - 1, where nRedundant is a member variable that tracks the number of constraints that have been marked redundant.
Finding an integer sample is done with the Generalized Basis Reduction algorithm. See the documentation for findIntegerSample and reduceBasis.
Definition at line 661 of file Simplex.h.
Member Enumeration Documentation
Direction
enum mlir::presburger::Simplex::Direction strong
Enumerator
Up
Down
Definition at line 663 of file Simplex.h.
IneqType
enum mlir::presburger::Simplex::IneqType strong
Enumerator
Redundant
Cut
Separate
Definition at line 733 of file Simplex.h.
Constructor & Destructor Documentation
Simplex() [1/3]
mlir::presburger::Simplex::Simplex () delete
Simplex() [2/3]
mlir::presburger::Simplex::Simplex (unsigned nVar) inline explicit
Definition at line 666 of file Simplex.h.
Simplex() [3/3]
mlir::presburger::Simplex::Simplex (const IntegerRelation & constraints) inline explicit
Definition at line 669 of file Simplex.h.
References mlir::presburger::SimplexBase::addInequality(), and mlir::presburger::SimplexBase::intersectIntegerRelation().
~Simplex()
mlir::presburger::Simplex::~Simplex () override default
Member Function Documentation
addInequality()
void Simplex::addInequality (ArrayRef< int64_t > coeffs) final virtual
Add an inequality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
This also tries to restore the tableau configuration to a consistent state and marks the Simplex empty if this is not possible.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
We add the inequality and mark it as restricted. We then try to make its sample value non-negative. If this is not possible, the tableau has become empty and we mark it as such.
Implements mlir::presburger::SimplexBase.
Definition at line 1076 of file Simplex.cpp.
References mlir::presburger::SimplexBase::addRow(), mlir::presburger::SimplexBase::con, mlir::failed(), and mlir::presburger::SimplexBase::markEmpty().
computeIntegerBounds()
std::pair< MaybeOptimum< int64_t >, MaybeOptimum< int64_t > > Simplex::computeIntegerBounds (ArrayRef< int64_t > coeffs)
Returns a (min, max) pair denoting the minimum and maximum integer values of the given expression.
Compute the minimum and maximum integer values the expression can take.
If no integer value exists, both results will be of kind Empty.
We compute each separately.
Definition at line 2067 of file Simplex.cpp.
References mlir::presburger::ceil(), Down, mlir::presburger::floor(), and Up.
Referenced by mlir::presburger::IntegerRelation::computeVolume().
computeOptimum()
MaybeOptimum< Fraction > Simplex::computeOptimum (Direction direction, ArrayRef< int64_t > coeffs)
Compute the maximum or minimum value of the given expression, depending on direction.
Compute the optimum of the specified expression in the specified direction, or None if it is unbounded.
Should not be called when the Simplex is empty.
Returns a Fraction denoting the optimum, or a null value if no optimum exists, i.e., if the expression is unbounded in this direction.
Definition at line 1328 of file Simplex.cpp.
References mlir::presburger::SimplexBase::addRow(), mlir::presburger::SimplexBase::Column, mlir::presburger::SimplexBase::con, mlir::presburger::Empty, mlir::presburger::SimplexBase::empty, mlir::failed(), mlir::presburger::MaybeOptimum< T >::isUnbounded(), mlir::presburger::SimplexBase::Unknown::orientation, mlir::presburger::SimplexBase::pivot(), mlir::presburger::SimplexBase::Unknown::pos, mlir::presburger::SimplexBase::Unknown::restricted, and mlir::presburger::Unbounded.
computeRowOptimum()
MaybeOptimum< Fraction > Simplex::computeRowOptimum (Direction direction, unsigned row)
Compute the maximum or minimum value of the given row, depending on direction.
The specified row is never pivoted. On return, the row may have a negative sample value if the direction is down.
Returns a Fraction denoting the optimum, or a null value if no optimum exists, i.e., if the expression is unbounded in this direction.
Definition at line 1309 of file Simplex.cpp.
References mlir::presburger::SimplexBase::pivot(), mlir::presburger::SimplexBase::tableau, and mlir::presburger::Unbounded.
detectRedundant()
void Simplex::detectRedundant ()
Finds a subset of constraints that is redundant, i.e., such that the set of solutions does not change if these constraints are removed.
Find a subset of constraints that is redundant and mark them redundant.
Marks these constraints as redundant. Whether a specific constraint has been marked redundant can be queried using isMarkedRedundant.
Definition at line 1394 of file Simplex.cpp.
References mlir::presburger::SimplexBase::Column, mlir::presburger::SimplexBase::con, mlir::presburger::SimplexBase::empty, mlir::failed(), mlir::presburger::MaybeOptimum< T >::isUnbounded(), mlir::presburger::SimplexBase::Unknown::orientation, mlir::presburger::SimplexBase::pivot(), and mlir::presburger::SimplexBase::Unknown::pos.
Referenced by mlir::presburger::IntegerRelation::removeRedundantConstraints().
findIneqType()
Simplex::IneqType Simplex::findIneqType (ArrayRef< int64_t > coeffs)
Returns the type of the inequality with coefficients coeffs.
Possible types are: Redundant The inequality is satisfied in the polytope Cut The inequality is satisfied by some points, but not by others Separate The inequality is not satisfied by any point
Possible types are: Redundant The inequality is satisfied by all points in the polytope Cut The inequality is satisfied by some points, but not by others Separate The inequality is not satisfied by any point
Internally, this computes the minimum and the maximum the inequality with coefficients coeffs can take. If the minimum is >= 0, the inequality holds for all points in the polytope, so it is redundant. If the minimum is <= 0 and the maximum is >= 0, the points in between the minimum and the inequality do not satisfy it, the points in between the inequality and the maximum satisfy it. Hence, it is a cut inequality. If both are < 0, no points of the polytope satisfy the inequality, which means it is a separate inequality.
Definition at line 2141 of file Simplex.cpp.
References mlir::presburger::MaybeOptimum< T >::isBounded().
Referenced by mlir::presburger::SetCoalescer::coalesce().
findIntegerSample()
Optional< SmallVector< int64_t, 8 > > Simplex::findIntegerSample ()
Returns an integer sample point if one exists, or None otherwise.
Search for an integer sample point using a branch and bound algorithm.
This should only be called for bounded sets.
Each row in the basis matrix is a vector, and the set of basis vectors should span the space. Initially this is the identity matrix, i.e., the basis vectors are just the variables.
In every level, a value is assigned to the level-th basis vector, as follows. Compute the minimum and maximum rational values of this direction. If only one integer point lies in this range, constrain the variable to have this value and recurse to the next variable.
If the range has multiple values, perform generalized basis reduction via reduceBasis and then compute the bounds again. Now we try constraining this direction in the first value in this range and "recurse" to the next level. If we fail to find a sample, we try assigning the direction the next value in this range, and so on.
If no integer sample is found from any of the assignments, or if the range contains no integer value, then of course the polytope is empty for the current assignment of the values in previous levels, so we return to the previous level.
If we reach the last level where all the variables have been assigned values already, then we simply return the current sample point if it is integral, and go back to the previous level otherwise.
To avoid potentially arbitrarily large recursion depths leading to stack overflows, this algorithm is implemented iteratively.
Definition at line 1954 of file Simplex.cpp.
References mlir::presburger::SimplexBase::addEquality(), mlir::presburger::SimplexBase::empty, mlir::presburger::Matrix::getNumRows(), mlir::presburger::Matrix::getRow(), mlir::presburger::SimplexBase::getSnapshot(), mlir::presburger::Matrix::identity(), mlir::presburger::MaybeOptimum< T >::isBounded(), mlir::presburger::MaybeOptimum< T >::isEmpty(), mlir::presburger::SimplexBase::rollback(), and mlir::presburger::SimplexBase::var.
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
getRationalSample()
Optional< SmallVector< Fraction, 8 > > Simplex::getRationalSample () const
Returns the current sample point, which may contain non-integer (rational) coordinates.
Returns an empty optional when the tableau is empty.
Definition at line 1533 of file Simplex.cpp.
References mlir::presburger::SimplexBase::Column, mlir::presburger::SimplexBase::empty, mlir::presburger::SimplexBase::Unknown::orientation, mlir::presburger::SimplexBase::Unknown::pos, mlir::presburger::SimplexBase::tableau, and mlir::presburger::SimplexBase::var.
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
getSamplePointIfIntegral()
Optional< SmallVector< int64_t, 8 > > Simplex::getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
Otherwise, returns None.
Definition at line 1588 of file Simplex.cpp.
References mlir::presburger::SimplexBase::empty, and mlir::presburger::SimplexBase::var.
isBoundedAlongConstraint()
bool Simplex::isBoundedAlongConstraint (unsigned constraintIndex)
Returns whether the perpendicular of the specified constraint is a is a direction along which the polytope is bounded.
Definition at line 1364 of file Simplex.cpp.
References mlir::presburger::SimplexBase::con, and mlir::presburger::SimplexBase::empty.
Referenced by mlir::presburger::IntegerRelation::getBoundedDirections().
isMarkedRedundant()
bool Simplex::isMarkedRedundant (unsigned constraintIndex) const
Returns whether the specified constraint has been marked as redundant.
Redundant constraints are those that are in row orientation and lie in rows 0 to nRedundant - 1.
Constraints are numbered from 0 starting at the first added inequality. Equalities are added as a pair of inequalities and so correspond to two inequalities with successive indices.
Definition at line 1374 of file Simplex.cpp.
References mlir::presburger::SimplexBase::con, mlir::presburger::SimplexBase::nRedundant, mlir::presburger::SimplexBase::Unknown::orientation, mlir::presburger::SimplexBase::Unknown::pos, mlir::presburger::SimplexBase::Row, mlir::presburger::SimplexBase::swapRows(), mlir::presburger::SimplexBase::undoLog, and mlir::presburger::SimplexBase::UnmarkLastRedundant.
Referenced by mlir::presburger::IntegerRelation::removeRedundantConstraints().
isRationalSubsetOf()
bool Simplex::isRationalSubsetOf (const IntegerRelation & rel)
Returns true if this Simplex's polytope is a rational subset of rel.
Otherwise, returns false.
Definition at line 2112 of file Simplex.cpp.
References mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), and mlir::presburger::SimplexBase::isEmpty().
isRedundantEquality()
bool Simplex::isRedundantEquality (ArrayRef< int64_t > coeffs)
Check if the specified equality already holds in the polytope.
Check whether the equality given by coeffs == 0 is redundant given the existing constraints.
This is redundant when coeffs is already always zero under the existing constraints. coeffs is always zero when the minimum and maximum value that coeffs can take are both zero.
Definition at line 2166 of file Simplex.cpp.
References mlir::presburger::SimplexBase::empty, mlir::presburger::MaybeOptimum< T >::isBounded(), and mlir::presburger::MaybeOptimum< T >::isEmpty().
isRedundantInequality()
bool Simplex::isRedundantInequality (ArrayRef< int64_t > coeffs)
Check if the specified inequality already holds in the polytope.
Checks whether the type of the inequality with coefficients coeffs is Redundant.
Definition at line 2156 of file Simplex.cpp.
References mlir::presburger::SimplexBase::empty.
Referenced by mlir::presburger::SetCoalescer::coalesce().
isUnbounded()
bool Simplex::isUnbounded ()
Returns true if the polytope is unbounded, i.e., extends to infinity in some direction.
Otherwise, returns false.
Definition at line 1433 of file Simplex.cpp.
References mlir::presburger::SimplexBase::empty, and mlir::presburger::SimplexBase::var.
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
makeProduct()
Simplex Simplex::makeProduct (const Simplex & a, const Simplex & b) static
Make a tableau to represent a pair of points in the given tableaus, one in tableau A and one in B.
Make a tableau to represent a pair of points in the original tableau.
The product constraints and variables are stored as: first A's, then B's.
The product tableau has row layout: A's redundant rows, B's redundant rows, A's other rows, B's other rows.
It has column layout: denominator, constant, A's columns, B's columns.
Definition at line 1461 of file Simplex.cpp.
References mlir::presburger::SimplexBase::colUnknown, mlir::presburger::SimplexBase::con, mlir::linalg::concat(), mlir::presburger::SimplexBase::empty, mlir::presburger::SimplexBase::getNumConstraints(), mlir::presburger::SimplexBase::getNumVariables(), mlir::presburger::SimplexBase::nCol, mlir::presburger::SimplexBase::nRedundant, mlir::presburger::SimplexBase::nRow, nullIndex, mlir::presburger::Matrix::resizeVertically(), mlir::presburger::SimplexBase::rowUnknown, mlir::presburger::SimplexBase::tableau, mlir::presburger::SimplexBase::unknownFromIndex(), and mlir::presburger::SimplexBase::var.
Friends And Related Function Documentation
GBRSimplex
friend class GBRSimplex friend
Definition at line 762 of file Simplex.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Simplex.h
lib/Analysis/Presburger/Simplex.cpp