MLIR: mlir::RegisteredOperationName Class Reference
mlir::RegisteredOperationName Class Reference
This is a "type erased" representation of a registered operation.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
Dialect & getDialect () const
Return the dialect this operation is registered to.
TypeID getTypeID () const
Return the unique identifier of the derived Op class.
ParseResult parseAssembly (OpAsmParser &parser, OperationState &result) const
Use the specified object to parse this ops custom assembly format.
const ParseAssemblyFn & getParseAssemblyFn () const
Return the static hook for parsing this operation assembly.
void printAssembly (Operation *op, OpAsmPrinter &p, StringRef defaultDialect) const
This hook implements the AsmPrinter for this operation.
LogicalResult verifyInvariants (Operation *op) const
These hooks implement the verifiers for this operation.
LogicalResult verifyRegionInvariants (Operation *op) const
LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results) const
This hook implements a generalized folder for this operation.
void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context) const
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
template<typename... Models>
void attachInterface ()
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
template<template< typename T > class Trait>
bool hasTrait () const
Returns true if the operation has a particular trait.
bool hasTrait (TypeID traitID) const
Returns true if the operation has a particular trait.
ArrayRef< StringAttr > getAttributeNames () const
Return the list of cached attribute names registered to this operation.
Public Member Functions inherited from mlir::OperationName
OperationName (StringRef name, MLIRContext *context)
bool isRegistered () const
Return if this operation is registered.
Optional< RegisteredOperationName > getRegisteredInfo () const
If this operation is registered, returns the registered information, None otherwise.
template<template< typename T > class Trait>
bool hasTrait () const
Returns true if the operation was registered with a particular trait, e.g.
bool hasTrait (TypeID traitID) const
template<template< typename T > class Trait>
bool mightHaveTrait () const
Returns true if the operation might have the provided trait.
bool mightHaveTrait (TypeID traitID) const
template<typename T >
T::Concept * getInterface () const
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
template<typename T >
bool hasInterface () const
Returns true if this operation has the given interface registered to it.
bool hasInterface (TypeID interfaceID) const
template<typename T >
bool mightHaveInterface () const
Returns true if the operation might have the provided interface.
bool mightHaveInterface (TypeID interfaceID) const
Dialect * getDialect () const
Return the dialect this operation is registered to if the dialect is loaded in the context, or nullptr if the dialect isn't loaded.
StringRef getDialectNamespace () const
Return the name of the dialect this operation is registered to.
StringRef stripDialect () const
Return the operation name with dialect name stripped, if it has one.
StringRef getStringRef () const
Return the name of this operation. This always succeeds.
StringAttr getIdentifier () const
Return the name of this operation as a StringAttr.
void print (raw_ostream &os) const
void dump () const
void * getAsOpaquePointer () const
Represent the operation name as an opaque pointer.
bool operator== (const OperationName &rhs) const
bool operator!= (const OperationName &rhs) const
Static Public Member Functions
static Optional< RegisteredOperationName > lookup (StringRef name, MLIRContext *ctx)
Lookup the registered operation information for the given operation.
template<typename T >
static void insert (Dialect &dialect)
Register a new operation in a Dialect object.
static void insert (StringRef name, Dialect &dialect, TypeID typeID, ParseAssemblyFn &&parseAssembly, PrintAssemblyFn &&printAssembly, VerifyInvariantsFn &&verifyInvariants, VerifyRegionInvariantsFn &&verifyRegionInvariants, FoldHookFn &&foldHook, GetCanonicalizationPatternsFn &&getCanonicalizationPatterns, detail::InterfaceMap &&interfaceMap, HasTraitFn &&hasTrait, ArrayRef< StringRef > attrNames)
The use of this method is in general discouraged in favor of 'insert<CustomOp>(dialect)'.
static RegisteredOperationName getFromOpaquePointer (const void *pointer)
Represent the operation name as an opaque pointer.
Static Public Member Functions inherited from mlir::OperationName
static OperationName getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::OperationName
using GetCanonicalizationPatternsFn = llvm::unique_function< void(RewritePatternSet &, MLIRContext *) const >
using FoldHookFn = llvm::unique_function< LogicalResult(Operation *, ArrayRef< Attribute >, SmallVectorImpl< OpFoldResult > &) const >
using HasTraitFn = llvm::unique_function< bool(TypeID) const >
using ParseAssemblyFn = llvm::unique_function< ParseResult(OpAsmParser &, OperationState &) const >
using PrintAssemblyFn = llvm::unique_function< void(Operation *, OpAsmPrinter &, StringRef) const >
using VerifyInvariantsFn = llvm::unique_function< LogicalResult(Operation *) const >
using VerifyRegionInvariantsFn = llvm::unique_function< LogicalResult(Operation *) const >
Protected Member Functions inherited from mlir::OperationName
OperationName (Impl *impl)
Protected Attributes inherited from mlir::OperationName
Impl * impl
The internal implementation of the operation name.
friend MLIRContextImpl
Allow access to the Impl struct.
Detailed Description
This is a "type erased" representation of a registered operation.
This should only be used by things like the AsmPrinter and other things that need to be parameterized by generic operation hooks. Most user code should use the concrete operation types.
Definition at line 241 of file OperationSupport.h.
Member Function Documentation
attachInterface()
template<typename... Models> void mlir::RegisteredOperationName::attachInterface () inline
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
Definition at line 335 of file OperationSupport.h.
foldHook()
LogicalResult mlir::RegisteredOperationName::foldHook (Operation * op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results) const inline
This hook implements a generalized folder for this operation.
Operations can implement this to provide simplifications rules that are applied by the Builder::createOrFold API and the canonicalization pass.
This is an intentionally limited interface - implementations of this hook can only perform the following changes to the operation:
They can leave the operation alone and without changing the IR, and return failure.
They can mutate the operation in place, without changing anything else in the IR. In this case, return success.
They can return a list of existing values that can be used instead of the operation. In this case, fill in the results list and return success. The caller will remove the operation and use those results instead.
This allows expression of some simple in-place canonicalizations (e.g. "x+0 -> x", "min(x,y,x,z) -> min(x,y,z)", "x+y-x -> y", etc), as well as generalized constant folding.
Definition at line 320 of file OperationSupport.h.
getAttributeNames()
ArrayRef<StringAttr> mlir::RegisteredOperationName::getAttributeNames () const inline
Return the list of cached attribute names registered to this operation.
The order of attributes cached here is unique to each type of operation, and the interpretation of this attribute list should generally be driven by the respective operation. In many cases, this caching removes the need to use the raw string name of a known attribute.
For example the ODS generator, with an op defining the following attributes:
let arguments = (ins I32Attr:$attr1, I32Attr:$attr2);
... may produce an order here of ["attr1", "attr2"]. This allows for the ODS generator to directly access the cached name for a known attribute, greatly simplifying the cost and complexity of attribute usage produced by the generator.
Definition at line 363 of file OperationSupport.h.
getCanonicalizationPatterns()
void mlir::RegisteredOperationName::getCanonicalizationPatterns (RewritePatternSet & results, MLIRContext * context) const inline
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Definition at line 327 of file OperationSupport.h.
getDialect()
Dialect& mlir::RegisteredOperationName::getDialect () const inline
Return the dialect this operation is registered to.
Definition at line 272 of file OperationSupport.h.
getFromOpaquePointer()
static RegisteredOperationName mlir::RegisteredOperationName::getFromOpaquePointer (const void * pointer) inline static
Represent the operation name as an opaque pointer.
(Used to support PointerLikeTypeTraits).
Definition at line 369 of file OperationSupport.h.
Referenced by llvm::DenseMapInfo< mlir::RegisteredOperationName >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::RegisteredOperationName >::getFromVoidPointer(), and llvm::DenseMapInfo< mlir::RegisteredOperationName >::getTombstoneKey().
getParseAssemblyFn()
const ParseAssemblyFn& mlir::RegisteredOperationName::getParseAssemblyFn () const inline
Return the static hook for parsing this operation assembly.
Definition at line 281 of file OperationSupport.h.
getTypeID()
TypeID mlir::RegisteredOperationName::getTypeID () const inline
Return the unique identifier of the derived Op class.
Definition at line 275 of file OperationSupport.h.
hasTrait() [1/2]
template<template< typename T > class Trait> bool mlir::RegisteredOperationName::hasTrait () const inline
Returns true if the operation has a particular trait.
Definition at line 340 of file OperationSupport.h.
References mlir::op_definition_impl::hasTrait().
Referenced by mlir::transform::detail::checkImplementsTransformInterface(), and mlir::FrozenRewritePatternSet::FrozenRewritePatternSet().
hasTrait() [2/2]
bool mlir::RegisteredOperationName::hasTrait (TypeID traitID) const inline
Returns true if the operation has a particular trait.
Definition at line 345 of file OperationSupport.h.
insert() [1/2]
template<typename T > static void mlir::RegisteredOperationName::insert (Dialect & dialect) inline static
Register a new operation in a Dialect object.
This constructor is used by Dialect objects when they register the list of operations they contain.
Definition at line 252 of file OperationSupport.h.
References mlir::op_definition_impl::hasTrait().
Referenced by mlir::ExtensibleDialect::registerDynamicOp().
insert() [2/2]
void RegisteredOperationName::insert (StringRef name, Dialect & dialect, TypeID typeID, ParseAssemblyFn && parseAssembly, PrintAssemblyFn && printAssembly, VerifyInvariantsFn && verifyInvariants, VerifyRegionInvariantsFn && verifyRegionInvariants, FoldHookFn && foldHook, GetCanonicalizationPatternsFn && getCanonicalizationPatterns, detail::InterfaceMap && interfaceMap, HasTraitFn && hasTrait, ArrayRef< StringRef > attrNames) static
The use of this method is in general discouraged in favor of 'insert<CustomOp>(dialect)'.
Definition at line 710 of file MLIRContext.cpp.
References mlir::Dialect::getContext(), mlir::MLIRContext::getImpl(), mlir::OperationName::Impl::isRegistered(), and value.
lookup()
Optional< RegisteredOperationName > RegisteredOperationName::lookup (StringRef name, MLIRContext * ctx) static
Lookup the registered operation information for the given operation.
Returns None if the operation isn't registered.
Definition at line 696 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
Referenced by mlir::Op< AffineDmaWaitOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >::attachInterface(), mlir::transform::detail::checkImplementsTransformInterface(), mlir::OpBuilder::getBlock(), mlir::MLIRContext::isOperationRegistered(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirOperationImplementsInterfaceStatic(), and verifyResultTypesAreInferrable().
parseAssembly()
ParseResult RegisteredOperationName::parseAssembly (OpAsmParser & parser, OperationState & result) const
Use the specified object to parse this ops custom assembly format.
Definition at line 705 of file MLIRContext.cpp.
printAssembly()
void mlir::RegisteredOperationName::printAssembly (Operation * op, OpAsmPrinter & p, StringRef defaultDialect) const inline
This hook implements the AsmPrinter for this operation.
Definition at line 286 of file OperationSupport.h.
verifyInvariants()
LogicalResult mlir::RegisteredOperationName::verifyInvariants (Operation * op) const inline
These hooks implement the verifiers for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 294 of file OperationSupport.h.
verifyRegionInvariants()
LogicalResult mlir::RegisteredOperationName::verifyRegionInvariants (Operation * op) const inline
Definition at line 297 of file OperationSupport.h.
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/MLIRContext.cpp