MLIR: mlir::pdll::ast::NamedAttributeDecl Class Reference
mlir::pdll::ast::NamedAttributeDecl Class Reference
This Decl represents a NamedAttribute, and contains a string name and attribute value.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
const Name & getName () const
Return the name of the attribute.
Expr * getValue () const
Return value of the attribute.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static NamedAttributeDecl * create (Context &ctx, const Name &name, Expr *value)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< NamedAttributeDecl, Decl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< NamedAttributeDecl, Decl >
using Base = NodeBase< NamedAttributeDecl, Decl >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< NamedAttributeDecl, Decl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This Decl represents a NamedAttribute, and contains a string name and attribute value.
Definition at line 929 of file Nodes.h.
Member Function Documentation
create()
NamedAttributeDecl * NamedAttributeDecl::create (Context & ctx, const Name & name, Expr * value) static
Definition at line 453 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator().
getName()
const Name& mlir::pdll::ast::NamedAttributeDecl::getName () const inline
Return the name of the attribute.
Definition at line 935 of file Nodes.h.
References mlir::pdll::ast::Decl::getName().
getValue()
Expr* mlir::pdll::ast::NamedAttributeDecl::getValue () const inline
Return value of the attribute.
Definition at line 938 of file Nodes.h.
References mlir::pdll::ast::Name::getLoc(), and value.
Referenced by mlir::pdll::ast::Name::create().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp