MLIR: mlir::pdll::ast::UserConstraintDecl Class Reference
mlir::pdll::ast::UserConstraintDecl Class Reference final
This decl represents a user defined constraint.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
const Name & getName () const
Return the name of the constraint.
MutableArrayRef< VariableDecl * > getInputs ()
Return the input arguments of this constraint.
ArrayRef< VariableDecl * > getInputs () const
MutableArrayRef< VariableDecl * > getResults ()
Return the explicit results of the constraint declaration.
ArrayRef< VariableDecl * > getResults () const
Optional< StringRef > getCodeBlock () const
Return the optional code block of this constraint, if this is a native constraint with a provided implementation.
const CompoundStmt * getBody () const
Return the body of this constraint if this constraint is a PDLL constraint, otherwise returns nullptr.
Type getResultType () const
Return the result type of this constraint.
bool isExternal () const
Returns true if this constraint is external.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static UserConstraintDecl * createNative (Context &ctx, const Name &name, ArrayRef< VariableDecl *> inputs, ArrayRef< VariableDecl *> results, Optional< StringRef > codeBlock, Type resultType)
Create a native constraint with the given optional code block.
static UserConstraintDecl * createPDLL (Context &ctx, const Name &name, ArrayRef< VariableDecl *> inputs, ArrayRef< VariableDecl *> results, const CompoundStmt *body, Type resultType)
Create a PDLL constraint with the given body.
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< UserConstraintDecl, ConstraintDecl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::ConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< UserConstraintDecl, ConstraintDecl >
using Base = NodeBase< UserConstraintDecl, ConstraintDecl >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< UserConstraintDecl, ConstraintDecl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::ConstraintDecl
ConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This decl represents a user defined constraint.
This is either:
an imported native constraint
Similar to an external function declaration. This is a native constraint defined externally, and imported into PDLL via a declaration.
a native constraint defined in PDLL
This is a native constraint, i.e. a constraint whose implementation is defined in C++(or potentially some other non-PDLL language). The implementation of this constraint is specified as a string code block in PDLL.
a PDLL constraint
This is a constraint which is defined using only PDLL constructs.
Definition at line 831 of file Nodes.h.
Member Function Documentation
createNative()
static UserConstraintDecl* mlir::pdll::ast::UserConstraintDecl::createNative (Context & ctx, const Name & name, ArrayRef< VariableDecl *> inputs, ArrayRef< VariableDecl *> results, Optional< StringRef > codeBlock, Type resultType) inline static
Create a native constraint with the given optional code block.
Definition at line 836 of file Nodes.h.
createPDLL()
static UserConstraintDecl* mlir::pdll::ast::UserConstraintDecl::createPDLL (Context & ctx, const Name & name, ArrayRef< VariableDecl *> inputs, ArrayRef< VariableDecl *> results, const CompoundStmt * body, Type resultType) inline static
Create a PDLL constraint with the given body.
Definition at line 846 of file Nodes.h.
getBody()
const CompoundStmt* mlir::pdll::ast::UserConstraintDecl::getBody () const inline
Return the body of this constraint if this constraint is a PDLL constraint, otherwise returns nullptr.
Definition at line 881 of file Nodes.h.
Referenced by mlir::pdll::ast::Name::create().
getCodeBlock()
Optional<StringRef> mlir::pdll::ast::UserConstraintDecl::getCodeBlock () const inline
Return the optional code block of this constraint, if this is a native constraint with a provided implementation.
Definition at line 877 of file Nodes.h.
getInputs() [1/2]
MutableArrayRef<VariableDecl *> mlir::pdll::ast::UserConstraintDecl::getInputs () inline
Return the input arguments of this constraint.
Definition at line 859 of file Nodes.h.
Referenced by checkAndNestUnderRewriteOp(), mlir::pdll::ast::Name::create(), and mlir::pdll::ast::ValueRangeConstraintDecl::create().
getInputs() [2/2]
ArrayRef<VariableDecl *> mlir::pdll::ast::UserConstraintDecl::getInputs () const inline
Definition at line 862 of file Nodes.h.
getName()
const Name& mlir::pdll::ast::UserConstraintDecl::getName () const inline
Return the name of the constraint.
Definition at line 856 of file Nodes.h.
References mlir::pdll::ast::Decl::getName().
getResults() [1/2]
MutableArrayRef<VariableDecl *> mlir::pdll::ast::UserConstraintDecl::getResults () inline
Return the explicit results of the constraint declaration.
May be empty, even if the constraint has results (e.g. in the case of inferred results).
Definition at line 868 of file Nodes.h.
Referenced by mlir::pdll::ast::Name::create(), and mlir::pdll::ast::ValueRangeConstraintDecl::create().
getResults() [2/2]
ArrayRef<VariableDecl *> mlir::pdll::ast::UserConstraintDecl::getResults () const inline
Definition at line 871 of file Nodes.h.
getResultType()
Type mlir::pdll::ast::UserConstraintDecl::getResultType () const inline
Return the result type of this constraint.
Definition at line 884 of file Nodes.h.
isExternal()
bool mlir::pdll::ast::UserConstraintDecl::isExternal () const inline
Returns true if this constraint is external.
Definition at line 887 of file Nodes.h.
References mlir::pdll::ast::Name::getLoc().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp