MLIR: mlir::DynamicOpDefinition Class Reference
mlir::DynamicOpDefinition Class Reference
The definition of a dynamic op.
#include "mlir/IR/ExtensibleDialect.h"
Public Member Functions
TypeID getTypeID ()
Returns the op typeID.
void setVerifyFn (OperationName::VerifyInvariantsFn &&verify)
Sets the verifier function for this operation.
void setVerifyRegionFn (OperationName::VerifyRegionInvariantsFn &&verify)
Sets the region verifier function for this operation.
void setParseFn (OperationName::ParseAssemblyFn &&parse)
Sets the static hook for parsing this op assembly.
void setPrintFn (OperationName::PrintAssemblyFn &&print)
Sets the static hook for printing this op assembly.
void setFoldHookFn (OperationName::FoldHookFn &&foldHook)
Sets the hook implementing a generalized folder for the op.
void setGetCanonicalizationPatternsFn (OperationName::GetCanonicalizationPatternsFn &&getCanonicalizationPatterns)
Set the hook returning any canonicalization pattern rewrites that the op supports, for use by the canonicalization pass.
Static Public Member Functions
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn)
Create a new op at runtime.
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn, OperationName::ParseAssemblyFn &&parseFn, OperationName::PrintAssemblyFn &&printFn)
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn, OperationName::ParseAssemblyFn &&parseFn, OperationName::PrintAssemblyFn &&printFn, OperationName::FoldHookFn &&foldHookFn, OperationName::GetCanonicalizationPatternsFn &&getCanonicalizationPatternsFn)
Detailed Description
The definition of a dynamic op.
A dynamic op is an op that is defined at runtime, and that can be registered at runtime by an extensible dialect (a dialect inheriting ExtensibleDialect). This class stores the functions that are in the OperationName class, and in addition defines the TypeID of the op that will be defined. Each dynamic operation definition refers to one instance of this class.
Definition at line 343 of file ExtensibleDialect.h.
Member Function Documentation
get() [1/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn) static
Create a new op at runtime.
The op is registered only after passing it to the dialect using registerDynamicOp.
Definition at line 306 of file ExtensibleDialect.cpp.
References mlir::AsmParser::emitError(), and mlir::AsmParser::getCurrentLocation().
Referenced by get().
get() [2/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn, OperationName::ParseAssemblyFn && parseFn, OperationName::PrintAssemblyFn && printFn) static
Definition at line 325 of file ExtensibleDialect.cpp.
References mlir::failure(), and get().
get() [3/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn, OperationName::ParseAssemblyFn && parseFn, OperationName::PrintAssemblyFn && printFn, OperationName::FoldHookFn && foldHookFn, OperationName::GetCanonicalizationPatternsFn && getCanonicalizationPatternsFn) static
Definition at line 346 of file ExtensibleDialect.cpp.
References MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID.
getTypeID()
TypeID mlir::DynamicOpDefinition::getTypeID () inline
Returns the op typeID.
Definition at line 368 of file ExtensibleDialect.h.
setFoldHookFn()
void mlir::DynamicOpDefinition::setFoldHookFn (OperationName::FoldHookFn && foldHook) inline
Sets the hook implementing a generalized folder for the op.
See RegisteredOperationName::foldHook for more details
Definition at line 396 of file ExtensibleDialect.h.
setGetCanonicalizationPatternsFn()
void mlir::DynamicOpDefinition::setGetCanonicalizationPatternsFn (OperationName::GetCanonicalizationPatternsFn && getCanonicalizationPatterns) inline
Set the hook returning any canonicalization pattern rewrites that the op supports, for use by the canonicalization pass.
Definition at line 403 of file ExtensibleDialect.h.
setParseFn()
void mlir::DynamicOpDefinition::setParseFn (OperationName::ParseAssemblyFn && parse) inline
Sets the static hook for parsing this op assembly.
Definition at line 385 of file ExtensibleDialect.h.
setPrintFn()
void mlir::DynamicOpDefinition::setPrintFn (OperationName::PrintAssemblyFn && print) inline
Sets the static hook for printing this op assembly.
Definition at line 390 of file ExtensibleDialect.h.
References print().
setVerifyFn()
void mlir::DynamicOpDefinition::setVerifyFn (OperationName::VerifyInvariantsFn && verify) inline
Sets the verifier function for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 373 of file ExtensibleDialect.h.
References mlir::verify().
setVerifyRegionFn()
void mlir::DynamicOpDefinition::setVerifyRegionFn (OperationName::VerifyRegionInvariantsFn && verify) inline
Sets the region verifier function for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 380 of file ExtensibleDialect.h.
References mlir::verify().
The documentation for this class was generated from the following files:
include/mlir/IR/ExtensibleDialect.h
lib/IR/ExtensibleDialect.cpp