MLIR: mlir::pdll::ast::PatternDecl Class Reference
mlir::pdll::ast::PatternDecl Class Reference
This Decl represents a single Pattern.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Optional< uint16_t > getBenefit () const
Return the benefit of this pattern if specified, or None.
bool hasBoundedRewriteRecursion () const
Return if this pattern has bounded rewrite recursion.
const CompoundStmt * getBody () const
Return the body of this pattern.
const OpRewriteStmt * getRootRewriteStmt () const
Return the root rewrite statement of this pattern.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static PatternDecl * create (Context &ctx, SMRange location, const Name *name, Optional< uint16_t > benefit, bool hasBoundedRecursion, const CompoundStmt *body)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< PatternDecl, Decl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< PatternDecl, Decl >
using Base = NodeBase< PatternDecl, Decl >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< PatternDecl, Decl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This Decl represents a single Pattern.
Definition at line 974 of file Nodes.h.
Member Function Documentation
create()
PatternDecl * PatternDecl::create (Context & ctx, SMRange location, const Name * name, Optional< uint16_t > benefit, bool hasBoundedRecursion, const CompoundStmt * body) static
Definition at line 474 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), mlir::pdll::ast::UserRewriteDecl::getInputs(), and mlir::pdll::ast::UserRewriteDecl::getResults().
getBenefit()
Optional<uint16_t> mlir::pdll::ast::PatternDecl::getBenefit () const inline
Return the benefit of this pattern if specified, or None.
Definition at line 982 of file Nodes.h.
Referenced by checkAndNestUnderRewriteOp(), and getLspDiagnoticFromDiag().
getBody()
const CompoundStmt* mlir::pdll::ast::PatternDecl::getBody () const inline
Return the body of this pattern.
Definition at line 988 of file Nodes.h.
Referenced by checkAndNestUnderRewriteOp(), mlir::pdll::ast::Name::create(), and getLspDiagnoticFromDiag().
getRootRewriteStmt()
const OpRewriteStmt* mlir::pdll::ast::PatternDecl::getRootRewriteStmt () const inline
Return the root rewrite statement of this pattern.
Definition at line 991 of file Nodes.h.
Referenced by getLspDiagnoticFromDiag().
hasBoundedRewriteRecursion()
bool mlir::pdll::ast::PatternDecl::hasBoundedRewriteRecursion () const inline
Return if this pattern has bounded rewrite recursion.
Definition at line 985 of file Nodes.h.
Referenced by getLspDiagnoticFromDiag().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp