MLIR: mlir::presburger::GBRSimplex Class Reference
mlir::presburger::GBRSimplex Class Reference
Given a simplex for a polytope, construct a new simplex whose variables are identified with a pair of points (x, y) in the original polytope.
Public Member Functions
GBRSimplex (const Simplex &originalSimplex)
void addEqualityForDirection (ArrayRef< int64_t > dir)
Add an equality dotProduct(dir, x - y) == 0.
Fraction computeWidth (ArrayRef< int64_t > dir)
Compute max(dotProduct(dir, x - y)).
Fraction computeWidthAndDuals (ArrayRef< int64_t > dir, SmallVectorImpl< int64_t > &dual, int64_t &dualDenom)
Compute max(dotProduct(dir, x - y)) and save the dual variables for only the direction equalities to dual.
void removeLastEquality ()
Remove the last equality that was added through addEqualityForDirection.
Detailed Description
Given a simplex for a polytope, construct a new simplex whose variables are identified with a pair of points (x, y) in the original polytope.
Supports some operations needed for generalized basis reduction. In what follows, dotProduct(x, y) = x_1 * y_1 + x_2 * y_2 + ... x_n * y_n where n is the dimension of the original polytope.
This supports adding equality constraints dotProduct(dir, x - y) == 0. It also supports rolling back this addition, by maintaining a snapshot stack that contains a snapshot of the Simplex's state for each equality, just before that equality was added.
Definition at line 1616 of file Simplex.cpp.
Constructor & Destructor Documentation
GBRSimplex()
mlir::presburger::GBRSimplex::GBRSimplex (const Simplex & originalSimplex) inline
Definition at line 1620 of file Simplex.cpp.
Member Function Documentation
addEqualityForDirection()
void mlir::presburger::GBRSimplex::addEqualityForDirection (ArrayRef< int64_t > dir) inline
Add an equality dotProduct(dir, x - y) == 0.
First pushes a snapshot for the current simplex state to the stack so that this can be rolled back later.
Definition at line 1627 of file Simplex.cpp.
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
computeWidth()
Fraction mlir::presburger::GBRSimplex::computeWidth (ArrayRef< int64_t > dir) inline
Compute max(dotProduct(dir, x - y)).
Definition at line 1634 of file Simplex.cpp.
References mlir::presburger::MaybeOptimum< T >::isBounded().
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
computeWidthAndDuals()
Fraction mlir::presburger::GBRSimplex::computeWidthAndDuals (ArrayRef< int64_t > dir, SmallVectorImpl< int64_t > & dual, int64_t & dualDenom) inline
Compute max(dotProduct(dir, x - y)) and save the dual variables for only the direction equalities to dual.
Definition at line 1643 of file Simplex.cpp.
References mlir::presburger::SimplexBase::Column, mlir::presburger::MaybeOptimum< T >::isBounded(), and mlir::presburger::Simplex::Up.
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
removeLastEquality()
void mlir::presburger::GBRSimplex::removeLastEquality () inline
Remove the last equality that was added through addEqualityForDirection.
We do this by rolling back to the snapshot at the top of the stack, which should be a snapshot taken just before the last equality was added.
Definition at line 1702 of file Simplex.cpp.
References mlir::presburger::GBRSimplex::addEqualityForDirection(), mlir::presburger::Matrix::addToRow(), mlir::presburger::GBRSimplex::computeWidth(), mlir::presburger::GBRSimplex::computeWidthAndDuals(), mlir::floorDiv(), mlir::presburger::Matrix::getNumRows(), mlir::presburger::Matrix::getRow(), mlir::presburger::GBRSimplex::removeLastEquality(), scaleAndAddForAssert(), and mlir::presburger::Matrix::swapRows().
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
The documentation for this class was generated from the following file:
lib/Analysis/Presburger/Simplex.cpp