MLIR: mlir::arith::ConstantIntOp Class Reference
mlir::arith::ConstantIntOp Class Reference
Specialization of arith.constant op that returns an integer value.
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
Public Member Functions
int64_t value ()
Static Public Member Functions
static void build (OpBuilder &builder, OperationState &result, int64_t value, unsigned width)
Build a constant int op that produces an integer of the specified width.
static void build (OpBuilder &builder, OperationState &result, int64_t value, Type type)
Build a constant int op that produces an integer of the specified type, which must be an integer type.
static bool classof (Operation *op)
Detailed Description
Specialization of arith.constant op that returns an integer value.
Definition at line 42 of file Arithmetic.h.
Member Function Documentation
build() [1/2]
void arith::ConstantIntOp::build (OpBuilder & builder, OperationState & result, int64_t value, unsigned width) static
Build a constant int op that produces an integer of the specified width.
Definition at line 144 of file ArithmeticOps.cpp.
References mlir::Builder::getIntegerAttr(), and mlir::Builder::getIntegerType().
build() [2/2]
void arith::ConstantIntOp::build (OpBuilder & builder, OperationState & result, int64_t value, Type type) static
Build a constant int op that produces an integer of the specified type, which must be an integer type.
Definition at line 151 of file ArithmeticOps.cpp.
References mlir::Builder::getIntegerAttr(), and mlir::Type::isSignlessInteger().
classof()
bool arith::ConstantIntOp::classof (Operation * op) static
Definition at line 159 of file ArithmeticOps.cpp.
Referenced by value(), mlir::arith::ConstantFloatOp::value(), and mlir::arith::ConstantIndexOp::value().
value()
int64_t mlir::arith::ConstantIntOp::value () inline
Definition at line 55 of file Arithmetic.h.
References classof().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Arithmetic/IR/Arithmetic.h
lib/Dialect/Arithmetic/IR/ArithmeticOps.cpp