MLIR: mlir::tblgen::AttrOrTypeParameter Class Reference
mlir::tblgen::AttrOrTypeParameter Class Reference
A wrapper class for tblgen AttrOrTypeParameter, arrays of which belong to AttrOrTypeDefs to parameterize them.
#include "mlir/TableGen/AttrOrTypeDef.h"
Public Member Functions
AttrOrTypeParameter (const llvm::DagInit *def, unsigned index)
bool isAnonymous () const
Returns true if the parameter is anonymous (has no name).
StringRef getName () const
Get the parameter name.
Optional< StringRef > getAllocator () const
If specified, get the custom allocator code for this parameter.
StringRef getComparator () const
If specified, get the custom comparator code for this parameter.
StringRef getCppType () const
Get the C++ type of this parameter.
StringRef getCppAccessorType () const
Get the C++ accessor type of this parameter.
StringRef getCppStorageType () const
Get the C++ storage type of this parameter.
Optional< StringRef > getParser () const
Get an optional C++ parameter parser.
Optional< StringRef > getPrinter () const
Get an optional C++ parameter printer.
Optional< StringRef > getSummary () const
Get a description of this parameter for documentation purposes.
StringRef getSyntax () const
Get the assembly syntax documentation.
bool isOptional () const
Returns true if the parameter is optional.
Optional< StringRef > getDefaultValue () const
Get the default value of the parameter if it has one.
llvm::Init * getDef () const
Return the underlying def of this parameter.
bool operator== (const AttrOrTypeParameter &other) const
The parameter is pointer-comparable.
bool operator!= (const AttrOrTypeParameter &other) const
Detailed Description
A wrapper class for tblgen AttrOrTypeParameter, arrays of which belong to AttrOrTypeDefs to parameterize them.
Definition at line 50 of file AttrOrTypeDef.h.
Constructor & Destructor Documentation
AttrOrTypeParameter()
mlir::tblgen::AttrOrTypeParameter::AttrOrTypeParameter (const llvm::DagInit * def, unsigned index) inline explicit
Definition at line 52 of file AttrOrTypeDef.h.
Member Function Documentation
getAllocator()
Optional< StringRef > AttrOrTypeParameter::getAllocator () const
If specified, get the custom allocator code for this parameter.
Definition at line 218 of file AttrOrTypeDef.cpp.
getComparator()
StringRef AttrOrTypeParameter::getComparator () const
If specified, get the custom comparator code for this parameter.
Definition at line 222 of file AttrOrTypeDef.cpp.
getCppAccessorType()
StringRef AttrOrTypeParameter::getCppAccessorType () const
Get the C++ accessor type of this parameter.
Definition at line 238 of file AttrOrTypeDef.cpp.
getCppStorageType()
StringRef AttrOrTypeParameter::getCppStorageType () const
Get the C++ storage type of this parameter.
Definition at line 243 of file AttrOrTypeDef.cpp.
getCppType()
StringRef AttrOrTypeParameter::getCppType () const
Get the C++ type of this parameter.
Definition at line 227 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeDef::getDef().
getDef()
llvm::Init * AttrOrTypeParameter::getDef () const
Return the underlying def of this parameter.
Definition at line 276 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeDef::def.
Referenced by mlir::tblgen::AttributeSelfTypeParameter::classof().
getDefaultValue()
Optional< StringRef > AttrOrTypeParameter::getDefaultValue () const
Get the default value of the parameter if it has one.
Definition at line 272 of file AttrOrTypeDef.cpp.
getName()
StringRef AttrOrTypeParameter::getName () const
Get the parameter name.
Definition at line 214 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeDef::def.
getParser()
Optional< StringRef > AttrOrTypeParameter::getParser () const
Get an optional C++ parameter parser.
Definition at line 248 of file AttrOrTypeDef.cpp.
getPrinter()
Optional< StringRef > AttrOrTypeParameter::getPrinter () const
Get an optional C++ parameter printer.
Definition at line 252 of file AttrOrTypeDef.cpp.
getSummary()
Optional< StringRef > AttrOrTypeParameter::getSummary () const
Get a description of this parameter for documentation purposes.
Definition at line 256 of file AttrOrTypeDef.cpp.
getSyntax()
StringRef AttrOrTypeParameter::getSyntax () const
Get the assembly syntax documentation.
Definition at line 260 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeDef::getDef().
isAnonymous()
bool AttrOrTypeParameter::isAnonymous () const
Returns true if the parameter is anonymous (has no name).
Definition at line 210 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeDef::def.
isOptional()
bool AttrOrTypeParameter::isOptional () const
Returns true if the parameter is optional.
Definition at line 266 of file AttrOrTypeDef.cpp.
operator!=()
bool mlir::tblgen::AttrOrTypeParameter::operator!= (const AttrOrTypeParameter & other) const inline
Definition at line 101 of file AttrOrTypeDef.h.
operator==()
bool mlir::tblgen::AttrOrTypeParameter::operator== (const AttrOrTypeParameter & other) const inline
The parameter is pointer-comparable.
Definition at line 98 of file AttrOrTypeDef.h.
The documentation for this class was generated from the following files:
include/mlir/TableGen/AttrOrTypeDef.h
lib/TableGen/AttrOrTypeDef.cpp