MLIR: mlir::AffineDmaStartOp Class Reference
mlir::AffineDmaStartOp Class Reference
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
#include "mlir/Dialect/Affine/IR/AffineOps.h"
Public Member Functions
unsigned getSrcMemRefOperandIndex ()
Returns the operand index of the source memref.
Value getSrcMemRef ()
Returns the source MemRefType for this DMA operation.
MemRefType getSrcMemRefType ()
unsigned getSrcMemRefRank ()
Returns the rank (number of indices) of the source MemRefType.
AffineMap getSrcMap ()
Returns the affine map used to access the source memref.
AffineMapAttr getSrcMapAttr ()
operand_range getSrcIndices ()
Returns the source memref affine map indices for this DMA operation.
unsigned getSrcMemorySpace ()
Returns the memory space of the source memref.
unsigned getDstMemRefOperandIndex ()
Returns the operand index of the destination memref.
Value getDstMemRef ()
Returns the destination MemRefType for this DMA operation.
MemRefType getDstMemRefType ()
unsigned getDstMemRefRank ()
Returns the rank (number of indices) of the destination MemRefType.
unsigned getDstMemorySpace ()
Returns the memory space of the source memref.
AffineMap getDstMap ()
Returns the affine map used to access the destination memref.
AffineMapAttr getDstMapAttr ()
operand_range getDstIndices ()
Returns the destination memref indices for this DMA operation.
unsigned getTagMemRefOperandIndex ()
Returns the operand index of the tag memref.
Value getTagMemRef ()
Returns the Tag MemRef for this DMA operation.
MemRefType getTagMemRefType ()
unsigned getTagMemRefRank ()
Returns the rank (number of indices) of the tag MemRefType.
AffineMap getTagMap ()
Returns the affine map used to access the tag memref.
AffineMapAttr getTagMapAttr ()
operand_range getTagIndices ()
Returns the tag memref indices for this DMA operation.
Value getNumElements ()
Returns the number of elements being transferred by this DMA operation.
NamedAttribute getAffineMapAttrForMemRef (Value memref)
Impelements the AffineMapAccessInterface.
bool isDestMemorySpaceFaster ()
Returns true if this is a DMA from a faster memory space to a slower one.
bool isSrcMemorySpaceFaster ()
Returns true if this is a DMA from a slower memory space to a faster one.
unsigned getFasterMemPos ()
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
void print (OpAsmPrinter &p)
LogicalResult verifyInvariantsImpl ()
LogicalResult verifyInvariants ()
LogicalResult fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > &results)
bool isStrided ()
Returns true if this DMA operation is strided, returns false otherwise.
Value getStride ()
Returns the stride value for this DMA operation.
Value getNumElementsPerStride ()
Returns the number of elements to transfer per stride for this DMA op.
Public Member Functions inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >
AffineDmaStartOp clone ()
Create a deep copy of this operation.
AffineDmaStartOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * operator-> () const
Shortcut of -> to access a member of Operation.
Operation * getOperation ()
Return the operation that this refers to.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<WalkOrder Order = WalkOrder::PostOrder, typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT >::type walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT >::type walk (FnT &&callback)
Generic walker with a stage aware callback.
Static Public Member Functions
static ArrayRef< StringRef > getAttributeNames ()
static void build (OpBuilder &builder, OperationState &result, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride=nullptr, Value elementsPerStride=nullptr)
static StringRef getSrcMapAttrName ()
static StringRef getDstMapAttrName ()
static StringRef getTagMapAttrName ()
static StringRef getOperationName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Static Public Member Functions inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static std::enable_if_t< std::is_base_of< OpState, T >::value, bool > classof (const T *op)
Provide classof support for other OpBase derived classes, such as Interfaces.
static ConcreteOpType getFromOpaquePointer (const void *pointer)
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Additional Inherited Members
Public Types inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >
using ConcreteOpType = AffineDmaStartOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
LogicalResult verifyRegions ()
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineDmaStartOp, MemRefsNormalizable >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Parse the custom form of an operation.
static void print (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print the operation.
static void printOpName (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print an operation name, eliding the dialect prefix if necessary.
Detailed Description
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
The source and destination memref need not be of the same dimensionality, but need to have the same elemental type. The operands include the source and destination memref's each followed by its indices, size of the data transfer in terms of the number of elements (of the elemental type of the memref), a tag memref with its indices, and optionally at the end, a stride and a number_of_elements_per_stride arguments. The tag location is used by an AffineDmaWaitOp to check for completion. The indices of the source memref, destination memref, and the tag memref have the same restrictions as any affine.load/store. In particular, index for each memref dimension must be an affine expression of loop induction variables and symbols. The optional stride arguments should be of 'index' type, and specify a stride for the slower memory space (memory space with a lower memory space id), transferring chunks of number_of_elements_per_stride every stride until num_elements are transferred. Either both or no stride arguments should be specified. The value of 'num_elements' must be a multiple of 'number_of_elements_per_stride'. If the source and destination locations overlap the behavior of this operation is not defined.
Definition at line 89 of file AffineOps.h.
Member Function Documentation
build()
void AffineDmaStartOp::build (OpBuilder & builder, OperationState & result, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride = nullptr, Value elementsPerStride = nullptr) static
Definition at line 999 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), and mlir::OperationState::addOperands().
Referenced by getAttributeNames(), and mlir::AffineDmaWaitOp::getAttributeNames().
fold()
LogicalResult AffineDmaStartOp::fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > & results)
dma_start(memrefcast) -> dma_start
Definition at line 1154 of file AffineOps.cpp.
References foldMemRefCast().
Referenced by verifyInvariants(), and mlir::AffineDmaWaitOp::verifyInvariants().
getAffineMapAttrForMemRef()
NamedAttribute mlir::AffineDmaStartOp::getAffineMapAttrForMemRef (Value memref) inline
Impelements the AffineMapAccessInterface.
Returns the AffineMapAttr associated with 'memref'.
Definition at line 204 of file AffineOps.h.
References mlir::OpState::getContext(), getDstMapAttr(), getDstMapAttrName(), getDstMemRef(), getSrcMapAttr(), getSrcMapAttrName(), getSrcMemRef(), getTagMapAttr(), getTagMapAttrName(), and getTagMemRef().
getAttributeNames()
static ArrayRef<StringRef> mlir::AffineDmaStartOp::getAttributeNames () inline static
Definition at line 95 of file AffineOps.h.
References build().
getDstIndices()
operand_range mlir::AffineDmaStartOp::getDstIndices () inline
Returns the destination memref indices for this DMA operation.
Definition at line 161 of file AffineOps.h.
References getDstMap(), getDstMemRefOperandIndex(), and mlir::AffineMap::getNumInputs().
getDstMap()
AffineMap mlir::AffineDmaStartOp::getDstMap () inline
Returns the affine map used to access the destination memref.
Definition at line 155 of file AffineOps.h.
References getDstMapAttr().
Referenced by getDstIndices(), getTagMemRefOperandIndex(), and mlir::lowerAffineLowerBound().
getDstMapAttr()
AffineMapAttr mlir::AffineDmaStartOp::getDstMapAttr () inline
Definition at line 156 of file AffineOps.h.
References getDstMapAttrName().
Referenced by getAffineMapAttrForMemRef(), and getDstMap().
getDstMapAttrName()
static StringRef mlir::AffineDmaStartOp::getDstMapAttrName () inline static
Definition at line 237 of file AffineOps.h.
Referenced by getAffineMapAttrForMemRef(), and getDstMapAttr().
getDstMemorySpace()
unsigned mlir::AffineDmaStartOp::getDstMemorySpace () inline
Returns the memory space of the source memref.
Definition at line 150 of file AffineOps.h.
References mlir::Type::cast(), getDstMemRef(), mlir::detail::getMemorySpaceAsInt(), and mlir::Value::getType().
Referenced by isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getDstMemRef()
Value mlir::AffineDmaStartOp::getDstMemRef () inline
Returns the destination MemRefType for this DMA operation.
Definition at line 139 of file AffineOps.h.
References getDstMemRefOperandIndex().
Referenced by getAffineMapAttrForMemRef(), getDstMemorySpace(), getDstMemRefRank(), and getDstMemRefType().
getDstMemRefOperandIndex()
unsigned mlir::AffineDmaStartOp::getDstMemRefOperandIndex () inline
Returns the operand index of the destination memref.
Definition at line 134 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getSrcMap(), and getSrcMemRefOperandIndex().
Referenced by getDstIndices(), getDstMemRef(), getFasterMemPos(), getTagMemRefOperandIndex(), and mlir::lowerAffineLowerBound().
getDstMemRefRank()
unsigned mlir::AffineDmaStartOp::getDstMemRefRank () inline
Returns the rank (number of indices) of the destination MemRefType.
Definition at line 145 of file AffineOps.h.
References mlir::Type::cast(), getDstMemRef(), and mlir::Value::getType().
getDstMemRefType()
MemRefType mlir::AffineDmaStartOp::getDstMemRefType () inline
Definition at line 140 of file AffineOps.h.
References mlir::Type::cast(), getDstMemRef(), and mlir::Value::getType().
getFasterMemPos()
unsigned mlir::AffineDmaStartOp::getFasterMemPos () inline
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
Asserts failure if neither is true.
Definition at line 231 of file AffineOps.h.
References getDstMemRefOperandIndex(), isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getNumElements()
Value mlir::AffineDmaStartOp::getNumElements () inline
Returns the number of elements being transferred by this DMA operation.
Definition at line 197 of file AffineOps.h.
References getTagMap(), and getTagMemRefOperandIndex().
getNumElementsPerStride()
Value mlir::AffineDmaStartOp::getNumElementsPerStride () inline
Returns the number of elements to transfer per stride for this DMA op.
Definition at line 262 of file AffineOps.h.
References isStrided().
getOperationName()
static StringRef mlir::AffineDmaStartOp::getOperationName () inline static
Definition at line 240 of file AffineOps.h.
References parse(), print(), and verifyInvariantsImpl().
getSrcIndices()
operand_range mlir::AffineDmaStartOp::getSrcIndices () inline
Returns the source memref affine map indices for this DMA operation.
Definition at line 122 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getSrcMap(), and getSrcMemRefOperandIndex().
getSrcMap()
AffineMap mlir::AffineDmaStartOp::getSrcMap () inline
Returns the affine map used to access the source memref.
Definition at line 116 of file AffineOps.h.
References getSrcMapAttr().
Referenced by getDstMemRefOperandIndex(), getSrcIndices(), and mlir::lowerAffineLowerBound().
getSrcMapAttr()
AffineMapAttr mlir::AffineDmaStartOp::getSrcMapAttr () inline
Definition at line 117 of file AffineOps.h.
References getSrcMapAttrName().
Referenced by getAffineMapAttrForMemRef(), and getSrcMap().
getSrcMapAttrName()
static StringRef mlir::AffineDmaStartOp::getSrcMapAttrName () inline static
Definition at line 236 of file AffineOps.h.
Referenced by getAffineMapAttrForMemRef(), and getSrcMapAttr().
getSrcMemorySpace()
unsigned mlir::AffineDmaStartOp::getSrcMemorySpace () inline
Returns the memory space of the source memref.
Definition at line 129 of file AffineOps.h.
References mlir::Type::cast(), mlir::detail::getMemorySpaceAsInt(), getSrcMemRef(), and mlir::Value::getType().
Referenced by isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getSrcMemRef()
Value mlir::AffineDmaStartOp::getSrcMemRef () inline
Returns the source MemRefType for this DMA operation.
Definition at line 107 of file AffineOps.h.
References getSrcMemRefOperandIndex().
Referenced by getAffineMapAttrForMemRef(), getSrcMemorySpace(), getSrcMemRefType(), and mlir::lowerAffineLowerBound().
getSrcMemRefOperandIndex()
unsigned mlir::AffineDmaStartOp::getSrcMemRefOperandIndex () inline
Returns the operand index of the source memref.
Definition at line 104 of file AffineOps.h.
Referenced by getDstMemRefOperandIndex(), getSrcIndices(), getSrcMemRef(), and mlir::lowerAffineLowerBound().
getSrcMemRefRank()
unsigned mlir::AffineDmaStartOp::getSrcMemRefRank () inline
Returns the rank (number of indices) of the source MemRefType.
Definition at line 113 of file AffineOps.h.
References getSrcMemRefType().
getSrcMemRefType()
MemRefType mlir::AffineDmaStartOp::getSrcMemRefType () inline
Definition at line 108 of file AffineOps.h.
References mlir::Type::cast(), getSrcMemRef(), and mlir::Value::getType().
Referenced by getSrcMemRefRank().
getStride()
Value mlir::AffineDmaStartOp::getStride () inline
Returns the stride value for this DMA operation.
Definition at line 255 of file AffineOps.h.
References isStrided().
getTagIndices()
operand_range mlir::AffineDmaStartOp::getTagIndices () inline
Returns the tag memref indices for this DMA operation.
Definition at line 190 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getTagMap(), and getTagMemRefOperandIndex().
Referenced by checkTagMatch().
getTagMap()
AffineMap mlir::AffineDmaStartOp::getTagMap () inline
Returns the affine map used to access the tag memref.
Definition at line 184 of file AffineOps.h.
References getTagMapAttr().
Referenced by getNumElements(), mlir::AffineDmaWaitOp::getNumElements(), getTagIndices(), mlir::AffineDmaWaitOp::getTagIndices(), isStrided(), and mlir::lowerAffineLowerBound().
getTagMapAttr()
AffineMapAttr mlir::AffineDmaStartOp::getTagMapAttr () inline
Definition at line 185 of file AffineOps.h.
References getTagMapAttrName().
Referenced by getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), getTagMap(), and mlir::AffineDmaWaitOp::getTagMap().
getTagMapAttrName()
static StringRef mlir::AffineDmaStartOp::getTagMapAttrName () inline static
Definition at line 238 of file AffineOps.h.
Referenced by getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), getTagMapAttr(), and mlir::AffineDmaWaitOp::getTagMapAttr().
getTagMemRef()
Value mlir::AffineDmaStartOp::getTagMemRef () inline
Returns the Tag MemRef for this DMA operation.
Definition at line 173 of file AffineOps.h.
References getTagMemRefOperandIndex().
Referenced by checkTagMatch(), getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), getTagMemRefRank(), mlir::AffineDmaWaitOp::getTagMemRefRank(), getTagMemRefType(), and mlir::AffineDmaWaitOp::getTagMemRefType().
getTagMemRefOperandIndex()
unsigned mlir::AffineDmaStartOp::getTagMemRefOperandIndex () inline
Returns the operand index of the tag memref.
Definition at line 168 of file AffineOps.h.
References getDstMap(), getDstMemRefOperandIndex(), and mlir::AffineMap::getNumInputs().
Referenced by getNumElements(), getTagIndices(), getTagMemRef(), isStrided(), and mlir::lowerAffineLowerBound().
getTagMemRefRank()
unsigned mlir::AffineDmaStartOp::getTagMemRefRank () inline
Returns the rank (number of indices) of the tag MemRefType.
Definition at line 179 of file AffineOps.h.
References mlir::Type::cast(), getTagMemRef(), and mlir::Value::getType().
getTagMemRefType()
MemRefType mlir::AffineDmaStartOp::getTagMemRefType () inline
Definition at line 174 of file AffineOps.h.
References mlir::Type::cast(), getTagMemRef(), and mlir::Value::getType().
isDestMemorySpaceFaster()
bool mlir::AffineDmaStartOp::isDestMemorySpaceFaster () inline
Returns true if this is a DMA from a faster memory space to a slower one.
Definition at line 218 of file AffineOps.h.
References getDstMemorySpace(), and getSrcMemorySpace().
Referenced by getFasterMemPos().
isSrcMemorySpaceFaster()
bool mlir::AffineDmaStartOp::isSrcMemorySpaceFaster () inline
Returns true if this is a DMA from a slower memory space to a faster one.
Definition at line 223 of file AffineOps.h.
References getDstMemorySpace(), and getSrcMemorySpace().
Referenced by getFasterMemPos().
isStrided()
bool mlir::AffineDmaStartOp::isStrided () inline
Returns true if this DMA operation is strided, returns false otherwise.
Definition at line 249 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getTagMap(), and getTagMemRefOperandIndex().
Referenced by getNumElementsPerStride(), and getStride().
parse()
ParseResult AffineDmaStartOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 1043 of file AffineOps.cpp.
References mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), mlir::isStrided(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
Referenced by getOperationName(), and mlir::AffineDmaWaitOp::getTagMapAttrName().
print()
void AffineDmaStartOp::print (OpAsmPrinter & p)
Definition at line 1021 of file AffineOps.cpp.
References getNumElements(), mlir::isStrided(), and mlir::OpAsmPrinter::printAffineMapOfSSAIds().
Referenced by getOperationName(), and mlir::AffineDmaWaitOp::getTagMapAttrName().
verifyInvariants()
LogicalResult mlir::AffineDmaStartOp::verifyInvariants () inline
Definition at line 244 of file AffineOps.h.
References fold(), and verifyInvariantsImpl().
verifyInvariantsImpl()
LogicalResult AffineDmaStartOp::verifyInvariantsImpl ()
Definition at line 1116 of file AffineOps.cpp.
References mlir::getAffineScope(), isValidAffineIndexOperand(), and mlir::success().
Referenced by getOperationName(), mlir::AffineDmaWaitOp::getTagMapAttrName(), verifyInvariants(), and mlir::AffineDmaWaitOp::verifyInvariants().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/IR/AffineOps.h
lib/Dialect/Affine/IR/AffineOps.cpp