MLIR: mlir::AsmPrinter::Impl Class Reference
mlir::AsmPrinter::Impl Class Reference
Public Types
enum AttrTypeElision { AttrTypeElision::Never, AttrTypeElision::May, AttrTypeElision::Must }
This enum describes the different kinds of elision for the type of an attribute when printing it.
Public Member Functions
Impl (raw_ostream &os, OpPrintingFlags flags=llvm::None, AsmStateImpl *state=nullptr)
Impl (Impl &other)
raw_ostream & getStream ()
Returns the output stream of the printer.
template<typename Container , typename UnaryFunctor >
void interleaveComma (const Container &c, UnaryFunctor eachFn) const
void printAttribute (Attribute attr, AttrTypeElision typeElision=AttrTypeElision::Never)
Print the given attribute.
LogicalResult printAlias (Attribute attr)
Print the alias for the given attribute, return failure if no alias could be printed.
void printType (Type type)
LogicalResult printAlias (Type type)
Print the alias for the given type, return failure if no alias could be printed.
void printLocation (LocationAttr loc, bool allowAlias=false)
Print the given location to the stream.
void printAffineMap (AffineMap map)
void printAffineExpr (AffineExpr expr, function_ref< void(unsigned, bool)> printValueName=nullptr)
void printAffineConstraint (AffineExpr expr, bool isEq)
void printIntegerSet (IntegerSet set)
Protected Types
enum BindingStrength { BindingStrength::Weak, BindingStrength::Strong }
This enum is used to represent the binding strength of the enclosing context that an AffineExprStorage is being printed in, so we can intelligently produce parens.
Protected Member Functions
void printOptionalAttrDict (ArrayRef< NamedAttribute > attrs, ArrayRef< StringRef > elidedAttrs={}, bool withKeyword=false)
void printNamedAttribute (NamedAttribute attr)
void printTrailingLocation (Location loc, bool allowAlias=true)
void printLocationInternal (LocationAttr loc, bool pretty=false)
void printDenseElementsAttr (DenseElementsAttr attr, bool allowHex)
Print a dense elements attribute.
void printDenseStringElementsAttr (DenseStringElementsAttr attr)
Print a dense string elements attribute.
void printDenseIntOrFPElementsAttr (DenseIntOrFPElementsAttr attr, bool allowHex)
Print a dense elements attribute.
void printDialectAttribute (Attribute attr)
void printDialectType (Type type)
void printAffineExprInternal (AffineExpr expr, BindingStrength enclosingTightness, function_ref< void(unsigned, bool)> printValueName=nullptr)
Protected Attributes
raw_ostream & os
The output stream for the printer.
OpPrintingFlags printerFlags
A set of flags to control the printer's behavior.
AsmStateImpl * state
An optional printer state for the module.
NewLineCounter newLine
A tracker for the number of new lines emitted during printing.
Detailed Description
Definition at line 1343 of file AsmPrinter.cpp.
Member Enumeration Documentation
AttrTypeElision
enum mlir::AsmPrinter::Impl::AttrTypeElision strong
This enum describes the different kinds of elision for the type of an attribute when printing it.
Enumerator
Never
The type must not be elided,.
May
The type may be elided when it matches the default used in the parser (for example i64 is the default for integer attributes).
Must
The type must be elided.
Definition at line 1361 of file AsmPrinter.cpp.
BindingStrength
enum mlir::AsmPrinter::Impl::BindingStrength strong protected
This enum is used to represent the binding strength of the enclosing context that an AffineExprStorage is being printed in, so we can intelligently produce parens.
Enumerator
Weak
Strong
Definition at line 1422 of file AsmPrinter.cpp.
Constructor & Destructor Documentation
Impl() [1/2]
mlir::AsmPrinter::Impl::Impl (raw_ostream & os, OpPrintingFlags flags = llvm::None, AsmStateImpl * state = nullptr) inline
Definition at line 1345 of file AsmPrinter.cpp.
Impl() [2/2]
mlir::AsmPrinter::Impl::Impl (Impl & other) inline explicit
Definition at line 1348 of file AsmPrinter.cpp.
Member Function Documentation
getStream()
raw_ostream& mlir::AsmPrinter::Impl::getStream () inline
Returns the output stream of the printer.
Definition at line 1352 of file AsmPrinter.cpp.
interleaveComma()
template<typename Container , typename UnaryFunctor > void mlir::AsmPrinter::Impl::interleaveComma (const Container & c, UnaryFunctor eachFn) const inline
Definition at line 1355 of file AsmPrinter.cpp.
printAffineConstraint()
void AsmPrinter::Impl::printAffineConstraint (AffineExpr expr, bool isEq)
Definition at line 2422 of file AsmPrinter.cpp.
printAffineExpr()
void AsmPrinter::Impl::printAffineExpr (AffineExpr expr, function_ref< void(unsigned, bool)> printValueName = nullptr)
Definition at line 2284 of file AsmPrinter.cpp.
Referenced by mlir::AffineExpr::print().
printAffineExprInternal()
void AsmPrinter::Impl::printAffineExprInternal (AffineExpr expr, BindingStrength enclosingTightness, function_ref< void(unsigned, bool)> printValueName = nullptr) protected
Definition at line 2289 of file AsmPrinter.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::AffineExpr::dyn_cast(), mlir::FloorDiv, mlir::AffineExpr::getKind(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
printAffineMap()
void AsmPrinter::Impl::printAffineMap (AffineMap map)
Definition at line 2427 of file AsmPrinter.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::AffineMap::print().
printAlias() [1/2]
LogicalResult AsmPrinter::Impl::printAlias (Attribute attr)
Print the alias for the given attribute, return failure if no alias could be printed.
Definition at line 1725 of file AsmPrinter.cpp.
References mlir::succeeded(), and mlir::success().
printAlias() [2/2]
LogicalResult AsmPrinter::Impl::printAlias (Type type)
Print the alias for the given type, return failure if no alias could be printed.
Definition at line 1729 of file AsmPrinter.cpp.
References mlir::succeeded(), and mlir::success().
printAttribute()
void AsmPrinter::Impl::printAttribute (Attribute attr, AttrTypeElision typeElision = AttrTypeElision::Never)
Print the given attribute.
Definition at line 1733 of file AsmPrinter.cpp.
References mlir::Attribute::dyn_cast(), mlir::Attribute::getDialect(), mlir::Attribute::getType(), mlir::Attribute::isa(), print(), printDialectSymbol(), printFloatValue(), mlir::LLVM::detail::printType(), and mlir::succeeded().
Referenced by mlir::Attribute::print().
printDenseElementsAttr()
void AsmPrinter::Impl::printDenseElementsAttr (DenseElementsAttr attr, bool allowHex) protected
Print a dense elements attribute.
If 'allowHex' is true, a hex string is used instead of individual elements when the elements attr is large.
Definition at line 1934 of file AsmPrinter.cpp.
References mlir::Attribute::cast(), and mlir::Attribute::dyn_cast().
printDenseIntOrFPElementsAttr()
void AsmPrinter::Impl::printDenseIntOrFPElementsAttr (DenseIntOrFPElementsAttr attr, bool allowHex) protected
Print a dense elements attribute.
If 'allowHex' is true, a hex string is used instead of individual elements when the elements attr is large.
Definition at line 1943 of file AsmPrinter.cpp.
References mlir::Type::isa(), mlir::Type::isUnsignedInteger(), printDenseElementsAttrImpl(), printDenseIntElement(), printFloatValue(), and shouldPrintElementsAttrWithHex().
printDenseStringElementsAttr()
void AsmPrinter::Impl::printDenseStringElementsAttr (DenseStringElementsAttr attr) protected
Print a dense string elements attribute.
Definition at line 2014 of file AsmPrinter.cpp.
References printDenseElementsAttrImpl().
printDialectAttribute()
void AsmPrinter::Impl::printDialectAttribute (Attribute attr) protected
Definition at line 2199 of file AsmPrinter.cpp.
References mlir::Attribute::getDialect(), and printDialectSymbol().
printDialectType()
void AsmPrinter::Impl::printDialectType (Type type) protected
Definition at line 2213 of file AsmPrinter.cpp.
References mlir::Type::getDialect(), printDialectSymbol(), and mlir::AsmPrinter::~AsmPrinter().
printIntegerSet()
void AsmPrinter::Impl::printIntegerSet (IntegerSet set)
Definition at line 2453 of file AsmPrinter.cpp.
References mlir::Block::args_empty(), mlir::detail::enumerate(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Operation::getDialect(), mlir::Operation::getLoc(), mlir::BlockArgument::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getPredecessors(), mlir::detail::AsmStateImpl::getPrinterFlags(), mlir::Operation::getRegions(), mlir::Operation::getRegisteredInfo(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::Block::getSinglePredecessor(), mlir::detail::AsmStateImpl::getSSANameState(), mlir::OperationName::getStringRef(), mlir::Operation::getSuccessors(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::Operation::getUsers(), mlir::Block::hasNoPredecessors(), mlir::Block::isEntryBlock(), print(), printNewline(), printOperation(), mlir::LLVM::detail::printType(), mlir::OpPrintingFlags::shouldPrintGenericOpForm(), mlir::OpPrintingFlags::shouldPrintValueUsers(), mlir::Value::use_empty(), mlir::Operation::use_empty(), and value.
Referenced by mlir::IntegerSet::print().
printLocation()
void AsmPrinter::Impl::printLocation (LocationAttr loc, bool allowAlias = false)
Print the given location to the stream.
If allowAlias is true, this allows for the internal location to use an attribute alias.
Definition at line 1574 of file AsmPrinter.cpp.
References mlir::failed(), and mlir::OpPrintingFlags::shouldPrintDebugInfoPrettyForm().
printLocationInternal()
void AsmPrinter::Impl::printLocationInternal (LocationAttr loc, bool pretty = false) protected
Definition at line 1453 of file AsmPrinter.cpp.
References mlir::Location::isa().
printNamedAttribute()
void AsmPrinter::Impl::printNamedAttribute (NamedAttribute attr) protected
Definition at line 2187 of file AsmPrinter.cpp.
References mlir::NamedAttribute::getName(), mlir::NamedAttribute::getValue(), mlir::Attribute::isa(), and printKeywordOrString().
printOptionalAttrDict()
void AsmPrinter::Impl::printOptionalAttrDict (ArrayRef< NamedAttribute > attrs, ArrayRef< StringRef > elidedAttrs = {}, bool withKeyword = false) protected
Definition at line 2153 of file AsmPrinter.cpp.
References mlir::NamedAttribute::getName().
printTrailingLocation()
void AsmPrinter::Impl::printTrailingLocation (Location loc, bool allowAlias = true) protected
Definition at line 1444 of file AsmPrinter.cpp.
References mlir::OpPrintingFlags::shouldPrintDebugInfo().
printType()
void AsmPrinter::Impl::printType (Type type)
Definition at line 2025 of file AsmPrinter.cpp.
References printDialectSymbol(), mlir::LLVM::detail::printType(), and mlir::succeeded().
Referenced by mlir::Type::print().
Member Data Documentation
newLine
NewLineCounter mlir::AsmPrinter::Impl::newLine protected
A tracker for the number of new lines emitted during printing.
Definition at line 1440 of file AsmPrinter.cpp.
os
raw_ostream& mlir::AsmPrinter::Impl::os protected
The output stream for the printer.
Definition at line 1431 of file AsmPrinter.cpp.
printerFlags
OpPrintingFlags mlir::AsmPrinter::Impl::printerFlags protected
A set of flags to control the printer's behavior.
Definition at line 1434 of file AsmPrinter.cpp.
state
AsmStateImpl* mlir::AsmPrinter::Impl::state protected
An optional printer state for the module.
Definition at line 1437 of file AsmPrinter.cpp.
The documentation for this class was generated from the following file:
lib/IR/AsmPrinter.cpp