MLIR: mlir::SymbolTable Class Reference
mlir::SymbolTable Class Reference
This class allows for representing and managing the symbol table used by operations with the 'SymbolTable' trait.
#include "mlir/IR/SymbolTable.h"
Classes
class SymbolUse
This class represents a specific symbol use.
class UseRange
This class implements a range of SymbolRef uses.
Public Types
enum Visibility { Visibility::Public, Visibility::Private, Visibility::Nested }
An enumeration detailing the different visibility types that a symbol may have.
Public Member Functions
SymbolTable (Operation *symbolTableOp)
Build a symbol table with the symbols within the given operation.
Operation * lookup (StringRef name) const
Look up a symbol with the specified name, returning null if no such name exists.
template<typename T >
T lookup (StringRef name) const
Operation * lookup (StringAttr name) const
Look up a symbol with the specified name, returning null if no such name exists.
template<typename T >
T lookup (StringAttr name) const
void erase (Operation *symbol)
Erase the given symbol from the table.
StringAttr insert (Operation *symbol, Block::iterator insertPt={})
Insert a new symbol into the table, and rename it as necessary to avoid collisions.
Operation * getOp () const
Returns the associated operation.
Static Public Member Functions
static StringRef getSymbolAttrName ()
Return the name of the attribute used for symbol names.
static StringRef getVisibilityAttrName ()
Return the name of the attribute used for symbol visibility.
static StringAttr getSymbolName (Operation *symbol)
Returns the name of the given symbol operation, aborting if no symbol is present.
static void setSymbolName (Operation *symbol, StringAttr name)
Sets the name of the given symbol operation.
static void setSymbolName (Operation *symbol, StringRef name)
static Visibility getSymbolVisibility (Operation *symbol)
Returns the visibility of the given symbol operation.
static void setSymbolVisibility (Operation *symbol, Visibility vis)
Sets the visibility of the given symbol operation.
static Operation * getNearestSymbolTable (Operation *from)
Returns the nearest symbol table from a given operation from.
static void walkSymbolTables (Operation *op, bool allSymUsesVisible, function_ref< void(Operation *, bool)> callback)
Walks all symbol table operations nested within, and including, op.
static Operation * lookupSymbolIn (Operation *op, StringAttr symbol)
Returns the operation registered with the given symbol name with the regions of 'symbolTableOp'.
static Operation * lookupSymbolIn (Operation *op, StringRef symbol)
static Operation * lookupSymbolIn (Operation *op, SymbolRefAttr symbol)
static LogicalResult lookupSymbolIn (Operation *op, SymbolRefAttr symbol, SmallVectorImpl< Operation *> &symbols)
A variant of 'lookupSymbolIn' that returns all of the symbols referenced by a given SymbolRefAttr.
static Operation * lookupNearestSymbolFrom (Operation *from, StringAttr symbol)
Returns the operation registered with the given symbol name within the closest parent operation of, or including, 'from' with the 'OpTrait::SymbolTable' trait.
static Operation * lookupNearestSymbolFrom (Operation *from, SymbolRefAttr symbol)
template<typename T >
static T lookupNearestSymbolFrom (Operation *from, StringAttr symbol)
template<typename T >
static T lookupNearestSymbolFrom (Operation *from, SymbolRefAttr symbol)
static Optional< UseRange > getSymbolUses (Operation *from)
Get an iterator range for all of the uses, for any symbol, that are nested within the given operation 'from'.
static Optional< UseRange > getSymbolUses (Region *from)
static Optional< UseRange > getSymbolUses (StringAttr symbol, Operation *from)
Get all of the uses of the given symbol that are nested within the given operation 'from'.
static Optional< UseRange > getSymbolUses (Operation *symbol, Operation *from)
static Optional< UseRange > getSymbolUses (StringAttr symbol, Region *from)
static Optional< UseRange > getSymbolUses (Operation *symbol, Region *from)
static bool symbolKnownUseEmpty (StringAttr symbol, Operation *from)
Return if the given symbol is known to have no uses that are nested within the given operation 'from'.
static bool symbolKnownUseEmpty (Operation *symbol, Operation *from)
static bool symbolKnownUseEmpty (StringAttr symbol, Region *from)
static bool symbolKnownUseEmpty (Operation *symbol, Region *from)
static LogicalResult replaceAllSymbolUses (StringAttr oldSymbol, StringAttr newSymbol, Operation *from)
Attempt to replace all uses of the given symbol 'oldSymbol' with the provided symbol 'newSymbol' that are nested within the given operation 'from'.
static LogicalResult replaceAllSymbolUses (Operation *oldSymbol, StringAttr newSymbolName, Operation *from)
static LogicalResult replaceAllSymbolUses (StringAttr oldSymbol, StringAttr newSymbol, Region *from)
static LogicalResult replaceAllSymbolUses (Operation *oldSymbol, StringAttr newSymbolName, Region *from)
Detailed Description
This class allows for representing and managing the symbol table used by operations with the 'SymbolTable' trait.
Inserting into and erasing from this SymbolTable will also insert and erase from the Operation given to it at construction.
Definition at line 23 of file SymbolTable.h.
Member Enumeration Documentation
Visibility
enum mlir::SymbolTable::Visibility strong
An enumeration detailing the different visibility types that a symbol may have.
Enumerator
Public
The symbol is public and may be referenced anywhere internal or external to the visible references in the IR.
Private
The symbol is private and may only be referenced by SymbolRefAttrs local to the operations within the current symbol table.
Nested
The symbol is visible to the current IR, which may include operations in symbol tables above the one that owns the current symbol.
Nested visibility allows for referencing a symbol outside of its current symbol table, while retaining the ability to observe all uses.
Definition at line 69 of file SymbolTable.h.
Constructor & Destructor Documentation
SymbolTable()
SymbolTable::SymbolTable (Operation * symbolTableOp)
Build a symbol table with the symbols within the given operation.
Definition at line 105 of file SymbolTable.cpp.
References mlir::Region::front(), mlir::Operation::getContext(), getNameIfSymbol(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), getSymbolAttrName(), and mlir::Operation::hasTrait().
Member Function Documentation
erase()
void SymbolTable::erase (Operation * symbol)
Erase the given symbol from the table.
Definition at line 138 of file SymbolTable.cpp.
References mlir::Operation::erase(), getNameIfSymbol(), and mlir::Operation::getParentOp().
Referenced by lookup().
getNearestSymbolTable()
Operation * SymbolTable::getNearestSymbolTable (Operation * from) static
Returns the nearest symbol table from a given operation from.
Returns nullptr if no valid parent symbol table could be found.
Definition at line 252 of file SymbolTable.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::hasTrait(), and isPotentiallyUnknownSymbolTable().
Referenced by castBoolToIntN(), collectSymbolScopes(), declareReduction(), getOrInsertBuiltinVariable(), mlir::spirv::getPushConstantValue(), lookupNearestSymbolFrom(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::spirv::lookupTargetEnv(), and setSymbolName().
getOp()
Operation* mlir::SymbolTable::getOp () const inline
Returns the associated operation.
Definition at line 58 of file SymbolTable.h.
getSymbolAttrName()
static StringRef mlir::SymbolTable::getSymbolAttrName () inline static
Return the name of the attribute used for symbol names.
Definition at line 55 of file SymbolTable.h.
Referenced by buildLLVMFunctionType(), collectValidReferencesFor(), computeHash(), filterFuncAttributes(), findDuplicateElement(), getNameIfSymbol(), hasOneBranchOpTo(), isZeroAttribute(), lookupSymbolIn(), lookupSymbolInModule(), lowerAsEntryFunction(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlirSymbolTableGetSymbolAttributeName(), parseAttributions(), mlir::function_interface_impl::parseFunctionOp(), mlir::function_interface_impl::printFunctionAttributes(), mlir::function_interface_impl::printFunctionOp(), printIR(), printLaunchFuncOperands(), setSymbolName(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), SymbolTable(), verifyAttributions(), verifyConstantType(), verifyCoopMatrixMulAdd(), mlir::detail::verifySymbol(), mlir::detail::verifySymbolTable(), and visitInPrettyBlockOrder().
getSymbolName()
StringAttr SymbolTable::getSymbolName (Operation * symbol) static
Returns the name of the given symbol operation, aborting if no symbol is present.
Returns the name of the given symbol operation.
Definition at line 207 of file SymbolTable.cpp.
References getNameIfSymbol().
Referenced by collectSymbolScopes(), and insert().
getSymbolUses() [1/6]
auto SymbolTable::getSymbolUses (Operation * from) static
Get an iterator range for all of the uses, for any symbol, that are nested within the given operation 'from'.
This does not traverse into any nested symbol tables. This function returns None if there are any unknown operations that may potentially be symbol tables.
This does not traverse into any nested symbol tables, and will also only return uses on 'from' if it does not also define a symbol table. This is because we treat the region as the boundary of the symbol table, and not the op itself. This function returns None if there are any unknown operations that may potentially be symbol tables.
Definition at line 741 of file SymbolTable.cpp.
References getSymbolUsesImpl().
Referenced by convertToLaunchFuncOp(), mlir::SymbolTable::UseRange::empty(), mlir::SymbolUserMap::SymbolUserMap(), and walkReferencedSymbolNodes().
getSymbolUses() [2/6]
auto SymbolTable::getSymbolUses (Region * from) static
Definition at line 744 of file SymbolTable.cpp.
References getSymbolUsesImpl().
getSymbolUses() [3/6]
auto SymbolTable::getSymbolUses (StringAttr symbol, Operation * from) static
Get all of the uses of the given symbol that are nested within the given operation 'from'.
Get all of the uses of the given symbol that are nested within the given operation 'from', invoking the provided callback for each.
This does not traverse into any nested symbol tables. This function returns None if there are any unknown operations that may potentially be symbol tables.
Definition at line 770 of file SymbolTable.cpp.
References getSymbolUsesImpl().
getSymbolUses() [4/6]
auto SymbolTable::getSymbolUses (Operation * symbol, Operation * from) static
Definition at line 774 of file SymbolTable.cpp.
References getSymbolUsesImpl().
getSymbolUses() [5/6]
auto SymbolTable::getSymbolUses (StringAttr symbol, Region * from) static
Definition at line 778 of file SymbolTable.cpp.
References getSymbolUsesImpl().
getSymbolUses() [6/6]
auto SymbolTable::getSymbolUses (Operation * symbol, Region * from) static
Definition at line 782 of file SymbolTable.cpp.
References getSymbolUsesImpl().
getSymbolVisibility()
SymbolTable::Visibility SymbolTable::getSymbolVisibility (Operation * symbol) static
Returns the visibility of the given symbol operation.
Definition at line 219 of file SymbolTable.cpp.
References mlir::Operation::getAttrOfType(), getVisibilityAttrName(), Nested, Private, and Public.
Referenced by setSymbolName().
getVisibilityAttrName()
static StringRef mlir::SymbolTable::getVisibilityAttrName () inline static
Return the name of the attribute used for symbol visibility.
Definition at line 61 of file SymbolTable.h.
Referenced by getSymbolVisibility(), mlirSymbolTableGetVisibilityAttributeName(), mlir::function_interface_impl::parseFunctionOp(), mlir::impl::parseOptionalVisibilityKeyword(), mlir::function_interface_impl::printFunctionOp(), setSymbolVisibility(), and mlir::detail::verifySymbol().
insert()
StringAttr SymbolTable::insert (Operation * symbol, Block::iterator insertPt = {})
Insert a new symbol into the table, and rename it as necessary to avoid collisions.
Insert a new symbol into the table and associated operation if not already there and rename it as necessary to avoid collisions.
Also insert at the specified location in the body of the associated operation if it is not already there. It is asserted that the symbol is not inside another operation. Return the name of the symbol after insertion as attribute.
Return the name of the symbol after insertion as attribute.
Definition at line 156 of file SymbolTable.cpp.
References mlir::Region::front(), mlir::Operation::getContext(), mlir::Operation::getParentOp(), mlir::Operation::getRegion(), getSymbolName(), and setSymbolName().
Referenced by convertToLaunchFuncOp(), createAsyncDispatchFunction(), createDecl(), createParallelComputeFunction(), lookup(), and outlineExecuteOp().
lookup() [1/4]
Operation * SymbolTable::lookup (StringRef name) const
Look up a symbol with the specified name, returning null if no such name exists.
Names never include the @ on them.
Definition at line 130 of file SymbolTable.cpp.
References mlir::Operation::getContext().
Referenced by convertToLaunchFuncOp(), hasOneBranchOpTo(), and lookup().
lookup() [2/4]
template<typename T > T mlir::SymbolTable::lookup (StringRef name) const inline
Definition at line 32 of file SymbolTable.h.
References lookup().
lookup() [3/4]
Operation * SymbolTable::lookup (StringAttr name) const
Look up a symbol with the specified name, returning null if no such name exists.
Names never include the @ on them.
Definition at line 133 of file SymbolTable.cpp.
lookup() [4/4]
template<typename T > T mlir::SymbolTable::lookup (StringAttr name) const inline
Definition at line 40 of file SymbolTable.h.
References erase(), insert(), and lookup().
lookupNearestSymbolFrom() [1/4]
Operation * SymbolTable::lookupNearestSymbolFrom (Operation * from, StringAttr symbol) static
Returns the operation registered with the given symbol name within the closest parent operation of, or including, 'from' with the 'OpTrait::SymbolTable' trait.
Returns the operation registered with the given symbol name within the closes parent operation with the 'OpTrait::SymbolTable' trait.
Returns nullptr if no valid symbol was found.
Definition at line 370 of file SymbolTable.cpp.
References getNearestSymbolTable(), and lookupSymbolIn().
Referenced by mlir::LLVM::ModuleTranslation::getAccessGroup(), mlir::LLVM::ModuleTranslation::getAliasScope(), mlir::bufferization::func_ext::getCalledFunction(), getCalledFunction(), getLoadStoreElementType(), hasOneBranchOpTo(), lookupNearestSymbolFrom(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), lookupSymbolIn(), mlir::SymbolTableCollection::lookupSymbolIn(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::LLVM::ModuleTranslation::setAccessGroupsMetadata(), verifyAccessChain(), verifyConstantType(), verifyCoopMatrixMulAdd(), and verifySymbolAttribute().
lookupNearestSymbolFrom() [2/4]
Operation * SymbolTable::lookupNearestSymbolFrom (Operation * from, SymbolRefAttr symbol) static
Definition at line 375 of file SymbolTable.cpp.
References getNearestSymbolTable(), and lookupSymbolIn().
lookupNearestSymbolFrom() [3/4]
template<typename T > static T mlir::SymbolTable::lookupNearestSymbolFrom (Operation * from, StringAttr symbol) inline static
Definition at line 135 of file SymbolTable.h.
References lookupNearestSymbolFrom().
lookupNearestSymbolFrom() [4/4]
template<typename T > static T mlir::SymbolTable::lookupNearestSymbolFrom (Operation * from, SymbolRefAttr symbol) inline static
Definition at line 139 of file SymbolTable.h.
References lookupNearestSymbolFrom().
lookupSymbolIn() [1/4]
Operation * SymbolTable::lookupSymbolIn (Operation * symbolTableOp, StringAttr symbol) static
Returns the operation registered with the given symbol name with the regions of 'symbolTableOp'.
'symbolTableOp' is required to be an operation with the 'OpTrait::SymbolTable' trait.
'symbolTableOp' is required to be an operation with the 'OpTrait::SymbolTable' trait. Returns nullptr if no valid symbol was found.
Definition at line 300 of file SymbolTable.cpp.
References mlir::Region::empty(), mlir::Region::front(), mlir::Operation::getContext(), getNameIfSymbol(), mlir::Operation::getRegion(), getSymbolAttrName(), and mlir::Operation::hasTrait().
Referenced by eachHasOnlyOneOfTypes(), hasSameBitwidthScalarType(), lookupNearestSymbolFrom(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::OpTrait::SymbolTable< ConcreteType >::lookupSymbol(), lookupSymbolIn(), mlir::SymbolTableCollection::lookupSymbolIn(), lookupSymbolInModule(), ConvertAddressOf::matchAndRewrite(), ConvertAccessChain::matchAndRewrite(), renameSymbol(), setSymbolName(), updateSymbolAndAllUses(), and verifyMemoryOpIndexing().
lookupSymbolIn() [2/4]
static Operation* mlir::SymbolTable::lookupSymbolIn (Operation * op, StringRef symbol) inline static
Definition at line 117 of file SymbolTable.h.
References mlir::Operation::getContext(), lookupNearestSymbolFrom(), and lookupSymbolIn().
lookupSymbolIn() [3/4]
Operation * SymbolTable::lookupSymbolIn (Operation * op, SymbolRefAttr symbol) static
Definition at line 315 of file SymbolTable.cpp.
References mlir::failed(), and lookupSymbolIn().
lookupSymbolIn() [4/4]
LogicalResult SymbolTable::lookupSymbolIn (Operation * op, SymbolRefAttr symbol, SmallVectorImpl< Operation *> & symbols) static
A variant of 'lookupSymbolIn' that returns all of the symbols referenced by a given SymbolRefAttr.
Returns failure if any of the nested references could not be resolved.
Definition at line 359 of file SymbolTable.cpp.
References lookupSymbolIn(), and lookupSymbolInImpl().
replaceAllSymbolUses() [1/4]
LogicalResult SymbolTable::replaceAllSymbolUses (StringAttr oldSymbol, StringAttr newSymbol, Operation * from) static
Attempt to replace all uses of the given symbol 'oldSymbol' with the provided symbol 'newSymbol' that are nested within the given operation 'from'.
This does not traverse into any nested symbol tables. If there are any unknown operations that may potentially be symbol tables, no uses are replaced and failure is returned.
Definition at line 962 of file SymbolTable.cpp.
References replaceAllSymbolUsesImpl().
Referenced by mlir::spirv::combine(), mlir::SymbolTable::UseRange::empty(), mlir::encodeBindAttribute(), encodeKernelName(), mlirSymbolTableReplaceAllSymbolUses(), mlir::SymbolUserMap::replaceAllUsesWith(), and updateSymbolAndAllUses().
replaceAllSymbolUses() [2/4]
LogicalResult SymbolTable::replaceAllSymbolUses (Operation * oldSymbol, StringAttr newSymbolName, Operation * from) static
Definition at line 967 of file SymbolTable.cpp.
References replaceAllSymbolUsesImpl().
replaceAllSymbolUses() [3/4]
LogicalResult SymbolTable::replaceAllSymbolUses (StringAttr oldSymbol, StringAttr newSymbol, Region * from) static
Definition at line 972 of file SymbolTable.cpp.
References replaceAllSymbolUsesImpl().
replaceAllSymbolUses() [4/4]
LogicalResult SymbolTable::replaceAllSymbolUses (Operation * oldSymbol, StringAttr newSymbolName, Region * from) static
Definition at line 977 of file SymbolTable.cpp.
References replaceAllSymbolUsesImpl().
setSymbolName() [1/2]
void SymbolTable::setSymbolName (Operation * symbol, StringAttr name) static
Sets the name of the given symbol operation.
Definition at line 214 of file SymbolTable.cpp.
References getSymbolAttrName(), and mlir::Operation::setAttr().
Referenced by mlir::encodeBindAttribute(), encodeKernelName(), insert(), setSymbolName(), and updateSymbolAndAllUses().
setSymbolName() [2/2]
static void mlir::SymbolTable::setSymbolName (Operation * symbol, StringRef name) inline static
Definition at line 91 of file SymbolTable.h.
References mlir::Operation::getContext(), getNearestSymbolTable(), getSymbolVisibility(), lookupSymbolIn(), setSymbolName(), setSymbolVisibility(), and walkSymbolTables().
setSymbolVisibility()
void SymbolTable::setSymbolVisibility (Operation * symbol, Visibility vis) static
Sets the visibility of the given symbol operation.
Definition at line 232 of file SymbolTable.cpp.
References mlir::Operation::getContext(), getVisibilityAttrName(), Nested, Private, Public, mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by outlineExecuteOp(), and setSymbolName().
symbolKnownUseEmpty() [1/4]
bool SymbolTable::symbolKnownUseEmpty (StringAttr symbol, Operation * from) static
Return if the given symbol is known to have no uses that are nested within the given operation 'from'.
This does not traverse into any nested symbol tables. This function will also return false if there are any unknown operations that may potentially be symbol tables. This doesn't necessarily mean that there are no uses, we just can't conservatively prove it.
This does not traverse into any nested symbol tables. This function will also return false if there are any unknown operations that may potentially be symbol tables.
Definition at line 809 of file SymbolTable.cpp.
References symbolKnownUseEmptyImpl().
Referenced by mlir::SymbolTable::UseRange::empty().
symbolKnownUseEmpty() [2/4]
bool SymbolTable::symbolKnownUseEmpty (Operation * symbol, Operation * from) static
Definition at line 812 of file SymbolTable.cpp.
References symbolKnownUseEmptyImpl().
symbolKnownUseEmpty() [3/4]
bool SymbolTable::symbolKnownUseEmpty (StringAttr symbol, Region * from) static
Definition at line 815 of file SymbolTable.cpp.
References symbolKnownUseEmptyImpl().
symbolKnownUseEmpty() [4/4]
bool SymbolTable::symbolKnownUseEmpty (Operation * symbol, Region * from) static
Definition at line 818 of file SymbolTable.cpp.
References symbolKnownUseEmptyImpl().
walkSymbolTables()
void SymbolTable::walkSymbolTables (Operation * op, bool allSymUsesVisible, function_ref< void(Operation *, bool)> callback) static
Walks all symbol table operations nested within, and including, op.
For each symbol table operation, the provided callback is invoked with the op and a boolean signifying if the symbols within that symbol table can be treated as if all uses within the IR are visible to the caller. allSymUsesVisible identifies whether all of the symbol uses of symbols within op are visible.
For each symbol table operation, the provided callback is invoked with the op and a boolean signifying if the symbols within that symbol table can be treated as if all uses are visible. allSymUsesVisible identifies whether all of the symbol uses of symbols within op are visible.
Definition at line 272 of file SymbolTable.cpp.
References mlir::Operation::getRegions(), and mlir::Operation::hasTrait().
Referenced by mlirSymbolTableWalkSymbolTables(), setSymbolName(), and mlir::SymbolUserMap::SymbolUserMap().
The documentation for this class was generated from the following files:
include/mlir/IR/SymbolTable.h
lib/IR/SymbolTable.cpp