MLIR: mlir::Sliceable< Derived, ElementTy > Class Template Reference
mlir::Sliceable< Derived, ElementTy > Class Template Reference
A CRTP base class for pseudo-containers willing to support Python-type slicing access on top of indexed access.
#include "Bindings/Python/PybindUtils.h"
Public Member Functions
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
std::vector< ElementTy > dunderAdd (Derived &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Member Functions
static void bind (pybind11::module &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Protected Types
using ClassTy = pybind11::class_< Derived >
Protected Member Functions
intptr_t wrapIndex (intptr_t index)
pybind11::object getItem (intptr_t index)
Returns the element at the given slice index.
pybind11::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Detailed Description
template<typename Derived, typename ElementTy>
class mlir::Sliceable< Derived, ElementTy >
A CRTP base class for pseudo-containers willing to support Python-type slicing access on top of indexed access.
Calling ::bind on this class will define __len__ as well as __getitem__ with integer and slice arguments.
This is intended for pseudo-containers that can refer to arbitrary slices of underlying storage indexed by a single integer. Indexing those with an integer produces an instance of ElementTy. Indexing those with a slice produces a new instance of Derived, which can be sliced further.
A derived class must provide the following:
a static const char *pyClassName field containing the name of the Python class to bind;
an instance method intptr_t getNumElements() that returns the number of elements in the backing container (NOT that of the slice);
an instance method ElementTy getElement(intptr_t) that returns a single element at the given index.
an instance method Derived slice(intptr_t, intptr_t, intptr_t) that constructs a new instance of the derived pseudo-container with the given slice parameters (to be forwarded to the Sliceable constructor).
The getNumElements() and getElement(intptr_t) callbacks must not throw.
A derived class may additionally define:
a static void bindDerived(ClassTy &) method to bind additional methods the python class.
Definition at line 216 of file PybindUtils.h.
Member Typedef Documentation
ClassTy
template<typename Derived , typename ElementTy > using mlir::Sliceable< Derived, ElementTy >::ClassTy = pybind11::class_<Derived> protected
Definition at line 218 of file PybindUtils.h.
Constructor & Destructor Documentation
Sliceable()
template<typename Derived , typename ElementTy > mlir::Sliceable< Derived, ElementTy >::Sliceable (intptr_t startIndex, intptr_t length, intptr_t step) inline explicit
Definition at line 264 of file PybindUtils.h.
Member Function Documentation
bind()
template<typename Derived , typename ElementTy > static void mlir::Sliceable< Derived, ElementTy >::bind (pybind11::module & m) inline static
Binds the indexing and length methods in the Python class.
Definition at line 285 of file PybindUtils.h.
References mlir::Sliceable< Derived, ElementTy >::dunderAdd().
bindDerived()
template<typename Derived , typename ElementTy > static void mlir::Sliceable< Derived, ElementTy >::bindDerived (ClassTy &) inline static
Hook for derived classes willing to bind more methods.
Definition at line 336 of file PybindUtils.h.
dunderAdd()
template<typename Derived , typename ElementTy > std::vector<ElementTy> mlir::Sliceable< Derived, ElementTy >::dunderAdd (Derived & other) inline
Returns a new vector (mapped to Python list) containing elements from two slices.
The new vector is necessary because slices may not be contiguous or even come from the same original sequence.
Definition at line 272 of file PybindUtils.h.
Referenced by mlir::Sliceable< Derived, ElementTy >::bind().
getItem()
template<typename Derived , typename ElementTy > pybind11::object mlir::Sliceable< Derived, ElementTy >::getItem (intptr_t index) inline protected
Returns the element at the given slice index.
Supports negative indices by taking elements in inverse order. Returns a nullptr object if out of bounds.
Definition at line 233 of file PybindUtils.h.
References getNumElements().
getItemSlice()
template<typename Derived , typename ElementTy > pybind11::object mlir::Sliceable< Derived, ElementTy >::getItemSlice (PyObject * slice) inline protected
Returns a new instance of the pseudo-container restricted to the given slice.
Returns a nullptr object on failure.
Definition at line 252 of file PybindUtils.h.
wrapIndex()
template<typename Derived , typename ElementTy > intptr_t mlir::Sliceable< Derived, ElementTy >::wrapIndex (intptr_t index) inline protected
Definition at line 222 of file PybindUtils.h.
The documentation for this class was generated from the following file:
lib/Bindings/Python/PybindUtils.h