MLIR: mlir::python::PyInferTypeOpInterface Class Reference
mlir::python::PyInferTypeOpInterface Class Reference
Python wrapper for InterTypeOpInterface.
Classes
struct AppendResultsCallbackData
C-style user-data structure for type appending callback.
Public Member Functions
std::vector< PyType > inferReturnTypes (llvm::Optional< std::vector< PyValue >> operands, llvm::Optional< PyAttribute > attributes, llvm::Optional< std::vector< PyRegion >> regions, DefaultingPyMlirContext context, DefaultingPyLocation location)
Given the arguments required to build an operation, attempts to infer its return types.
Public Member Functions inherited from mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >
PyConcreteOpInterface (py::object object, DefaultingPyMlirContext context)
Constructs an interface instance from an object that is either an operation or a subclass of OpView.
bool isStatic ()
Returns true if this object was constructed from a subclass of OpView rather than from an operation instance.
py::object getOperationObject ()
Returns the operation instance from which this object was constructed.
py::object getOpView ()
Returns the opview of the operation instance from which this object was constructed.
const std::string & getOpName ()
Returns the canonical name of the operation this interface is constructed from.
Static Public Member Functions
static void appendResultsCallback (intptr_t nTypes, MlirType *types, void *userData)
Appends the types provided as the two first arguments to the user-data structure (expects AppendResultsCallbackData).
static void bindDerived (ClassTy &cls)
Static Public Member Functions inherited from mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >
static void bind (py::module &m)
Creates the Python bindings for this class in the given module.
static void bindDerived (ClassTy &cls)
Hook for derived classes to add class-specific bindings.
Static Public Attributes
static constexpr const char * pyClassName = "InferTypeOpInterface"
static constexpr GetTypeIDFunctionTy getInterfaceID
Additional Inherited Members
Protected Types inherited from mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >
using ClassTy = py::class_< PyInferTypeOpInterface >
using GetTypeIDFunctionTy = MlirTypeID(*)()
Detailed Description
Python wrapper for InterTypeOpInterface.
This interface has only static methods.
Definition at line 158 of file IRInterfaces.cpp.
Member Function Documentation
appendResultsCallback()
static void mlir::python::PyInferTypeOpInterface::appendResultsCallback (intptr_t nTypes, MlirType * types, void * userData) inline static
Appends the types provided as the two first arguments to the user-data structure (expects AppendResultsCallbackData).
Definition at line 175 of file IRInterfaces.cpp.
References mlir::python::PyInferTypeOpInterface::AppendResultsCallbackData::inferredTypes.
bindDerived()
static void mlir::python::PyInferTypeOpInterface::bindDerived (ClassTy & cls) inline static
Definition at line 229 of file IRInterfaces.cpp.
References inferReturnTypes().
inferReturnTypes()
std::vector<PyType> mlir::python::PyInferTypeOpInterface::inferReturnTypes (llvm::Optional< std::vector< PyValue >> operands, llvm::Optional< PyAttribute > attributes, llvm::Optional< std::vector< PyRegion >> regions, DefaultingPyMlirContext context, DefaultingPyLocation location) inline
Given the arguments required to build an operation, attempts to infer its return types.
Throws value_error on faliure.
Definition at line 187 of file IRInterfaces.cpp.
References mlir::python::PyConcreteOpInterface< ConcreteIface >::getOpName(), mlirAttributeGetNull(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirLogicalResultIsFailure(), mlirStringRefCreate(), mlir::python::DefaultingPyMlirContext::resolve(), mlir::python::DefaultingPyLocation::resolve(), and value.
Referenced by bindDerived().
Member Data Documentation
getInterfaceID
constexpr GetTypeIDFunctionTy mlir::python::PyInferTypeOpInterface::getInterfaceID static
Initial value:
=
      &mlirInferTypeOpInterfaceTypeID
Definition at line 164 of file IRInterfaces.cpp.
pyClassName
constexpr const char* mlir::python::PyInferTypeOpInterface::pyClassName = "InferTypeOpInterface" static
Definition at line 163 of file IRInterfaces.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRInterfaces.cpp