MLIR: mlir::AsmPrinter Class Reference
mlir::AsmPrinter Class Reference
This base class exposes generic asm printer hooks, usable across the various derived printers.
#include "mlir/IR/OpImplementation.h"
Classes
class Impl
Public Types
template<typename AttrOrType >
using has_print_method = decltype(std::declval< AttrOrType >().print(std::declval< AsmPrinter & >()))
Trait to check if AttrType provides a print method.
template<typename AttrOrType >
using detect_has_print_method = llvm::is_detected< has_print_method, AttrOrType >
Public Member Functions
AsmPrinter (Impl &impl)
Initialize the printer with the given internal implementation.
virtual ~AsmPrinter ()
virtual raw_ostream & getStream () const
Return the raw output stream used by this printer.
virtual void printFloat (const APFloat &value)
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
virtual void printType (Type type)
virtual void printAttribute (Attribute attr)
template<typename AttrOrType , std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr>
void printStrippedAttrOrType (AttrOrType attrOrType)
Print the provided attribute in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
template<typename AttrOrType , std::enable_if_t<!detect_has_print_method< AttrOrType >::value > * sfinae = nullptr>
void printStrippedAttrOrType (AttrOrType attrOrType)
SFINAE for printing the provided attribute in the context of an operation custom printer in the case where the attribute does not define a print method.
virtual void printAttributeWithoutType (Attribute attr)
Print the given attribute without its type.
virtual void printKeywordOrString (StringRef keyword)
Print the given string as a keyword, or a quoted and escaped string if it has any special or non-printable characters in it.
virtual void printSymbolName (StringRef symbolRef)
Print the given string as a symbol reference, i.e.
template<typename TypeRange >
void printOptionalArrowTypeList (TypeRange &&types)
Print an optional arrow followed by a type list.
template<typename TypeRange >
void printArrowTypeList (TypeRange &&types)
template<typename InputRangeT , typename ResultRangeT >
void printFunctionalType (InputRangeT &&inputs, ResultRangeT &&results)
Print the two given type ranges in a functional form.
Protected Member Functions
AsmPrinter ()
Initialize the printer with no internal implementation.
Detailed Description
This base class exposes generic asm printer hooks, usable across the various derived printers.
Definition at line 32 of file OpImplementation.h.
Member Typedef Documentation
detect_has_print_method
template<typename AttrOrType > using mlir::AsmPrinter::detect_has_print_method = llvm::is_detected<has_print_method, AttrOrType>
Definition at line 59 of file OpImplementation.h.
has_print_method
template<typename AttrOrType > using mlir::AsmPrinter::has_print_method = decltype(std::declval<AttrOrType>().print(std::declval<AsmPrinter &>()))
Trait to check if AttrType provides a print method.
Definition at line 56 of file OpImplementation.h.
Constructor & Destructor Documentation
AsmPrinter() [1/2]
mlir::AsmPrinter::AsmPrinter (Impl & impl) inline
Initialize the printer with the given internal implementation.
Definition at line 39 of file OpImplementation.h.
References getStream(), printAttribute(), printFloat(), printType(), value, and ~AsmPrinter().
~AsmPrinter()
AsmPrinter::~AsmPrinter () virtual default
Referenced by AsmPrinter(), and mlir::AsmPrinter::Impl::printDialectType().
AsmPrinter() [2/2]
mlir::AsmPrinter::AsmPrinter () inline protected
Initialize the printer with no internal implementation.
In this case, all virtual methods of this class must be overriden.
Definition at line 129 of file OpImplementation.h.
References value.
Member Function Documentation
getStream()
raw_ostream & AsmPrinter::getStream () const virtual
Return the raw output stream used by this printer.
Definition at line 2233 of file AsmPrinter.cpp.
Referenced by AsmPrinter(), print(), printArrowTypeList(), printFunctionalType(), printFunctionResultList(), mlir::function_interface_impl::printFunctionSignature(), mlir::OpAsmPrinter::printOperands(), mlir::OpState::printOpName(), and typeOrAttrPrinter().
printArrowTypeList()
template<typename TypeRange > void mlir::AsmPrinter::printArrowTypeList (TypeRange && types) inline
Definition at line 104 of file OpImplementation.h.
References getStream().
Referenced by isIntegerPtxType(), printFunctionalType(), and printOptionalArrowTypeList().
printAttribute()
void AsmPrinter::printAttribute (Attribute attr) virtual
Definition at line 2249 of file AsmPrinter.cpp.
Referenced by AsmPrinter(), and lookupSymbolInModule().
printAttributeWithoutType()
void AsmPrinter::printAttributeWithoutType (Attribute attr) virtual
Print the given attribute without its type.
The corresponding parser must provide a valid type for the attribute.
Definition at line 2264 of file AsmPrinter.cpp.
Referenced by printGlobalMemrefOpTypeAndInitialValue(), and printStrippedAttrOrType().
printFloat()
void AsmPrinter::printFloat (const APFloat & value) virtual
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
Print the given floating point value in a stablized form.
This is the companion to the 'parseFloat' hook on the AsmParser.
Definition at line 2239 of file AsmPrinter.cpp.
References printFloatValue().
Referenced by AsmPrinter().
printFunctionalType()
template<typename InputRangeT , typename ResultRangeT > void mlir::AsmPrinter::printFunctionalType (InputRangeT && inputs, ResultRangeT && results) inline
Print the two given type ranges in a functional form.
Definition at line 118 of file OpImplementation.h.
References getStream(), and printArrowTypeList().
Referenced by mlir::OpAsmPrinter::printOperands().
printKeywordOrString()
void AsmPrinter::printKeywordOrString (StringRef keyword) virtual
Print the given string as a keyword, or a quoted and escaped string if it has any special or non-printable characters in it.
Definition at line 2270 of file AsmPrinter.cpp.
References printKeywordOrString().
Referenced by printStrippedAttrOrType().
printOptionalArrowTypeList()
template<typename TypeRange > void mlir::AsmPrinter::printOptionalArrowTypeList (TypeRange && types) inline
Print an optional arrow followed by a type list.
Definition at line 99 of file OpImplementation.h.
References printArrowTypeList().
Referenced by mlir::scf::insideMutuallyExclusiveBranches(), printNamedStructuredOpResults(), mlir::replaceForOpWithNewYields(), and replaceOpWithRegion().
printStrippedAttrOrType() [1/2]
template<typename AttrOrType , std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr> void mlir::AsmPrinter::printStrippedAttrOrType (AttrOrType attrOrType) inline
Print the provided attribute in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
Definition at line 67 of file OpImplementation.h.
References mlir::succeeded(), and value.
printStrippedAttrOrType() [2/2]
template<typename AttrOrType , std::enable_if_t<!detect_has_print_method< AttrOrType >::value > * sfinae = nullptr> void mlir::AsmPrinter::printStrippedAttrOrType (AttrOrType attrOrType) inline
SFINAE for printing the provided attribute in the context of an operation custom printer in the case where the attribute does not define a print method.
Definition at line 79 of file OpImplementation.h.
References printAttributeWithoutType(), printKeywordOrString(), and printSymbolName().
printSymbolName()
void AsmPrinter::printSymbolName (StringRef symbolRef) virtual
Print the given string as a symbol reference, i.e.
a form representable by a SymbolRefAttr. A symbol reference is represented as a string prefixed with '@'. The reference is surrounded with ""'s and escaped if it has any special or non-printable characters in it.
Definition at line 2275 of file AsmPrinter.cpp.
References printSymbolReference().
Referenced by buildLLVMFunctionType(), getLoadStoreElementType(), hasOneBranchOpTo(), lookupSymbolInModule(), printAttributions(), mlir::function_interface_impl::printFunctionOp(), printStrippedAttrOrType(), verifyAttributions(), verifyConstantType(), and verifyCoopMatrixMulAdd().
printType()
void AsmPrinter::printType (Type type) virtual
Definition at line 2244 of file AsmPrinter.cpp.
Referenced by AsmPrinter(), dispatchPrint(), eachHasOnlyOneOfTypes(), printFunctionResultList(), mlir::function_interface_impl::printFunctionSignature(), and printLaunchFuncOperands().
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/AsmPrinter.cpp