MLIR: mlir::DialectRegistry Class Reference
mlir::DialectRegistry Class Reference
The DialectRegistry maps a dialect namespace to a constructor for the matching dialect.
#include "mlir/IR/DialectRegistry.h"
Public Member Functions
DialectRegistry ()
template<typename ConcreteDialect >
void insert ()
template<typename ConcreteDialect , typename OtherDialect , typename... MoreDialects>
void insert ()
void insert (TypeID typeID, StringRef name, const DialectAllocatorFunction &ctor)
Add a new dialect constructor to the registry.
DialectAllocatorFunctionRef getDialectAllocator (StringRef name) const
Return an allocation function for constructing the dialect identified by its namespace, or nullptr if the namespace is not in this registry.
void appendTo (DialectRegistry &destination) const
auto getDialectNames () const
Return the names of dialects known to this registry.
void applyExtensions (Dialect *dialect) const
Apply any held extensions that require the given dialect.
void applyExtensions (MLIRContext *ctx) const
Apply any applicable extensions to the given context.
void addExtension (std::unique_ptr< DialectExtensionBase > extension)
Add the given extension to the registry.
template<typename... ExtensionsT>
void addExtensions ()
Add the given extensions to the registry.
template<typename... DialectsT>
void addExtension (void(*extensionFn)(MLIRContext *, DialectsT *...))
Add an extension function that requires the given dialects.
template<typename... DialectsT>
void addExtension (std::function< void(MLIRContext *, DialectsT *...)> extensionFn)
bool isSubsetOf (const DialectRegistry &rhs) const
Returns true if the current registry is a subset of 'rhs', i.e.
Detailed Description
The DialectRegistry maps a dialect namespace to a constructor for the matching dialect.
This allows for decoupling the list of dialects "available" from the dialects loaded in the Context. The parser in particular will lazily load dialects in the Context as operations are encountered.
Definition at line 108 of file DialectRegistry.h.
Constructor & Destructor Documentation
DialectRegistry()
DialectRegistry::DialectRegistry () explicit
Definition at line 145 of file Dialect.cpp.
Member Function Documentation
addExtension() [1/3]
void mlir::DialectRegistry::addExtension (std::unique_ptr< DialectExtensionBase > extension) inline
Add the given extension to the registry.
Definition at line 171 of file DialectRegistry.h.
Referenced by mlir::bufferization::registerAllocationOpInterfaceExternalModels(), mlir::registerAMXDialectTranslation(), mlir::registerArmNeonDialectTranslation(), mlir::registerArmSVEDialectTranslation(), mlir::shape::registerBufferizableOpInterfaceExternalModels(), mlir::tensor::registerBufferizableOpInterfaceExternalModels(), mlir::scf::registerBufferizableOpInterfaceExternalModels(), mlir::vector::registerBufferizableOpInterfaceExternalModels(), mlir::arith::registerBufferizableOpInterfaceExternalModels(), mlir::linalg::registerBufferizableOpInterfaceExternalModels(), mlir::bufferization::func_ext::registerBufferizableOpInterfaceExternalModels(), mlir::tensor::registerInferTypeOpInterfaceExternalModels(), mlir::registerLLVMDialectTranslation(), mlir::registerNVVMDialectTranslation(), mlir::registerOpenACCDialectTranslation(), mlir::registerOpenMPDialectTranslation(), mlir::registerROCDLDialectTranslation(), mlir::tensor::registerTilingOpInterfaceExternalModels(), and mlir::registerX86VectorDialectTranslation().
addExtension() [2/3]
template<typename... DialectsT> void mlir::DialectRegistry::addExtension (void(*)(MLIRContext *, DialectsT *...) extensionFn) inline
Add an extension function that requires the given dialects.
Note: This bare functor overload is provided in addition to the std::function variant to enable dialect type deduction, e.g.: registry.addExtension(+[](MLIRContext *ctx, MyDialect *dialect) { ... })
is equivalent to: registry.addExtension<MyDialect>([](MLIRContext *ctx, MyDialect *dialect){ ... })
Definition at line 192 of file DialectRegistry.h.
addExtension() [3/3]
template<typename... DialectsT> void mlir::DialectRegistry::addExtension (std::function< void(MLIRContext *, DialectsT *...)> extensionFn) inline
Definition at line 198 of file DialectRegistry.h.
References mlir::DialectExtensionBase::apply().
addExtensions()
template<typename... ExtensionsT> void mlir::DialectRegistry::addExtensions () inline
Add the given extensions to the registry.
Definition at line 177 of file DialectRegistry.h.
Referenced by mlir::linalg::registerTransformDialectExtension().
appendTo()
void mlir::DialectRegistry::appendTo (DialectRegistry & destination) const inline
Definition at line 145 of file DialectRegistry.h.
References insert().
Referenced by mlir::MLIRContext::appendDialectRegistry(), and mlir::MLIRContext::MLIRContext().
applyExtensions() [1/2]
void DialectRegistry::applyExtensions (Dialect * dialect) const
Apply any held extensions that require the given dialect.
Users are not expected to call this directly.
Definition at line 166 of file Dialect.cpp.
References mlir::Dialect::getContext(), mlir::MLIRContext::getLoadedDialect(), and mlir::Dialect::getNamespace().
Referenced by mlir::MLIRContext::appendDialectRegistry().
applyExtensions() [2/2]
void DialectRegistry::applyExtensions (MLIRContext * ctx) const
Apply any applicable extensions to the given context.
Users are not expected to call this directly.
Definition at line 211 of file Dialect.cpp.
References mlir::MLIRContext::getLoadedDialect().
getDialectAllocator()
DialectAllocatorFunctionRef DialectRegistry::getDialectAllocator (StringRef name) const
Return an allocation function for constructing the dialect identified by its namespace, or nullptr if the namespace is not in this registry.
Definition at line 148 of file Dialect.cpp.
getDialectNames()
auto mlir::DialectRegistry::getDialectNames () const inline
Return the names of dialects known to this registry.
Definition at line 156 of file DialectRegistry.h.
Referenced by mlir::MlirOptMain().
insert() [1/3]
template<typename ConcreteDialect > void mlir::DialectRegistry::insert () inline
Definition at line 116 of file DialectRegistry.h.
References mlir::MLIRContext::getOrLoadDialect().
Referenced by appendTo(), linalgOpToLoopsImpl(), mlir::bufferization::populateEliminateBufferizeMaterializationsPatterns(), mlir::registerAllDialects(), mlir::registerAMXDialectTranslation(), mlir::registerArmNeonDialectTranslation(), mlir::registerArmSVEDialectTranslation(), mlir::registerLLVMDialectTranslation(), mlir::registerNVVMDialectTranslation(), mlir::registerOpenACCDialectTranslation(), mlir::registerOpenMPDialectTranslation(), mlir::registerROCDLDialectTranslation(), mlir::registerX86VectorDialectTranslation(), and validateSupportedControlFlow().
insert() [2/3]
template<typename ConcreteDialect , typename OtherDialect , typename... MoreDialects> void mlir::DialectRegistry::insert () inline
Definition at line 128 of file DialectRegistry.h.
insert() [3/3]
void DialectRegistry::insert (TypeID typeID, StringRef name, const DialectAllocatorFunction & ctor)
Add a new dialect constructor to the registry.
The constructor must be calling MLIRContext::getOrLoadDialect in order for the context to take ownership of the dialect and for delayed interface registration to happen.
Definition at line 155 of file Dialect.cpp.
isSubsetOf()
bool DialectRegistry::isSubsetOf (const DialectRegistry & rhs) const
Returns true if the current registry is a subset of 'rhs', i.e.
if 'rhs' contains all of the components of this registry.
Definition at line 232 of file Dialect.cpp.
Referenced by mlir::MLIRContext::appendDialectRegistry().
The documentation for this class was generated from the following files:
include/mlir/IR/DialectRegistry.h
lib/IR/Dialect.cpp