MLIR: mlir::tblgen::VisibilityDeclaration Class Reference
mlir::tblgen::VisibilityDeclaration Class Reference
A declaration for the visibility of subsequent declarations.
#include "mlir/TableGen/Class.h"
Public Member Functions
VisibilityDeclaration (Visibility visibility)
Create a declaration for the given visibility.
Visibility getVisibility () const
Get the visibility.
void writeDeclTo (raw_indented_ostream &os) const override
Write the visibility declaration.
Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::VisibilityDeclaration >
ClassDeclarationBase ()
Public Member Functions inherited from mlir::tblgen::ClassDeclaration
virtual ~ClassDeclaration ()=default
ClassDeclaration (Kind kind)
Create a class declaration with a given kind.
Kind getKind () const
Get the class declaration kind.
virtual void writeDefTo (raw_indented_ostream &os, StringRef namePrefix) const
Write the definition, if any.
Additional Inherited Members
Public Types inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::VisibilityDeclaration >
using Base = ClassDeclarationBase< DeclKind >
Public Types inherited from mlir::tblgen::ClassDeclaration
enum Kind {
Method, UsingDeclaration, VisibilityDeclaration, Field,
ExtraClassDeclaration
}
Kinds for LLVM-style RTTI.
Static Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::VisibilityDeclaration >
static bool classof (const ClassDeclaration *other)
Detailed Description
A declaration for the visibility of subsequent declarations.
Definition at line 518 of file Class.h.
Constructor & Destructor Documentation
VisibilityDeclaration()
mlir::tblgen::VisibilityDeclaration::VisibilityDeclaration (Visibility visibility) inline
Create a declaration for the given visibility.
Definition at line 522 of file Class.h.
Member Function Documentation
getVisibility()
Visibility mlir::tblgen::VisibilityDeclaration::getVisibility () const inline
Get the visibility.
Definition at line 525 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo().
writeDeclTo()
void VisibilityDeclaration::writeDeclTo (raw_indented_ostream & os) const override virtual
Write the visibility declaration.
Implements mlir::tblgen::ClassDeclaration.
Definition at line 249 of file Class.cpp.
References mlir::raw_indented_ostream::indent(), and mlir::raw_indented_ostream::unindent().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp