MLIR: mlir::pdll::ast::VariableDecl Class Reference
mlir::pdll::ast::VariableDecl Class Reference final
This Decl represents the definition of a PDLL variable.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
MutableArrayRef< ConstraintRef > getConstraints ()
Return the constraints of this variable.
ArrayRef< ConstraintRef > getConstraints () const
Expr * getInitExpr () const
Return the initializer expression of this statement, or nullptr if there was no initializer.
const Name & getName () const
Return the name of the decl.
Type getType () const
Return the type of the decl.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static VariableDecl * create (Context &ctx, const Name &name, Type type, Expr *initExpr, ArrayRef< ConstraintRef > constraints)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< VariableDecl, Decl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< VariableDecl, Decl >
using Base = NodeBase< VariableDecl, Decl >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< VariableDecl, Decl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This Decl represents the definition of a PDLL variable.
Definition at line 1159 of file Nodes.h.
Member Function Documentation
create()
VariableDecl * VariableDecl::create (Context & ctx, const Name & name, Type type, Expr * initExpr, ArrayRef< ConstraintRef > constraints) static
Definition at line 512 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), and getConstraints().
getConstraints() [1/2]
MutableArrayRef<ConstraintRef> mlir::pdll::ast::VariableDecl::getConstraints () inline
Return the constraints of this variable.
Definition at line 1168 of file Nodes.h.
Referenced by checkAndNestUnderRewriteOp(), mlir::pdll::ast::Name::create(), and create().
getConstraints() [2/2]
ArrayRef<ConstraintRef> mlir::pdll::ast::VariableDecl::getConstraints () const inline
Definition at line 1171 of file Nodes.h.
getInitExpr()
Expr* mlir::pdll::ast::VariableDecl::getInitExpr () const inline
Return the initializer expression of this statement, or nullptr if there was no initializer.
Definition at line 1177 of file Nodes.h.
Referenced by checkAndNestUnderRewriteOp(), and mlir::pdll::ast::Name::create().
getName()
const Name& mlir::pdll::ast::VariableDecl::getName () const inline
Return the name of the decl.
Definition at line 1180 of file Nodes.h.
References mlir::pdll::ast::Decl::getName().
Referenced by getLspDiagnoticFromDiag().
getType()
Type mlir::pdll::ast::VariableDecl::getType () const inline
Return the type of the decl.
Definition at line 1183 of file Nodes.h.
References mlir::pdll::ast::Name::getLoc().
Referenced by checkAndNestUnderRewriteOp(), and getLspDiagnoticFromDiag().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp