MLIR: lib/Interfaces/ControlFlowInterfaces.cpp File Reference
ControlFlowInterfaces.cpp File Reference
#include <utility>
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "mlir/Interfaces/ControlFlowInterfaces.cpp.inc"
Functions
static LogicalResult verifyTypesAlongAllEdges (Operation *op, Optional< unsigned > sourceNo, function_ref< Optional< TypeRange >(Optional< unsigned >)> getInputsTypesForRegion)
Verify that types match along all region control flow edges originating from sourceNo (region # if source is a region, llvm::None if source is parent op).
static bool isRegionReachable (Region *begin, Region *r)
Return true if region r is reachable from region begin according to the RegionBranchOpInterface (by taking a branch).
Function Documentation
isRegionReachable()
static bool isRegionReachable (Region * begin, Region * r) static
Return true if region r is reachable from region begin according to the RegionBranchOpInterface (by taking a branch).
Definition at line 245 of file ControlFlowInterfaces.cpp.
References mlir::Region::getParentOp(), and mlir::Region::getRegionNumber().
Referenced by mlir::insideMutuallyExclusiveRegions().
verifyTypesAlongAllEdges()
static LogicalResult verifyTypesAlongAllEdges (Operation * op, Optional< unsigned > sourceNo, function_ref< Optional< TypeRange >(Optional< unsigned >)> getInputsTypesForRegion) static
Verify that types match along all region control flow edges originating from sourceNo (region # if source is a region, llvm::None if source is parent op).
getInputsTypesForRegion is a function that returns the types of the inputs that flow from `sourceIndex' to the given region, or llvm::None if the exact type match verification is not necessary (e.g., if the Op verifies the match itself).
Definition at line 94 of file ControlFlowInterfaces.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::Region::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getRegion(), and mlir::success().
Referenced by mlir::detail::verifyTypesAlongControlFlowEdges().