MLIR: lib/Dialect/ControlFlow/IR/ControlFlowOps.cpp File Reference
ControlFlowOps.cpp File Reference
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include <numeric>
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOpsDialect.cpp.inc"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult collapseBranch (Block *&successor, ValueRange &successorOperands, SmallVectorImpl< Value > &argStorage)
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter &rewriter)
Simplify a branch to a block that has a single predecessor.
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter &rewriter)
br ^bb1 ^bb1 br ^bbN(...)
static ParseResult parseSwitchOpCases (OpAsmParser &parser, Type &flagType, Block *&defaultDestination, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &defaultOperands, SmallVectorImpl< Type > &defaultOperandTypes, DenseIntElementsAttr &caseValues, SmallVectorImpl< Block *> &caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::UnresolvedOperand >> &caseOperands, SmallVectorImpl< SmallVector< Type >> &caseOperandTypes)
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
static void printSwitchOpCases (OpAsmPrinter &p, SwitchOp op, Type flagType, Block *defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, const TypeRangeRange &caseOperandTypes)
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
static void foldSwitch (SwitchOp op, PatternRewriter &rewriter, const APInt &caseValue)
Helper for folding a switch with a constant value.
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 890 of file ControlFlowOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
collapseBranch()
static LogicalResult collapseBranch (Block *& successor, ValueRange & successorOperands, SmallVectorImpl< Value > & argStorage) static
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
If the successor is collapsable, successor and successorOperands are updated to reference the new destination and values. argStorage is used as storage if operands to the collapsed successor need to be remapped. It must outlive uses of successorOperands.
Definition at line 98 of file ControlFlowOps.cpp.
References mlir::Block::args_empty(), mlir::Block::begin(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::failure(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArguments(), mlir::BlockArgument::getOwner(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), and mlir::success().
Referenced by simplifyPassThroughBr(), and simplifyPassThroughSwitch().
dropSwitchCasesThatMatchDefault()
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
Definition at line 625 of file ControlFlowOps.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
foldSwitch()
static void foldSwitch (SwitchOp op, PatternRewriter & rewriter, const APInt & caseValue) static
Helper for folding a switch with a constant value.
switch c_42 : i32, [ default: ^bb1 , 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 660 of file ControlFlowOps.cpp.
References mlir::detail::enumerate(), and mlir::RewriterBase::replaceOpWithNewOp().
Referenced by simplifyConstSwitchValue(), and simplifySwitchFromSwitchOnSameCondition().
parseSwitchOpCases()
static ParseResult parseSwitchOpCases (OpAsmParser & parser, Type & flagType, Block *& defaultDestination, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & defaultOperands, SmallVectorImpl< Type > & defaultOperandTypes, DenseIntElementsAttr & caseValues, SmallVectorImpl< Block *> & caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::UnresolvedOperand >> & caseOperands, SmallVectorImpl< SmallVector< Type >> & caseOperandTypes) static
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
Definition at line 480 of file ControlFlowOps.cpp.
References mlir::failed(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::Type::getIntOrFloatBitWidth(), mlir::AsmParser::None, mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::parseSuccessor(), mlir::succeeded(), and mlir::success().
printSwitchOpCases()
static void printSwitchOpCases (OpAsmPrinter & p, SwitchOp op, Type flagType, Block * defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, const TypeRangeRange & caseOperandTypes) static
Definition at line 532 of file ControlFlowOps.cpp.
References mlir::detail::enumerate(), mlir::OpAsmPrinter::printNewline(), mlir::OpAsmPrinter::printSuccessorAndUseList(), mlir::success(), and mlir::verify().
simplifyBrToBlockWithSinglePred()
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter & rewriter) static
Simplify a branch to a block that has a single predecessor.
This effectively merges the two blocks.
Definition at line 144 of file ControlFlowOps.cpp.
References mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::getPredecessors(), mlir::RewriterBase::mergeBlocks(), and mlir::success().
Referenced by simplifyPassThroughBr().
simplifyConstSwitchValue()
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 681 of file ControlFlowOps.cpp.
References mlir::failure(), foldSwitch(), mlir::m_ConstantInt(), mlir::matchPattern(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifyPassThroughBr()
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter & rewriter) static
br ^bb1 ^bb1 br ^bbN(...)
-> br ^bbN(...)
Definition at line 163 of file ControlFlowOps.cpp.
References mlir::RewritePatternSet::add(), collapseBranch(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getBoolAttr(), mlir::Builder::getI1Type(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Block::getUniquePredecessor(), mlir::m_NonZero(), mlir::m_Zero(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyBrToBlockWithSinglePred(), mlir::succeeded(), mlir::success(), mlir::RewriterBase::updateRootInPlace(), and value.
simplifyPassThroughSwitch()
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
Definition at line 702 of file ControlFlowOps.cpp.
References collapseBranch(), mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchFromDefaultSwitchOnSameCondition()
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
Definition at line 826 of file ControlFlowOps.cpp.
References mlir::RewritePatternSet::add(), dropSwitchCasesThatMatchDefault(), mlir::detail::enumerate(), mlir::failure(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyConstSwitchValue(), simplifyPassThroughSwitch(), simplifySwitchFromSwitchOnSameCondition(), simplifySwitchWithOnlyDefault(), and mlir::success().
simplifySwitchFromSwitchOnSameCondition()
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
and
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 43: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3
Definition at line 775 of file ControlFlowOps.cpp.
References mlir::failure(), foldSwitch(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchWithOnlyDefault()
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
Definition at line 604 of file ControlFlowOps.cpp.
References mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().