MLIR: lib/Dialect/SPIRV/Transforms/DecorateCompositeTypeLayoutPass.cpp File Reference
DecorateCompositeTypeLayoutPass.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static void populateSPIRVLayoutInfoPatterns (RewritePatternSet &patterns)
Function Documentation
populateSPIRVLayoutInfoPatterns()
static void populateSPIRVLayoutInfoPatterns (RewritePatternSet & patterns) static
Definition at line 91 of file DecorateCompositeTypeLayoutPass.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), mlir::applyFullConversion(), mlir::failed(), mlir::RewritePatternSet::getContext(), and mlir::VulkanLayoutUtils::isLegalType().