MLIR: lib/Transforms/Utils/DialectConversion.cpp File Reference
DialectConversion.cpp File Reference
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "mlir/Rewrite/PatternApplicator.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/ScopedPrinter.h"
Classes
struct mlir::detail::ConversionPatternRewriterImpl
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Macros
#define DEBUG_TYPE "dialect-conversion"
Enumerations
enum BlockActionKind
The kind of the block action performed during the rewrite.
enum OpConversionMode
Functions
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, SmallVectorImpl< Operation *> &toConvert, ConversionTarget *target=nullptr)
Recursively collect all of the operations to convert from within 'region'.
template<typename... Args>
static void logSuccess (llvm::ScopedPrinter &os, StringRef fmt, Args &&...args)
A utility function to log a successful result for the given reason.
template<typename... Args>
static void logFailure (llvm::ScopedPrinter &os, StringRef fmt, Args &&...args)
A utility function to log a failure result for the given reason.
static Value buildUnresolvedMaterialization (UnresolvedMaterialization::Kind kind, Block *insertBlock, Block::iterator insertPt, Location loc, ValueRange inputs, Type outputType, Type origOutputType, TypeConverter *converter, SmallVectorImpl< UnresolvedMaterialization > &unresolvedMaterializations)
Build an unresolved materialization operation given an output type and set of input operands.
static Value buildUnresolvedArgumentMaterialization (PatternRewriter &rewriter, Location loc, ValueRange inputs, Type origOutputType, Type outputType, TypeConverter *converter, SmallVectorImpl< UnresolvedMaterialization > &unresolvedMaterializations)
static Value buildUnresolvedTargetMaterialization (Location loc, Value input, Type outputType, TypeConverter *converter, SmallVectorImpl< UnresolvedMaterialization > &unresolvedMaterializations)
static void detachNestedAndErase (Operation *op)
Detach any operations nested in the given operation from their parent blocks, and erase the given operation.
static void replaceMaterialization (ConversionPatternRewriterImpl &rewriterImpl, ResultRange matResults, ValueRange values, DenseMap< Value, SmallVector< Value >> &inverseMapping)
Replace the results of a materialization operation with the given values.
static void computeNecessaryMaterializations (DenseMap< Operation *, UnresolvedMaterialization *> &materializationOps, ConversionPatternRewriter &rewriter, ConversionPatternRewriterImpl &rewriterImpl, DenseMap< Value, SmallVector< Value >> &inverseMapping, SetVector< UnresolvedMaterialization *> &necessaryMaterializations)
Compute all of the unresolved materializations that will persist beyond the conversion process, and require inserting a proper user materialization for.
static LogicalResult legalizeUnresolvedMaterialization (UnresolvedMaterialization &mat, DenseMap< Operation *, UnresolvedMaterialization *> &materializationOps, ConversionPatternRewriter &rewriter, ConversionPatternRewriterImpl &rewriterImpl, DenseMap< Value, SmallVector< Value >> &inverseMapping)
Legalize the given unresolved materialization.
static Operation * findLiveUserOfReplaced (Value initialValue, ConversionPatternRewriterImpl &rewriterImpl, const DenseMap< Value, SmallVector< Value >> &inverseMapping)
Finds a user of the given value, or of any other value that the given value replaced, that was not replaced in the conversion process.
static ConversionTarget::DynamicLegalityCallbackFn composeLegalityCallbacks (ConversionTarget::DynamicLegalityCallbackFn oldCallback, ConversionTarget::DynamicLegalityCallbackFn newCallback)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dialect-conversion"
Definition at line 27 of file DialectConversion.cpp.
Enumeration Type Documentation
BlockActionKind
enum BlockActionKind strong
The kind of the block action performed during the rewrite.
Actions can be undone if the conversion fails.
Definition at line 287 of file DialectConversion.cpp.
OpConversionMode
enum OpConversionMode
Definition at line 2329 of file DialectConversion.cpp.
Function Documentation
buildUnresolvedArgumentMaterialization()
static Value buildUnresolvedArgumentMaterialization (PatternRewriter & rewriter, Location loc, ValueRange inputs, Type origOutputType, Type outputType, TypeConverter * converter, SmallVectorImpl< UnresolvedMaterialization > & unresolvedMaterializations) static
Definition at line 432 of file DialectConversion.cpp.
References buildUnresolvedMaterialization(), mlir::OpBuilder::getInsertionBlock(), and mlir::OpBuilder::getInsertionPoint().
Referenced by buildUnresolvedTargetMaterialization().
buildUnresolvedMaterialization()
static Value buildUnresolvedMaterialization (UnresolvedMaterialization::Kind kind, Block * insertBlock, Block::iterator insertPt, Location loc, ValueRange inputs, Type outputType, Type origOutputType, TypeConverter * converter, SmallVectorImpl< UnresolvedMaterialization > & unresolvedMaterializations) static
Build an unresolved materialization operation given an output type and set of input operands.
Definition at line 414 of file DialectConversion.cpp.
Referenced by buildUnresolvedArgumentMaterialization(), and buildUnresolvedTargetMaterialization().
buildUnresolvedTargetMaterialization()
static Value buildUnresolvedTargetMaterialization (Location loc, Value input, Type outputType, TypeConverter * converter, SmallVectorImpl< UnresolvedMaterialization > & unresolvedMaterializations) static
Definition at line 441 of file DialectConversion.cpp.
References mlir::Block::addArguments(), mlir::InFlightDiagnostic::attachNote(), mlir::Block::begin(), buildUnresolvedArgumentMaterialization(), buildUnresolvedMaterialization(), mlir::TypeConverter::convertBlockSignature(), mlir::TypeConverter::convertType(), diag(), mlir::Value::dropAllUses(), mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Value::dyn_cast(), mlir::emitError(), mlir::Block::end(), mlir::Block::erase(), mlir::failure(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Region::getBlocks(), mlir::TypeConverter::SignatureConversion::getConvertedTypes(), mlir::TypeConverter::SignatureConversion::getInputMapping(), mlir::Operation::getLoc(), mlir::BlockArgument::getLoc(), mlir::Block::getNumArguments(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Value::getType(), mlir::Block::moveBefore(), mlir::Value::replaceAllUsesWith(), mlir::IRObjectWithUseList< OperandType >::replaceAllUsesWith(), mlir::Block::splitBlock(), mlir::success(), and mlir::Value::use_empty().
Referenced by mlir::detail::ConversionPatternRewriterImpl::remapValues().
composeLegalityCallbacks()
static ConversionTarget::DynamicLegalityCallbackFn composeLegalityCallbacks (ConversionTarget::DynamicLegalityCallbackFn oldCallback, ConversionTarget::DynamicLegalityCallbackFn newCallback) static
Definition at line 3178 of file DialectConversion.cpp.
Referenced by mlir::ConversionTarget::markOpRecursivelyLegal().
computeConversionSet()
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, SmallVectorImpl< Operation *> & toConvert, ConversionTarget * target = nullptr) static
Recursively collect all of the operations to convert from within 'region'.
If 'target' is nonnull, operations that are recursively legal have their regions pre-filtered to avoid considering them for legalization.
Definition at line 33 of file DialectConversion.cpp.
References mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Block::getSuccessors(), and mlir::success().
Referenced by mlir::detail::ConversionPatternRewriterImpl::notifyRegionWasClonedBefore().
computeNecessaryMaterializations()
static void computeNecessaryMaterializations (DenseMap< Operation *, UnresolvedMaterialization *> & materializationOps, ConversionPatternRewriter & rewriter, ConversionPatternRewriterImpl & rewriterImpl, DenseMap< Value, SmallVector< Value >> & inverseMapping, SetVector< UnresolvedMaterialization *> & necessaryMaterializations) static
Compute all of the unresolved materializations that will persist beyond the conversion process, and require inserting a proper user materialization for.
Definition at line 2578 of file DialectConversion.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), mlir::OperandRange::getTypes(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), mlir::detail::ConversionPatternRewriterImpl::mapping, replaceMaterialization(), mlir::detail::ConversionPatternRewriterImpl::unresolvedMaterializations, and value.
Referenced by legalizeUnresolvedMaterialization().
detachNestedAndErase()
static void detachNestedAndErase (Operation * op) static
Detach any operations nested in the given operation from their parent blocks, and erase the given operation.
This can be used when the nested operations are scheduled for erasure themselves, so deleting the regions of the given operation together with their content would result in double-free. This happens, for example, when rolling back op creation in the reverse order and if the nested ops were created before the parent op. This function does not need to collect nested ops recursively because it is expected to also be called for each nested op when it is about to be deleted.
Definition at line 1035 of file DialectConversion.cpp.
References mlir::Block::dropAllDefinedValueUses(), mlir::Operation::dropAllUses(), mlir::Operation::erase(), mlir::Block::getOperations(), and mlir::Operation::getRegions().
Referenced by mlir::detail::ConversionPatternRewriterImpl::discardRewrites(), and mlir::detail::ConversionPatternRewriterImpl::resetState().
findLiveUserOfReplaced()
static Operation* findLiveUserOfReplaced (Value initialValue, ConversionPatternRewriterImpl & rewriterImpl, const DenseMap< Value, SmallVector< Value >> & inverseMapping) static
Finds a user of the given value, or of any other value that the given value replaced, that was not replaced in the conversion process.
Definition at line 2855 of file DialectConversion.cpp.
References mlir::InFlightDiagnostic::attachNote(), diag(), mlir::Operation::emitError(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), mlir::detail::ConversionPatternRewriterImpl::mapping, mlir::TypeConverter::materializeSourceConversion(), mlir::success(), mlir::Value::user_end(), and value.
legalizeUnresolvedMaterialization()
static LogicalResult legalizeUnresolvedMaterialization (UnresolvedMaterialization & mat, DenseMap< Operation *, UnresolvedMaterialization *> & materializationOps, ConversionPatternRewriter & rewriter, ConversionPatternRewriterImpl & rewriterImpl, DenseMap< Value, SmallVector< Value >> & inverseMapping) static
Legalize the given unresolved materialization.
Returns success if the materialization was legalized, failure otherise.
Definition at line 2696 of file DialectConversion.cpp.
References mlir::InFlightDiagnostic::attachNote(), computeNecessaryMaterializations(), diag(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Value::getDefiningOp(), mlir::Operation::getName(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::OperandRange::getTypes(), mlir::Value::getUsers(), mlir::detail::ConversionPatternRewriterImpl::ignoredOps, mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), mlir::detail::ConversionPatternRewriterImpl::mapping, mlir::TypeConverter::materializeArgumentConversion(), mlir::TypeConverter::materializeTargetConversion(), replaceMaterialization(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfterValue(), mlir::success(), mlir::detail::ConversionPatternRewriterImpl::unresolvedMaterializations, mlir::Value::user_end(), and value.
logFailure()
template<typename... Args> static void logFailure (llvm::ScopedPrinter & os, StringRef fmt, Args &&... args) static
A utility function to log a failure result for the given reason.
Definition at line 92 of file DialectConversion.cpp.
References mlir::detail::enumerate(), mlir::Operation::getAttrDictionary(), mlir::Operation::getLoc(), mlir::Value::getType(), mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::Operation::setAttrs(), mlir::Operation::setLoc(), mlir::Operation::setOperands(), mlir::Operation::setSuccessor(), mlir::Operation::successor_begin(), mlir::Operation::successor_end(), and value.
Referenced by mlir::ConversionPattern::matchAndRewrite().
logSuccess()
template<typename... Args> static void logSuccess (llvm::ScopedPrinter & os, StringRef fmt, Args &&... args) static
A utility function to log a successful result for the given reason.
Definition at line 79 of file DialectConversion.cpp.
Referenced by mlir::ConversionPattern::matchAndRewrite().
replaceMaterialization()
static void replaceMaterialization (ConversionPatternRewriterImpl & rewriterImpl, ResultRange matResults, ValueRange values, DenseMap< Value, SmallVector< Value >> & inverseMapping) static
Replace the results of a materialization operation with the given values.
Definition at line 2550 of file DialectConversion.cpp.
References mlir::detail::ConversionPatternRewriterImpl::mapping, and mlir::ResultRange::replaceAllUsesWith().
Referenced by computeNecessaryMaterializations(), and legalizeUnresolvedMaterialization().