MLIR: lib/Dialect/Linalg/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Arithmetic/Utils/Utils.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tensor/Utils/Utils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
Macros
#define DEBUG_TYPE "linalg-utils"
Functions
static bool isZero (Value v)
static bool isTiled (AffineExpr expr, ValueRange tileSizes)
static bool isTiled (AffineMap map, ValueRange tileSizes)
static void unpackRanges (ArrayRef< Range > ranges, SmallVectorImpl< Value > &lbs, SmallVectorImpl< Value > &ubs, SmallVectorImpl< Value > &steps)
Given a list of subview ranges, extract individual values for lower, upper bounds and steps and put them into the corresponding vectors.
bool mlir::linalg::isPermutation (ArrayRef< int64_t > permutation)
Check if permutation is a permutation of the range [0, permutation.size()).
Value mlir::linalg::createOrFoldDimOp (OpBuilder &b, Location loc, Value source, int64_t dim)
Helper function that creates a memref::DimOp or tensor::DimOp depending on the type of source.
SmallVector< Value, 4 > mlir::linalg::getDynOperands (Location loc, Value val, OpBuilder &b)
Given an operation, retrieves the value of each dynamic dimension through constructing the necessary DimOp operators.
void mlir::linalg::getUpperBoundForIndex (Value value, AffineMap &boundMap, SmallVectorImpl< Value > &boundOperands)
Computes an upper bound for the result value of an index computation.
FailureOr< int64_t > mlir::linalg::getConstantUpperBoundForIndex (Value value)
Returns a constant upper bound for the result value of an index computation.
tensor::ExtractSliceOp mlir::linalg::makeComposedExtractSliceOp (OpBuilder &b, Location loc, Value source, ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
Create an ExtractSliceOp and, if source is defined by an ExtractSliceOp, fold it by adding the offsets.
Value mlir::linalg::makeComposedPadHighOp (OpBuilder &b, Location loc, RankedTensorType type, Value source, Value pad, bool nofold)
Create a tensor::PadOp that pads source to the size of the statically sized type whose static sizes are assumed to be greater than the dynamic source size.
GenericOp mlir::linalg::makeTransposeOp (OpBuilder &b, Location loc, Value inputTensor, Value outputTensor, ArrayRef< int64_t > transposeVector)
Returns a GenericOp that tansposes inputTensor into outputTensor using transposeVector to permute the inputTensor dimensions.
GenericOp mlir::linalg::makeMemRefCopyOp (OpBuilder &b, Location loc, Value from, Value to)
Returns GenericOp that copies an n-D memref.
void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
static void mlir::linalg::generateParallelLoopNest (OpBuilder &b, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage, ArrayRef< DistributionMethod > distributionMethod={})
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
static Value mlir::linalg::fullyComposeAndAffineApply (OpBuilder &b, Location loc, AffineExpr expr, ValueRange operands)
Value mlir::linalg::makeTiledShape (OpBuilder &builder, Location loc, Value valueToTile, ValueRange tileSizes, AffineMap map, ValueRange lbs, ValueRange ubs, ValueRange subShapeSizes, bool omitPartialTileCheck)
Creates an extract_slice/subview op for a single valueToTile with builder.
SmallVector< Value > mlir::linalg::computeTileOffsets (OpBuilder &b, Location loc, ValueRange ivs, ValueRange tileSizes)
Compute tile offsets, given a list of loop ivs and tileSizes.
SmallVector< Value > mlir::linalg::computeTileSizes (OpBuilder &b, Location loc, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Compute tile sizes, given a list of loop ivs, tileSizes and dimension sizes (sizeBounds).
SmallVector< Value, 4 > mlir::linalg::makeTiledShapes (OpBuilder &builder, Location loc, LinalgOp linalgOp, ArrayRef< Value > valuesToTile, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds, bool omitPartialTileCheck)
Creates extract_slice/subview ops for all valuesToTile of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
void mlir::linalg::addTileLoopIvsToIndexOpResults (OpBuilder &b, LinalgOp tiledOp, ArrayRef< Value > ivs)
Add the tile loop induction variables ivs to the IndexOp results found in the body of the tiledOp to account for the tile offset.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-utils"
Definition at line 37 of file Utils.cpp.
Function Documentation
isTiled() [1/2]
static bool isTiled (AffineExpr expr, ValueRange tileSizes) static
Definition at line 79 of file Utils.cpp.
Referenced by mlir::linalg::computeTileOffsets(), mlir::linalg::computeTileSizes(), isTiled(), isZero(), mlir::linalg::makeTiledShape(), and mlir::linalg::makeTiledShapes().
isTiled() [2/2]
static bool isTiled (AffineMap map, ValueRange tileSizes) static
Definition at line 88 of file Utils.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), and isTiled().
isZero()
static bool isZero (Value v) static
Definition at line 44 of file Utils.cpp.
References mlir::AffineExpr::cast(), mlir::Value::getDefiningOp(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineDimExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), isTiled(), mlir::Mul, and visit().
Referenced by mlir::linalg::computeTileOffsets(), mlir::linalg::computeTileSizes(), and mlir::linalg::makeTiledShapes().
unpackRanges()
static void unpackRanges (ArrayRef< Range > ranges, SmallVectorImpl< Value > & lbs, SmallVectorImpl< Value > & ubs, SmallVectorImpl< Value > & steps) static
Given a list of subview ranges, extract individual values for lower, upper bounds and steps and put them into the corresponding vectors.
Definition at line 131 of file Utils.cpp.
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().