MLIR: lib/Bindings/Python/DialectLinalg.cpp File Reference
DialectLinalg.cpp File Reference
#include "mlir-c/Dialect/Linalg.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
Functions
static void populateDialectLinalgSubmodule (py::module m)
PYBIND11_MODULE (_mlirDialectsLinalg, m)
Function Documentation
populateDialectLinalgSubmodule()
static void populateDialectLinalgSubmodule (py::module m) static
Definition at line 15 of file DialectLinalg.cpp.
References mlirLinalgFillBuiltinNamedOpRegion().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_mlirDialectsLinalg , m)
Definition at line 24 of file DialectLinalg.cpp.
References populateDialectLinalgSubmodule().