MLIR: lib/CAPI/IR/DialectHandle.cpp File Reference
DialectHandle.cpp File Reference
#include "mlir/CAPI/Registration.h"
Functions
static const MlirDialectRegistrationHooks * unwrap (MlirDialectHandle handle)
MlirStringRef mlirDialectHandleGetNamespace (MlirDialectHandle handle)
Returns the namespace associated with the provided dialect handle.
void mlirDialectHandleInsertDialect (MlirDialectHandle handle, MlirDialectRegistry registry)
Inserts the dialect associated with the provided dialect handle into the provided dialect registry.
void mlirDialectHandleRegisterDialect (MlirDialectHandle handle, MlirContext ctx)
Registers the dialect associated with the provided dialect handle.
MlirDialect mlirDialectHandleLoadDialect (MlirDialectHandle handle, MlirContext ctx)
Loads the dialect associated with the provided dialect handle.
Function Documentation
mlirDialectHandleGetNamespace()
MlirStringRef mlirDialectHandleGetNamespace (MlirDialectHandle handle)
Returns the namespace associated with the provided dialect handle.
Definition at line 16 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::getNamespaceHook, and unwrap().
mlirDialectHandleInsertDialect()
void mlirDialectHandleInsertDialect (MlirDialectHandle handle, MlirDialectRegistry registry)
Inserts the dialect associated with the provided dialect handle into the provided dialect registry.
Definition at line 20 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::insertHook, and unwrap().
Referenced by mlir::ExternalPass::getDependentDialects(), and mlirDialectHandleRegisterDialect().
mlirDialectHandleLoadDialect()
MlirDialect mlirDialectHandleLoadDialect (MlirDialectHandle handle, MlirContext ctx)
Loads the dialect associated with the provided dialect handle.
Definition at line 32 of file DialectHandle.cpp.
References MlirDialectRegistrationHooks::loadHook, and unwrap().
mlirDialectHandleRegisterDialect()
void mlirDialectHandleRegisterDialect (MlirDialectHandle handle, MlirContext ctx)
Registers the dialect associated with the provided dialect handle.
Definition at line 25 of file DialectHandle.cpp.
References mlirDialectHandleInsertDialect(), unwrap(), and wrap().
unwrap()
static const MlirDialectRegistrationHooks* unwrap (MlirDialectHandle handle) inline static
Definition at line 12 of file DialectHandle.cpp.
References MlirDialectHandle::ptr.
Referenced by mlirDialectHandleGetNamespace(), mlirDialectHandleInsertDialect(), mlirDialectHandleLoadDialect(), and mlirDialectHandleRegisterDialect().