MLIR: lib/Dialect/PDL/IR/PDL.cpp File Reference
PDL.cpp File Reference
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/PDL/IR/PDLOpsDialect.cpp.inc"
#include "mlir/Dialect/PDL/IR/PDLOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool hasBindingUse (Operation *op)
Returns true if the given operation is used by a "binding" pdl operation.
static LogicalResult verifyHasBindingUse (Operation *op)
Returns success if the given operation is not in the main matcher body or is used by a "binding" operation.
static void visit (Operation *op, DenseSet< Operation *> &visited)
Visits all the pdl.operand(s), pdl.result(s), and pdl.operation(s) connected to the given operation.
static ParseResult parseOperationOpAttributes (OpAsmParser &p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &attrOperands, ArrayAttr &attrNamesAttr)
static void printOperationOpAttributes (OpAsmPrinter &p, OperationOp op, OperandRange attrArgs, ArrayAttr attrNames)
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, OperandRange resultTypes)
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
static ParseResult parseResultsValueType (OpAsmParser &p, IntegerAttr index, Type &resultType)
static void printResultsValueType (OpAsmPrinter &p, ResultsOp op, IntegerAttr index, Type resultType)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 498 of file PDL.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
hasBindingUse()
static bool hasBindingUse (Operation * op) static
Returns true if the given operation is used by a "binding" pdl operation.
Definition at line 39 of file PDL.cpp.
References mlir::Operation::getUsers().
Referenced by verifyHasBindingUse().
parseOperationOpAttributes()
static ParseResult parseOperationOpAttributes (OpAsmParser & p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & attrOperands, ArrayAttr & attrNamesAttr) static
Definition at line 144 of file PDL.cpp.
References mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), mlir::succeeded(), and mlir::success().
parseResultsValueType()
static ParseResult parseResultsValueType (OpAsmParser & p, IntegerAttr index, Type & resultType) static
Definition at line 412 of file PDL.cpp.
References mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getType(), mlir::AsmParser::parseArrow(), mlir::AsmParser::parseType(), and mlir::success().
printOperationOpAttributes()
static void printOperationOpAttributes (OpAsmPrinter & p, OperationOp op, OperandRange attrArgs, ArrayAttr attrNames) static
Definition at line 167 of file PDL.cpp.
printResultsValueType()
static void printResultsValueType (OpAsmPrinter & p, ResultsOp op, IntegerAttr index, Type resultType) static
Definition at line 423 of file PDL.cpp.
References mlir::Region::empty(), mlir::success(), mlir::verify(), and verifyHasBindingUse().
verifyHasBindingUse()
static LogicalResult verifyHasBindingUse (Operation * op) static
Returns success if the given operation is not in the main matcher body or is used by a "binding" operation.
On failure, emits an error.
Definition at line 49 of file PDL.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getParentOp(), hasBindingUse(), and mlir::success().
Referenced by printResultsValueType(), verifyResultTypesAreInferrable(), and visit().
verifyResultTypesAreInferrable()
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, OperandRange resultTypes) static
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
Definition at line 180 of file PDL.cpp.
References mlir::WalkResult::advance(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::Operation::getBlock(), mlir::Operation::getDialect(), mlir::Builder::getI16IntegerAttr(), mlir::Operation::getLoc(), mlir::Block::getOps(), mlir::Region::getParentOp(), mlir::Region::getParentRegion(), mlir::Builder::getStringAttr(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), mlir::OperationName::hasInterface(), mlir::WalkResult::interrupt(), mlir::Operation::isBeforeInBlock(), mlir::RegisteredOperationName::lookup(), mlir::OperationName::mightHaveInterface(), mlir::OperationState::regions, mlir::success(), mlir::verify(), verifyHasBindingUse(), visit(), mlir::Region::walk(), and mlir::WalkResult::wasInterrupted().
visit()
static void visit (Operation * op, DenseSet< Operation *> & visited) static
Visits all the pdl.operand(s), pdl.result(s), and pdl.operation(s) connected to the given operation.
Definition at line 62 of file PDL.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::getUsers(), mlir::success(), value, mlir::verify(), and verifyHasBindingUse().
Referenced by computeIterationGraph(), mlir::pdll::ast::Name::create(), isZero(), GpuAsyncRegionPass::ThreadTokenCallback::operator()(), shouldPrintElementsAttrWithHex(), verifyResultTypesAreInferrable(), and HasAffineDimExprVisitor::visitAffineBinaryOpExpr().