MLIR: lib/Dialect/Affine/Analysis/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Affine/Analysis/Utils.h"
#include "mlir/Analysis/Presburger/PresburgerRelation.h"
#include "mlir/Dialect/Affine/Analysis/AffineAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/IR/IntegerSet.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "analysis-utils"
Functions
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType)
static void findInstPosition (Operation *op, Block *limitBlock, SmallVectorImpl< unsigned > *positions)
static Operation * getInstAtPosition (ArrayRef< unsigned > positions, unsigned level, Block *block)
static LogicalResult addMissingLoopIVBounds (SmallPtrSet< Value, 8 > &ivs, FlatAffineValueConstraints *cst)
static Optional< uint64_t > getConstDifference (AffineMap lbMap, AffineMap ubMap)
static Optional< int64_t > getMemoryFootprintBytes (Block &block, Block::iterator start, Block::iterator end, int memorySpace)
Variables
const char *const kSliceFusionBarrierAttrName = "slice_fusion_barrier"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "analysis-utils"
Definition at line 26 of file Utils.cpp.
Function Documentation
addMissingLoopIVBounds()
static LogicalResult addMissingLoopIVBounds (SmallPtrSet< Value, 8 > & ivs, FlatAffineValueConstraints * cst) static
Definition at line 763 of file Utils.cpp.
References mlir::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::failed(), mlir::failure(), mlir::getForInductionVarOwner(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::FlatAffineValueConstraints::getValue(), mlir::isForInductionVar(), mlir::success(), and value.
Referenced by mlir::computeSliceUnion().
findInstPosition()
static void findInstPosition (Operation * op, Block * limitBlock, SmallVectorImpl< unsigned > * positions) static
Definition at line 721 of file Utils.cpp.
References mlir::Block::begin(), mlir::Operation::getBlock(), and mlir::Block::getParentOp().
Referenced by mlir::insertBackwardComputationSlice().
getConstDifference()
static Optional<uint64_t> getConstDifference (AffineMap lbMap, AffineMap ubMap) static
Definition at line 974 of file Utils.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::presburger::None, and mlir::simplifyAffineExpr().
Referenced by mlir::buildSliceTripCountMap().
getInstAtPosition()
static Operation* getInstAtPosition (ArrayRef< unsigned > positions, unsigned level, Block * block) static
Definition at line 738 of file Utils.cpp.
Referenced by mlir::insertBackwardComputationSlice().
getMemoryFootprintBytes()
static Optional<int64_t> getMemoryFootprintBytes (Block & block, Block::iterator start, Block::iterator end, int memorySpace) static
Definition at line 1287 of file Utils.cpp.
References mlir::WalkResult::advance(), mlir::Block::begin(), mlir::Operation::emitError(), mlir::Operation::emitWarning(), mlir::failed(), mlir::Operation::getLoc(), mlir::getNestingDepth(), mlir::presburger::None, and mlir::Block::walk().
Referenced by mlir::getMemoryFootprintBytes().
getMemRefEltSizeInBytes()
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType) static
Definition at line 602 of file Utils.cpp.
References vectorType().
Referenced by mlir::getMemRefSizeInBytes(), and mlir::MemRefRegion::getRegionSize().
Variable Documentation
kSliceFusionBarrierAttrName
const char* const kSliceFusionBarrierAttrName = "slice_fusion_barrier"
Definition at line 1040 of file Utils.cpp.
Referenced by mlir::getComputationSliceState().