MLIR: lib/Bindings/Python/DialectQuant.cpp File Reference
DialectQuant.cpp File Reference
#include "mlir-c/Dialect/Quant.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
Functions
static void populateDialectQuantSubmodule (const py::module &m)
PYBIND11_MODULE (_mlirDialectsQuant, m)
Function Documentation
populateDialectQuantSubmodule()
static void populateDialectQuantSubmodule (const py::module & m) static
Definition at line 18 of file DialectQuant.cpp.
References mlir::python::adaptors::pure_subclass::def_classmethod(), mlir::python::adaptors::pure_subclass::def_property_readonly(), max(), min(), mlirAnyQuantizedTypeGet(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetMax(), mlirCalibratedQuantizedTypeGetMin(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetDefaultMaximumForInteger(), mlirQuantizedTypeGetDefaultMinimumForInteger(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetFlags(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetSignedFlag(), mlirQuantizedTypeGetStorageType(), mlirQuantizedTypeGetStorageTypeIntegralWidth(), mlirQuantizedTypeGetStorageTypeMax(), mlirQuantizedTypeGetStorageTypeMin(), mlirQuantizedTypeIsCompatibleExpressedType(), mlirQuantizedTypeIsSigned(), mlirTypeIsAAnyQuantizedType(), mlirTypeIsACalibratedQuantizedType(), mlirTypeIsAQuantizedType(), mlirTypeIsAUniformQuantizedPerAxisType(), mlirTypeIsAUniformQuantizedType(), mlirTypeIsNull(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetNumDims(), mlirUniformQuantizedPerAxisTypeGetQuantizedDimension(), mlirUniformQuantizedPerAxisTypeGetScale(), mlirUniformQuantizedPerAxisTypeGetZeroPoint(), mlirUniformQuantizedPerAxisTypeIsFixedPoint(), mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetScale(), mlirUniformQuantizedTypeGetZeroPoint(), and mlirUniformQuantizedTypeIsFixedPoint().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_mlirDialectsQuant , m)
Definition at line 305 of file DialectQuant.cpp.
References populateDialectQuantSubmodule().