MLIR: lib/IR/FunctionImplementation.cpp File Reference
FunctionImplementation.cpp File Reference
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "mlir/IR/SymbolTable.h"
Functions
static ParseResult parseFunctionArgumentList (OpAsmParser &parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::Argument > &arguments, bool &isVariadic)
static ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< DictionaryAttr > &resultAttrs)
Parse a function result list.
static void printFunctionResultList (OpAsmPrinter &p, ArrayRef< Type > types, ArrayAttr attrs)
Print a function result list.
Function Documentation
parseFunctionArgumentList()
static ParseResult parseFunctionArgumentList (OpAsmParser & parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::Argument > & arguments, bool & isVariadic) static
Definition at line 17 of file FunctionImplementation.cpp.
References mlir::OpAsmParser::Argument::attrs, mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::NamedAttrList::getDictionary(), mlir::OpAsmParser::UnresolvedOperand::location, mlir::AsmParser::Paren, mlir::AsmParser::parseCommaSeparatedList(), mlir::OpAsmParser::parseOptionalArgument(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalEllipsis(), mlir::OpAsmParser::parseOptionalLocationSpecifier(), mlir::AsmParser::parseType(), mlir::OpAsmParser::Argument::sourceLoc, mlir::OpAsmParser::Argument::ssaName, mlir::succeeded(), mlir::success(), and mlir::OpAsmParser::Argument::type.
Referenced by mlir::function_interface_impl::parseFunctionSignature().
parseFunctionResultList()
static ParseResult parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< DictionaryAttr > & resultAttrs) static
Parse a function result list.
function-result-list ::= function-result-list-parens | non-function-type function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= type attribute-dict?
Definition at line 83 of file FunctionImplementation.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalRParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by mlir::function_interface_impl::parseFunctionSignature().
printFunctionResultList()
static void printFunctionResultList (OpAsmPrinter & p, ArrayRef< Type > types, ArrayAttr attrs) static
Print a function result list.
The provided attrs must either be null, or contain a set of DictionaryAttrs of the same arity as types.
Definition at line 244 of file FunctionImplementation.cpp.
References mlir::AsmPrinter::getStream(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::AsmPrinter::printType().
Referenced by mlir::function_interface_impl::printFunctionSignature().