MLIR: lib/IR/FunctionInterfaces.cpp File Reference
FunctionInterfaces.cpp File Reference
#include "mlir/IR/FunctionInterfaces.h"
#include "mlir/IR/FunctionOpInterfaces.cpp.inc"
Functions
static bool isEmptyAttrDict (Attribute attr)
static void setAllArgResAttrDicts (Operation *op, StringRef attrName, ArrayRef< Attribute > attrs)
Set all of the argument or result attribute dictionaries for a function.
Function Documentation
isEmptyAttrDict()
static bool isEmptyAttrDict (Attribute attr) static
Definition at line 23 of file FunctionInterfaces.cpp.
References mlir::Attribute::cast().
Referenced by setAllArgResAttrDicts(), and mlir::function_interface_impl::detail::setArgResAttrDict().
setAllArgResAttrDicts()
static void setAllArgResAttrDicts (Operation * op, StringRef attrName, ArrayRef< Attribute > attrs) static
Set all of the argument or result attribute dictionaries for a function.
Definition at line 80 of file FunctionInterfaces.cpp.
References mlir::Operation::getContext(), isEmptyAttrDict(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::function_interface_impl::setAllArgAttrDicts(), and mlir::function_interface_impl::setAllResultAttrDicts().