MLIR: lib/Transforms/Utils/InliningUtils.cpp File Reference
InliningUtils.cpp File Reference
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "inlining"
Functions
static void remapInlinedLocations (iterator_range< Region::iterator > inlinedBlocks, Location callerLoc)
Remap locations from the inlined blocks with CallSiteLoc locations with the provided caller location.
static void remapInlinedOperands (iterator_range< Region::iterator > inlinedBlocks, BlockAndValueMapping &mapper)
static bool isLegalToInline (InlinerInterface &interface, Region *src, Region *insertRegion, bool shouldCloneInlinedRegion, BlockAndValueMapping &valueMapping)
Utility to check that all of the operations within 'src' can be inlined.
static LogicalResult inlineRegionImpl (InlinerInterface &interface, Region *src, Block *inlineBlock, Block::iterator inlinePoint, BlockAndValueMapping &mapper, ValueRange resultsToReplace, TypeRange regionResultTypes, Optional< Location > inlineLoc, bool shouldCloneInlinedRegion, Operation *call=nullptr)
static LogicalResult inlineRegionImpl (InlinerInterface &interface, Region *src, Block *inlineBlock, Block::iterator inlinePoint, ValueRange inlinedOperands, ValueRange resultsToReplace, Optional< Location > inlineLoc, bool shouldCloneInlinedRegion, Operation *call=nullptr)
static Value materializeConversion (const DialectInlinerInterface *interface, SmallVectorImpl< Operation *> &castOps, OpBuilder &castBuilder, Value arg, Type type, Location conversionLoc)
Utility function used to generate a cast operation from the given interface, or return nullptr if a cast could not be generated.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inlining"
Definition at line 23 of file InliningUtils.cpp.
Function Documentation
inlineRegionImpl() [1/2]
static LogicalResult inlineRegionImpl (InlinerInterface & interface, Region * src, Block * inlineBlock, Block::iterator inlinePoint, BlockAndValueMapping & mapper, ValueRange resultsToReplace, TypeRange regionResultTypes, Optional< Location > inlineLoc, bool shouldCloneInlinedRegion, Operation * call = nullptr) static
Handle the terminators for each of the new blocks.
Definition at line 144 of file InliningUtils.cpp.
References mlir::Block::addArgument(), mlir::Region::begin(), mlir::Block::begin(), mlir::Region::cloneInto(), mlir::BlockAndValueMapping::contains(), mlir::Region::empty(), mlir::Region::end(), mlir::Block::end(), mlir::detail::enumerate(), mlir::Block::erase(), mlir::failure(), mlir::Region::front(), mlir::Region::getBlocks(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::InlinerInterface::handleTerminator(), mlir::InlinerInterface::isLegalToInline(), mlir::InlinerInterface::processInlinedBlocks(), mlir::InlinerInterface::processInlinedCallBlocks(), remapInlinedLocations(), remapInlinedOperands(), mlir::Block::splitBlock(), and mlir::success().
Referenced by mlir::inlineCall(), mlir::inlineRegion(), and inlineRegionImpl().
inlineRegionImpl() [2/2]
static LogicalResult inlineRegionImpl (InlinerInterface & interface, Region * src, Block * inlineBlock, Block::iterator inlinePoint, ValueRange inlinedOperands, ValueRange resultsToReplace, Optional< Location > inlineLoc, bool shouldCloneInlinedRegion, Operation * call = nullptr) static
Definition at line 233 of file InliningUtils.cpp.
References mlir::Region::empty(), mlir::failure(), mlir::Region::front(), mlir::Value::getType(), mlir::ValueRange::getTypes(), inlineRegionImpl(), and mlir::BlockAndValueMapping::map().
isLegalToInline()
static bool isLegalToInline (InlinerInterface & interface, Region * src, Region * insertRegion, bool shouldCloneInlinedRegion, BlockAndValueMapping & valueMapping) static
Utility to check that all of the operations within 'src' can be inlined.
Definition at line 113 of file InliningUtils.cpp.
References mlir::InlinerInterface::isLegalToInline(), and mlir::InlinerInterface::shouldAnalyzeRecursively().
Referenced by containsReturn(), eachHasOnlyOneOfTypes(), and remainsLegalAfterInline().
materializeConversion()
static Value materializeConversion (const DialectInlinerInterface * interface, SmallVectorImpl< Operation *> & castOps, OpBuilder & castBuilder, Value arg, Type type, Location conversionLoc) static
Utility function used to generate a cast operation from the given interface, or return nullptr if a cast could not be generated.
Definition at line 306 of file InliningUtils.cpp.
References mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::DialectInlinerInterface::materializeCallConversion(), and mlir::Operation::result_type_begin().
Referenced by mlir::inlineCall().
remapInlinedLocations()
static void remapInlinedLocations (iterator_range< Region::iterator > inlinedBlocks, Location callerLoc) static
Remap locations from the inlined blocks with CallSiteLoc locations with the provided caller location.
Definition at line 30 of file InliningUtils.cpp.
Referenced by inlineRegionImpl().
remapInlinedOperands()
static void remapInlinedOperands (iterator_range< Region::iterator > inlinedBlocks, BlockAndValueMapping & mapper) static
Definition at line 45 of file InliningUtils.cpp.
References mlir::BlockAndValueMapping::lookupOrNull().
Referenced by inlineRegionImpl().