MLIR: lib/Dialect/Linalg/Transforms/Interchange.cpp File Reference
Interchange.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-interchange"
Functions
static LogicalResult interchangeGenericOpPrecondition (GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-interchange"
Definition at line 31 of file Interchange.cpp.
Function Documentation
interchangeGenericOpPrecondition()
static LogicalResult interchangeGenericOpPrecondition (GenericOp genericOp, ArrayRef< unsigned > interchangeVector) static
Definition at line 37 of file Interchange.cpp.
References mlir::failure(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::interchangeGenericOp().