MLIR: lib/Analysis/Presburger/IntegerRelation.cpp File Reference
IntegerRelation.cpp File Reference
#include "mlir/Analysis/Presburger/IntegerRelation.h"
#include "mlir/Analysis/Presburger/LinearTransform.h"
#include "mlir/Analysis/Presburger/PWMAFunction.h"
#include "mlir/Analysis/Presburger/PresburgerRelation.h"
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Analysis/Presburger/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "presburger"
#define DEBUG_TYPE "fm"
#define DEBUG_TYPE "presburger"
Enumerations
enum BoundCmpResult
Functions
static bool rangeIsZero (ArrayRef< int64_t > range)
void removeConstraintsInvolvingIdRange (IntegerRelation &poly, unsigned begin, unsigned count)
static void eliminateFromConstraint (IntegerRelation *constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq)
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
static unsigned getBestIdToEliminate (const IntegerRelation &cst, unsigned start, unsigned end)
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point)
Helper to evaluate an affine expression at a point.
static int findEqualityToConstant (const IntegerRelation &cst, unsigned pos, bool symbolic=false)
Finds an equality that equates the specified identifier to a constant.
static void getCommonConstraints (const IntegerRelation &a, const IntegerRelation &b, IntegerRelation &c)
static void getIndependentConstraints (const IntegerRelation &cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > &nbIneqIndices, SmallVectorImpl< unsigned > &nbEqIndices)
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Macro Definition Documentation
DEBUG_TYPE [1/3]
#define DEBUG_TYPE "presburger"
Definition at line 1828 of file IntegerRelation.cpp.
DEBUG_TYPE [2/3]
#define DEBUG_TYPE "fm"
Definition at line 1828 of file IntegerRelation.cpp.
DEBUG_TYPE [3/3]
#define DEBUG_TYPE "presburger"
Definition at line 1828 of file IntegerRelation.cpp.
Enumeration Type Documentation
BoundCmpResult
enum BoundCmpResult
Definition at line 1867 of file IntegerRelation.cpp.
Function Documentation
eliminateFromConstraint()
static void eliminateFromConstraint (IntegerRelation * constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq) static
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
Columns in range [elimColStart, pivotCol) will not be updated as they have already been eliminated.
Definition at line 434 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::atEq(), mlir::presburger::IntegerRelation::atIneq(), mlir::presburger::IntegerRelation::getNumCols(), and mlir::lcm().
Referenced by mlir::presburger::IntegerRelation::gaussianEliminateIds(), and mlir::presburger::IntegerRelation::removeRedundantLocalVars().
findEqualityToConstant()
static int findEqualityToConstant (const IntegerRelation & cst, unsigned pos, bool symbolic = false) static
Finds an equality that equates the specified identifier to a constant.
Returns the position of the equality row. If 'symbolic' is set to true, symbols are also treated like a constant, i.e., an affine function of the symbols is also treated like a constant. Returns -1 if such an equality could not be found.
Definition at line 1272 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::atEq(), mlir::presburger::IntegerRelation::getNumDimIds(), mlir::presburger::IntegerRelation::getNumEqualities(), and mlir::presburger::IntegerRelation::getNumIds().
Referenced by mlir::presburger::IntegerRelation::computeConstantLowerOrUpperBound(), mlir::presburger::IntegerRelation::constantFoldId(), and mlir::presburger::IntegerRelation::getConstantBoundOnDimSize().
getBestIdToEliminate()
static unsigned getBestIdToEliminate (const IntegerRelation & cst, unsigned start, unsigned end) static
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
It is often best to eliminate in the increasing order of these counts when doing Fourier-Motzkin elimination since FM adds that many new constraints.
Definition at line 471 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::atIneq(), mlir::presburger::IntegerRelation::getNumIds(), mlir::presburger::IntegerRelation::getNumInequalities(), and min().
Referenced by mlir::presburger::IntegerRelation::isEmpty(), and mlir::presburger::IntegerRelation::projectOut().
getCommonConstraints()
static void getCommonConstraints (const IntegerRelation & a, const IntegerRelation & b, IntegerRelation & c) static
Definition at line 1889 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::IntegerRelation::getSpace(), and mlir::presburger::IntegerRelation::IntegerRelation().
Referenced by mlir::presburger::IntegerRelation::unionBoundingBox().
getIndependentConstraints()
static void getIndependentConstraints (const IntegerRelation & cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > & nbIneqIndices, SmallVectorImpl< unsigned > & nbEqIndices) static
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Definition at line 2032 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::atEq(), mlir::presburger::IntegerRelation::atIneq(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumIds(), and mlir::presburger::IntegerRelation::getNumInequalities().
Referenced by mlir::presburger::IntegerRelation::removeIndependentConstraints().
rangeIsZero()
static bool rangeIsZero (ArrayRef< int64_t > range) static
Definition at line 113 of file IntegerRelation.cpp.
Referenced by removeConstraintsInvolvingIdRange().
removeConstraintsInvolvingIdRange()
void removeConstraintsInvolvingIdRange (IntegerRelation & poly, unsigned begin, unsigned count)
Definition at line 117 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), rangeIsZero(), mlir::presburger::IntegerRelation::removeEquality(), and mlir::presburger::IntegerRelation::removeInequality().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
valueAt()
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point) static
Helper to evaluate an affine expression at a point.
The expression is a list of coefficients for the dimensions followed by the constant term.
Definition at line 784 of file IntegerRelation.cpp.
References value.
Referenced by mlir::presburger::IntegerRelation::containsPoint().