MLIR: include/mlir-c/Bindings/Python/Interop.h File Reference
Interop.h File Reference
#include <Python.h>
#include "mlir-c/AffineExpr.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/ExecutionEngine.h"
#include "mlir-c/IR.h"
#include "mlir-c/IntegerSet.h"
#include "mlir-c/Pass.h"
Macros
#define MLIR_PYTHON_PACKAGE_PREFIX mlir.
#define MLIR_PYTHON_STRINGIZE(s) #s
#define MLIR_PYTHON_STRINGIZE_ARG(arg) MLIR_PYTHON_STRINGIZE(arg)
#define MAKE_MLIR_PYTHON_QUALNAME(local) MLIR_PYTHON_STRINGIZE_ARG(MLIR_PYTHON_PACKAGE_PREFIX) local
#define MLIR_PYTHON_CAPSULE_AFFINE_EXPR MAKE_MLIR_PYTHON_QUALNAME("ir.AffineExpr._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_AFFINE_MAP MAKE_MLIR_PYTHON_QUALNAME("ir.AffineMap._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_ATTRIBUTE MAKE_MLIR_PYTHON_QUALNAME("ir.Attribute._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_CONTEXT MAKE_MLIR_PYTHON_QUALNAME("ir.Context._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE MAKE_MLIR_PYTHON_QUALNAME("execution_engine.ExecutionEngine._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_INTEGER_SET MAKE_MLIR_PYTHON_QUALNAME("ir.IntegerSet._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_LOCATION MAKE_MLIR_PYTHON_QUALNAME("ir.Location._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_MODULE MAKE_MLIR_PYTHON_QUALNAME("ir.Module._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_OPERATION MAKE_MLIR_PYTHON_QUALNAME("ir.Operation._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_TYPE MAKE_MLIR_PYTHON_QUALNAME("ir.Type._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_PASS_MANAGER MAKE_MLIR_PYTHON_QUALNAME("passmanager.PassManager._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_VALUE MAKE_MLIR_PYTHON_QUALNAME("ir.Value._CAPIPtr")
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
#define MLIR_PYTHON_GET_WRAPPED_POINTER(object) (void *)(object.ptr)
Gets a void* from a wrapped struct.
Functions
static PyObject * mlirPythonAffineExprToCapsule (MlirAffineExpr expr)
Creates a capsule object encapsulating the raw C-API MlirAffineExpr.
static MlirAffineExpr mlirPythonCapsuleToAffineExpr (PyObject *capsule)
Extracts an MlirAffineExpr from a capsule as produced from mlirPythonAffineExprToCapsule.
static PyObject * mlirPythonAttributeToCapsule (MlirAttribute attribute)
Creates a capsule object encapsulating the raw C-API MlirAttribute.
static MlirAttribute mlirPythonCapsuleToAttribute (PyObject *capsule)
Extracts an MlirAttribute from a capsule as produced from mlirPythonAttributeToCapsule.
static PyObject * mlirPythonContextToCapsule (MlirContext context)
Creates a capsule object encapsulating the raw C-API MlirContext.
static MlirContext mlirPythonCapsuleToContext (PyObject *capsule)
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
static PyObject * mlirPythonLocationToCapsule (MlirLocation loc)
Creates a capsule object encapsulating the raw C-API MlirLocation.
static MlirLocation mlirPythonCapsuleToLocation (PyObject *capsule)
Extracts an MlirLocation from a capsule as produced from mlirPythonLocationToCapsule.
static PyObject * mlirPythonModuleToCapsule (MlirModule module)
Creates a capsule object encapsulating the raw C-API MlirModule.
static MlirModule mlirPythonCapsuleToModule (PyObject *capsule)
Extracts an MlirModule from a capsule as produced from mlirPythonModuleToCapsule.
static PyObject * mlirPythonPassManagerToCapsule (MlirPassManager pm)
Creates a capsule object encapsulating the raw C-API MlirPassManager.
static MlirPassManager mlirPythonCapsuleToPassManager (PyObject *capsule)
Extracts an MlirPassManager from a capsule as produced from mlirPythonPassManagerToCapsule.
static PyObject * mlirPythonOperationToCapsule (MlirOperation operation)
Creates a capsule object encapsulating the raw C-API MlirOperation.
static MlirOperation mlirPythonCapsuleToOperation (PyObject *capsule)
Extracts an MlirOperations from a capsule as produced from mlirPythonOperationToCapsule.
static PyObject * mlirPythonTypeToCapsule (MlirType type)
Creates a capsule object encapsulating the raw C-API MlirType.
static MlirType mlirPythonCapsuleToType (PyObject *capsule)
Extracts an MlirType from a capsule as produced from mlirPythonTypeToCapsule.
static PyObject * mlirPythonAffineMapToCapsule (MlirAffineMap affineMap)
Creates a capsule object encapsulating the raw C-API MlirAffineMap.
static MlirAffineMap mlirPythonCapsuleToAffineMap (PyObject *capsule)
Extracts an MlirAffineMap from a capsule as produced from mlirPythonAffineMapToCapsule.
static PyObject * mlirPythonIntegerSetToCapsule (MlirIntegerSet integerSet)
Creates a capsule object encapsulating the raw C-API MlirIntegerSet.
static MlirIntegerSet mlirPythonCapsuleToIntegerSet (PyObject *capsule)
Extracts an MlirIntegerSet from a capsule as produced from mlirPythonIntegerSetToCapsule.
static PyObject * mlirPythonExecutionEngineToCapsule (MlirExecutionEngine jit)
Creates a capsule object encapsulating the raw C-API MlirExecutionEngine.
static MlirExecutionEngine mlirPythonCapsuleToExecutionEngine (PyObject *capsule)
Extracts an MlirExecutionEngine from a capsule as produced from mlirPythonIntegerSetToCapsule.
static PyObject * mlirPythonValueToCapsule (MlirValue value)
Creates a capsule object encapsulating the raw C-API MlirValue.
static MlirValue mlirPythonCapsuleToValue (PyObject *capsule)
Extracts an MlirValue from a capsule as produced from mlirPythonValueToCapsule.
Macro Definition Documentation
MAKE_MLIR_PYTHON_QUALNAME
#define MAKE_MLIR_PYTHON_QUALNAME (local) MLIR_PYTHON_STRINGIZE_ARG(MLIR_PYTHON_PACKAGE_PREFIX) local
Definition at line 46 of file Interop.h.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), pybind11::detail::type_caster< MlirAttribute >::cast(), pybind11::detail::type_caster< MlirLocation >::cast(), pybind11::detail::type_caster< MlirModule >::cast(), pybind11::detail::type_caster< MlirOperation >::cast(), pybind11::detail::type_caster< MlirType >::cast(), pybind11::detail::type_caster< MlirContext >::load(), pybind11::detail::type_caster< MlirLocation >::load(), and mlir::python::PyGlobals::PyGlobals().
MLIR_PYTHON_CAPI_FACTORY_ATTR
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
The signature of the function is: def _CAPICreate(capsule) -> object Calling such a function implies a transfer of ownership of the object the capsule wraps: after such a call, the capsule should be considered invalid, and its wrapped pointer must not be destroyed.
Only a very small number of Python objects can be created in such a fashion (i.e. top-level types such as Context where the lifetime can be cleanly delineated).
Definition at line 94 of file Interop.h.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), pybind11::detail::type_caster< MlirAttribute >::cast(), pybind11::detail::type_caster< MlirLocation >::cast(), pybind11::detail::type_caster< MlirModule >::cast(), pybind11::detail::type_caster< MlirOperation >::cast(), pybind11::detail::type_caster< MlirType >::cast(), mlir::python::PyIntegerSet::createFromCapsule(), PYBIND11_MODULE(), and mlir::python::PySymbolTable::walkSymbolTables().
MLIR_PYTHON_CAPI_PTR_ATTR
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
This will be a type-specific capsule created as per one of the helpers below.
Ownership is not transferred by acquiring a capsule in this way: the validity of the pointer wrapped by the capsule will be bounded by the lifetime of the Python object that produced it. Only the name and pointer of the capsule are set. The caller is free to set a destructor and context as needed to manage anything further.
Definition at line 81 of file Interop.h.
Referenced by mlir::python::PyIntegerSet::createFromCapsule(), pybind11::detail::mlirApiObjectToCapsule(), PYBIND11_MODULE(), and mlir::python::PySymbolTable::walkSymbolTables().
MLIR_PYTHON_CAPSULE_AFFINE_EXPR
#define MLIR_PYTHON_CAPSULE_AFFINE_EXPR MAKE_MLIR_PYTHON_QUALNAME("ir.AffineExpr._CAPIPtr")
Definition at line 49 of file Interop.h.
Referenced by mlirPythonAffineExprToCapsule(), and mlirPythonCapsuleToAffineExpr().
MLIR_PYTHON_CAPSULE_AFFINE_MAP
#define MLIR_PYTHON_CAPSULE_AFFINE_MAP MAKE_MLIR_PYTHON_QUALNAME("ir.AffineMap._CAPIPtr")
Definition at line 51 of file Interop.h.
Referenced by mlirPythonAffineMapToCapsule(), and mlirPythonCapsuleToAffineMap().
MLIR_PYTHON_CAPSULE_ATTRIBUTE
#define MLIR_PYTHON_CAPSULE_ATTRIBUTE MAKE_MLIR_PYTHON_QUALNAME("ir.Attribute._CAPIPtr")
Definition at line 53 of file Interop.h.
Referenced by mlirPythonAttributeToCapsule(), and mlirPythonCapsuleToAttribute().
MLIR_PYTHON_CAPSULE_CONTEXT
#define MLIR_PYTHON_CAPSULE_CONTEXT MAKE_MLIR_PYTHON_QUALNAME("ir.Context._CAPIPtr")
Definition at line 55 of file Interop.h.
Referenced by mlirPythonCapsuleToContext(), and mlirPythonContextToCapsule().
MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE
#define MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE MAKE_MLIR_PYTHON_QUALNAME("execution_engine.ExecutionEngine._CAPIPtr")
Definition at line 57 of file Interop.h.
Referenced by mlirPythonCapsuleToExecutionEngine(), and mlirPythonExecutionEngineToCapsule().
MLIR_PYTHON_CAPSULE_INTEGER_SET
#define MLIR_PYTHON_CAPSULE_INTEGER_SET MAKE_MLIR_PYTHON_QUALNAME("ir.IntegerSet._CAPIPtr")
Definition at line 59 of file Interop.h.
Referenced by mlirPythonCapsuleToIntegerSet(), and mlirPythonIntegerSetToCapsule().
MLIR_PYTHON_CAPSULE_LOCATION
#define MLIR_PYTHON_CAPSULE_LOCATION MAKE_MLIR_PYTHON_QUALNAME("ir.Location._CAPIPtr")
Definition at line 61 of file Interop.h.
Referenced by mlirPythonCapsuleToLocation(), and mlirPythonLocationToCapsule().
MLIR_PYTHON_CAPSULE_MODULE
#define MLIR_PYTHON_CAPSULE_MODULE MAKE_MLIR_PYTHON_QUALNAME("ir.Module._CAPIPtr")
Definition at line 63 of file Interop.h.
Referenced by mlirPythonCapsuleToModule(), and mlirPythonModuleToCapsule().
MLIR_PYTHON_CAPSULE_OPERATION
#define MLIR_PYTHON_CAPSULE_OPERATION MAKE_MLIR_PYTHON_QUALNAME("ir.Operation._CAPIPtr")
Definition at line 65 of file Interop.h.
Referenced by mlirPythonCapsuleToOperation(), and mlirPythonOperationToCapsule().
MLIR_PYTHON_CAPSULE_PASS_MANAGER
#define MLIR_PYTHON_CAPSULE_PASS_MANAGER MAKE_MLIR_PYTHON_QUALNAME("passmanager.PassManager._CAPIPtr")
Definition at line 68 of file Interop.h.
Referenced by mlirPythonCapsuleToPassManager(), and mlirPythonPassManagerToCapsule().
MLIR_PYTHON_CAPSULE_TYPE
#define MLIR_PYTHON_CAPSULE_TYPE MAKE_MLIR_PYTHON_QUALNAME("ir.Type._CAPIPtr")
Definition at line 67 of file Interop.h.
Referenced by mlirPythonCapsuleToType(), and mlirPythonTypeToCapsule().
MLIR_PYTHON_CAPSULE_VALUE
#define MLIR_PYTHON_CAPSULE_VALUE MAKE_MLIR_PYTHON_QUALNAME("ir.Value._CAPIPtr")
Definition at line 70 of file Interop.h.
Referenced by mlirPythonCapsuleToValue(), and mlirPythonValueToCapsule().
MLIR_PYTHON_GET_WRAPPED_POINTER
#define MLIR_PYTHON_GET_WRAPPED_POINTER (object) (void *)(object.ptr)
Gets a void* from a wrapped struct.
Needed because const cast is different between C/C++.
Definition at line 102 of file Interop.h.
Referenced by mlirPythonAffineExprToCapsule(), mlirPythonAffineMapToCapsule(), mlirPythonAttributeToCapsule(), mlirPythonExecutionEngineToCapsule(), mlirPythonIntegerSetToCapsule(), mlirPythonLocationToCapsule(), mlirPythonModuleToCapsule(), mlirPythonPassManagerToCapsule(), mlirPythonTypeToCapsule(), and mlirPythonValueToCapsule().
MLIR_PYTHON_PACKAGE_PREFIX
#define MLIR_PYTHON_PACKAGE_PREFIX mlir.
Definition at line 40 of file Interop.h.
MLIR_PYTHON_STRINGIZE
#define MLIR_PYTHON_STRINGIZE (s) #s
Definition at line 44 of file Interop.h.
MLIR_PYTHON_STRINGIZE_ARG
#define MLIR_PYTHON_STRINGIZE_ARG (arg) MLIR_PYTHON_STRINGIZE(arg)
Definition at line 45 of file Interop.h.
Function Documentation
mlirPythonAffineExprToCapsule()
static PyObject* mlirPythonAffineExprToCapsule (MlirAffineExpr expr) inline static
Creates a capsule object encapsulating the raw C-API MlirAffineExpr.
The returned capsule does not extend or affect ownership of any Python objects that reference the expression in any way.
Definition at line 113 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_EXPR, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyAffineExpr::getCapsule().
mlirPythonAffineMapToCapsule()
static PyObject* mlirPythonAffineMapToCapsule (MlirAffineMap affineMap) inline static
Creates a capsule object encapsulating the raw C-API MlirAffineMap.
The returned capsule does not extend or affect ownership of any Python objects that reference the type in any way.
Definition at line 260 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_MAP, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), and mlir::python::PyAffineMap::getCapsule().
mlirPythonAttributeToCapsule()
static PyObject* mlirPythonAttributeToCapsule (MlirAttribute attribute) inline static
Creates a capsule object encapsulating the raw C-API MlirAttribute.
The returned capsule does not extend or affect ownership of any Python objects that reference the attribute in any way.
Definition at line 132 of file Interop.h.
References MLIR_PYTHON_CAPSULE_ATTRIBUTE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirAttribute >::cast(), and mlir::python::PyAttribute::getCapsule().
mlirPythonCapsuleToAffineExpr()
static MlirAffineExpr mlirPythonCapsuleToAffineExpr (PyObject * capsule) inline static
Extracts an MlirAffineExpr from a capsule as produced from mlirPythonAffineExprToCapsule.
If the capsule is not of the right type, then a null expression is returned (as checked via mlirAffineExprIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 122 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_EXPR.
Referenced by mlir::python::PyAffineExpr::createFromCapsule().
mlirPythonCapsuleToAffineMap()
static MlirAffineMap mlirPythonCapsuleToAffineMap (PyObject * capsule) inline static
Extracts an MlirAffineMap from a capsule as produced from mlirPythonAffineMapToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirAffineMapIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 269 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_MAP.
Referenced by mlir::python::PyAffineMap::createFromCapsule(), and pybind11::detail::type_caster< MlirAffineMap >::load().
mlirPythonCapsuleToAttribute()
static MlirAttribute mlirPythonCapsuleToAttribute (PyObject * capsule) inline static
Extracts an MlirAttribute from a capsule as produced from mlirPythonAttributeToCapsule.
If the capsule is not of the right type, then a null attribute is returned (as checked via mlirAttributeIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 141 of file Interop.h.
References MLIR_PYTHON_CAPSULE_ATTRIBUTE.
Referenced by mlir::python::PyAttribute::createFromCapsule(), and pybind11::detail::type_caster< MlirAttribute >::load().
mlirPythonCapsuleToContext()
static MlirContext mlirPythonCapsuleToContext (PyObject * capsule) inline static
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
If the capsule is not of the right type, then a null context is returned (as checked via mlirContextIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 159 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::createFromCapsule(), and pybind11::detail::type_caster< MlirContext >::load().
mlirPythonCapsuleToExecutionEngine()
static MlirExecutionEngine mlirPythonCapsuleToExecutionEngine (PyObject * capsule) inline static
Extracts an MlirExecutionEngine from a capsule as produced from mlirPythonIntegerSetToCapsule.
If the capsule is not of the right type, then a null set is returned (as checked via mlirExecutionEngineIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 308 of file Interop.h.
References MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE.
mlirPythonCapsuleToIntegerSet()
static MlirIntegerSet mlirPythonCapsuleToIntegerSet (PyObject * capsule) inline static
Extracts an MlirIntegerSet from a capsule as produced from mlirPythonIntegerSetToCapsule.
If the capsule is not of the right type, then a null set is returned (as checked via mlirIntegerSetIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 288 of file Interop.h.
References MLIR_PYTHON_CAPSULE_INTEGER_SET.
Referenced by mlir::python::PyIntegerSet::createFromCapsule().
mlirPythonCapsuleToLocation()
static MlirLocation mlirPythonCapsuleToLocation (PyObject * capsule) inline static
Extracts an MlirLocation from a capsule as produced from mlirPythonLocationToCapsule.
If the capsule is not of the right type, then a null module is returned (as checked via mlirLocationIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 177 of file Interop.h.
References MLIR_PYTHON_CAPSULE_LOCATION.
Referenced by mlir::python::PyLocation::createFromCapsule(), and pybind11::detail::type_caster< MlirLocation >::load().
mlirPythonCapsuleToModule()
static MlirModule mlirPythonCapsuleToModule (PyObject * capsule) inline static
Extracts an MlirModule from a capsule as produced from mlirPythonModuleToCapsule.
If the capsule is not of the right type, then a null module is returned (as checked via mlirModuleIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 195 of file Interop.h.
References MLIR_PYTHON_CAPSULE_MODULE.
Referenced by mlir::python::PyModule::createFromCapsule(), and pybind11::detail::type_caster< MlirModule >::load().
mlirPythonCapsuleToOperation()
static MlirOperation mlirPythonCapsuleToOperation (PyObject * capsule) inline static
Extracts an MlirOperations from a capsule as produced from mlirPythonOperationToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirOperationIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 231 of file Interop.h.
References MLIR_PYTHON_CAPSULE_OPERATION.
Referenced by mlir::python::PyOperation::createFromCapsule(), and pybind11::detail::type_caster< MlirOperation >::load().
mlirPythonCapsuleToPassManager()
static MlirPassManager mlirPythonCapsuleToPassManager (PyObject * capsule) inline static
Extracts an MlirPassManager from a capsule as produced from mlirPythonPassManagerToCapsule.
If the capsule is not of the right type, then a null pass manager is returned (as checked via mlirPassManagerIsNull).
Definition at line 213 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER.
Referenced by pybind11::detail::type_caster< MlirPassManager >::load().
mlirPythonCapsuleToType()
static MlirType mlirPythonCapsuleToType (PyObject * capsule) inline static
Extracts an MlirType from a capsule as produced from mlirPythonTypeToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirTypeIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 250 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPE.
Referenced by mlir::python::PyType::createFromCapsule(), and pybind11::detail::type_caster< MlirType >::load().
mlirPythonCapsuleToValue()
static MlirValue mlirPythonCapsuleToValue (PyObject * capsule) inline static
Extracts an MlirValue from a capsule as produced from mlirPythonValueToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirValueIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 328 of file Interop.h.
References MLIR_PYTHON_CAPSULE_VALUE, and value.
Referenced by mlir::python::PyValue::createFromCapsule().
mlirPythonContextToCapsule()
static PyObject* mlirPythonContextToCapsule (MlirContext context) inline static
Creates a capsule object encapsulating the raw C-API MlirContext.
The returned capsule does not extend or affect ownership of any Python objects that reference the context in any way.
Definition at line 151 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::getCapsule().
mlirPythonExecutionEngineToCapsule()
static PyObject* mlirPythonExecutionEngineToCapsule (MlirExecutionEngine jit) inline static
Creates a capsule object encapsulating the raw C-API MlirExecutionEngine.
The returned capsule does not extend or affect ownership of any Python objects that reference the set in any way.
Definition at line 298 of file Interop.h.
References MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
mlirPythonIntegerSetToCapsule()
static PyObject* mlirPythonIntegerSetToCapsule (MlirIntegerSet integerSet) inline static
Creates a capsule object encapsulating the raw C-API MlirIntegerSet.
The returned capsule does not extend or affect ownership of any Python objects that reference the set in any way.
Definition at line 279 of file Interop.h.
References MLIR_PYTHON_CAPSULE_INTEGER_SET, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyIntegerSet::getCapsule().
mlirPythonLocationToCapsule()
static PyObject* mlirPythonLocationToCapsule (MlirLocation loc) inline static
Creates a capsule object encapsulating the raw C-API MlirLocation.
The returned capsule does not extend or affect ownership of any Python objects that reference the location in any way.
Definition at line 168 of file Interop.h.
References MLIR_PYTHON_CAPSULE_LOCATION, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirLocation >::cast(), and mlir::python::PyLocation::getCapsule().
mlirPythonModuleToCapsule()
static PyObject* mlirPythonModuleToCapsule (MlirModule module) inline static
Creates a capsule object encapsulating the raw C-API MlirModule.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 186 of file Interop.h.
References MLIR_PYTHON_CAPSULE_MODULE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirModule >::cast(), and mlir::python::PyModule::getCapsule().
mlirPythonOperationToCapsule()
static PyObject* mlirPythonOperationToCapsule (MlirOperation operation) inline static
Creates a capsule object encapsulating the raw C-API MlirOperation.
The returned capsule does not extend or affect ownership of any Python objects that reference the operation in any way.
Definition at line 223 of file Interop.h.
References MLIR_PYTHON_CAPSULE_OPERATION.
Referenced by pybind11::detail::type_caster< MlirOperation >::cast(), and mlir::python::PyOperation::getCapsule().
mlirPythonPassManagerToCapsule()
static PyObject* mlirPythonPassManagerToCapsule (MlirPassManager pm) inline static
Creates a capsule object encapsulating the raw C-API MlirPassManager.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 204 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER, and MLIR_PYTHON_GET_WRAPPED_POINTER.
mlirPythonTypeToCapsule()
static PyObject* mlirPythonTypeToCapsule (MlirType type) inline static
Creates a capsule object encapsulating the raw C-API MlirType.
The returned capsule does not extend or affect ownership of any Python objects that reference the type in any way.
Definition at line 241 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirType >::cast(), and mlir::python::PyType::getCapsule().
mlirPythonValueToCapsule()
static PyObject* mlirPythonValueToCapsule (MlirValue value) inline static
Creates a capsule object encapsulating the raw C-API MlirValue.
The returned capsule does not extend or affect ownership of any Python objects that reference the operation in any way.
Definition at line 319 of file Interop.h.
References MLIR_PYTHON_CAPSULE_VALUE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyValue::getCapsule().