MLIR: lib/IR/BuiltinAttributes.cpp File Reference
BuiltinAttributes.cpp File Reference
#include "mlir/IR/BuiltinAttributes.h"
#include "AttributeDetail.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/DecodeAttributesInterfaces.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/Support/Endian.h"
#include "mlir/IR/BuiltinAttributes.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
Tablegen Attribute Definitions.
Functions
template<bool inPlace>
static bool dictionaryAttrSort (ArrayRef< NamedAttribute > value, SmallVectorImpl< NamedAttribute > &storage)
Helper function that does either an in place sort or sorts from source array into destination.
static Optional< NamedAttribute > findDuplicateElement (ArrayRef< NamedAttribute > value)
Returns an entry with a duplicate name from the given sorted array of named attributes.
static size_t getDenseElementStorageWidth (size_t origWidth)
Get the bitwidth of a dense element type within the buffer.
static size_t getDenseElementStorageWidth (Type elementType)
static void setBit (char *rawData, size_t bitPos, bool value)
Set a bit to a specific value.
static bool getBit (const char *rawData, size_t bitPos)
Return the value of the specified bit.
static void copyAPIntToArrayForBEmachine (APInt value, size_t numBytes, char *result)
Copy actual numBytes data from value (APInt) to char array(result) for BE format.
static void copyArrayToAPIntForBEmachine (const char *inArray, size_t numBytes, APInt &result)
Copy numBytes data from inArray(char array) to result(APINT) for BE format.
static void writeBits (char *rawData, size_t bitPos, APInt value)
Writes value to the bit position bitPos in array rawData.
static APInt readBits (const char *rawData, size_t bitPos, size_t bitWidth)
Reads the next bitWidth bits from the bit position bitPos in array rawData.
template<typename Values >
static bool hasSameElementsOrSplat (ShapedType type, const Values &values)
Returns true if 'values' corresponds to a splat, i.e.
static bool isValidIntOrFloat (Type type, int64_t dataEltSize, bool isInt, bool isSigned)
Check the information for a C++ data type, check if this type is valid for the current attribute.
static LLVM_ATTRIBUTE_UNUSED bool isComplexOfIntType (Type type)
Return if the given complex type has an integer element type.
template<typename APRangeT >
static void writeAPIntsToBuffer (size_t storageWidth, std::vector< char > &data, APRangeT &&values)
Utility method to write a range of APInt values to a buffer.
template<typename Fn , typename Attr >
static ShapedType mappingHelper (Fn mapping, Attr &attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > &data)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Tablegen Attribute Definitions.
Definition at line 30 of file BuiltinAttributes.cpp.
Function Documentation
copyAPIntToArrayForBEmachine()
static void copyAPIntToArrayForBEmachine (APInt value, size_t numBytes, char * result) static
Copy actual numBytes data from value (APInt) to char array(result) for BE format.
Definition at line 442 of file BuiltinAttributes.cpp.
Referenced by writeBits().
copyArrayToAPIntForBEmachine()
static void copyArrayToAPIntForBEmachine (const char * inArray, size_t numBytes, APInt & result) static
Copy numBytes data from inArray(char array) to result(APINT) for BE format.
Definition at line 472 of file BuiltinAttributes.cpp.
Referenced by readBits().
dictionaryAttrSort()
template<bool inPlace> static bool dictionaryAttrSort (ArrayRef< NamedAttribute > value, SmallVectorImpl< NamedAttribute > & storage) static
Helper function that does either an in place sort or sorts from source array into destination.
If inPlace then storage is both the source and the destination, else value is the source and storage destination. Returns whether source was sorted.
Definition at line 74 of file BuiltinAttributes.cpp.
Referenced by findDuplicateElement().
findDuplicateElement()
static Optional<NamedAttribute> findDuplicateElement (ArrayRef< NamedAttribute > value) static
Returns an entry with a duplicate name from the given sorted array of named attributes.
Returns llvm::None if all elements have unique names.
Definition at line 116 of file BuiltinAttributes.cpp.
References mlir::Attribute::cast(), mlir::Type::cast(), contains(), dictionaryAttrSort(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::impl::findAttrSorted(), mlir::Operation::getAttrOfType(), mlir::Type::getContext(), mlir::FloatType::getFloatSemantics(), mlir::NamedAttribute::getName(), mlir::SymbolTable::getSymbolAttrName(), mlir::Type::isa(), mlir::success(), value, and mlir::verify().
getBit()
static bool getBit (const char * rawData, size_t bitPos) static
Return the value of the specified bit.
Definition at line 436 of file BuiltinAttributes.cpp.
Referenced by mlir::DenseElementsAttr::BoolElementIterator::operator*(), and readBits().
getDenseElementStorageWidth() [1/2]
static size_t getDenseElementStorageWidth (size_t origWidth) static
Get the bitwidth of a dense element type within the buffer.
DenseElementsAttr requires bitwidths greater than 1 to be aligned by 8.
Definition at line 420 of file BuiltinAttributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), getDenseElementStorageWidth(), mlir::DenseElementsAttr::isValidRawBuffer(), mappingHelper(), mlir::DenseElementsAttr::IntElementIterator::operator*(), mlir::DenseElementsAttr::ComplexIntElementIterator::operator*(), and writeAPIntsToBuffer().
getDenseElementStorageWidth() [2/2]
static size_t getDenseElementStorageWidth (Type elementType) static
Definition at line 423 of file BuiltinAttributes.cpp.
References mlir::detail::getDenseElementBitWidth(), and getDenseElementStorageWidth().
hasSameElementsOrSplat()
template<typename Values > static bool hasSameElementsOrSplat (ShapedType type, const Values & values) static
Returns true if 'values' corresponds to a splat, i.e.
one element, or has the same element count as 'type'.
Definition at line 563 of file BuiltinAttributes.cpp.
References mlir::Attribute::getAsOpaquePointer().
Referenced by mlir::DenseElementsAttr::get().
isComplexOfIntType()
static LLVM_ATTRIBUTE_UNUSED bool isComplexOfIntType (Type type) static
Return if the given complex type has an integer element type.
Definition at line 882 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getElementType(), and mlir::Type::isa().
Referenced by mlir::DenseElementsAttr::complex_value_begin(), mlir::DenseElementsAttr::complex_value_end(), and mlir::DenseElementsAttr::getComplexIntValues().
isValidIntOrFloat()
static bool isValidIntOrFloat (Type type, int64_t dataEltSize, bool isInt, bool isSigned) static
Check the information for a C++ data type, check if this type is valid for the current attribute.
This method is used to verify specific type invariants that the templatized 'getValues' method cannot.
Definition at line 824 of file BuiltinAttributes.cpp.
References mlir::Type::dyn_cast(), mlir::detail::getDenseElementBitWidth(), mlir::Type::isa(), and mlir::Type::isIndex().
Referenced by mlir::DenseElementsAttr::getValues(), mlir::DenseElementsAttr::isValidBool(), mlir::DenseElementsAttr::isValidComplex(), mlir::DenseElementsAttr::isValidIntOrFloat(), mlir::DenseElementsAttr::value_begin(), mlir::DenseElementsAttr::value_end(), and writeAPIntsToBuffer().
mappingHelper()
template<typename Fn , typename Attr > static ShapedType mappingHelper (Fn mapping, Attr & attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > & data) static
Definition at line 1169 of file BuiltinAttributes.cpp.
References mlir::detail::getDenseElementBitWidth(), getDenseElementStorageWidth(), and writeBits().
Referenced by mlir::DenseFPElementsAttr::mapValues(), and mlir::DenseIntElementsAttr::mapValues().
readBits()
static APInt readBits (const char * rawData, size_t bitPos, size_t bitWidth) static
Reads the next bitWidth bits from the bit position bitPos in array rawData.
Definition at line 534 of file BuiltinAttributes.cpp.
References copyArrayToAPIntForBEmachine(), and getBit().
Referenced by mlir::DenseElementsAttr::IntElementIterator::operator*(), and mlir::DenseElementsAttr::ComplexIntElementIterator::operator*().
setBit()
static void setBit (char * rawData, size_t bitPos, bool value) static
Set a bit to a specific value.
Definition at line 428 of file BuiltinAttributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), and writeBits().
writeAPIntsToBuffer()
template<typename APRangeT > static void writeAPIntsToBuffer (size_t storageWidth, std::vector< char > & data, APRangeT && values) static
Utility method to write a range of APInt values to a buffer.
Definition at line 1028 of file BuiltinAttributes.cpp.
References mlir::Type::dyn_cast(), getDenseElementStorageWidth(), getElementType(), isValidIntOrFloat(), and writeBits().
writeBits()
static void writeBits (char * rawData, size_t bitPos, APInt value) static
Writes value to the bit position bitPos in array rawData.
Definition at line 507 of file BuiltinAttributes.cpp.
References copyAPIntToArrayForBEmachine(), and setBit().
Referenced by mlir::DenseElementsAttr::get(), mappingHelper(), and writeAPIntsToBuffer().