MLIR: lib/CAPI/IR/IR.cpp File Reference
IR.cpp File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Parser/Parser.h"
#include "llvm/Support/Debug.h"
#include <cstddef>
Macros
#define APPEND_ELEMS(type, sizeName, elemName)
Functions
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
bool mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
void mlirContextSetAllowUnregisteredDialects (MlirContext context, bool allow)
Sets whether unregistered dialects are allowed in this context.
bool mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
void mlirContextAppendDialectRegistry (MlirContext ctx, MlirDialectRegistry registry)
Append the contents of the given dialect registry to the registry associated with the context.
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
bool mlirContextIsRegisteredOperation (MlirContext context, MlirStringRef name)
Returns whether the given fully-qualified operation (i.e.
void mlirContextEnableMultithreading (MlirContext context, bool enable)
Set threading mode (must be set to false to mlir-print-ir-after-all).
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
bool mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
MlirDialectRegistry mlirDialectRegistryCreate ()
Creates a dialect registry and transfers its ownership to the caller.
void mlirDialectRegistryDestroy (MlirDialectRegistry registry)
Takes a dialect registry owned by the caller and destroys it.
MlirOpPrintingFlags mlirOpPrintingFlagsCreate ()
Creates new printing flags with defaults, intended for customization.
void mlirOpPrintingFlagsDestroy (MlirOpPrintingFlags flags)
Destroys printing flags created with mlirOpPrintingFlagsCreate.
void mlirOpPrintingFlagsElideLargeElementsAttrs (MlirOpPrintingFlags flags, intptr_t largeElementLimit)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
void mlirOpPrintingFlagsEnableDebugInfo (MlirOpPrintingFlags flags, bool prettyForm)
Enable printing of debug information.
void mlirOpPrintingFlagsPrintGenericOpForm (MlirOpPrintingFlags flags)
Always print operations in the generic form.
void mlirOpPrintingFlagsUseLocalScope (MlirOpPrintingFlags flags)
Use local scope when printing the operation.
MlirLocation mlirLocationFileLineColGet (MlirContext context, MlirStringRef filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
MlirLocation mlirLocationCallSiteGet (MlirLocation callee, MlirLocation caller)
Creates a call site location with a callee and a caller.
MlirLocation mlirLocationFusedGet (MlirContext ctx, intptr_t nLocations, MlirLocation const *locations, MlirAttribute metadata)
Creates a fused location with an array of locations and metadata.
MlirLocation mlirLocationNameGet (MlirContext context, MlirStringRef name, MlirLocation childLoc)
Creates a name location owned by the given context.
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
bool mlirLocationEqual (MlirLocation l1, MlirLocation l2)
Checks if two locations are equal.
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
MlirModule mlirModuleCreateParse (MlirContext context, MlirStringRef module)
Parses a module from the string and transfers ownership to the caller.
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
MlirBlock mlirModuleGetBody (MlirModule module)
Gets the body of the module, i.e. the only block it contains.
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
MlirModule mlirModuleFromOperation (MlirOperation op)
Views the generic operation as a module.
MlirOperationState mlirOperationStateGet (MlirStringRef name, MlirLocation loc)
Constructs an operation state from a name and a location.
void mlirOperationStateAddResults (MlirOperationState *state, intptr_t n, MlirType const *results)
Adds a list of components to the operation state.
void mlirOperationStateAddOperands (MlirOperationState *state, intptr_t n, MlirValue const *operands)
void mlirOperationStateAddOwnedRegions (MlirOperationState *state, intptr_t n, MlirRegion const *regions)
void mlirOperationStateAddSuccessors (MlirOperationState *state, intptr_t n, MlirBlock const *successors)
void mlirOperationStateAddAttributes (MlirOperationState *state, intptr_t n, MlirNamedAttribute const *attributes)
void mlirOperationStateEnableResultTypeInference (MlirOperationState *state)
Enables result type inference for the operation under construction.
static LogicalResult inferOperationTypes (OperationState &state)
MlirOperation mlirOperationCreate (MlirOperationState *state)
Creates an operation and transfers ownership to the caller.
MlirOperation mlirOperationClone (MlirOperation op)
Creates a deep copy of an operation.
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
void mlirOperationRemoveFromParent (MlirOperation op)
Removes the given operation from its parent block.
bool mlirOperationEqual (MlirOperation op, MlirOperation other)
Checks whether two operation handles point to the same operation.
MlirContext mlirOperationGetContext (MlirOperation op)
Gets the context this operation is associated with.
MlirLocation mlirOperationGetLocation (MlirOperation op)
Gets the location of the operation.
MlirTypeID mlirOperationGetTypeID (MlirOperation op)
Gets the type id of the operation.
MlirIdentifier mlirOperationGetName (MlirOperation op)
Gets the name of the operation as an identifier.
MlirBlock mlirOperationGetBlock (MlirOperation op)
Gets the block that owns this operation, returning null if the operation is not owned.
MlirOperation mlirOperationGetParentOperation (MlirOperation op)
Gets the operation that owns this operation, returning null if the operation is not owned.
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
MlirRegion mlirOperationGetFirstRegion (MlirOperation op)
Returns first region attached to the operation.
MlirRegion mlirRegionGetNextInOperation (MlirRegion region)
Returns the region immediately following the given region in its parent operation.
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
void mlirOperationSetOperand (MlirOperation op, intptr_t pos, MlirValue newValue)
Sets the pos-th operand of the operation.
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, MlirStringRef name)
Returns an attribute attached to the operation given its name.
void mlirOperationSetAttributeByName (MlirOperation op, MlirStringRef name, MlirAttribute attr)
Sets an attribute by name, replacing the existing if it exists or adding a new one otherwise.
bool mlirOperationRemoveAttributeByName (MlirOperation op, MlirStringRef name)
Removes an attribute by name.
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void *userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
void mlirOperationPrintWithFlags (MlirOperation op, MlirOpPrintingFlags flags, MlirStringCallback callback, void *userData)
Same as mlirOperationPrint but accepts flags controlling the printing behavior.
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
bool mlirOperationVerify (MlirOperation op)
Verify the operation and return true if it passes, false if it fails.
void mlirOperationMoveAfter (MlirOperation op, MlirOperation other)
Moves the given operation immediately after the other operation in its parent block.
void mlirOperationMoveBefore (MlirOperation op, MlirOperation other)
Moves the given operation immediately before the other operation in its parent block.
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
bool mlirRegionEqual (MlirRegion region, MlirRegion other)
Checks whether two region handles point to the same region.
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType const *args, MlirLocation const *locs)
Creates a new empty block with the given argument types and transfers ownership to the caller.
bool mlirBlockEqual (MlirBlock block, MlirBlock other)
Checks whether two blocks handles point to the same block.
MlirOperation mlirBlockGetParentOperation (MlirBlock block)
Returns the closest surrounding operation that contains this block.
MlirRegion mlirBlockGetParentRegion (MlirBlock block)
Returns the region that contains this block.
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
MlirOperation mlirBlockGetTerminator (MlirBlock block)
Returns the terminator operation in the block or null if no terminator.
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
void mlirBlockDetach (MlirBlock block)
Detach a block from the owning region and assume ownership.
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
MlirValue mlirBlockAddArgument (MlirBlock block, MlirType type, MlirLocation loc)
Appends an argument of the specified type to the block.
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void *userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
bool mlirValueEqual (MlirValue value1, MlirValue value2)
Returns 1 if two values are equal, 0 otherwise.
bool mlirValueIsABlockArgument (MlirValue value)
Returns 1 if the value is a block argument, 0 otherwise.
bool mlirValueIsAOpResult (MlirValue value)
Returns 1 if the value is an operation result, 0 otherwise.
MlirBlock mlirBlockArgumentGetOwner (MlirValue value)
Returns the block in which this value is defined as an argument.
intptr_t mlirBlockArgumentGetArgNumber (MlirValue value)
Returns the position of the value in the argument list of its block.
void mlirBlockArgumentSetType (MlirValue value, MlirType type)
Sets the type of the block argument to the given type.
MlirOperation mlirOpResultGetOwner (MlirValue value)
Returns an operation that produced this value as its result.
intptr_t mlirOpResultGetResultNumber (MlirValue value)
Returns the position of the value in the list of results of the operation that produced it.
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
void mlirValueDump (MlirValue value)
Prints the value to the standard error stream.
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void *userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
MlirType mlirTypeParseGet (MlirContext context, MlirStringRef type)
Parses a type. The type is owned by the context.
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
MlirTypeID mlirTypeGetTypeID (MlirType type)
Gets the type ID of the type.
bool mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
void mlirTypePrint (MlirType type, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
MlirAttribute mlirAttributeParseGet (MlirContext context, MlirStringRef attr)
Parses an attribute. The attribute is owned by the context.
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
MlirType mlirAttributeGetType (MlirAttribute attribute)
Gets the type of this attribute.
MlirTypeID mlirAttributeGetTypeID (MlirAttribute attr)
Gets the type id of the attribute.
bool mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void *userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
MlirNamedAttribute mlirNamedAttributeGet (MlirIdentifier name, MlirAttribute attr)
Associates an attribute with the name. Takes ownership of neither.
MlirIdentifier mlirIdentifierGet (MlirContext context, MlirStringRef str)
Gets an identifier with the given string value.
MlirContext mlirIdentifierGetContext (MlirIdentifier ident)
Returns the context associated with this identifier.
bool mlirIdentifierEqual (MlirIdentifier ident, MlirIdentifier other)
Checks whether two identifiers are the same.
MlirStringRef mlirIdentifierStr (MlirIdentifier ident)
Gets the string value of the identifier.
MlirStringRef mlirSymbolTableGetSymbolAttributeName ()
Returns the name of the attribute used to store symbol names compatible with symbol tables.
MlirStringRef mlirSymbolTableGetVisibilityAttributeName ()
Returns the name of the attribute used to store symbol visibility.
MlirSymbolTable mlirSymbolTableCreate (MlirOperation operation)
Creates a symbol table for the given operation.
void mlirSymbolTableDestroy (MlirSymbolTable symbolTable)
Destroys the symbol table created with mlirSymbolTableCreate.
MlirOperation mlirSymbolTableLookup (MlirSymbolTable symbolTable, MlirStringRef name)
Looks up a symbol with the given name in the given symbol table and returns the operation that corresponds to the symbol.
MlirAttribute mlirSymbolTableInsert (MlirSymbolTable symbolTable, MlirOperation operation)
Inserts the given operation into the given symbol table.
void mlirSymbolTableErase (MlirSymbolTable symbolTable, MlirOperation operation)
Removes the given operation from the symbol table and erases it.
MlirLogicalResult mlirSymbolTableReplaceAllSymbolUses (MlirStringRef oldSymbol, MlirStringRef newSymbol, MlirOperation from)
Attempt to replace all uses that are nested within the given operation of the given symbol 'oldSymbol' with the provided 'newSymbol'.
void mlirSymbolTableWalkSymbolTables (MlirOperation from, bool allSymUsesVisible, void(*callback)(MlirOperation, bool, void *userData), void *userData)
Walks all symbol table operations nested within, and including, op.
Macro Definition Documentation
APPEND_ELEMS
#define APPEND_ELEMS (type, sizeName, elemName)
Value:
state->elemName =                                                            \
      (type *)realloc(state->elemName, (state->sizeName + n) * sizeof(type));  \
  memcpy(state->elemName + state->sizeName, elemName, n * sizeof(type));       \
  state->sizeName += n;
Definition at line 248 of file IR.cpp.
Referenced by mlirOperationStateAddAttributes(), mlirOperationStateAddOperands(), mlirOperationStateAddOwnedRegions(), mlirOperationStateAddResults(), and mlirOperationStateAddSuccessors().
Function Documentation
inferOperationTypes()
static LogicalResult inferOperationTypes (OperationState & state) static
Definition at line 284 of file IR.cpp.
References mlir::OperationState::attributes, mlir::emitError(), mlir::failure(), mlir::OperationState::getContext(), mlir::NamedAttrList::getDictionary(), mlir::OperationName::getRegisteredInfo(), mlir::OperationState::location, mlir::OperationState::name, mlir::OperationState::operands, mlir::OperationState::regions, mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
Referenced by mlirOperationCreate().
mlirAttributeDump()
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
Definition at line 768 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirAttributeEqual()
bool mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
Definition at line 758 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyAttribute::operator==().
mlirAttributeGetContext()
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
Definition at line 746 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::create(), mlir::python::PyAttribute::createFromCapsule(), mlirTypeIsNull(), mlir::python::PyNamedAttribute::PyNamedAttribute(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirAttributeGetType()
MlirType mlirAttributeGetType (MlirAttribute attribute)
Gets the type of this attribute.
Definition at line 750 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlirTypeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirAttributeGetTypeID()
MlirTypeID mlirAttributeGetTypeID (MlirAttribute attr)
Gets the type id of the attribute.
Definition at line 754 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirTypeIsNull().
mlirAttributeParseGet()
MlirAttribute mlirAttributeParseGet (MlirContext context, MlirStringRef attr)
Parses an attribute. The attribute is owned by the context.
Definition at line 742 of file IR.cpp.
References mlir::parseAttribute(), unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirAttributePrint()
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void * userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 762 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockAddArgument()
MlirValue mlirBlockAddArgument (MlirBlock block, MlirType type, MlirLocation loc)
Appends an argument of the specified type to the block.
Returns the newly added argument.
Definition at line 646 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirBlockIsNull().
mlirBlockAppendOwnedOperation()
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
Definition at line 598 of file IR.cpp.
References unwrap().
Referenced by mlirBlockInsertOwnedOperationBefore(), mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockArgumentGetArgNumber()
intptr_t mlirBlockArgumentGetArgNumber (MlirValue value)
Returns the position of the value in the argument list of its block.
Definition at line 681 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockArgumentGetOwner()
MlirBlock mlirBlockArgumentGetOwner (MlirValue value)
Returns the block in which this value is defined as an argument.
Asserts if the value is not a block argument.
Definition at line 677 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyValue::createFromCapsule(), mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockArgumentSetType()
void mlirBlockArgumentSetType (MlirValue value, MlirType type)
Sets the type of the block argument to the given type.
Definition at line 686 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockCreate()
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType const * args, MlirLocation const * locs)
Creates a new empty block with the given argument types and transfers ownership to the caller.
Definition at line 557 of file IR.cpp.
References mlir::Block::addArgument(), unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockDestroy()
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
Definition at line 635 of file IR.cpp.
References unwrap().
Referenced by mlirRegionIsNull().
mlirBlockDetach()
void mlirBlockDetach (MlirBlock block)
Detach a block from the owning region and assume ownership.
Definition at line 637 of file IR.cpp.
References mlir::Region::getBlocks(), mlir::Block::getParent(), and unwrap().
Referenced by mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockEqual()
bool mlirBlockEqual (MlirBlock block, MlirBlock other)
Checks whether two blocks handles point to the same block.
This does not perform deep comparison.
Definition at line 565 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull().
mlirBlockGetArgument()
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
Definition at line 651 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockGetFirstOperation()
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
Definition at line 581 of file IR.cpp.
References mlir::Block::empty(), mlir::Block::front(), unwrap(), and wrap().
Referenced by mlir::python::PyInsertionPoint::atBlockBegin(), PyGlobalDebugFlag::bind(), mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockGetNextInRegion()
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
Definition at line 577 of file IR.cpp.
References unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), and mlirBlockIsNull().
mlirBlockGetNumArguments()
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
Definition at line 642 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockGetParentOperation()
MlirOperation mlirBlockGetParentOperation (MlirBlock block)
Returns the closest surrounding operation that contains this block.
Definition at line 569 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyValue::createFromCapsule(), mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockGetParentRegion()
MlirRegion mlirBlockGetParentRegion (MlirBlock block)
Returns the region that contains this block.
Definition at line 573 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirBlockGetTerminator()
MlirOperation mlirBlockGetTerminator (MlirBlock block)
Returns the terminator operation in the block or null if no terminator.
Definition at line 588 of file IR.cpp.
References mlir::Block::back(), mlir::Block::empty(), mlir::Operation::hasTrait(), unwrap(), and wrap().
Referenced by mlir::python::PyInsertionPoint::atBlockTerminator(), mlir::python::PyInsertionPoint::insert(), and mlirBlockIsNull().
mlirBlockInsertOwnedOperation()
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
This is an expensive operation that scans the block linearly, prefer insertBefore/After instead.
Definition at line 602 of file IR.cpp.
References unwrap().
Referenced by mlirBlockIsNull().
mlirBlockInsertOwnedOperationAfter()
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
If the reference is null, prepends the operation. Otherwise, the reference must belong to the block.
Definition at line 608 of file IR.cpp.
References mlir::Block::begin(), mlir::Block::getOperations(), mlirOperationIsNull(), and unwrap().
Referenced by mlirBlockIsNull().
mlirBlockInsertOwnedOperationBefore()
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
If the reference is null, appends the operation. Otherwise, the reference must belong to the block.
Definition at line 623 of file IR.cpp.
References mlirBlockAppendOwnedOperation(), mlirOperationIsNull(), and unwrap().
Referenced by mlir::python::PyInsertionPoint::insert(), and mlirBlockIsNull().
mlirBlockPrint()
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void * userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 655 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirBlockIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirContextAppendDialectRegistry()
void mlirContextAppendDialectRegistry (MlirContext ctx, MlirDialectRegistry registry)
Append the contents of the given dialect registry to the registry associated with the context.
Definition at line 56 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextCreate()
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
Definition at line 34 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().
mlirContextDestroy()
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
Definition at line 43 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyMlirContext::~PyMlirContext().
mlirContextEnableMultithreading()
void mlirContextEnableMultithreading (MlirContext context, bool enable)
Set threading mode (must be set to false to mlir-print-ir-after-all).
Definition at line 76 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirContextEqual()
bool mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
Definition at line 39 of file IR.cpp.
References unwrap().
mlirContextGetAllowUnregisteredDialects()
bool mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
Definition at line 49 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirContextGetNumLoadedDialects()
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
Definition at line 63 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetNumRegisteredDialects()
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
A registered dialect will be loaded if needed by the parser.
Definition at line 52 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetOrLoadDialect()
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
If the dialect is not registered with the context, returns null. Use mlirContextLoad<Name>Dialect to load an unregistered dialect.
Definition at line 67 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyDialects::getDialectForKey(), mlirContextIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirContextIsRegisteredOperation()
bool mlirContextIsRegisteredOperation (MlirContext context, MlirStringRef name)
Returns whether the given fully-qualified operation (i.e.
'dialect.operation') is registered with the context. This will return true if the dialect is loaded and the operation is registered within the dialect.
Definition at line 72 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirContextSetAllowUnregisteredDialects()
void mlirContextSetAllowUnregisteredDialects (MlirContext context, bool allow)
Sets whether unregistered dialects are allowed in this context.
Definition at line 45 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirDialectEqual()
bool mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
Dialects from different contexts will not compare equal.
Definition at line 88 of file IR.cpp.
References unwrap().
Referenced by mlirDialectIsNull().
mlirDialectGetContext()
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
Definition at line 84 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirDialectGetNamespace()
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
Definition at line 92 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirDialectIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirDialectRegistryCreate()
MlirDialectRegistry mlirDialectRegistryCreate ()
Creates a dialect registry and transfers its ownership to the caller.
Definition at line 100 of file IR.cpp.
References wrap().
Referenced by mlirDialectIsNull().
mlirDialectRegistryDestroy()
void mlirDialectRegistryDestroy (MlirDialectRegistry registry)
Takes a dialect registry owned by the caller and destroys it.
Definition at line 104 of file IR.cpp.
References unwrap().
Referenced by mlirDialectRegistryIsNull().
mlirIdentifierEqual()
bool mlirIdentifierEqual (MlirIdentifier ident, MlirIdentifier other)
Checks whether two identifiers are the same.
Definition at line 787 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull().
mlirIdentifierGet()
MlirIdentifier mlirIdentifierGet (MlirContext context, MlirStringRef str)
Gets an identifier with the given string value.
Definition at line 779 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::create(), mlirAttributeIsNull(), and mlir::python::PyNamedAttribute::PyNamedAttribute().
mlirIdentifierGetContext()
MlirContext mlirIdentifierGetContext (MlirIdentifier ident)
Returns the context associated with this identifier.
Definition at line 783 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirAttributeIsNull().
mlirIdentifierStr()
MlirStringRef mlirIdentifierStr (MlirIdentifier ident)
Gets the string value of the identifier.
Definition at line 791 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::createOpView(), mlirAttributeIsNull(), mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::PyConcreteOpInterface(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationCallSiteGet()
MlirLocation mlirLocationCallSiteGet (MlirLocation callee, MlirLocation caller)
Creates a call site location with a callee and a caller.
Definition at line 149 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirDialectRegistryIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationEqual()
bool mlirLocationEqual (MlirLocation l1, MlirLocation l2)
Checks if two locations are equal.
Definition at line 174 of file IR.cpp.
References unwrap().
Referenced by mlirLocationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationFileLineColGet()
MlirLocation mlirLocationFileLineColGet (MlirContext context, MlirStringRef filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
Definition at line 142 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirDialectRegistryIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationFusedGet()
MlirLocation mlirLocationFusedGet (MlirContext ctx, intptr_t nLocations, MlirLocation const * locations, MlirAttribute metadata)
Creates a fused location with an array of locations and metadata.
Definition at line 153 of file IR.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlirDialectRegistryIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationGetContext()
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
Definition at line 178 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyLocation::createFromCapsule(), mlir::python::PyDiagnostic::getLocation(), and mlirDialectRegistryIsNull().
mlirLocationNameGet()
MlirLocation mlirLocationNameGet (MlirContext context, MlirStringRef name, MlirLocation childLoc)
Creates a name location owned by the given context.
Providing null location for childLoc is allowed and if childLoc is null location, then the behavior is the same as having unknown child location.
Definition at line 161 of file IR.cpp.
References mlirLocationIsNull(), unwrap(), and wrap().
Referenced by mlirDialectRegistryIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationPrint()
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 182 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirLocationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirLocationUnknownGet()
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
Definition at line 170 of file IR.cpp.
References unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), mlirDialectRegistryIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirModuleCreateEmpty()
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
Definition at line 192 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirLocationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirModuleCreateParse()
MlirModule mlirModuleCreateParse (MlirContext context, MlirStringRef module)
Parses a module from the string and transfers ownership to the caller.
Definition at line 196 of file IR.cpp.
References mlir::OwningOpRef< OpTy >::release(), and unwrap().
Referenced by mlirLocationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirModuleDestroy()
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
Definition at line 212 of file IR.cpp.
References unwrap().
Referenced by mlirModuleIsNull(), and mlir::python::PyModule::~PyModule().
mlirModuleFromOperation()
MlirModule mlirModuleFromOperation (MlirOperation op)
Views the generic operation as a module.
The returned module is null when the input operation was not a ModuleOp.
Definition at line 222 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirModuleIsNull().
mlirModuleGetBody()
MlirBlock mlirModuleGetBody (MlirModule module)
Gets the body of the module, i.e. the only block it contains.
Definition at line 208 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirLocationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirModuleGetContext()
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
Definition at line 204 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyModule::forModule(), and mlirLocationIsNull().
mlirModuleGetOperation()
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
Definition at line 218 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirModuleIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirNamedAttributeGet()
MlirNamedAttribute mlirNamedAttributeGet (MlirIdentifier name, MlirAttribute attr)
Associates an attribute with the name. Takes ownership of neither.
Definition at line 770 of file IR.cpp.
Referenced by mlir::python::PyOperation::create(), mlirAttributeIsNull(), and mlir::python::PyNamedAttribute::PyNamedAttribute().
mlirOperationClone()
MlirOperation mlirOperationClone (MlirOperation op)
Creates a deep copy of an operation.
The operation is not inserted and ownership is transferred to the caller.
Definition at line 353 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::clone().
mlirOperationCreate()
MlirOperation mlirOperationCreate (MlirOperationState * state)
Creates an operation and transfers ownership to the caller.
Note that caller owned child objects are transferred in this call and must not be further used. Particularly, this applies to any regions added to the state (the implementation may invalidate any such pointers).
This call can fail under the following conditions, in which case, it will return a null operation and emit diagnostics:
Result type inference is enabled and cannot be performed.
Definition at line 315 of file IR.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), MlirNamedAttribute::attribute, MlirOperationState::attributes, mlir::OperationState::attributes, mlir::Operation::create(), MlirOperationState::enableResultTypeInference, mlir::failed(), inferOperationTypes(), MlirOperationState::location, MlirNamedAttribute::name, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, mlir::NamedAttrList::reserve(), MlirOperationState::results, MlirOperationState::successors, mlir::OperationState::types, unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyOperation::create().
mlirOperationDestroy()
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
Definition at line 357 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::erase(), and mlir::python::PyOperation::~PyOperation().
mlirOperationDump()
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
Definition at line 483 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationEqual()
bool mlirOperationEqual (MlirOperation op, MlirOperation other)
Checks whether two operation handles point to the same operation.
This does not perform deep comparison.
Definition at line 361 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetAttribute()
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
Definition at line 452 of file IR.cpp.
References mlir::NamedAttribute::getName(), mlir::NamedAttribute::getValue(), unwrap(), and wrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetAttributeByName()
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, MlirStringRef name)
Returns an attribute attached to the operation given its name.
Definition at line 457 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PySymbolTable::insert(), mlirOperationIsNull(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetBlock()
MlirBlock mlirOperationGetBlock (MlirOperation op)
Gets the block that owns this operation, returning null if the operation is not owned.
Definition at line 383 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::getBlock(), and mlirOperationIsNull().
mlirOperationGetContext()
MlirContext mlirOperationGetContext (MlirOperation op)
Gets the context this operation is associated with.
Definition at line 365 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::createFromCapsule(), mlir::python::PyValue::createFromCapsule(), and mlirOperationIsNull().
mlirOperationGetFirstRegion()
MlirRegion mlirOperationGetFirstRegion (MlirOperation op)
Returns first region attached to the operation.
Definition at line 399 of file IR.cpp.
References mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), unwrap(), and wrap().
Referenced by mlirRegionIsNull().
mlirOperationGetLocation()
MlirLocation mlirOperationGetLocation (MlirOperation op)
Gets the location of the operation.
Definition at line 369 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetName()
MlirIdentifier mlirOperationGetName (MlirOperation op)
Gets the name of the operation as an identifier.
Definition at line 379 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::createOpView(), mlirOperationIsNull(), mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::PyConcreteOpInterface(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetNextInBlock()
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
Definition at line 415 of file IR.cpp.
References unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), and mlirOperationIsNull().
mlirOperationGetNumAttributes()
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
Definition at line 448 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetNumOperands()
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
Definition at line 419 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetNumRegions()
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
Definition at line 391 of file IR.cpp.
References unwrap().
Referenced by PyGlobalDebugFlag::bind(), and mlirOperationIsNull().
mlirOperationGetNumResults()
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
Definition at line 432 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetNumSuccessors()
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
Definition at line 440 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull().
mlirOperationGetOperand()
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
Definition at line 423 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetParentOperation()
MlirOperation mlirOperationGetParentOperation (MlirOperation op)
Gets the operation that owns this operation, returning null if the operation is not owned.
Definition at line 387 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOperation::getParentOperation(), and mlirOperationIsNull().
mlirOperationGetRegion()
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
Definition at line 395 of file IR.cpp.
References unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), and mlirOperationIsNull().
mlirOperationGetResult()
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
Definition at line 436 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationGetSuccessor()
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
Definition at line 444 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationGetTypeID()
MlirTypeID mlirOperationGetTypeID (MlirOperation op)
Gets the type id of the operation.
Returns null if the operation does not have a registered operation description.
Definition at line 373 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirOperationIsNull().
mlirOperationMoveAfter()
void mlirOperationMoveAfter (MlirOperation op, MlirOperation other)
Moves the given operation immediately after the other operation in its parent block.
The given operation may be owned by the caller or by its current block. The other operation must belong to a block. In any case, the ownership is transferred to the block of the other operation.
Definition at line 489 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyOperationBase::moveAfter().
mlirOperationMoveBefore()
void mlirOperationMoveBefore (MlirOperation op, MlirOperation other)
Moves the given operation immediately before the other operation in its parent block.
The given operation may be owner by the caller or by its current block. The other operation must belong to a block. In any case, the ownership is transferred to the block of the other operation.
Definition at line 493 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyOperationBase::moveBefore().
mlirOperationPrint()
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void * userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 471 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirOperationIsNull().
mlirOperationPrintWithFlags()
void mlirOperationPrintWithFlags (MlirOperation op, MlirOpPrintingFlags flags, MlirStringCallback callback, void * userData)
Same as mlirOperationPrint but accepts flags controlling the printing behavior.
Definition at line 477 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PyOperationBase::print().
mlirOperationRemoveAttributeByName()
bool mlirOperationRemoveAttributeByName (MlirOperation op, MlirStringRef name)
Removes an attribute by name.
Returns false if the attribute was not found and true if removed.
Definition at line 467 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationRemoveFromParent()
void mlirOperationRemoveFromParent (MlirOperation op)
Removes the given operation from its parent block.
The operation is not destroyed. The ownership of the operation is transferred to the caller.
Definition at line 359 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::detachFromParent().
mlirOperationSetAttributeByName()
void mlirOperationSetAttributeByName (MlirOperation op, MlirStringRef name, MlirAttribute attr)
Sets an attribute by name, replacing the existing if it exists or adding a new one otherwise.
Definition at line 462 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationSetOperand()
void mlirOperationSetOperand (MlirOperation op, intptr_t pos, MlirValue newValue)
Sets the pos-th operand of the operation.
Definition at line 427 of file IR.cpp.
References unwrap().
Referenced by mlirOperationIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOperationStateAddAttributes()
void mlirOperationStateAddAttributes (MlirOperationState * state, intptr_t n, MlirNamedAttribute const * attributes)
Definition at line 271 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyOperation::create().
mlirOperationStateAddOperands()
void mlirOperationStateAddOperands (MlirOperationState * state, intptr_t n, MlirValue const * operands)
Definition at line 259 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyOperation::create().
mlirOperationStateAddOwnedRegions()
void mlirOperationStateAddOwnedRegions (MlirOperationState * state, intptr_t n, MlirRegion const * regions)
Definition at line 263 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyOperation::create().
mlirOperationStateAddResults()
void mlirOperationStateAddResults (MlirOperationState * state, intptr_t n, MlirType const * results)
Adds a list of components to the operation state.
Definition at line 254 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyOperation::create().
mlirOperationStateAddSuccessors()
void mlirOperationStateAddSuccessors (MlirOperationState * state, intptr_t n, MlirBlock const * successors)
Definition at line 267 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyOperation::create().
mlirOperationStateEnableResultTypeInference()
void mlirOperationStateEnableResultTypeInference (MlirOperationState * state)
Enables result type inference for the operation under construction.
If enabled, then the caller must not have called mlirOperationStateAddResults(). Note that if enabled, the mlirOperationCreate() call is failable: it will return a null operation on inference failure and will emit diagnostics.
Definition at line 276 of file IR.cpp.
References MlirOperationState::enableResultTypeInference.
mlirOperationStateGet()
MlirOperationState mlirOperationStateGet (MlirStringRef name, MlirLocation loc)
Constructs an operation state from a name and a location.
Definition at line 230 of file IR.cpp.
References MlirOperationState::attributes, MlirOperationState::enableResultTypeInference, MlirOperationState::location, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, MlirOperationState::results, and MlirOperationState::successors.
Referenced by mlir::python::PyOperation::create().
mlirOperationVerify()
bool mlirOperationVerify (MlirOperation op)
Verify the operation and return true if it passes, false if it fails.
Definition at line 485 of file IR.cpp.
References mlir::succeeded(), unwrap(), and mlir::verify().
Referenced by mlirOperationIsNull(), mlir::python::PyOperationBase::print(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOpPrintingFlagsCreate()
MlirOpPrintingFlags mlirOpPrintingFlagsCreate ()
Creates new printing flags with defaults, intended for customization.
Must be freed with a call to mlirOpPrintingFlagsDestroy().
Definition at line 112 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyOperationBase::print().
mlirOpPrintingFlagsDestroy()
void mlirOpPrintingFlagsDestroy (MlirOpPrintingFlags flags)
Destroys printing flags created with mlirOpPrintingFlagsCreate.
Definition at line 116 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperationBase::print().
mlirOpPrintingFlagsElideLargeElementsAttrs()
void mlirOpPrintingFlagsElideLargeElementsAttrs (MlirOpPrintingFlags flags, intptr_t largeElementLimit)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
The largeElementLimit is used to configure what is considered to be a "large" ElementsAttr by providing an upper limit to the number of elements.
Definition at line 120 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperationBase::print().
mlirOpPrintingFlagsEnableDebugInfo()
void mlirOpPrintingFlagsEnableDebugInfo (MlirOpPrintingFlags flags, bool prettyForm)
Enable printing of debug information.
If 'prettyForm' is set to true, debug information is printed in a more readable 'pretty' form. Note: The IR generated with 'prettyForm' is not parsable.
Definition at line 125 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperationBase::print().
mlirOpPrintingFlagsPrintGenericOpForm()
void mlirOpPrintingFlagsPrintGenericOpForm (MlirOpPrintingFlags flags)
Always print operations in the generic form.
Definition at line 130 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperationBase::print().
mlirOpPrintingFlagsUseLocalScope()
void mlirOpPrintingFlagsUseLocalScope (MlirOpPrintingFlags flags)
Use local scope when printing the operation.
This allows for using the printer in a more localized and thread-safe setting, but may not necessarily be identical to what the IR will look like when dumping the full module.
Definition at line 134 of file IR.cpp.
References unwrap().
mlirOpResultGetOwner()
MlirOperation mlirOpResultGetOwner (MlirValue value)
Returns an operation that produced this value as its result.
Asserts if the value is not an op result.
Definition at line 690 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyValue::createFromCapsule(), mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirOpResultGetResultNumber()
intptr_t mlirOpResultGetResultNumber (MlirValue value)
Returns the position of the value in the list of results of the operation that produced it.
Definition at line 694 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirRegionAppendOwnedBlock()
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
Definition at line 514 of file IR.cpp.
References unwrap().
Referenced by PyGlobalDebugFlag::bind(), mlirRegionInsertOwnedBlockBefore(), mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirRegionCreate()
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
Definition at line 501 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyOperation::create(), and mlirOperationIsNull().
mlirRegionDestroy()
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
Definition at line 549 of file IR.cpp.
Referenced by mlirOperationIsNull().
mlirRegionEqual()
bool mlirRegionEqual (MlirRegion region, MlirRegion other)
Checks whether two region handles point to the same region.
This does not perform deep comparison.
Definition at line 503 of file IR.cpp.
References unwrap().
Referenced by mlirRegionIsNull().
mlirRegionGetFirstBlock()
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
Definition at line 507 of file IR.cpp.
References mlir::Region::empty(), mlir::Region::front(), unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirRegionGetNextInOperation()
MlirRegion mlirRegionGetNextInOperation (MlirRegion region)
Returns the region immediately following the given region in its parent operation.
Definition at line 406 of file IR.cpp.
References mlir::Operation::getNumRegions(), mlir::Region::getParentOp(), mlir::Operation::getRegion(), mlir::Region::getRegionNumber(), unwrap(), and wrap().
Referenced by mlirRegionIsNull().
mlirRegionInsertOwnedBlock()
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
This is an expensive operation that linearly scans the region, prefer insertAfter/Before instead.
Definition at line 518 of file IR.cpp.
References unwrap().
Referenced by mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirRegionInsertOwnedBlockAfter()
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, prepends the block to the region.
Definition at line 524 of file IR.cpp.
References mlir::Region::begin(), mlir::Region::getBlocks(), mlirBlockIsNull(), and unwrap().
Referenced by mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirRegionInsertOwnedBlockBefore()
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, appends the block to the region.
Definition at line 538 of file IR.cpp.
References mlirBlockIsNull(), mlirRegionAppendOwnedBlock(), and unwrap().
Referenced by mlirRegionIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirSymbolTableCreate()
MlirSymbolTable mlirSymbolTableCreate (MlirOperation operation)
Creates a symbol table for the given operation.
If the operation does not have the SymbolTable trait, returns a null symbol table.
Definition at line 807 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PySymbolTable::PySymbolTable().
mlirSymbolTableDestroy()
void mlirSymbolTableDestroy (MlirSymbolTable symbolTable)
Destroys the symbol table created with mlirSymbolTableCreate.
This does not affect the operations in the table.
Definition at line 813 of file IR.cpp.
References unwrap().
Referenced by mlirSymbolTableIsNull(), and mlir::python::PySymbolTable::~PySymbolTable().
mlirSymbolTableErase()
void mlirSymbolTableErase (MlirSymbolTable symbolTable, MlirOperation operation)
Removes the given operation from the symbol table and erases it.
Definition at line 827 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PySymbolTable::erase(), and mlirSymbolTableIsNull().
mlirSymbolTableGetSymbolAttributeName()
MlirStringRef mlirSymbolTableGetSymbolAttributeName ()
Returns the name of the attribute used to store symbol names compatible with symbol tables.
Definition at line 799 of file IR.cpp.
References mlir::SymbolTable::getSymbolAttrName(), and wrap().
Referenced by mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::insert(), mlirAttributeIsNull(), and mlir::python::PySymbolTable::setSymbolName().
mlirSymbolTableGetVisibilityAttributeName()
MlirStringRef mlirSymbolTableGetVisibilityAttributeName ()
Returns the name of the attribute used to store symbol visibility.
Definition at line 803 of file IR.cpp.
References mlir::SymbolTable::getVisibilityAttrName(), and wrap().
Referenced by mlir::python::PySymbolTable::getVisibility(), mlirAttributeIsNull(), and mlir::python::PySymbolTable::setVisibility().
mlirSymbolTableInsert()
MlirAttribute mlirSymbolTableInsert (MlirSymbolTable symbolTable, MlirOperation operation)
Inserts the given operation into the given symbol table.
The operation must have the symbol trait. If the symbol table already has a symbol with the same name, renames the symbol being inserted to ensure name uniqueness. Note that this does not move the operation itself into the block of the symbol table operation, this should be done separately. Returns the name of the symbol after insertion.
Definition at line 822 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PySymbolTable::insert(), and mlirSymbolTableIsNull().
mlirSymbolTableLookup()
MlirOperation mlirSymbolTableLookup (MlirSymbolTable symbolTable, MlirStringRef name)
Looks up a symbol with the given name in the given symbol table and returns the operation that corresponds to the symbol.
If the symbol cannot be found, returns a null operation.
Definition at line 817 of file IR.cpp.
References MlirStringRef::data, MlirStringRef::length, unwrap(), and wrap().
Referenced by mlir::python::PySymbolTable::dunderGetItem(), mlirSymbolTableIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirSymbolTableReplaceAllSymbolUses()
MlirLogicalResult mlirSymbolTableReplaceAllSymbolUses (MlirStringRef oldSymbol, MlirStringRef newSymbol, MlirOperation from)
Attempt to replace all uses that are nested within the given operation of the given symbol 'oldSymbol' with the provided 'newSymbol'.
This does not traverse into nested symbol tables. Will fail atomically if there are any unknown operations that may be potential symbol tables.
Definition at line 832 of file IR.cpp.
References mlir::SymbolTable::replaceAllSymbolUses(), unwrap(), and wrap().
Referenced by mlirSymbolTableIsNull(), and mlir::python::PySymbolTable::replaceAllSymbolUses().
mlirSymbolTableWalkSymbolTables()
void mlirSymbolTableWalkSymbolTables (MlirOperation from, bool allSymUsesVisible, void(*)(MlirOperation, bool, void *userData) callback, void * userData)
Walks all symbol table operations nested within, and including, op.
For each symbol table operation, the provided callback is invoked with the op and a boolean signifying if the symbols within that symbol table can be treated as if all uses within the IR are visible to the caller. allSymUsesVisible identifies whether all of the symbol uses of symbols within op are visible.
Definition at line 843 of file IR.cpp.
References unwrap(), mlir::SymbolTable::walkSymbolTables(), and wrap().
Referenced by mlirSymbolTableIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirTypeDump()
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
Definition at line 736 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirTypeEqual()
bool mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
Definition at line 727 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirTypeGetContext()
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
Definition at line 719 of file IR.cpp.
References unwrap(), and wrap().
Referenced by PyGlobalDebugFlag::bind(), mlir::python::PyType::createFromCapsule(), mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirTypeGetTypeID()
MlirTypeID mlirTypeGetTypeID (MlirType type)
Gets the type ID of the type.
Definition at line 723 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull().
mlirTypeParseGet()
MlirType mlirTypeParseGet (MlirContext context, MlirStringRef type)
Parses a type. The type is owned by the context.
Definition at line 715 of file IR.cpp.
References mlir::parseType(), unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirTypePrint()
void mlirTypePrint (MlirType type, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 731 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirValueDump()
void mlirValueDump (MlirValue value)
Prints the value to the standard error stream.
Definition at line 703 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirValueEqual()
bool mlirValueEqual (MlirValue value1, MlirValue value2)
Returns 1 if two values are equal, 0 otherwise.
Definition at line 665 of file IR.cpp.
References unwrap().
Referenced by mlirValueIsNull().
mlirValueGetType()
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
Definition at line 699 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirValueIsABlockArgument()
bool mlirValueIsABlockArgument (MlirValue value)
Returns 1 if the value is a block argument, 0 otherwise.
Definition at line 669 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyValue::createFromCapsule(), mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirValueIsAOpResult()
bool mlirValueIsAOpResult (MlirValue value)
Returns 1 if the value is an operation result, 0 otherwise.
Definition at line 673 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyValue::createFromCapsule(), mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().
mlirValuePrint()
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void * userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 705 of file IR.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirValueIsNull(), and mlir::python::PySymbolTable::walkSymbolTables().