MLIR: lib/Bindings/Python/IRAffine.cpp File Reference
IRAffine.cpp File Reference
#include <utility>
#include "IRModule.h"
#include "PybindUtils.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/Bindings/Python/Interop.h"
#include "mlir-c/IntegerSet.h"
Functions
template<typename PyType , typename CType >
static void pyListToVector (const py::list &list, llvm::SmallVectorImpl< CType > &result, StringRef action)
Attempts to populate result with the content of list casted to the appropriate type (Python and C types are provided as template arguments).
template<typename PermutationTy >
static bool isPermutation (std::vector< PermutationTy > permutation)
Variables
static const char kDumpDocstring []
Function Documentation
isPermutation()
template<typename PermutationTy > static bool isPermutation (std::vector< PermutationTy > permutation) static
Definition at line 57 of file IRAffine.cpp.
References mlir::python::BaseContextObject::getContext(), mlirAffineConstantExprGet(), mlirAffineConstantExprGetValue(), mlirAffineDimExprGet(), mlirAffineDimExprGetPosition(), mlirAffineExprIsABinary(), mlirAffineExprIsAConstant(), mlirAffineExprIsADim(), mlirAffineExprIsASymbol(), mlirAffineSymbolExprGet(), mlirAffineSymbolExprGetPosition(), mlir::python::SetPyError(), and value.
Referenced by mlir::AffineMap::getPermutedPosition(), mlir::linalg::makeTransposeOp(), and mlir::AffineMap::shiftSymbols().
pyListToVector()
template<typename PyType , typename CType > static void pyListToVector (const py::list & list, llvm::SmallVectorImpl< CType > & result, StringRef action) static
Attempts to populate result with the content of list casted to the appropriate type (Python and C types are provided as template arguments).
Throws errors in case of failure, using "action" to describe what the caller was attempting to do.
Definition at line 35 of file IRAffine.cpp.
Variable Documentation
kDumpDocstring
const char kDumpDocstring[] static
Initial value:
=
    R"(Dumps a debug representation of the object to stderr.)"
Definition at line 27 of file IRAffine.cpp.
Referenced by mlir::python::PyIntegerSet::createFromCapsule().