MLIR: lib/Dialect/Linalg/IR/LinalgOps.cpp File Reference
LinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Arithmetic/Utils/Utils.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Parser/Parser.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yamlgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_CLASSES
#define GET_OP_CLASSES
Typedefs
using RegionBuilderFn = llvm::function_ref< void(ImplicitLocOpBuilder &, Block &, ArrayRef< NamedAttribute >)>
Functions
static void fillStructuredOpRegion (OpBuilder &opBuilder, Region &region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder)
Fills the region of a structured operation using the provided regionBuilder.
static void buildStructuredOp (OpBuilder &b, OperationState &state, llvm::Optional< TypeRange > resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes, RegionBuilderFn regionBuilder)
Creates a structured operation given inputs, outputs, and attributes.
static ParseResult parseCommonStructuredOpParts (OpAsmParser &parser, OperationState &result, SmallVectorImpl< Type > &inputTypes, SmallVectorImpl< Type > &outputTypes)
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
static void printCommonStructuredOpParts (OpAsmPrinter &p, ValueRange inputs, ValueRange outputs)
static ParseResult parseNamedStructuredOpRegion (OpAsmParser &parser, Region &region, unsigned numRegionArgs, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder)
static ParseResult parseNamedStructuredOpResults (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes)
static ParseResult parseNamedStructuredOp (OpAsmParser &parser, OperationState &result, unsigned numRegionArgs, RegionBuilderFn regionBuilder)
static void printNamedStructuredOpResults (OpAsmPrinter &p, TypeRange resultTypes)
static void printNamedStructuredOp (OpAsmPrinter &p, Operation *op, ValueRange inputs, ValueRange outputs)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
static bool hasaUniqueDim (ArrayRef< AffineMap > maps, unsigned testMapLocation)
Helper function to find if there is atleast one dimension in an AffineMap testMap that is contained in testMapLocation of maps but not in any other locations.
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> &effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs)
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp)
static void appendMangledType (llvm::raw_string_ostream &ss, Type t)
Macro Definition Documentation
GET_OP_CLASSES [1/2]
#define GET_OP_CLASSES
Definition at line 1440 of file LinalgOps.cpp.
GET_OP_CLASSES [2/2]
#define GET_OP_CLASSES
Definition at line 1440 of file LinalgOps.cpp.
Typedef Documentation
RegionBuilderFn
using RegionBuilderFn = llvm::function_ref<void(ImplicitLocOpBuilder &, Block &, ArrayRef<NamedAttribute>)>
Definition at line 49 of file LinalgOps.cpp.
Function Documentation
appendMangledType()
static void appendMangledType (llvm::raw_string_ostream & ss, Type t) static
Definition at line 1487 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isSignlessIntOrIndexOrFloat().
Referenced by mlir::linalg::generateLibraryCallName().
buildStructuredOp()
static void buildStructuredOp (OpBuilder & b, OperationState & state, llvm::Optional< TypeRange > resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes, RegionBuilderFn regionBuilder) static
Creates a structured operation given inputs, outputs, and attributes.
The result types are derived automatically if resultTensorTypes is none. The body of the operation is filled using regionBuilder. All ods-gen created structured operations use the method to implement their builders.
Definition at line 94 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, fillStructuredOpRegion(), mlir::NamedAttrList::getAttrs(), mlir::Builder::getI32VectorAttr(), and mlir::ValueRange::getTypes().
fillStructuredOpRegion()
static void fillStructuredOpRegion (OpBuilder & opBuilder, Region & region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder) static
Fills the region of a structured operation using the provided regionBuilder.
The method is used by both named structured ops created by ods-gen and by manually defined C++ ops. It is called by both builders and parsers and creates a block with arguments corresponding to the elemental types of inputTypes and outputTypes. All output types are asserted to be ShapedType.
Definition at line 57 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::getElementTypeOrSelf(), mlir::Builder::getUnknownLoc(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by buildStructuredOp(), and parseNamedStructuredOpRegion().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
Definition at line 257 of file LinalgOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::getOpOperands(), and mlir::success().
Referenced by getGenericEffectsImpl().
getGenericEffectsImpl()
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> & effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs) static
Definition at line 819 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::OperationState::attributes, mlir::tensor::canFoldIntoProducerOp(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::dispatchIndexOpFoldResults(), mlir::emitError(), mlir::detail::enumerate(), mlir::Block::eraseArgument(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), foldMemRefCast(), mlir::Block::front(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::getAsOpFoldResult(), mlir::AsmParser::getCurrentLocation(), mlir::Value::getDefiningOp(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexAttr(), mlir::getMixedSizes(), getShape(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Block::getTerminator(), mlir::Value::getType(), hasaUniqueDim(), mlir::RewriterBase::inlineRegionBefore(), mlir::RewriterBase::notifyMatchFailure(), mlir::OperationState::operands, mlir::AsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::Value::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpAsmParser::resolveOperands(), mlir::success(), mlir::Value::use_empty(), value, mlir::verify(), and mlir::verifyListOfOperandsOrIntegers().
hasaUniqueDim()
static bool hasaUniqueDim (ArrayRef< AffineMap > maps, unsigned testMapLocation) static
Helper function to find if there is atleast one dimension in an AffineMap testMap that is contained in testMapLocation of maps but not in any other locations.
Definition at line 272 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::applyMapToValues(), mlir::NamedAttrList::assign(), mlir::OperationState::attributes, mlir::bindSymbols(), mlir::presburger::ceil(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::AffineExpr::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitWarning(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::presburger::floor(), mlir::AffineMap::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArguments(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::getElementTypeOrSelf(), mlir::Value::getLoc(), mlir::AffineMap::getResults(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getStringAttr(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Builder::getUnknownLoc(), mlir::getValueOrCreateConstantIndexOp(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::OperationState::location, mlir::RewriterBase::notifyMatchFailure(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::parseAttribute(), mlir::AsmParser::parseAttribute(), parseCommonStructuredOpParts(), mlir::AsmParser::parseEqual(), parseNamedStructuredOpResults(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), print(), printCommonStructuredOpParts(), printNamedStructuredOpResults(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OperationState::regions, mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::succeeded(), mlir::success(), and value.
Referenced by getGenericEffectsImpl().
parseCommonStructuredOpParts()
static ParseResult parseCommonStructuredOpParts (OpAsmParser & parser, OperationState & result, SmallVectorImpl< Type > & inputTypes, SmallVectorImpl< Type > & outputTypes) static
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Does not handle regions.
Definition at line 124 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::OperationState::operands, mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
Referenced by hasaUniqueDim(), and parseNamedStructuredOp().
parseNamedStructuredOp()
static ParseResult parseNamedStructuredOp (OpAsmParser & parser, OperationState & result, unsigned numRegionArgs, RegionBuilderFn regionBuilder) static
Definition at line 201 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::NamedAttrList::getAttrs(), parseCommonStructuredOpParts(), parseNamedStructuredOpRegion(), parseNamedStructuredOpResults(), and mlir::success().
parseNamedStructuredOpRegion()
static ParseResult parseNamedStructuredOpRegion (OpAsmParser & parser, Region & region, unsigned numRegionArgs, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder) static
Definition at line 175 of file LinalgOps.cpp.
References mlir::AsmParser::emitError(), fillStructuredOpRegion(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), and mlir::success().
Referenced by parseNamedStructuredOp().
parseNamedStructuredOpResults()
static ParseResult parseNamedStructuredOpResults (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes) static
Definition at line 194 of file LinalgOps.cpp.
References mlir::failure(), mlir::AsmParser::parseOptionalArrowTypeList(), and mlir::success().
Referenced by hasaUniqueDim(), and parseNamedStructuredOp().
printCommonStructuredOpParts()
static void printCommonStructuredOpParts (OpAsmPrinter & p, ValueRange inputs, ValueRange outputs) static
Definition at line 163 of file LinalgOps.cpp.
References mlir::ValueRange::getTypes().
Referenced by hasaUniqueDim(), and printNamedStructuredOp().
printNamedStructuredOp()
static void printNamedStructuredOp (OpAsmPrinter & p, Operation * op, ValueRange inputs, ValueRange outputs) static
Definition at line 234 of file LinalgOps.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getResultTypes(), printCommonStructuredOpParts(), printNamedStructuredOpResults(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printNamedStructuredOpResults()
static void printNamedStructuredOpResults (OpAsmPrinter & p, TypeRange resultTypes) static
Definition at line 227 of file LinalgOps.cpp.
References mlir::AsmPrinter::printOptionalArrowTypeList().
Referenced by hasaUniqueDim(), and printNamedStructuredOp().
verifyYield()
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp) static
Definition at line 1386 of file LinalgOps.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), mlir::success(), and mlir::verify().