MLIR: lib/Dialect/Linalg/Transforms/BufferizableOpInterfaceImpl.cpp File Reference
BufferizableOpInterfaceImpl.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_LIST
Functions
static bool neededValuesDominateInsertionPoint (const DominanceInfo &domInfo, Operation *insertionPoint, const SmallVector< Value > &neededValues)
Return true if all neededValues are in scope at the given insertionPoint.
static bool insertionPointDominatesUses (const DominanceInfo &domInfo, Operation *insertionPoint, Operation *initTensorOp)
Return true if the given insertionPoint dominates all uses of initTensorOp.
static Operation * findValidInsertionPoint (Operation *initTensorOp, const SmallVector< Value > &neededValues)
Find a valid insertion point for a replacement of initTensorOp, assuming that the replacement may use any value from neededValues.
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
findValidInsertionPoint()
static Operation* findValidInsertionPoint (Operation * initTensorOp, const SmallVector< Value > & neededValues) static
Find a valid insertion point for a replacement of initTensorOp, assuming that the replacement may use any value from neededValues.
Definition at line 293 of file BufferizableOpInterfaceImpl.cpp.
References insertionPointDominatesUses(), and neededValuesDominateInsertionPoint().
Referenced by mlir::linalg::eliminateInitTensors().
insertionPointDominatesUses()
static bool insertionPointDominatesUses (const DominanceInfo & domInfo, Operation * insertionPoint, Operation * initTensorOp) static
Return true if the given insertionPoint dominates all uses of initTensorOp.
Definition at line 281 of file BufferizableOpInterfaceImpl.cpp.
References mlir::DominanceInfo::dominates(), and mlir::Operation::getUsers().
Referenced by findValidInsertionPoint().
neededValuesDominateInsertionPoint()
static bool neededValuesDominateInsertionPoint (const DominanceInfo & domInfo, Operation * insertionPoint, const SmallVector< Value > & neededValues) static
Return true if all neededValues are in scope at the given insertionPoint.
Definition at line 262 of file BufferizableOpInterfaceImpl.cpp.
References mlir::Value::cast(), mlir::DominanceInfo::dominates(), mlir::Block::findAncestorOpInBlock(), and mlir::OpResult::getOwner().
Referenced by findValidInsertionPoint().