MLIR: lib/Dialect/LLVMIR/IR/LLVMTypes.cpp File Reference
LLVMTypes.cpp File Reference
#include "TypeDetail.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/TypeSupport.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/TypeSize.h"
#include "mlir/Dialect/LLVMIR/LLVMTypeInterfaces.cpp.inc"
Enumerations
enum DLEntryPos
The positions of different values in the data layout entry.
enum StructDLEntryPos
Functions
static unsigned extractPointerSpecValue (Attribute attr, DLEntryPos pos)
Returns the value that corresponds to named position pos from the attribute attr assuming it's a dense integer elements attribute.
static Optional< unsigned > getPointerDataLayoutEntry (DataLayoutEntryListRef params, LLVMPointerType type, DLEntryPos pos)
Returns the part of the data layout entry that corresponds to pos for the given type by interpreting the list of entries params.
static Optional< unsigned > getStructDataLayoutEntry (DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos)
static unsigned calculateStructAlignment (const DataLayout &dataLayout, DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos)
static unsigned extractStructSpecValue (Attribute attr, StructDLEntryPos pos)
template<typename VecTy >
static LogicalResult verifyVectorConstructionInvariants (function_ref< InFlightDiagnostic()> emitError, Type elementType, unsigned numElements)
Verifies that the type about to be constructed is well-formed.
static bool isCompatibleImpl (Type type, SetVector< Type > &callstack)
Variables
constexpr static const unsigned kBitsInByte = 8
constexpr static const unsigned kDefaultPointerSizeBits = 64
constexpr static const unsigned kDefaultPointerAlignment = 8
Enumeration Type Documentation
DLEntryPos
enum DLEntryPos strong
The positions of different values in the data layout entry.
Definition at line 209 of file LLVMTypes.cpp.
StructDLEntryPos
enum StructDLEntryPos strong
Definition at line 474 of file LLVMTypes.cpp.
Function Documentation
calculateStructAlignment()
static unsigned calculateStructAlignment (const DataLayout & dataLayout, DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos) static
Definition at line 496 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMStructType::getBody(), getStructDataLayoutEntry(), mlir::DataLayout::getTypeABIAlignment(), mlir::LLVM::LLVMStructType::isPacked(), kBitsInByte, and max().
Referenced by mlir::LLVM::LLVMStructType::getABIAlignment(), and mlir::LLVM::LLVMStructType::getPreferredAlignment().
extractPointerSpecValue()
static unsigned extractPointerSpecValue (Attribute attr, DLEntryPos pos) static
Returns the value that corresponds to named position pos from the attribute attr assuming it's a dense integer elements attribute.
Definition at line 217 of file LLVMTypes.cpp.
References mlir::Attribute::cast().
Referenced by mlir::LLVM::LLVMPointerType::areCompatible(), getPointerDataLayoutEntry(), and mlir::LLVM::LLVMPointerType::verifyEntries().
extractStructSpecValue()
static unsigned extractStructSpecValue (Attribute attr, StructDLEntryPos pos) static
Definition at line 534 of file LLVMTypes.cpp.
References mlir::Attribute::cast().
Referenced by mlir::LLVM::LLVMStructType::areCompatible(), and mlir::LLVM::LLVMStructType::verifyEntries().
getPointerDataLayoutEntry()
static Optional<unsigned> getPointerDataLayoutEntry (DataLayoutEntryListRef params, LLVMPointerType type, DLEntryPos pos) static
Returns the part of the data layout entry that corresponds to pos for the given type by interpreting the list of entries params.
For the pointer type in the default address space, returns the default value if the entries do not provide a custom one, for other address spaces returns None.
Definition at line 227 of file LLVMTypes.cpp.
References extractPointerSpecValue(), mlir::LLVM::LLVMPointerType::getAddressSpace(), kBitsInByte, kDefaultPointerAlignment, and kDefaultPointerSizeBits.
Referenced by mlir::LLVM::LLVMPointerType::getABIAlignment(), mlir::LLVM::LLVMPointerType::getPreferredAlignment(), and mlir::LLVM::LLVMPointerType::getTypeSizeInBits().
getStructDataLayoutEntry()
static Optional<unsigned> getStructDataLayoutEntry (DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos) static
Definition at line 478 of file LLVMTypes.cpp.
Referenced by calculateStructAlignment().
isCompatibleImpl()
static bool isCompatibleImpl (Type type, SetVector< Type > & callstack) static
Definition at line 724 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::isCompatibleType().
verifyVectorConstructionInvariants()
template<typename VecTy > static LogicalResult verifyVectorConstructionInvariants (function_ref< InFlightDiagnostic()> emitError, Type elementType, unsigned numElements) static
Verifies that the type about to be constructed is well-formed.
Definition at line 599 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::success().
Variable Documentation
kBitsInByte
constexpr static const unsigned kBitsInByte = 8 static
Definition at line 28 of file LLVMTypes.cpp.
Referenced by calculateStructAlignment(), getPointerDataLayoutEntry(), mlir::LLVM::LLVMArrayType::getTypeSizeInBits(), and mlir::LLVM::LLVMStructType::getTypeSizeInBits().
kDefaultPointerAlignment
constexpr static const unsigned kDefaultPointerAlignment = 8 static
Definition at line 213 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::LLVMPointerType::areCompatible(), and getPointerDataLayoutEntry().
kDefaultPointerSizeBits
constexpr static const unsigned kDefaultPointerSizeBits = 64 static
Definition at line 212 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::LLVMPointerType::areCompatible(), and getPointerDataLayoutEntry().