MLIR: lib/Dialect/MemRef/IR/MemRefOps.cpp File Reference
MemRefOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Arithmetic/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "mlir/Dialect/MemRef/IR/MemRefOps.cpp.inc"
Classes
struct AllocaScopeInliner
Inline an AllocaScopeOp if either the direct parent is an allocation scope or it contains no allocation.
struct AllocaScopeHoister
Move allocations into an allocation scope, if it is legal to move them (e.g.
struct CollapseShapeOpMemRefCastFolder
struct SubViewReturnTypeCanonicalizer
Return the canonical type of the result of a subview.
struct SubViewCanonicalizer
A canonicalizer wrapper to replace SubViewOps.
Namespaces
saturated_arith
Idiomatic saturated operations on offsets, sizes and strides.
Macros
#define GET_OP_CLASSES
Functions
template<typename AllocLikeOp >
static LogicalResult verifyAllocLikeOp (AllocLikeOp op)
static bool isGuaranteedAutomaticAllocation (Operation *op)
Given an operation, return whether this op is guaranteed to allocate an AutomaticAllocationScopeResource.
static bool isOpItselfPotentialAutomaticAllocation (Operation *op)
Given an operation, return whether this op itself could allocate an AutomaticAllocationScopeResource.
static bool lastNonTerminatorInRegion (Operation *op)
Return whether this op is the last non terminating op in a region.
static std::map< int64_t, unsigned > getNumOccurences (ArrayRef< int64_t > vals)
Return a map with key being elements in vals and data being number of occurences of it.
static llvm::Optional< llvm::SmallBitVector > computeMemRefRankReductionMask (MemRefType originalType, MemRefType reducedType, ArrayRef< OpFoldResult > sizes)
Given the originalType and a candidateReducedType whose shape is assumed to be a subset of originalType with some 1 entries erased, return the set of indices that specifies which of the entries of originalShape are dropped to obtain reducedShape.
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter &p, GlobalOp op, TypeAttr type, Attribute initialValue)
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &initialValue)
static LogicalResult verifyCollapsedShape (Operation *op, ArrayRef< int64_t > collapsedShape, ArrayRef< int64_t > expandedShape, ArrayRef< ReassociationIndices > reassociation, bool allowMultipleDynamicDimsPerGroup)
Helper function for verifying the shape of ExpandShapeOp and ResultShapeOp result and operand.
static FailureOr< AffineMap > computeExpandedLayoutMap (MemRefType srcType, ArrayRef< int64_t > resultShape, ArrayRef< ReassociationIndices > reassociation)
Compute the layout map after expanding a given source MemRef type with the specified reassociation indices.
static FailureOr< MemRefType > computeExpandedType (MemRefType srcType, ArrayRef< int64_t > resultShape, ArrayRef< ReassociationIndices > reassociation)
static FailureOr< AffineMap > computeCollapsedLayoutMap (MemRefType srcType, ArrayRef< ReassociationIndices > reassociation, bool strict=false)
Compute the layout map after collapsing a given source MemRef type with the specified reassociation indices.
static MemRefType computeCollapsedType (MemRefType srcType, ArrayRef< ReassociationIndices > reassociation)
static bool haveCompatibleOffsets (MemRefType t1, MemRefType t2)
Return true if t1 and t2 have equal offsets (both dynamic or of same static value).
static SliceVerificationResult isRankReducedMemRefType (MemRefType originalType, MemRefType candidateRankReducedType, ArrayRef< OpFoldResult > sizes)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSubViewErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType)
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType currentSourceType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Compute the canonical result type of a SubViewOp.
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Compute the canonical result type of a SubViewOp.
static bool isTrivialSubViewOp (SubViewOp subViewOp)
Helper method to check if a subview operation is trivially a no-op.
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap)
Build a strided memref type by applying permutationMap tp memRefType.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2891 of file MemRefOps.cpp.
Function Documentation
computeCollapsedLayoutMap()
static FailureOr<AffineMap> computeCollapsedLayoutMap (MemRefType srcType, ArrayRef< ReassociationIndices > reassociation, bool strict = false) static
Compute the layout map after collapsing a given source MemRef type with the specified reassociation indices.
Note: All collapsed dims in a reassociation group must be contiguous. It is not possible to check this by inspecting a MemRefType in the general case. If non-contiguity cannot be checked statically, the collapse is assumed to be valid (and thus accepted by this function) unless strict = true.
Definition at line 1818 of file MemRefOps.cpp.
References mlir::failed(), mlir::failure(), mlir::getStridesAndOffset(), mlir::makeStridedLinearLayoutMap(), and mlir::succeeded().
Referenced by computeCollapsedType().
computeCollapsedType()
static MemRefType computeCollapsedType (MemRefType srcType, ArrayRef< ReassociationIndices > reassociation) static
Definition at line 1895 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::canonicalizeStridedLayout(), mlir::Type::cast(), computeCollapsedLayoutMap(), mlir::failed(), mlir::failure(), mlir::getReassociationAttrName(), mlir::getReassociationIndicesAttribute(), mlir::Value::getType(), mlir::succeeded(), mlir::success(), mlir::verify(), and verifyCollapsedShape().
Referenced by CollapseShapeOpMemRefCastFolder::matchAndRewrite().
computeExpandedLayoutMap()
static FailureOr<AffineMap> computeExpandedLayoutMap (MemRefType srcType, ArrayRef< int64_t > resultShape, ArrayRef< ReassociationIndices > reassociation) static
Compute the layout map after expanding a given source MemRef type with the specified reassociation indices.
Definition at line 1703 of file MemRefOps.cpp.
References mlir::failed(), mlir::failure(), mlir::getStridesAndOffset(), and mlir::makeStridedLinearLayoutMap().
Referenced by computeExpandedType().
computeExpandedType()
static FailureOr<MemRefType> computeExpandedType (MemRefType srcType, ArrayRef< int64_t > resultShape, ArrayRef< ReassociationIndices > reassociation) static
Definition at line 1743 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::canonicalizeStridedLayout(), mlir::Type::cast(), computeExpandedLayoutMap(), mlir::failed(), mlir::failure(), mlir::Value::getType(), mlir::succeeded(), mlir::success(), mlir::verify(), and verifyCollapsedShape().
computeMemRefRankReductionMask()
static llvm::Optional<llvm::SmallBitVector> computeMemRefRankReductionMask (MemRefType originalType, MemRefType reducedType, ArrayRef< OpFoldResult > sizes) static
Given the originalType and a candidateReducedType whose shape is assumed to be a subset of originalType with some 1 entries erased, return the set of indices that specifies which of the entries of originalShape are dropped to obtain reducedShape.
This accounts for cases where there are multiple unit-dims, but only a subset of those are dropped. For MemRefTypes these can be disambiguated using the strides. If a dimension is dropped the stride must be dropped too.
Definition at line 794 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Region::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::WalkResult::advance(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::Operation::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::memref::foldMemRefCast(), mlir::AsmParser::getBuilder(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::Value::getLoc(), mlir::getMixedSizes(), mlir::AsmParser::getNameLoc(), getNumElements(), getNumOccurences(), mlir::getStridesAndOffset(), mlir::Value::getType(), hasSideEffects(), mlir::WalkResult::interrupt(), mlir::Type::isIndex(), mlir::isStrided(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseTrailingOperandList(), print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::Region::push_back(), mlir::RewriterBase::replaceOp(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), resultIndex(), mlir::OpBuilder::setInsertionPointAfter(), mlir::AsmParser::Square, mlir::succeeded(), mlir::success(), mlir::OperationState::types, and mlir::verify().
Referenced by getCanonicalSubViewResultType(), and isRankReducedMemRefType().
getCanonicalSubViewResultType() [1/2]
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType currentSourceType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Compute the canonical result type of a SubViewOp.
Call inferResultType to deduce the result type for the given sourceType. Additionally, reduce the rank of the inferred result type if currentResultType is lower rank than currentSourceType. Use this signature if sourceType is updated together with the result type. In this case, it is important to compute the dropped dimensions using currentSourceType whose strides align with currentResultType.
Definition at line 2433 of file MemRefOps.cpp.
References computeMemRefRankReductionMask(), mlir::detail::enumerate(), mlir::getProjectedMap(), and mlir::AffineMap::isIdentity().
Referenced by getCanonicalSubViewResultType(), isTrivialSubViewOp(), and SubViewReturnTypeCanonicalizer::operator()().
getCanonicalSubViewResultType() [2/2]
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Compute the canonical result type of a SubViewOp.
Call inferResultType to deduce the result type. Additionally, reduce the rank of the inferred result type if currentResultType is lower rank than sourceType.
Definition at line 2462 of file MemRefOps.cpp.
References getCanonicalSubViewResultType().
getNumOccurences()
static std::map<int64_t, unsigned> getNumOccurences (ArrayRef< int64_t > vals) static
Return a map with key being elements in vals and data being number of occurences of it.
Use std::map, since the vals here are strides and the dynamic stride value is the same as the tombstone value for DenseMap<int64_t>.
Definition at line 779 of file MemRefOps.cpp.
Referenced by computeMemRefRankReductionMask().
haveCompatibleOffsets()
static bool haveCompatibleOffsets (MemRefType t1, MemRefType t2) static
Return true if t1 and t2 have equal offsets (both dynamic or of same static value).
Definition at line 2302 of file MemRefOps.cpp.
References mlir::getStridesAndOffset(), and mlir::succeeded().
Referenced by isRankReducedMemRefType().
inferTransposeResultType()
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap) static
Build a strided memref type by applying permutationMap tp memRefType.
Definition at line 2631 of file MemRefOps.cpp.
References mlir::detail::enumerate(), and mlir::AffineMap::getResults().
isGuaranteedAutomaticAllocation()
static bool isGuaranteedAutomaticAllocation (Operation * op) static
Given an operation, return whether this op is guaranteed to allocate an AutomaticAllocationScopeResource.
Definition at line 303 of file MemRefOps.cpp.
Referenced by AllocaScopeHoister::matchAndRewrite().
isOpItselfPotentialAutomaticAllocation()
static bool isOpItselfPotentialAutomaticAllocation (Operation * op) static
Given an operation, return whether this op itself could allocate an AutomaticAllocationScopeResource.
Note that this will not check whether an operation contained within the op can allocate.
Definition at line 322 of file MemRefOps.cpp.
References mlir::Operation::hasTrait().
Referenced by AllocaScopeInliner::matchAndRewrite().
isRankReducedMemRefType()
static SliceVerificationResult isRankReducedMemRefType (MemRefType originalType, MemRefType candidateRankReducedType, ArrayRef< OpFoldResult > sizes) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 2314 of file MemRefOps.cpp.
References computeMemRefRankReductionMask(), haveCompatibleOffsets(), mlir::isRankReducedType(), mlir::LayoutMismatch, mlir::MemSpaceMismatch, and mlir::Success.
Referenced by produceSubViewErrorMsg().
isTrivialSubViewOp()
static bool isTrivialSubViewOp (SubViewOp subViewOp) static
Helper method to check if a subview operation is trivially a no-op.
This is the case if the all offsets are zero, all strides are 1, and the source shape is same as the size of the subview. In such cases, the subview can be folded into its source.
Definition at line 2475 of file MemRefOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), getCanonicalSubViewResultType(), mlir::getConstantIntValue(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
lastNonTerminatorInRegion()
static bool lastNonTerminatorInRegion (Operation * op) static
Return whether this op is the last non terminating op in a region.
That is to say, it is in a one-block region and is only followed by a terminator. This prevents extending the lifetime of allocations.
Definition at line 345 of file MemRefOps.cpp.
References mlir::Operation::getBlock(), mlir::Region::getBlocks(), mlir::Operation::getParentRegion(), and mlir::Block::getTerminator().
Referenced by AllocaScopeInliner::matchAndRewrite(), and AllocaScopeHoister::matchAndRewrite().
parseGlobalMemrefOpTypeAndInitialValue()
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & initialValue) static
Definition at line 1263 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::dispatchIndexOpFoldResults(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::emitError(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failed(), mlir::failure(), mlir::memref::foldMemRefCast(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getContext(), mlir::Value::getDefiningOp(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::BaseMemRefType::getMemorySpace(), mlir::bufferization::getMemRefType(), mlir::AsmParser::getNameLoc(), mlir::getStridesAndOffset(), mlir::memref::getTensorTypeFromMemRefType(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Attribute::isa(), mlir::isConstantIntValue(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalEqual(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseType(), print(), mlir::OpAsmPrinter::printOperands(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, mlir::succeeded(), mlir::success(), and mlir::verify().
printGlobalMemrefOpTypeAndInitialValue()
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter & p, GlobalOp op, TypeAttr type, Attribute initialValue) static
Definition at line 1249 of file MemRefOps.cpp.
References mlir::AsmPrinter::printAttributeWithoutType().
produceSubViewErrorMsg()
template<typename OpTy > static LogicalResult produceSubViewErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType) static
Definition at line 2340 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::ElemTypeMismatch, mlir::emitError(), mlir::extractFromI64ArrayAttr(), mlir::getMixedSizes(), isRankReducedMemRefType(), mlir::isStrided(), mlir::LayoutMismatch, mlir::MemSpaceMismatch, mlir::RankTooLarge, mlir::SizeMismatch, mlir::success(), mlir::Success, and mlir::verify().
verifyAllocLikeOp()
template<typename AllocLikeOp > static LogicalResult verifyAllocLikeOp (AllocLikeOp op) static
Definition at line 117 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::OperationState::location, mlir::matchConstantIndex(), mlir::matchPattern(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OperationState::regions, mlir::RewriterBase::replaceOp(), mlir::MemRefType::Builder::setShape(), mlir::success(), mlir::OperationState::types, value, and mlir::verify().
verifyCollapsedShape()
static LogicalResult verifyCollapsedShape (Operation * op, ArrayRef< int64_t > collapsedShape, ArrayRef< int64_t > expandedShape, ArrayRef< ReassociationIndices > reassociation, bool allowMultipleDynamicDimsPerGroup) static
Helper function for verifying the shape of ExpandShapeOp and ResultShapeOp result and operand.
Layout maps are verified separately.
If allowMultipleDynamicDimsPerGroup, multiple dynamic dimensions are allowed in a reassocation group.
Definition at line 1610 of file MemRefOps.cpp.
References mlir::convertReassociationIndicesToExprs(), mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::getSymbolLessAffineMaps(), and mlir::success().
Referenced by computeCollapsedType(), and computeExpandedType().