MLIR: mlir::matcher Namespace Reference
mlir::matcher Namespace Reference
Functions
NestedPattern Op (FilterFunctionType filter=defaultFilterFunction)
NestedPattern If (const NestedPattern &child)
NestedPattern If (const FilterFunctionType &filter, const NestedPattern &child)
NestedPattern If (ArrayRef< NestedPattern > nested={})
NestedPattern If (const FilterFunctionType &filter, ArrayRef< NestedPattern > nested={})
NestedPattern For (const NestedPattern &child)
NestedPattern For (const FilterFunctionType &filter, const NestedPattern &child)
NestedPattern For (ArrayRef< NestedPattern > nested={})
NestedPattern For (const FilterFunctionType &filter, ArrayRef< NestedPattern > nested={})
bool isParallelLoop (Operation &op)
bool isReductionLoop (Operation &op)
bool isLoadOrStore (Operation &op)
Function Documentation
For() [1/4]
NestedPattern mlir::matcher::For (const NestedPattern & child)
Definition at line 157 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
Referenced by makePattern().
For() [2/4]
NestedPattern mlir::matcher::For (const FilterFunctionType & filter, const NestedPattern & child)
Definition at line 160 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
For() [3/4]
NestedPattern mlir::matcher::For (ArrayRef< NestedPattern > nested = {})
Definition at line 165 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
For() [4/4]
NestedPattern mlir::matcher::For (const FilterFunctionType & filter, ArrayRef< NestedPattern > nested = {})
Definition at line 168 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
If() [1/4]
NestedPattern mlir::matcher::If (const NestedPattern & child)
Definition at line 139 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
Referenced by isVectorizableLoopBodyWithOpCond().
If() [2/4]
NestedPattern mlir::matcher::If (const FilterFunctionType & filter, const NestedPattern & child)
Definition at line 142 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
If() [3/4]
NestedPattern mlir::matcher::If (ArrayRef< NestedPattern > nested = {})
Definition at line 147 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
If() [4/4]
NestedPattern mlir::matcher::If (const FilterFunctionType & filter, ArrayRef< NestedPattern > nested = {})
Definition at line 150 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
isLoadOrStore()
bool mlir::matcher::isLoadOrStore (Operation & op)
Definition at line 174 of file NestedMatcher.cpp.
Referenced by isVectorizableLoopBodyWithOpCond().
isParallelLoop()
bool mlir::matcher::isParallelLoop (Operation & op)
Referenced by mlir::sinkSequentialLoops().
isReductionLoop()
bool mlir::matcher::isReductionLoop (Operation & op)
Op()
NestedPattern mlir::matcher::Op (FilterFunctionType filter = defaultFilterFunction)
Definition at line 135 of file NestedMatcher.cpp.
References mlir::NestedPattern::NestedPattern().
Referenced by isVectorizableLoopBodyWithOpCond(), and vectorTransferPattern().