MLIR: mlir::OpTrait::impl Namespace Reference
mlir::OpTrait::impl Namespace Reference
Functions
LogicalResult verifyCompatibleOperandBroadcast (Operation *op)
OpFoldResult foldIdempotent (Operation *op)
OpFoldResult foldInvolution (Operation *op)
LogicalResult verifyZeroOperands (Operation *op)
LogicalResult verifyOneOperand (Operation *op)
LogicalResult verifyNOperands (Operation *op, unsigned numOperands)
LogicalResult verifyIsIdempotent (Operation *op)
LogicalResult verifyIsInvolution (Operation *op)
LogicalResult verifyAtLeastNOperands (Operation *op, unsigned numOperands)
LogicalResult verifyOperandsAreFloatLike (Operation *op)
LogicalResult verifyOperandsAreSignlessIntegerLike (Operation *op)
LogicalResult verifySameTypeOperands (Operation *op)
LogicalResult verifyZeroRegion (Operation *op)
LogicalResult verifyOneRegion (Operation *op)
LogicalResult verifyNRegions (Operation *op, unsigned numRegions)
LogicalResult verifyAtLeastNRegions (Operation *op, unsigned numRegions)
LogicalResult verifyZeroResult (Operation *op)
LogicalResult verifyOneResult (Operation *op)
LogicalResult verifyNResults (Operation *op, unsigned numOperands)
LogicalResult verifyAtLeastNResults (Operation *op, unsigned numOperands)
LogicalResult verifySameOperandsShape (Operation *op)
LogicalResult verifySameOperandsAndResultShape (Operation *op)
LogicalResult verifySameOperandsElementType (Operation *op)
LogicalResult verifySameOperandsAndResultElementType (Operation *op)
LogicalResult verifySameOperandsAndResultType (Operation *op)
LogicalResult verifyResultsAreBoolLike (Operation *op)
LogicalResult verifyResultsAreFloatLike (Operation *op)
LogicalResult verifyResultsAreSignlessIntegerLike (Operation *op)
LogicalResult verifyIsTerminator (Operation *op)
LogicalResult verifyZeroSuccessor (Operation *op)
LogicalResult verifyOneSuccessor (Operation *op)
LogicalResult verifyNSuccessors (Operation *op, unsigned numSuccessors)
LogicalResult verifyAtLeastNSuccessors (Operation *op, unsigned numSuccessors)
LogicalResult verifyValueSizeAttr (Operation *op, StringRef attrName, StringRef valueGroupName, size_t expectedCount)
LogicalResult verifyOperandSizeAttr (Operation *op, StringRef sizeAttrName)
LogicalResult verifyResultSizeAttr (Operation *op, StringRef sizeAttrName)
LogicalResult verifyNoRegionArguments (Operation *op)
LogicalResult verifyElementwise (Operation *op)
LogicalResult verifyIsIsolatedFromAbove (Operation *op)
Check for any values used by operations regions attached to the specified "IsIsolatedFromAbove" operation defined outside of it.
Function Documentation
foldIdempotent()
OpFoldResult mlir::OpTrait::impl::foldIdempotent (Operation * op)
Definition at line 668 of file Operation.cpp.
References mlir::Value::getDefiningOp(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), and mlir::Operation::getOperand().
Referenced by mlir::OpTrait::IsIdempotent< ConcreteType >::foldTrait(), and mlir::operator<<().
foldInvolution()
OpFoldResult mlir::OpTrait::impl::foldInvolution (Operation * op)
Definition at line 682 of file Operation.cpp.
References mlir::Value::getDefiningOp(), mlir::Operation::getName(), and mlir::Operation::getOperand().
Referenced by mlir::OpTrait::IsInvolution< ConcreteType >::foldTrait(), and mlir::operator<<().
verifyAtLeastNOperands()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNOperands (Operation * op, unsigned numOperands)
Definition at line 713 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::operator<<(), verifySameOperandsAndResultElementType(), verifySameOperandsAndResultShape(), verifySameOperandsAndResultType(), verifySameOperandsElementType(), verifySameOperandsShape(), and mlir::OpTrait::AtLeastNOperands< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNRegions()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNRegions (Operation * op, unsigned numRegions)
Definition at line 801 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::AtLeastNRegions< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNResults()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNResults (Operation * op, unsigned numOperands)
Definition at line 827 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::operator<<(), verifySameOperandsAndResultElementType(), verifySameOperandsAndResultShape(), verifySameOperandsAndResultType(), and mlir::OpTrait::AtLeastNResults< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNSuccessors()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNSuccessors (Operation * op, unsigned numSuccessors)
Definition at line 962 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::operator<<(), and mlir::OpTrait::AtLeastNSuccessors< N >::Impl< ConcreteType >::verifyTrait().
verifyCompatibleOperandBroadcast()
LogicalResult mlir::OpTrait::impl::verifyCompatibleOperandBroadcast (Operation * op)
Definition at line 231 of file Traits.cpp.
References mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::OpTrait::util::getBroadcastedShape(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), getShape(), getShapeString(), hasTensorOrVectorType(), isCompatibleInferredReturnShape(), and mlir::success().
Referenced by mlir::OpTrait::ResultsBroadcastableShape< ConcreteType >::verifyTrait().
verifyElementwise()
LogicalResult mlir::OpTrait::impl::verifyElementwise (Operation * op)
Definition at line 1057 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::Type::getTypeID(), mlir::success(), and mlir::verifyCompatibleShapes().
Referenced by mlir::operator<<(), and mlir::OpTrait::Elementwise< ConcreteType >::verifyTrait().
verifyIsIdempotent()
LogicalResult mlir::OpTrait::impl::verifyIsIdempotent (Operation * op)
Definition at line 734 of file Operation.cpp.
References mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::IsIdempotent< ConcreteType >::verifyTrait().
verifyIsInvolution()
LogicalResult mlir::OpTrait::impl::verifyIsInvolution (Operation * op)
Definition at line 742 of file Operation.cpp.
References mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::IsInvolution< ConcreteType >::verifyTrait().
verifyIsIsolatedFromAbove()
LogicalResult mlir::OpTrait::impl::verifyIsIsolatedFromAbove (Operation * isolatedOp)
Check for any values used by operations regions attached to the specified "IsIsolatedFromAbove" operation defined outside of it.
Definition at line 1100 of file Operation.cpp.
References mlir::Operation::getLoc(), mlir::Operation::getRegions(), mlir::Operation::hasTrait(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::IsIsolatedFromAbove< ConcreteType >::verifyRegionTrait().
verifyIsTerminator()
LogicalResult mlir::OpTrait::impl::verifyIsTerminator (Operation * op)
Definition at line 920 of file Operation.cpp.
References mlir::Block::back(), mlir::Operation::emitOpError(), mlir::Operation::getBlock(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::IsTerminator< ConcreteType >::verifyTrait().
verifyNOperands()
LogicalResult mlir::OpTrait::impl::verifyNOperands (Operation * op, unsigned numOperands)
Definition at line 704 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::operator<<(), mlir::linalg::detail::verifyStructuredOpInterface(), and mlir::OpTrait::NOperands< N >::Impl< ConcreteType >::verifyTrait().
verifyNoRegionArguments()
LogicalResult mlir::OpTrait::impl::verifyNoRegionArguments (Operation * op)
Definition at line 1042 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), mlir::Operation::getRegions(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::NoRegionArguments< ConcrentType >::verifyTrait().
verifyNRegions()
LogicalResult mlir::OpTrait::impl::verifyNRegions (Operation * op, unsigned numRegions)
Definition at line 794 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::NRegions< N >::Impl< ConcreteType >::verifyTrait().
verifyNResults()
LogicalResult mlir::OpTrait::impl::verifyNResults (Operation * op, unsigned numOperands)
Definition at line 820 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::NResults< N >::Impl< ConcreteType >::verifyTrait().
verifyNSuccessors()
LogicalResult mlir::OpTrait::impl::verifyNSuccessors (Operation * op, unsigned numSuccessors)
Definition at line 953 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::operator<<(), and mlir::OpTrait::NSuccessors< N >::Impl< ConcreteType >::verifyTrait().
verifyOneOperand()
LogicalResult mlir::OpTrait::impl::verifyOneOperand (Operation * op)
Definition at line 698 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::OneOperand< ConcreteType >::verifyTrait().
verifyOneRegion()
LogicalResult mlir::OpTrait::impl::verifyOneRegion (Operation * op)
Definition at line 788 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::OneRegion< ConcreteType >::verifyTrait().
verifyOneResult()
LogicalResult mlir::OpTrait::impl::verifyOneResult (Operation * op)
Definition at line 814 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::OneResult< ConcreteType >::verifyTrait().
verifyOneSuccessor()
LogicalResult mlir::OpTrait::impl::verifyOneSuccessor (Operation * op)
Definition at line 946 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::operator<<(), and mlir::OpTrait::OneSuccessor< ConcreteType >::verifyTrait().
verifyOperandsAreFloatLike()
LogicalResult mlir::OpTrait::impl::verifyOperandsAreFloatLike (Operation * op)
Definition at line 760 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::OperandsAreFloatLike< ConcreteType >::verifyTrait().
verifyOperandsAreSignlessIntegerLike()
LogicalResult mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike (Operation * op)
Definition at line 751 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::OperandsAreSignlessIntegerLike< ConcreteType >::verifyTrait().
verifyOperandSizeAttr()
LogicalResult mlir::OpTrait::impl::verifyOperandSizeAttr (Operation * op, StringRef sizeAttrName)
Definition at line 1032 of file Operation.cpp.
References mlir::Operation::getNumOperands(), and verifyValueSizeAttr().
Referenced by mlir::operator<<(), and mlir::OpTrait::AttrSizedOperandSegments< ConcreteType >::verifyTrait().
verifyResultsAreBoolLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreBoolLike (Operation * op)
Definition at line 972 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ResultsAreBoolLike< ConcreteType >::verifyTrait().
verifyResultsAreFloatLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreFloatLike (Operation * op)
Definition at line 983 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), mlir::Type::isa(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ResultsAreFloatLike< ConcreteType >::verifyTrait().
verifyResultsAreSignlessIntegerLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike (Operation * op)
Definition at line 992 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), mlir::Type::isSignlessIntOrIndex(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ResultsAreSignlessIntegerLike< ConcreteType >::verifyTrait().
verifyResultSizeAttr()
LogicalResult mlir::OpTrait::impl::verifyResultSizeAttr (Operation * op, StringRef sizeAttrName)
Definition at line 1037 of file Operation.cpp.
References mlir::Operation::getNumResults(), and verifyValueSizeAttr().
Referenced by mlir::operator<<(), and mlir::OpTrait::AttrSizedResultSegments< ConcreteType >::verifyTrait().
verifySameOperandsAndResultElementType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultElementType (Operation * op)
Definition at line 874 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperands(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::success(), verifyAtLeastNOperands(), and verifyAtLeastNResults().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameOperandsAndResultElementType< ConcreteType >::verifyTrait().
verifySameOperandsAndResultShape()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultShape (Operation * op)
Definition at line 845 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::success(), verifyAtLeastNOperands(), verifyAtLeastNResults(), and mlir::verifyCompatibleShapes().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameOperandsAndResultShape< ConcreteType >::verifyTrait().
verifySameOperandsAndResultType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultType (Operation * op)
Definition at line 898 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::success(), verifyAtLeastNOperands(), verifyAtLeastNResults(), and mlir::verifyCompatibleShape().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameOperandsAndResultType< ConcreteType >::verifyTrait().
verifySameOperandsElementType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsElementType (Operation * op)
Definition at line 860 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::success(), and verifyAtLeastNOperands().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameOperandsElementType< ConcreteType >::verifyTrait().
verifySameOperandsShape()
LogicalResult mlir::OpTrait::impl::verifySameOperandsShape (Operation * op)
Definition at line 835 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperandTypes(), mlir::success(), verifyAtLeastNOperands(), and mlir::verifyCompatibleShapes().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameOperandsShape< ConcreteType >::verifyTrait().
verifySameTypeOperands()
LogicalResult mlir::OpTrait::impl::verifySameTypeOperands (Operation * op)
Definition at line 769 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getOperandTypes(), mlir::Value::getType(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::SameTypeOperands< ConcreteType >::verifyTrait().
verifyValueSizeAttr()
LogicalResult mlir::OpTrait::impl::verifyValueSizeAttr (Operation * op, StringRef attrName, StringRef valueGroupName, size_t expectedCount)
Definition at line 999 of file Operation.cpp.
References mlir::Operation::CloneOptions::all(), mlir::Operation::emitOpError(), mlir::Operation::getAttrOfType(), and mlir::success().
Referenced by mlir::operator<<(), verifyOperandSizeAttr(), and verifyResultSizeAttr().
verifyZeroOperands()
LogicalResult mlir::OpTrait::impl::verifyZeroOperands (Operation * op)
Definition at line 692 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ZeroOperands< ConcreteType >::verifyTrait().
verifyZeroRegion()
LogicalResult mlir::OpTrait::impl::verifyZeroRegion (Operation * op)
Definition at line 782 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ZeroRegion< ConcreteType >::verifyTrait().
verifyZeroResult()
LogicalResult mlir::OpTrait::impl::verifyZeroResult (Operation * op)
Definition at line 808 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ZeroResult< ConcreteType >::verifyTrait().
verifyZeroSuccessor()
LogicalResult mlir::OpTrait::impl::verifyZeroSuccessor (Operation * op)
Definition at line 938 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and mlir::success().
Referenced by mlir::operator<<(), and mlir::OpTrait::ZeroSuccessor< ConcreteType >::verifyTrait().