MLIR: mlir::scf Namespace Reference
mlir::scf Namespace Reference
Classes
struct LoopNest
struct PipeliningOption
Options to dictate how loops should be pipelined.
Typedefs
using ValueVector = std::vector< Value >
An owning vector of values, handy to return from functions.
using LoopVector = std::vector< scf::ForOp >
using LoopMatcherFn = function_ref< LogicalResult(Value, Value &, Value &, Value &)>
Match "for loop"-like operations: If the first parameter is an iteration variable, return lower/upper bounds via the second/third parameter and the step size via the last parameter.
Functions
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
void buildTerminatedBody (OpBuilder &builder, Location loc)
Default callback for IfOp builders. Inserts a yield without arguments.
void ensureLoopTerminator (Region &region, Builder &builder, Location loc)
ForOp getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
ParallelOp getParallelForInductionVarOwner (Value val)
Returns the parallel loop parent of an induction variable.
bool insideMutuallyExclusiveBranches (Operation *a, Operation *b)
Return true if ops a and b (or their ancestors) are in mutually exclusive regions/blocks of an IfOp.
LoopNest buildLoopNest (OpBuilder &builder, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ValueRange iterArgs, function_ref< ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilder=nullptr)
Creates a perfect nest of "for" loops, i.e.
LoopNest buildLoopNest (OpBuilder &builder, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilder=nullptr)
A convenience version for building loop nests without iteration arguments (like for reductions).
void naivelyFuseParallelOps (Region &region)
Fuses all adjacent scf.parallel operations with identical bounds and step into one scf.parallel operations.
LogicalResult peelAndCanonicalizeForLoop (RewriterBase &rewriter, ForOp forOp, scf::ForOp &partialIteration)
Rewrite a for loop with bounds/step that potentially do not divide evenly into a for loop where the step divides the iteration space evenly, followed by another scf.for for the last (partial) iteration (if any; returned via partialIteration).
std::pair< ParallelOp, ParallelOp > tileParallelLoop (ParallelOp op, llvm::ArrayRef< int64_t > tileSizes, bool noMinMaxBounds)
Tile a parallel loop of the form scf.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4, arg5)
void populateSCFStructuralTypeConversionsAndLegality (TypeConverter &typeConverter, RewritePatternSet &patterns, ConversionTarget &target)
Populates patterns for SCF structural type conversions and sets up the provided ConversionTarget with the appropriate legality configuration for the ops to get converted properly.
void populateSCFLoopPipeliningPatterns (RewritePatternSet &patterns, const PipeliningOption &options)
Populate patterns for SCF software pipelining transformation.
void populateSCFForLoopCanonicalizationPatterns (RewritePatternSet &patterns)
Populate patterns for canonicalizing operations inside SCF loop bodies.
LogicalResult canonicalizeMinMaxOpInLoop (RewriterBase &rewriter, Operation *op, AffineMap map, ValueRange operands, bool isMin, LoopMatcherFn loopMatcher)
Try to canonicalize an min/max operations in the context of for loops with a known range.
LogicalResult rewritePeeledMinMaxOp (RewriterBase &rewriter, Operation *op, AffineMap map, ValueRange operands, bool isMin, Value iv, Value ub, Value step, bool insideLoop)
Try to simplify a min/max operation op after loop peeling.
Typedef Documentation
LoopMatcherFn
using mlir::scf::LoopMatcherFn = typedef function_ref<LogicalResult(Value, Value &, Value &, Value &)>
Match "for loop"-like operations: If the first parameter is an iteration variable, return lower/upper bounds via the second/third parameter and the step size via the last parameter.
The function should return success in that case. If the first parameter is not an iteration variable, return failure.
Definition at line 36 of file AffineCanonicalizationUtils.h.
LoopVector
using mlir::scf::LoopVector = typedef std::vector<scf::ForOp>
Definition at line 56 of file SCF.h.
ValueVector
using mlir::scf::ValueVector = typedef std::vector<Value>
An owning vector of values, handy to return from functions.
Definition at line 55 of file SCF.h.
Function Documentation
buildLoopNest() [1/2]
LoopNest mlir::scf::buildLoopNest (OpBuilder & builder, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ValueRange iterArgs, function_ref< ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilder = nullptr)
Creates a perfect nest of "for" loops, i.e.
all loops but the innermost contain only another loop and a terminator. The lower, upper bounds and steps are provided as lbs, ubs and steps, which are expected to be of the same size. iterArgs points to the initial values of the loop iteration arguments, which will be forwarded through the nest to the innermost loop. The body of the loop is populated using bodyBuilder, which accepts an ordered list of induction variables of all loops, followed by a list of iteration arguments of the innermost loop, in the same order as provided to iterArgs. This function is expected to return as many values as iterArgs, of the same type and in the same order, that will be treated as yielded from the loop body and forwarded back through the loop nest. If the function is not provided, the loop nest is not expected to have iteration arguments, the body of the innermost loop will be left empty, containing only the zero-operand terminator. Returns the LoopNest containing the list of perfectly nest scf::ForOp build during the call. If bound arrays are empty, the body builder will be called once to construct the IR outside of the loop with an empty list of induction variables.
Definition at line 504 of file SCF.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by buildLoopNest(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::linalg::generateParallelLoopNest(), insertCopyLoops(), and tilePadOp().
buildLoopNest() [2/2]
LoopNest mlir::scf::buildLoopNest (OpBuilder & builder, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilder = nullptr)
A convenience version for building loop nests without iteration arguments (like for reductions).
Does not take the initial value of reductions or expect the body building functions to return their current value. The built nested scf::For are captured in capturedLoops when non-null.
Definition at line 577 of file SCF.cpp.
References mlir::RewritePatternSet::add(), buildLoopNest(), mlir::Value::cast(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Block::front(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getDefiningOp(), mlir::Block::getNumArguments(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::mergeBlockBefore(), mlir::RewriterBase::mergeBlocks(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithIf(), mlir::RewriterBase::replaceOpWithNewOp(), replaceOpWithRegion(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::RewriterBase::startRootUpdate(), and mlir::success().
buildTerminatedBody()
void mlir::scf::buildTerminatedBody (OpBuilder & builder, Location loc)
Default callback for IfOp builders. Inserts a yield without arguments.
Definition at line 74 of file SCF.cpp.
References mlir::OpBuilder::create().
canonicalizeMinMaxOpInLoop()
LogicalResult mlir::scf::canonicalizeMinMaxOpInLoop (RewriterBase & rewriter, Operation * op, AffineMap map, ValueRange operands, bool isMin, LoopMatcherFn loopMatcher)
Try to canonicalize an min/max operations in the context of for loops with a known range.
Canonicalize min/max operations in the context of for loops with a known range.
map is the body of the min/max operation and operands are the SSA values that the dimensions and symbols are bound to; dimensions are listed first. If isMin, the operation is a min operation; otherwise, a max operation. loopMatcher is used to retrieve loop bounds and the step size for a given iteration variable.
Note: loopMatcher allows this function to be used with any "for loop"-like operation (scf.for, scf.parallel and even ops defined in other dialects).
Call canonicalizeMinMaxOp and add the following constraints to the constraint system (along with the missing dimensions):
iv >= lb
iv < lb + step * ((ub - lb - 1) floorDiv step) + 1
Note: Due to limitations of IntegerPolyhedron, only constant step sizes are currently supported.
Definition at line 263 of file AffineCanonicalizationUtils.cpp.
References addLoopRangeConstraints(), canonicalizeMinMaxOp(), mlir::failed(), and mlir::failure().
Referenced by isShapePreserving().
ensureLoopTerminator()
void mlir::scf::ensureLoopTerminator (Region & region, Builder & builder, Location loc)
getForInductionVarOwner()
ForOp mlir::scf::getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Referenced by mlir::linalg::hoistPaddingOnTensors(), isShapePreserving(), and printInitializationList().
getParallelForInductionVarOwner()
ParallelOp mlir::scf::getParallelForInductionVarOwner (Value val)
Returns the parallel loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Definition at line 2062 of file SCF.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::InFlightDiagnostic::attachNote(), mlir::OperationState::attributes, mlir::OpBuilder::clone(), mlir::RewriterBase::cloneRegionBefore(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), diag(), mlir::Value::dyn_cast(), mlir::AsmParser::emitError(), mlir::Block::empty(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Region::front(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getCurrentLocation(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Operation::getLoc(), mlir::Block::getNumArguments(), mlir::Operation::getOperands(), mlir::Value::getParentBlock(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::OptionalParseResult::getValue(), mlir::OptionalParseResult::hasValue(), mlir::RewriterBase::inlineRegionBefore(), mlir::arith::invertPredicate(), mlir::OperationState::location, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::mergeBlocks(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAssignmentList(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseRParen(), print(), mlir::OpAsmPrinter::printFunctionalType(), printInitializationList(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpBuilder::setInsertionPoint(), mlir::RewriterBase::startRootUpdate(), mlir::success(), mlir::Value::use_empty(), mlir::verify(), and mlir::Block::without_terminator().
Referenced by isShapePreserving().
insideMutuallyExclusiveBranches()
bool mlir::scf::insideMutuallyExclusiveBranches (Operation * a, Operation * b)
Return true if ops a and b (or their ancestors) are in mutually exclusive regions/blocks of an IfOp.
Definition at line 1049 of file SCF.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Region::back(), mlir::Block::back(), mlir::OpBuilder::cloneWithoutRegions(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Operation::emitOpError(), mlir::Region::empty(), mlir::detail::enumerate(), mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Block::front(), mlir::Block::getArguments(), mlir::AsmParser::getBuilder(), mlir::Value::getDefiningOp(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Block::getOps(), mlir::Block::getParent(), mlir::Operation::getParentOfType(), mlir::Value::getParentRegion(), mlir::Region::getParentRegion(), mlir::OpResult::getResultNumber(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::RewriterBase::inlineRegionBefore(), mlir::Region::isAncestor(), mlir::OperationState::location, mlir::m_One(), mlir::matchPattern(), mlir::RewriterBase::mergeBlocks(), mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::OpAsmParser::parseArgumentList(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), print(), mlir::AsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OperationState::regions, mlir::Value::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), replaceOpWithRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::RewriterBase::startRootUpdate(), mlir::succeeded(), mlir::success(), mlir::OperationState::types, mlir::RewriterBase::updateRootInPlace(), mlir::Value::use_empty(), and mlir::verify().
naivelyFuseParallelOps()
void mlir::scf::naivelyFuseParallelOps (Region & region)
Fuses all adjacent scf.parallel operations with identical bounds and step into one scf.parallel operations.
Uses a naive aliasing and dependency analysis.
Definition at line 133 of file ParallelLoopFusion.cpp.
References fuseIfLegal(), and mlir::Operation::getRegions().
peelAndCanonicalizeForLoop()
LogicalResult mlir::scf::peelAndCanonicalizeForLoop (RewriterBase & rewriter, ForOp forOp, scf::ForOp & partialIteration)
Rewrite a for loop with bounds/step that potentially do not divide evenly into a for loop where the step divides the iteration space evenly, followed by another scf.for for the last (partial) iteration (if any; returned via partialIteration).
This transformation is called "loop peeling".
This transformation is beneficial for a wide range of transformations such as vectorization or loop tiling: It enables additional canonicalizations inside the peeled loop body such as rewriting masked loads into unmaked loads.
E.g., assuming a lower bound of 0 (for illustration purposes):
scf.for %iv = %c0 to %ub step %c4 {
  (loop body)
}
is rewritten into the following pseudo IR:
%newUb = %ub - (%ub mod %c4)
scf.for %iv = %c0 to %newUb step %c4 {
  (loop body)
}
scf.for %iv2 = %newUb to %ub {
  (loop body)
}
After loop peeling, this function tries to simplify/canonicalize affine.min and affine.max ops in the body of the peeled loop and in the body of the partial iteration loop, taking advantage of the fact that the peeled loop has only "full" iterations. This canonicalization is expected to enable further canonicalization opportunities through other patterns.
The return value indicates whether the loop was rewritten or not. Loops are not rewritten if:
Loop step size is 1 or
Loop bounds and step size are static, and step already divides the iteration space evenly.
Note: This function rewrites the given scf.for loop in-place and creates a new scf.for operation for the last iteration. It replaces all uses of the unpeeled loop with the results of the newly generated scf.for.
Referenced by peelLoop(), and rewriteAffineOpAfterPeeling().
populateSCFForLoopCanonicalizationPatterns()
void mlir::scf::populateSCFForLoopCanonicalizationPatterns (RewritePatternSet & patterns)
Populate patterns for canonicalizing operations inside SCF loop bodies.
At the moment, only affine.min/max computations with iteration variables, loop bounds and loop steps are canonicalized.
Definition at line 195 of file LoopCanonicalization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by applyExtractSliceOfPadTensorSwapPattern(), and isShapePreserving().
populateSCFLoopPipeliningPatterns()
void mlir::scf::populateSCFLoopPipeliningPatterns (RewritePatternSet & patterns, const PipeliningOption & options)
Populate patterns for SCF software pipelining transformation.
This transformation generates the pipelined loop and doesn't do any assumptions on the schedule dictated by the option structure. Software pipelining is usually done in two part. The first part of pipelining is to schedule the loop and assign a stage and cycle to each operations. This is highly dependent on the target and is implemented as an heuristic based on operation latencies, and other hardware characteristics. The second part is to take the schedule and generate the pipelined loop as well as the prologue and epilogue. It is independent of the target. This pattern only implement the second part. For example if we break a loop into 3 stages named S0, S1, S2 we would generate the following code with the number in parenthesis the iteration index: S0(0) // Prologue S0(1) S1(0) // Prologue scf.for I = C0 to N - 2 { S0(I+2) S1(I+1) S2(I) // Pipelined kernel } S1(N) S2(N-1) // Epilogue S2(N) // Epilogue
Definition at line 477 of file LoopPipelining.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
populateSCFStructuralTypeConversionsAndLegality()
void mlir::scf::populateSCFStructuralTypeConversionsAndLegality (TypeConverter & typeConverter, RewritePatternSet & patterns, ConversionTarget & target)
Populates patterns for SCF structural type conversions and sets up the provided ConversionTarget with the appropriate legality configuration for the ops to get converted properly.
A "structural" type conversion is one where the underlying ops are completely agnostic to the actual types involved and simply need to update their types. An example of this is scf.if – the scf.if op and the corresponding scf.yield ops need to update their types accordingly to the TypeConverter, but otherwise don't care what type conversions are happening.
Definition at line 177 of file StructuralTypeConversions.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addDynamicallyLegalOp(), and mlir::RewritePatternSet::getContext().
registerBufferizableOpInterfaceExternalModels()
void mlir::scf::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 526 of file BufferizableOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().
rewritePeeledMinMaxOp()
LogicalResult mlir::scf::rewritePeeledMinMaxOp (RewriterBase & rewriter, Operation * op, AffineMap map, ValueRange operands, bool isMin, Value iv, Value ub, Value step, bool insideLoop)
Try to simplify a min/max operation op after loop peeling.
This function can simplify min/max operations such as (ub is the previous upper bound of the unpeeled loop):
#map = affine_map<(d0)[s0, s1] -> (s0, -d0 + s1)>
%r = affine.min #affine.min #map(%iv)[%step, %ub]
and rewrites them into (in the case the peeled loop):
%r = %step
min/max operations inside the partial iteration are rewritten in a similar way.
This function can simplify min/max operations such as (ub is the previous upper bound of the unpeeled loop):
#map = affine_map<(d0)[s0, s1] -> (s0, -d0 + s1)>
%r = affine.min #affine.min #map(%iv)[%step, %ub]
and rewrites them into (in the case the peeled loop):
%r = %step
min/max operations inside the partial iteration are rewritten in a similar way.
This function builds up a set of constraints, capable of proving that:
Inside the peeled loop: min(step, ub - iv) == step
Inside the partial iteration: min(step, ub - iv) == ub - iv
Returns success if the given operation was replaced by a new operation; failure otherwise.
Note: ub is the previous upper bound of the loop (before peeling). insideLoop must be true for min/max ops inside the loop and false for affine.min ops inside the partial iteration. For an explanation of the other parameters, see comment of canonicalizeMinMaxOpInLoop.
Definition at line 317 of file AffineCanonicalizationUtils.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::presburger::IntegerRelation::addInequality(), mlir::FlatAffineValueConstraints::appendDimId(), canonicalizeMinMaxOp(), mlir::presburger::IntegerRelation::EQ, and mlir::getConstantIntValue().
Referenced by rewriteAffineOpAfterPeeling().
tileParallelLoop()
std::pair< ParallelOp, ParallelOp > mlir::scf::tileParallelLoop (ParallelOp op, llvm::ArrayRef< int64_t > tileSizes, bool noMinMaxBounds)
Tile a parallel loop of the form scf.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4, arg5)
into scf.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4*tileSize[0], arg5*tileSize[1]) scf.parallel (j0, j1) = (0, 0) to (min(tileSize[0], arg2-j0) min(tileSize[1], arg3-j1)) step (arg4, arg5) The old loop is replaced with the new one.
The function returns the resulting ParallelOps, i.e. {outer_loop_op, inner_loop_op}.
into scf.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4*tileSize[0], arg5*tileSize[1]) scf.parallel (j0, j1) = (0, 0) to (min(arg4*tileSize[0], arg2-i0) min(arg5*tileSize[1], arg3-i1)) step (arg4, arg5)
or, when no-min-max-bounds is true, into scf.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4*tileSize[0], arg5*tileSize[1]) scf.parallel (j0, j1) = (0, 0) to (arg4*tileSize[0], arg5*tileSize[1]) step (arg4, arg5) inbound = (j0 * arg4 + i0 < arg2) && (j1 * arg5 + i1 < arg3) scf.if (inbound) ....
where the uses of i0 and i1 in the loop body are replaced by i0 + j0 and i1 + j1. The old loop is replaced with the new one.
Definition at line 53 of file ParallelLoopTiling.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Block::eraseArguments(), mlir::Block::front(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Block::getArgument(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::getInnermostParallelLoops(), mlir::Builder::getIntegerType(), mlir::Block::getNumArguments(), mlir::Value::replaceAllUsesExcept(), mlir::OpBuilder::setInsertionPointToStart(), and value.