MLIR: mlir::presburger Namespace Reference
mlir::presburger Namespace Reference
Classes
struct Fraction
A class to represent fractions.
class GBRSimplex
Given a simplex for a polytope, construct a new simplex whose variables are identified with a pair of points (x, y) in the original polytope.
class IntegerPolyhedron
An IntegerPolyhedron represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
class IntegerRelation
An IntegerRelation represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
class LexSimplex
A class for lexicographic optimization without any symbols.
class LexSimplexBase
Simplex class using the lexicographic pivot rule.
class LinearTransform
class Matrix
This is a class to represent a resizable matrix.
struct MaybeLocalRepr
MaybeLocalRepr contains the indices of the contraints that can be expressed as a floordiv of an affine function.
class MaybeOptimum
class MultiAffineFunction
This class represents a multi-affine function whose domain is given by an IntegerPolyhedron.
class PresburgerRelation
A PresburgerRelation represents a union of IntegerRelations that live in the same PresburgerSpace with support for union, intersection, subtraction, and complement operations, as well as sampling.
class PresburgerSet
class PresburgerSpace
PresburgerSpace is the space of all possible values of a tuple of integer valued variables/identifiers.
class PWMAFunction
This class represents a piece-wise MultiAffineFunction.
class SetCoalescer
The SetCoalescer class contains all functionality concerning the coalesce heuristic.
class Simplex
The Simplex class uses the Normal pivot rule and supports integer emptiness checks as well as detecting redundancies.
class SimplexBase
The Simplex class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
class SimplexRollbackScopeExit
Takes a snapshot of the simplex state on construction and rolls back to the snapshot on destruction.
struct SymbolicLexMin
Represents the result of a symbolic lexicographic minimization computation.
class SymbolicLexSimplex
A class to perform symbolic lexicographic optimization, i.e., to find, for every assignment to the symbols the specified symbolDomain, the lexicographically minimum value integer value attained by the non-symbol variables.
Enumerations
enum IdKind {
IdKind::Symbol, IdKind::Local, IdKind::Domain, IdKind::Range,
IdKind::SetDim = Range
}
Kind of identifier.
enum OptimumKind { OptimumKind::Empty, OptimumKind::Unbounded, OptimumKind::Bounded }
This class represents the result of operations optimizing something subject to some constraints.
enum ReprKind { ReprKind::Inequality, ReprKind::Equality, ReprKind::None }
ReprKind enum is used to set the constraint type in MaybeLocalRepr.
Functions
int compare (Fraction x, Fraction y)
Three-way comparison between two fractions.
int64_t floor (Fraction f)
int64_t ceil (Fraction f)
Fraction operator- (Fraction x)
bool operator< (Fraction x, Fraction y)
bool operator<= (Fraction x, Fraction y)
bool operator== (Fraction x, Fraction y)
bool operator!= (Fraction x, Fraction y)
bool operator> (Fraction x, Fraction y)
bool operator>= (Fraction x, Fraction y)
Fraction operator* (Fraction x, Fraction y)
MaybeLocalRepr computeSingleVarRepr (const IntegerRelation &cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > &dividend, unsigned &divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
void removeDuplicateDivs (std::vector< SmallVector< int64_t, 8 >> &divs, SmallVectorImpl< unsigned > &denoms, unsigned localOffset, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given dividends of divisions divs and denominators denoms, detects and removes duplicate divisions.
void mergeLocalIds (IntegerRelation &relA, IntegerRelation &relB, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given two relations, A and B, add additional local ids to the sets such that both have the union of the local ids in each set, without changing the set of points that lie in A and B.
int64_t gcdRange (ArrayRef< int64_t > range)
Compute the gcd of the range.
int64_t normalizeRange (MutableArrayRef< int64_t > range)
Divide the range by its gcd and return the gcd.
void normalizeDiv (MutableArrayRef< int64_t > num, int64_t &denom)
Normalize the given (numerator, denominator) pair by dividing out the common factors between them.
SmallVector< int64_t, 8 > getNegatedCoeffs (ArrayRef< int64_t > coeffs)
Return coeffs with all the elements negated.
SmallVector< int64_t, 8 > getComplementIneq (ArrayRef< int64_t > ineq)
Return the complement of the given inequality.
Enumeration Type Documentation
IdKind
enum mlir::presburger::IdKind strong
Kind of identifier.
Implementation wise SetDims are treated as Range ids, and spaces with no distinction between dimension ids are treated as relations with zero domain ids.
Enumerator
Symbol
Local
Domain
Range
SetDim
Definition at line 26 of file PresburgerSpace.h.
OptimumKind
enum mlir::presburger::OptimumKind strong
This class represents the result of operations optimizing something subject to some constraints.
If the constraints were not satisfiable the, kind will be Empty. If the optimum is unbounded, the kind is Unbounded, and if the optimum is bounded, the kind will be Bounded and optimum holds the optimal value.
Enumerator
Empty
Unbounded
Bounded
Definition at line 29 of file Utils.h.
ReprKind
enum mlir::presburger::ReprKind strong
ReprKind enum is used to set the constraint type in MaybeLocalRepr.
Enumerator
Inequality
Equality
None
Definition at line 86 of file Utils.h.
Function Documentation
ceil()
int64_t mlir::presburger::ceil (Fraction f) inline
Definition at line 65 of file Fraction.h.
References mlir::ceilDiv(), mlir::presburger::Fraction::den, and mlir::presburger::Fraction::num.
Referenced by mlir::presburger::Simplex::computeIntegerBounds(), mlir::presburger::IntegerRelation::findIntegerSample(), getF64Values(), hasaUniqueDim(), and signedCeilNonnegInputs().
compare()
int mlir::presburger::compare (Fraction x, Fraction y) inline
Three-way comparison between two fractions.
Returns +1, 0, and -1 if the first fraction is greater than, equal to, or less than the second fraction, respectively.
Definition at line 54 of file Fraction.h.
References mlir::presburger::Fraction::den, and mlir::presburger::Fraction::num.
Referenced by createConst(), mlir::impl::findAttrSorted(), llvm::cl::OptionValue< mlir::OpPassManager >::getValue(), mlir::detail::InterfaceMap::insert(), insertCasts(), matchSelectReduction(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
computeSingleVarRepr()
MaybeLocalRepr mlir::presburger::computeSingleVarRepr (const IntegerRelation & cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > & dividend, unsigned & divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
foundRepr contains a boolean for each identifier indicating if the explicit representation for that identifier has already been computed. Returns the MaybeLocalRepr struct which contains the indices of the constraints that can be expressed as a floordiv of an affine function. If the representation could be computed, dividend and denominator are set. If the representation could not be computed, the kind attribute in MaybeLocalRepr is set to None.
Definition at line 216 of file Utils.cpp.
References checkExplicitRepresentation(), Equality, mlir::failed(), getDivRepr(), mlir::presburger::IntegerRelation::getLowerAndUpperBoundIndices(), mlir::presburger::IntegerRelation::getNumIds(), Inequality, and mlir::presburger::MaybeLocalRepr::kind.
Referenced by detectAsFloorDiv().
floor()
int64_t mlir::presburger::floor (Fraction f) inline
Definition at line 63 of file Fraction.h.
References mlir::presburger::Fraction::den, mlir::floorDiv(), and mlir::presburger::Fraction::num.
Referenced by mlir::presburger::Simplex::computeIntegerBounds(), getF64Values(), and hasaUniqueDim().
gcdRange()
int64_t mlir::presburger::gcdRange (ArrayRef< int64_t > range)
Compute the gcd of the range.
Definition at line 340 of file Utils.cpp.
Referenced by normalizeDiv(), and normalizeRange().
getComplementIneq()
SmallVector< int64_t, 8 > mlir::presburger::getComplementIneq (ArrayRef< int64_t > ineq)
Return the complement of the given inequality.
The complement of a_1 x_1 + ... + a_n x_ + c >= 0 is a_1 x_1 + ... + a_n x_ + c < 0, i.e., -a_1 x_1 - ... - a_n x_ - c - 1 >= 0, since all the variables are constrained to be integers.
Definition at line 375 of file Utils.cpp.
Referenced by mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), getSetDifference(), and mlir::presburger::LexSimplex::isRedundantInequality().
getNegatedCoeffs()
SmallVector< int64_t, 8 > mlir::presburger::getNegatedCoeffs (ArrayRef< int64_t > coeffs)
Return coeffs with all the elements negated.
Definition at line 367 of file Utils.cpp.
Referenced by mlir::presburger::SetCoalescer::coalesce(), and getIneqCoeffsFromIdx().
mergeLocalIds()
void mlir::presburger::mergeLocalIds (IntegerRelation & relA, IntegerRelation & relB, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given two relations, A and B, add additional local ids to the sets such that both have the union of the local ids in each set, without changing the set of points that lie in A and B.
While taking union, if a local id in any set has a division representation which is a duplicate of division representation, of another local id in any set, it is not added to the final union of local ids and is instead merged.
On every possible merge, merge(i, j) is called. i, j are position of local identifiers in both sets which are being merged. If merge(i, j) returns true, the divisions are merged, otherwise the divisions are not merged.
Definition at line 307 of file Utils.cpp.
References copy(), mlir::presburger::IntegerRelation::getIdKindOffset(), mlir::presburger::IntegerRelation::getLocalReprs(), mlir::presburger::IntegerRelation::getNumLocalIds(), mlir::presburger::IntegerRelation::getSpace(), mlir::presburger::IntegerRelation::insertId(), mlir::presburger::PresburgerSpace::isCompatible(), Local, and removeDuplicateDivs().
Referenced by mlir::presburger::MultiAffineFunction::mergeLocalIds(), and mlir::presburger::IntegerRelation::mergeLocalIds().
normalizeDiv()
void mlir::presburger::normalizeDiv (MutableArrayRef< int64_t > num, int64_t & denom)
Normalize the given (numerator, denominator) pair by dividing out the common factors between them.
The numerator here is an affine expression with integer coefficients.
Definition at line 359 of file Utils.cpp.
References gcdRange().
Referenced by isRangeDivisibleBy().
normalizeRange()
int64_t mlir::presburger::normalizeRange (MutableArrayRef< int64_t > range)
Divide the range by its gcd and return the gcd.
Definition at line 350 of file Utils.cpp.
References gcdRange().
Referenced by mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), mlir::presburger::LexSimplex::isRedundantInequality(), and mlir::presburger::Matrix::normalizeRow().
operator!=()
bool mlir::presburger::operator!= (Fraction x, Fraction y) inline
Definition at line 75 of file Fraction.h.
References compare().
operator*()
Fraction mlir::presburger::operator* (Fraction x, Fraction y) inline
Definition at line 81 of file Fraction.h.
References mlir::presburger::Fraction::den, mlir::presburger::Fraction::Fraction(), and mlir::presburger::Fraction::num.
operator-()
Fraction mlir::presburger::operator- (Fraction x) inline
Definition at line 67 of file Fraction.h.
References mlir::presburger::Fraction::den, mlir::presburger::Fraction::Fraction(), and mlir::presburger::Fraction::num.
operator<()
bool mlir::presburger::operator< (Fraction x, Fraction y) inline
Definition at line 69 of file Fraction.h.
References compare().
Referenced by buildPredicateList(), mlir::tblgen::AttrOrTypeDef::getTraits(), mlir::tblgen::Dialect::operator!=(), and mlir::NamedAttribute::setValue().
operator<=()
bool mlir::presburger::operator<= (Fraction x, Fraction y) inline
Definition at line 71 of file Fraction.h.
References compare().
operator==()
bool mlir::presburger::operator== (Fraction x, Fraction y) inline
Definition at line 73 of file Fraction.h.
References compare().
Referenced by mlir::tblgen::AttrOrTypeDef::getTraits().
operator>()
bool mlir::presburger::operator> (Fraction x, Fraction y) inline
Definition at line 77 of file Fraction.h.
References compare().
operator>=()
bool mlir::presburger::operator>= (Fraction x, Fraction y) inline
Definition at line 79 of file Fraction.h.
References compare().
removeDuplicateDivs()
void mlir::presburger::removeDuplicateDivs (std::vector< SmallVector< int64_t, 8 >> & divs, SmallVectorImpl< unsigned > & denoms, unsigned localOffset, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given dividends of divisions divs and denominators denoms, detects and removes duplicate divisions.
localOffset is the offset in dividend of a division from where local identifiers start.
On every possible duplicate division found, merge(i, j), where i, j are current index of the duplicate divisions, is called and division at index j is merged into division at index i. If merge(i, j) returns true, the divisions are merged i.e. j^th division gets eliminated and it's each instance is replaced by i^th division. If it returns false, the divisions are not merged. merge can also do side effects, For example it can merge the local identifiers in IntegerRelation.
Definition at line 256 of file Utils.cpp.
Referenced by mergeLocalIds(), and mlir::presburger::IntegerRelation::removeDuplicateDivs().