MLIR: mlir::tosa Namespace Reference
mlir::tosa Namespace Reference
Namespaces
detail
Classes
class TosaOp
struct ValueKnowledge
Statically known information for a particular Value.
Functions
std::unique_ptr< Pass > createTosaToArith ()
void populateTosaToArithConversionPatterns (RewritePatternSet *patterns)
void populateTosaRescaleToArithConversionPatterns (RewritePatternSet *patterns)
std::unique_ptr< Pass > createTosaToLinalg ()
std::unique_ptr< Pass > createTosaToLinalgNamed ()
void addTosaToLinalgPasses (OpPassManager &pm, bool disableTosaDecompositions=false)
Populates passes to convert from TOSA to Linalg on buffers.
void populateTosaToLinalgConversionPatterns (RewritePatternSet *patterns)
Populates conversion passes from TOSA dialect to Linalg dialect.
void populateTosaToLinalgNamedConversionPatterns (RewritePatternSet *patterns)
Populates conversion passes from TOSA dialect to Linalg named operations.
std::unique_ptr< Pass > createTosaToSCF ()
void populateTosaToSCFConversionPatterns (RewritePatternSet *patterns)
void addTosaToSCFPasses (OpPassManager &pm)
Populates passes to convert from TOSA to SCF.
std::unique_ptr< Pass > createTosaToTensor ()
void populateTosaToTensorConversionPatterns (RewritePatternSet *patterns)
void populateTosaDecomposeConv2D (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaDecomposeTransposeConv (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaDecomposeDepthwise (MLIRContext *ctx, RewritePatternSet &patterns)
std::unique_ptr< Pass > createTosaInferShapesPass ()
std::unique_ptr< Pass > createTosaMakeBroadcastablePass ()
std::unique_ptr< Pass > createTosaTestQuantUtilAPIPass ()
std::unique_ptr< Pass > createTosaOptionalDecompositions ()
SmallVector< StringRef > getNParallelLoopsAttrs (unsigned nParallelLoops)
SmallVector< Value > condenseValues (const SmallVector< Value > &values)
template<typename T , typename P >
arith::SelectOp clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder &rewriter)
template<typename T >
void getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > &arrayValues)
template<typename Op >
Optional< SmallVector< Value > > checkHasDynamicBatchDims (PatternRewriter &rewriter, Op op, ArrayRef< Value > params)
void computeMultiplierAndShift (double scale, int32_t &multiplier, int32_t &shift, int32_t scaleWidth)
From a scale value, computes multiplier and shift values for 16 or 32-bit scale widths.
ConvOpQuantizationAttr buildConvOpQuantizationAttr (OpBuilder &builder, Value input, Value weight)
Method to build ConvOpQuantizationAttr, called from ConvOpQuantInfoBuilder/TransConvOpQuantInfoBuilder: input_zp: input zeropoint weight_zp: weight zeropoint.
MatMulOpQuantizationAttr buildMatMulOpQuantizationAttr (OpBuilder &builder, Value a, Value b)
Builds MatMulOpQuantizationAttr, called from MatMulOpQuantInfoBuilder: aZp: input a zeropoint bZp: input b zeropoint.
UnaryOpQuantizationAttr buildUnaryOpQuantizationAttr (OpBuilder &builder, Value input, Type outputRawType)
Builds UnaryOpQuantizationAttr UnaryOpQuantInfoBuilder: inputZp: input zeropoint outputZp: output zeropoint.
PadOpQuantizationAttr buildPadOpQuantizationAttr (OpBuilder &builder, Value input)
Builds PadOpQuantizationAttr, called from PadOpQuantInfoBuilder: inputZp: input zeropoint.
Type buildConvOpResultTypeInfo (OpBuilder &builder, Type outputType, Value input, Value weight)
construct ConvOp output type with correct bitwidth based on input/weight width.
Type buildQTypeFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
TypeAttr buildQTypeAttrFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Function Documentation
addTosaToLinalgPasses()
void mlir::tosa::addTosaToLinalgPasses (OpPassManager & pm, bool disableTosaDecompositions = false)
Populates passes to convert from TOSA to Linalg on buffers.
At the end of the pass, the function will only contain linalg ops or standard ops if the pipeline succeeds. The option to disable decompositions is available for benchmarking performance improvements from the canonicalizations.
Definition at line 69 of file TosaToLinalgPass.cpp.
References mlir::OpPassManager::addNestedPass(), mlir::createCanonicalizerPass(), createTosaMakeBroadcastablePass(), createTosaOptionalDecompositions(), createTosaToLinalg(), and createTosaToLinalgNamed().
addTosaToSCFPasses()
void mlir::tosa::addTosaToSCFPasses (OpPassManager & pm)
Populates passes to convert from TOSA to SCF.
Definition at line 50 of file TosaToSCFPass.cpp.
References mlir::OpPassManager::addNestedPass(), and createTosaToSCF().
buildConvOpQuantizationAttr()
ConvOpQuantizationAttr mlir::tosa::buildConvOpQuantizationAttr (OpBuilder & builder, Value input, Value weight)
Method to build ConvOpQuantizationAttr, called from ConvOpQuantInfoBuilder/TransConvOpQuantInfoBuilder: input_zp: input zeropoint weight_zp: weight zeropoint.
Definition at line 116 of file QuantUtils.cpp.
References mlir::Type::dyn_cast(), GET_UQTYPE, mlir::Builder::getContext(), mlir::Builder::getI32IntegerAttr(), and mlir::Value::getType().
Referenced by buildConvOpWithQuantInfo(), buildFCOpWithQuantInfo(), and buildTransConvOpWithQuantInfo().
buildConvOpResultTypeInfo()
Type mlir::tosa::buildConvOpResultTypeInfo (OpBuilder & builder, Type outputType, Value input, Value weight)
construct ConvOp output type with correct bitwidth based on input/weight width.
Builds output type for a quantized ConvOp with the right bitwidth.
This is called by the builder when dealing with quantized content.
Definition at line 259 of file QuantUtils.cpp.
References mlir::Type::dyn_cast(), GET_QTYPE, mlir::Builder::getI32Type(), mlir::Builder::getIntegerType(), and mlir::Value::getType().
Referenced by buildConvOpWithQuantInfo(), buildFCOpWithQuantInfo(), and buildTransConvOpWithQuantInfo().
buildMatMulOpQuantizationAttr()
MatMulOpQuantizationAttr mlir::tosa::buildMatMulOpQuantizationAttr (OpBuilder & builder, Value a, Value b)
Builds MatMulOpQuantizationAttr, called from MatMulOpQuantInfoBuilder: aZp: input a zeropoint bZp: input b zeropoint.
Definition at line 165 of file QuantUtils.cpp.
References mlir::Type::dyn_cast(), GET_UQTYPE, mlir::Builder::getContext(), mlir::Builder::getI32IntegerAttr(), and mlir::Value::getType().
Referenced by buildMatMulOpWithQuantInfo().
buildPadOpQuantizationAttr()
PadOpQuantizationAttr mlir::tosa::buildPadOpQuantizationAttr (OpBuilder & builder, Value input)
Builds PadOpQuantizationAttr, called from PadOpQuantInfoBuilder: inputZp: input zeropoint.
Definition at line 234 of file QuantUtils.cpp.
References mlir::Type::dyn_cast(), GET_UQTYPE, mlir::Builder::getContext(), mlir::Builder::getI32IntegerAttr(), and mlir::Value::getType().
Referenced by buildExplicitValuePadOpWithQuantInfo(), and buildPadOpWithQuantInfo().
buildQTypeAttrFromMinMax()
TypeAttr mlir::tosa::buildQTypeAttrFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Definition at line 359 of file QuantUtils.cpp.
References buildQTypeFromMinMax().
buildQTypeFromMinMax()
Type mlir::tosa::buildQTypeFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Definition at line 291 of file QuantUtils.cpp.
References mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::quant::fakeQuantAttrsToType(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), mlir::Builder::getUnknownLoc(), mlir::BoolAttr::getValue(), max(), and min().
Referenced by buildQTypeAttrFromMinMax().
buildUnaryOpQuantizationAttr()
UnaryOpQuantizationAttr mlir::tosa::buildUnaryOpQuantizationAttr (OpBuilder & builder, Value input, Type outputRawType)
Builds UnaryOpQuantizationAttr UnaryOpQuantInfoBuilder: inputZp: input zeropoint outputZp: output zeropoint.
Definition at line 201 of file QuantUtils.cpp.
References mlir::Type::dyn_cast(), GET_UQTYPE, mlir::Builder::getContext(), mlir::Builder::getI32IntegerAttr(), and mlir::Value::getType().
Referenced by buildAvgPool2dOpWithQuantInfo(), and buildUnaryOpWithQuantInfo().
checkHasDynamicBatchDims()
template<typename Op > Optional<SmallVector<Value> > mlir::tosa::checkHasDynamicBatchDims (PatternRewriter & rewriter, Op op, ArrayRef< Value > params)
Definition at line 54 of file CoversionUtils.h.
References mlir::OpBuilder::create(), mlir::OpState::getLoc(), and mlir::RewriterBase::notifyMatchFailure().
Referenced by createReassociationMapsForCollapse(), and inferDynamicDimsForConv().
clampHelper()
template<typename T , typename P > arith::SelectOp mlir::tosa::clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder & rewriter)
Definition at line 32 of file CoversionUtils.h.
References mlir::OpBuilder::create(), max(), and min().
computeMultiplierAndShift()
void mlir::tosa::computeMultiplierAndShift (double scale, int32_t & multiplier, int32_t & shift, int32_t scaleWidth)
From a scale value, computes multiplier and shift values for 16 or 32-bit scale widths.
Generates a quantized multiplier/shift from double.
Definition at line 91 of file QuantUtils.cpp.
References computeMultiplierAndShiftTosaScale16(), and computeMultiplierAndShiftTosaScale32().
condenseValues()
SmallVector< Value > mlir::tosa::condenseValues (const SmallVector< Value > & values)
Definition at line 24 of file ConversionUtils.cpp.
References value.
Referenced by createReassociationMapsForCollapse(), elementwiseMatchAndRewriteHelper(), and inferDynamicDimsForConv().
createTosaInferShapesPass()
std::unique_ptr< Pass > mlir::tosa::createTosaInferShapesPass ()
Definition at line 325 of file TosaInferShapes.cpp.
createTosaMakeBroadcastablePass()
std::unique_ptr< Pass > mlir::tosa::createTosaMakeBroadcastablePass ()
Definition at line 266 of file TosaMakeBroadcastable.cpp.
Referenced by addTosaToLinalgPasses().
createTosaOptionalDecompositions()
std::unique_ptr< Pass > mlir::tosa::createTosaOptionalDecompositions ()
Definition at line 44 of file TosaOptionalDecompositions.cpp.
Referenced by addTosaToLinalgPasses().
createTosaTestQuantUtilAPIPass()
std::unique_ptr<Pass> mlir::tosa::createTosaTestQuantUtilAPIPass ()
createTosaToArith()
std::unique_ptr< Pass > mlir::tosa::createTosaToArith ()
Definition at line 50 of file TosaToArithPass.cpp.
createTosaToLinalg()
std::unique_ptr< Pass > mlir::tosa::createTosaToLinalg ()
Definition at line 65 of file TosaToLinalgPass.cpp.
Referenced by addTosaToLinalgPasses().
createTosaToLinalgNamed()
std::unique_ptr< Pass > mlir::tosa::createTosaToLinalgNamed ()
Definition at line 64 of file TosaToLinalgNamedPass.cpp.
Referenced by addTosaToLinalgPasses().
createTosaToSCF()
std::unique_ptr< Pass > mlir::tosa::createTosaToSCF ()
Definition at line 46 of file TosaToSCFPass.cpp.
Referenced by addTosaToSCFPasses().
createTosaToTensor()
std::unique_ptr< Pass > mlir::tosa::createTosaToTensor ()
Definition at line 45 of file TosaToTensorPass.cpp.
getNParallelLoopsAttrs()
SmallVector< StringRef > mlir::tosa::getNParallelLoopsAttrs (unsigned nParallelLoops)
Definition at line 19 of file ConversionUtils.cpp.
References mlir::getParallelIteratorTypeName().
Referenced by createReassociationMapsForCollapse(), elementwiseMatchAndRewriteHelper(), and inferDynamicDimsForConv().
getValuesFromIntArrayAttribute()
template<typename T > void mlir::tosa::getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > & arrayValues)
Definition at line 44 of file CoversionUtils.h.
Referenced by createReassociationMapsForCollapse(), and inferDynamicDimsForConv().
populateTosaDecomposeConv2D()
void mlir::tosa::populateTosaDecomposeConv2D (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 112 of file TosaDecomposeConv2D.cpp.
References mlir::RewritePatternSet::add().
populateTosaDecomposeDepthwise()
void mlir::tosa::populateTosaDecomposeDepthwise (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 118 of file TosaDecomposeDepthwise.cpp.
References mlir::RewritePatternSet::add().
populateTosaDecomposeTransposeConv()
void mlir::tosa::populateTosaDecomposeTransposeConv (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 376 of file TosaDecomposeTransposeConv.cpp.
References mlir::RewritePatternSet::add().
populateTosaRescaleToArithConversionPatterns()
void mlir::tosa::populateTosaRescaleToArithConversionPatterns (RewritePatternSet * patterns)
Definition at line 160 of file TosaToArith.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToArithConversionPatterns()
void mlir::tosa::populateTosaToArithConversionPatterns (RewritePatternSet * patterns)
Definition at line 155 of file TosaToArith.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToLinalgConversionPatterns()
void mlir::tosa::populateTosaToLinalgConversionPatterns (RewritePatternSet * patterns)
Populates conversion passes from TOSA dialect to Linalg dialect.
Definition at line 2260 of file TosaToLinalg.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToLinalgNamedConversionPatterns()
void mlir::tosa::populateTosaToLinalgNamedConversionPatterns (RewritePatternSet * patterns)
Populates conversion passes from TOSA dialect to Linalg named operations.
Definition at line 954 of file TosaToLinalgNamed.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToSCFConversionPatterns()
void mlir::tosa::populateTosaToSCFConversionPatterns (RewritePatternSet * patterns)
Definition at line 107 of file TosaToSCF.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToTensorConversionPatterns()
void mlir::tosa::populateTosaToTensorConversionPatterns (RewritePatternSet * patterns)
Definition at line 44 of file TosaToTensor.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().