MLIR: mlir::bufferization Namespace Reference
mlir::bufferization Namespace Reference
Namespaces
func_ext
Classes
class AlwaysCopyAnalysisState
This a "no analysis, always copy" AnalysisState.
class AnalysisState
AnalysisState provides a variety of helper functions for dealing with tensor values.
class BufferizationAliasInfo
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
struct BufferizationOptions
Options for BufferizableOpInterface-based bufferization.
struct BufferizationState
BufferizationState provides helper functions for performing bufferization rewrites and handling memref buffers.
class BufferizeTypeConverter
A helper type converter class that automatically populates the relevant materializations and type conversions for bufferization.
class BufferPlacementAllocs
A simple analysis that detects allocation operations.
class BufferPlacementTransformationBase
The base class for all BufferPlacement transformations.
struct DialectAnalysisState
Dialect-specific analysis state.
class OneShotAnalysisState
State for analysis-enabled bufferization.
struct OneShotBufferizationOptions
Options for analysis-enabled bufferization.
Typedefs
using PostAnalysisStepFn = std::function< LogicalResult(Operation *, AnalysisState &, BufferizationAliasInfo &, SmallVector< Operation * > &)>
PostAnalysisStepFns can be registered with BufferizationOptions and are executed after the analysis, but before bufferization.
using PostAnalysisStepList = SmallVector< PostAnalysisStepFn >
Enumerations
enum BufferRelation { BufferRelation::None, BufferRelation::Equivalent }
Specify fine-grain relationship between buffers to enable more analysis.
Functions
bool isFunctionArgument (Value value)
Return true if the given value is a BlockArgument of a func::FuncOp.
void replaceOpWithBufferizedValues (RewriterBase &rewriter, Operation *op, ValueRange values)
Replace an op with replacement values.
Value lookupBuffer (RewriterBase &rewriter, Value tensor, const BufferizationOptions &options)
Lookup the buffer for the given value.
template<typename OpTy , typename... Args>
OpTy replaceOpWithNewBufferizedOp (RewriterBase &rewriter, Operation *op, Args &&...args)
Replace an op with a new op.
MemRefType getContiguousMemRefType (ShapedType shapedType, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
BaseMemRefType getMemRefType (TensorType tensorType, const BufferizationOptions &options, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
LogicalResult createDealloc (OpBuilder &b, Location loc, Value allocatedBuffer, const BufferizationOptions &options)
Creates a memref deallocation.
LogicalResult createMemCpy (OpBuilder &b, Location loc, Value from, Value to, const BufferizationOptions &options)
Creates a memcpy between two given buffers.
LogicalResult hoistBufferAllocations (Operation *op, const BufferizationOptions &options)
Try to hoist all new buffer allocations until the next hoisting barrier.
LogicalResult createAllocDeallocOps (Operation *op, const BufferizationOptions &options, bool onlyLeakingAllocs=false, bool *changed=nullptr)
Create alloc/dealloc ops as specified in the bufferization options.
FailureOr< Value > castOrReallocMemRefValue (OpBuilder &b, Value value, MemRefType type)
Try to cast the given ranked MemRef-typed value to the given ranked MemRef type.
LogicalResult foldToMemrefToTensorPair (RewriterBase &rewriter, ToMemrefOp toMemref, bool allowSameType=true)
Try to fold to_memref(to_tensor(x)).
void populateBufferizeMaterializationLegality (ConversionTarget &target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
void populateEliminateBufferizeMaterializationsPatterns (BufferizeTypeConverter &typeConverter, RewritePatternSet &patterns)
Populate patterns to eliminate bufferize materializations.
LogicalResult bufferizeOp (Operation *op, const AnalysisState &analysisState)
Bufferize op and its nested ops that implement BufferizableOpInterface.
LogicalResult bufferizeOp (Operation *op, const BufferizationOptions &options)
Bufferize op and its nested ops that implement BufferizableOpInterface.
BufferizationOptions getPartialBufferizationOptions ()
LogicalResult bufferizeOp (Operation *op, BufferizationState &bufferizationState)
Bufferize op and its nested ops that implement BufferizableOpInterface.
LogicalResult finalizeBuffers (Operation *op, const BufferizationOptions &options)
Finalize all buffer allocations.
FailureOr< memref::GlobalOp > getGlobalFor (arith::ConstantOp constantOp, uint64_t alignment)
LogicalResult analyzeOp (Operation *op, OneShotAnalysisState &state)
Analyze op and its nested ops.
LogicalResult runOneShotBufferize (Operation *op, const OneShotBufferizationOptions &options)
Run One-Shot Bufferize on the given op: Analysis + Bufferization.
LogicalResult runOneShotModuleBufferize (ModuleOp moduleOp, bufferization::OneShotBufferizationOptions options)
Run One-Shot Module Bufferization on the given module.
std::unique_ptr< Pass > createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
LogicalResult deallocateBuffers (Operation *op)
Run buffer deallocation.
std::unique_ptr< Pass > createBufferHoistingPass ()
Creates a pass that moves allocations upwards to reduce the number of required copies that are inserted during the BufferDeallocation pass.
std::unique_ptr< Pass > createBufferLoopHoistingPass ()
Creates a pass that moves allocations upwards out of loops.
std::unique_ptr< Pass > createBufferResultsToOutParamsPass ()
Creates a pass that converts memref function results to out-params.
std::unique_ptr< OperationPass< func::FuncOp > > createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining bufferization.to_tensor and bufferization.to_memref operations.
std::unique_ptr< Pass > createOneShotBufferizePass ()
Create a pass that bufferizes all ops that implement BufferizableOpInterface with One-Shot Bufferize.
std::unique_ptr< Pass > createOneShotBufferizePass (const OneShotBufferizationOptions &options)
Create a pass that bufferizes all ops that implement BufferizableOpInterface with One-Shot Bufferize and the specified bufferization options.
std::unique_ptr< Pass > createPromoteBuffersToStackPass (unsigned maxAllocSizeInBytes=1024, unsigned maxRankOfAllocatedMemRef=1)
Creates a pass that promotes heap-based allocations to stack-based ones.
std::unique_ptr< Pass > createPromoteBuffersToStackPass (std::function< bool(Value)> isSmallAlloc)
Creates a pass that promotes heap-based allocations to stack-based ones.
void registerAllocationOpInterfaceExternalModels (DialectRegistry &registry)
Register external models for AllocationOpInterface.
Typedef Documentation
PostAnalysisStepFn
using mlir::bufferization::PostAnalysisStepFn = typedef std::function<LogicalResult(Operation *, AnalysisState &, BufferizationAliasInfo &, SmallVector<Operation *> &)>
PostAnalysisStepFns can be registered with BufferizationOptions and are executed after the analysis, but before bufferization.
They can be used to implement custom dialect-specific optimizations. They may modify the IR, but must keep aliasInfo consistent. Newly created operations and operations that should be re-analyzed must be added to newOps.
Definition at line 30 of file OneShotAnalysis.h.
PostAnalysisStepList
using mlir::bufferization::PostAnalysisStepList = typedef SmallVector<PostAnalysisStepFn>
Definition at line 32 of file OneShotAnalysis.h.
Enumeration Type Documentation
BufferRelation
enum mlir::bufferization::BufferRelation strong
Specify fine-grain relationship between buffers to enable more analysis.
Enumerator
None
Equivalent
Definition at line 247 of file BufferizableOpInterface.h.
Function Documentation
analyzeOp()
LogicalResult mlir::bufferization::analyzeOp (Operation * op, OneShotAnalysisState & state)
Analyze op and its nested ops.
Bufferization decisions are stored in state.
Definition at line 880 of file OneShotAnalysis.cpp.
References annotateOpsWithBufferizationMarkers(), assertDestinationPassingStyle(), checkAliasInfoConsistency(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), mlir::bufferization::OneShotAnalysisState::gatherYieldedTensors(), mlir::bufferization::OneShotAnalysisState::getAliasInfo(), mlir::bufferization::AnalysisState::getOptions(), mlir::bufferization::AnalysisState::hasDialectState(), inPlaceAnalysis(), mlir::success(), and mlir::Operation::walk().
Referenced by mlir::bufferization::OneShotAnalysisState::getAliasInfo(), runOneShotBufferize(), and runOneShotModuleBufferize().
bufferizeOp() [1/3]
LogicalResult mlir::bufferization::bufferizeOp (Operation * op, const AnalysisState & analysisState)
Bufferize op and its nested ops that implement BufferizableOpInterface.
Whether buffer copies are needed or not is queried from state.
Note: If allowUnknownOps is set to false, bufferization fails when an unknown op (that does not implement BufferizableOpInterface) is found. No to_tensor/to_memref ops are inserted in that case.
Note: The layout map chosen to bufferize is the most dynamic canonical strided layout of the proper rank. This ensures compatibility with expected layouts after transformations. Combinations of memref.cast + canonicalization are responsible for clean ups.
Definition at line 283 of file Bufferize.cpp.
References mlir::bufferization::BufferizationOptions::bufferizeFunctionBoundaries, mlir::failed(), mlir::failure(), finalizeBuffers(), mlir::bufferization::AnalysisState::getOptions(), mlir::bufferization::AnalysisState::hasDialectState(), hasTensorSemantics(), mlir::OpBuilder::Listener::notifyOperationInserted(), mlir::RewriterBase::notifyOperationRemoved(), and mlir::success().
Referenced by bufferizeOp(), runOneShotBufferize(), and runOneShotModuleBufferize().
bufferizeOp() [2/3]
LogicalResult mlir::bufferization::bufferizeOp (Operation * op, const BufferizationOptions & options)
Bufferize op and its nested ops that implement BufferizableOpInterface.
Buffers are duplicated and copied before any tensor use that bufferizes to a memory write.
Note: This function bufferizes ops without utilizing analysis results. It can be used to implement partial bufferization passes.
Definition at line 457 of file Bufferize.cpp.
References bufferizeOp().
bufferizeOp() [3/3]
LogicalResult mlir::bufferization::bufferizeOp (Operation * op, BufferizationState & bufferizationState)
Bufferize op and its nested ops that implement BufferizableOpInterface.
Reuse an existing BufferizationState.
Note: This function overload is useful for extending the bufferization.
Check the result of bufferization. Return an error if an op was not bufferized, unless partial bufferization is allowed.
Definition at line 346 of file Bufferize.cpp.
References mlir::bufferization::BufferizationOptions::allowUnknownOps, mlir::Operation::emitError(), foldToMemrefToTensorPair(), mlir::Operation::getContext(), mlir::bufferization::BufferizationState::getOptions(), mlir::Operation::getUses(), hasTensorSemantics(), isInPlace(), options, mlir::PreOrder, mlir::success(), and mlir::Operation::walk().
castOrReallocMemRefValue()
FailureOr< Value > mlir::bufferization::castOrReallocMemRefValue (OpBuilder & b, Value value, MemRefType type)
Try to cast the given ranked MemRef-typed value to the given ranked MemRef type.
Insert a reallocation + copy if it cannot be statically guaranteed that a direct cast would be valid.
E.g., when casting from a ranked MemRef type with dynamic layout to a ranked MemRef type with static layout, it is not statically known whether the cast will succeed or not. Such memref.cast ops may fail at runtime. This function never generates such casts and conservatively inserts a copy.
This function returns failure() in case of unsupported casts. E.g., casts with differing element types or memory spaces.
Definition at line 23 of file BufferizationOps.cpp.
References mlir::Type::cast(), copy(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::failed(), mlir::failure(), mlir::Value::getLoc(), mlir::getStridesAndOffset(), mlir::Value::getType(), and value.
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), and foldToMemrefToTensorPair().
createAllocDeallocOps()
LogicalResult mlir::bufferization::createAllocDeallocOps (Operation * op, const BufferizationOptions & options, bool onlyLeakingAllocs = false, bool * changed = nullptr)
Create alloc/dealloc ops as specified in the bufferization options.
If onlyLeakingAlloc, only those buffer allocations are processed for which no buffer deallocation can be created. changed is set to true if the IR was modified.
Definition at line 538 of file BufferizableOpInterface.cpp.
References mlir::WalkResult::advance(), createAlloc(), createDealloc(), mlir::failed(), mlir::Operation::getContext(), mlir::Block::getTerminator(), mlir::WalkResult::interrupt(), kBufferAllocationAttr, kSkipDeallocAttr, mlir::WalkResult::skip(), mlir::success(), mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by finalizeBuffers(), and replaceOpWithNewBufferizedOp().
createBufferDeallocationPass()
std::unique_ptr< Pass > mlir::bufferization::createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
Definition at line 702 of file BufferDeallocation.cpp.
createBufferHoistingPass()
std::unique_ptr< Pass > mlir::bufferization::createBufferHoistingPass ()
Creates a pass that moves allocations upwards to reduce the number of required copies that are inserted during the BufferDeallocation pass.
Definition at line 420 of file BufferOptimizations.cpp.
createBufferLoopHoistingPass()
std::unique_ptr< Pass > mlir::bufferization::createBufferLoopHoistingPass ()
Creates a pass that moves allocations upwards out of loops.
This avoids reallocations inside of loops.
Definition at line 424 of file BufferOptimizations.cpp.
createBufferResultsToOutParamsPass()
std::unique_ptr< Pass > mlir::bufferization::createBufferResultsToOutParamsPass ()
Creates a pass that converts memref function results to out-params.
Definition at line 145 of file BufferResultsToOutParams.cpp.
createDealloc()
LogicalResult mlir::bufferization::createDealloc (OpBuilder & b, Location loc, Value allocatedBuffer, const BufferizationOptions & options)
Creates a memref deallocation.
The given memref buffer must have been allocated using createAlloc.
Definition at line 438 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::bufferization::BufferizationOptions::deallocationFn, and mlir::success().
Referenced by createAllocDeallocOps(), and replaceOpWithNewBufferizedOp().
createFinalizingBufferizePass()
std::unique_ptr< OperationPass< func::FuncOp > > mlir::bufferization::createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining bufferization.to_tensor and bufferization.to_memref operations.
Definition at line 236 of file Bufferize.cpp.
Referenced by mlir::sparse_tensor::buildSparseCompiler().
createMemCpy()
LogicalResult mlir::bufferization::createMemCpy (OpBuilder & b, Location loc, Value from, Value to, const BufferizationOptions & options)
Creates a memcpy between two given buffers.
Create a memory copy between two memref buffers.
Definition at line 527 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::bufferization::BufferizationOptions::memCpyFn, and mlir::success().
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::BufferizationState::getBuffer(), and replaceOpWithNewBufferizedOp().
createOneShotBufferizePass() [1/2]
std::unique_ptr< Pass > mlir::bufferization::createOneShotBufferizePass ()
Create a pass that bufferizes all ops that implement BufferizableOpInterface with One-Shot Bufferize.
Definition at line 226 of file Bufferize.cpp.
createOneShotBufferizePass() [2/2]
std::unique_ptr< Pass > mlir::bufferization::createOneShotBufferizePass (const OneShotBufferizationOptions & options)
Create a pass that bufferizes all ops that implement BufferizableOpInterface with One-Shot Bufferize and the specified bufferization options.
Definition at line 230 of file Bufferize.cpp.
References options.
createPromoteBuffersToStackPass() [1/2]
std::unique_ptr< Pass > mlir::bufferization::createPromoteBuffersToStackPass (unsigned maxAllocSizeInBytes = 1024, unsigned maxRankOfAllocatedMemRef = 1)
Creates a pass that promotes heap-based allocations to stack-based ones.
Only buffers smaller than the provided size are promoted. Dynamic shaped buffers are promoted up to the given rank.
Definition at line 428 of file BufferOptimizations.cpp.
createPromoteBuffersToStackPass() [2/2]
std::unique_ptr< Pass > mlir::bufferization::createPromoteBuffersToStackPass (std::function< bool(Value)> isSmallAlloc)
Creates a pass that promotes heap-based allocations to stack-based ones.
Only buffers smaller with isSmallAlloc(alloc) == true are promoted.
Definition at line 434 of file BufferOptimizations.cpp.
deallocateBuffers()
LogicalResult mlir::bufferization::deallocateBuffers (Operation * op)
Run buffer deallocation.
Definition at line 655 of file BufferDeallocation.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::WalkResult::interrupt(), mlir::success(), validateSupportedControlFlow(), mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by finalizeBuffers(), and validateSupportedControlFlow().
finalizeBuffers()
LogicalResult mlir::bufferization::finalizeBuffers (Operation * op, const BufferizationOptions & options)
Finalize all buffer allocations.
Hoist buffer allocations as much as possible.
Create alloc/dealloc ops as specified by the bufferization options.
Definition at line 260 of file Bufferize.cpp.
References createAllocDeallocOps(), mlir::bufferization::BufferizationOptions::createDeallocs, deallocateBuffers(), mlir::failed(), mlir::failure(), hoistBufferAllocations(), and mlir::success().
Referenced by bufferizeOp(), and runOneShotModuleBufferize().
foldToMemrefToTensorPair()
LogicalResult mlir::bufferization::foldToMemrefToTensorPair (RewriterBase & rewriter, ToMemrefOp toMemref, bool allowSameType = true)
Try to fold to_memref(to_tensor(x)).
If x's type and the result type of the to_memref op are different, a memref.cast is needed.
Definition at line 83 of file BufferizationOps.cpp.
References mlir::RewritePatternSet::add(), castOrReallocMemRefValue(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::memref::findDealloc(), mlir::memref::foldMemRefCast(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::Operation::getBlock(), mlir::Value::getLoc(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
Referenced by bufferizeOp().
getContiguousMemRefType()
MemRefType mlir::bufferization::getContiguousMemRefType (ShapedType shapedType, Attribute memorySpace = {})
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified addressSpace.
Definition at line 652 of file BufferizableOpInterface.cpp.
Referenced by getAllocationTypeAndShape(), and replaceOpWithNewBufferizedOp().
getGlobalFor()
FailureOr< memref::GlobalOp > mlir::bufferization::getGlobalFor (arith::ConstantOp constantOp, uint64_t alignment)
Definition at line 149 of file BufferUtils.cpp.
References mlir::TypeConverter::convertType(), mlir::failure(), mlir::Region::getOps(), and mlir::Operation::getRegion().
getMemRefType()
BaseMemRefType mlir::bufferization::getMemRefType (TensorType tensorType, const BufferizationOptions & options, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {})
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 659 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::bufferization::BufferizationOptions::fullyDynamicLayoutMaps, and mlir::makeStridedLinearLayoutMap().
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), foldTransferInBoundsAttribute(), mlir::bufferization::func_ext::getBufferizedFunctionArgType(), mlir::bufferization::BufferizationState::getBufferType(), lookupBuffer(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), parseGlobalMemrefOpTypeAndInitialValue(), mlir::replaceForOpWithNewYields(), replaceOpWithNewBufferizedOp(), verifyMemoryOpIndexing(), verifyMultShape(), and verifyVectorMemoryOp().
getPartialBufferizationOptions()
BufferizationOptions mlir::bufferization::getPartialBufferizationOptions ()
Definition at line 463 of file Bufferize.cpp.
References mlir::bufferization::BufferizationOptions::allowUnknownOps, mlir::bufferization::BufferizationOptions::createDeallocs, mlir::bufferization::BufferizationOptions::fullyDynamicLayoutMaps, and options.
hoistBufferAllocations()
LogicalResult mlir::bufferization::hoistBufferAllocations (Operation * op, const BufferizationOptions & options)
Try to hoist all new buffer allocations until the next hoisting barrier.
Definition at line 587 of file BufferizableOpInterface.cpp.
References mlir::Block::findAncestorOpInBlock(), mlir::Operation::getParentOp(), mlir::Operation::getRegions(), mlir::bufferization::BufferizationOptions::hoistAllocations, kBufferAllocationAttr, mlir::success(), and mlir::Operation::walk().
Referenced by finalizeBuffers(), and replaceOpWithNewBufferizedOp().
isFunctionArgument()
bool mlir::bufferization::isFunctionArgument (Value value)
Return true if the given value is a BlockArgument of a func::FuncOp.
Definition at line 645 of file BufferizableOpInterface.cpp.
References mlir::Value::dyn_cast().
lookupBuffer()
Value mlir::bufferization::lookupBuffer (RewriterBase & rewriter, Value tensor, const BufferizationOptions & options)
Lookup the buffer for the given value.
If the value was not bufferized yet, wrap it in a ToMemrefOp. Otherwise, it is the result of a ToTensorOp, from which the memref operand is returned.
Note: Use BufferizationState::getBuffer during bufferization. lookupBuffer is just for compatibility and gradual migration of bufferization patterns to BufferizableOpInterface-based bufferization. It does not insert any buffer copies.
Definition at line 252 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), ensureToMemrefOpIsValid(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), getMemRefType(), mlir::Value::getType(), and setInsertionPointAfter().
Referenced by mlir::bufferization::BufferizationState::getAnalysisState(), and mlir::bufferization::BufferizationState::getBuffer().
populateBufferizeMaterializationLegality()
void mlir::bufferization::populateBufferizeMaterializationLegality (ConversionTarget & target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
This function should be called by all bufferization passes using BufferizeTypeConverter so that materializations work properly. One exception is bufferization passes doing "full" conversions, where it can be desirable for even the materializations to remain illegal so that they are eliminated, such as via the patterns in populateEliminateBufferizeMaterializationsPatterns.
Definition at line 79 of file Bufferize.cpp.
References mlir::ConversionTarget::addLegalOp(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
populateEliminateBufferizeMaterializationsPatterns()
void mlir::bufferization::populateEliminateBufferizeMaterializationsPatterns (BufferizeTypeConverter & typeConverter, RewritePatternSet & patterns)
Populate patterns to eliminate bufferize materializations.
In particular, these are the tensor_load/buffer_cast ops.
Definition at line 116 of file Bufferize.cpp.
References mlir::RewritePatternSet::add(), mlir::OpPassManager::addPass(), mlir::bufferization::BufferizationOptions::allowOperationInFilter(), mlir::bufferization::OneShotBufferizationOptions::allowReturnAllocs, mlir::bufferization::BufferizationOptions::allowUnknownOps, mlir::bufferization::BufferizationOptions::alwaysAliasingWithDest, mlir::bufferization::BufferizationOptions::analysisFuzzerSeed, mlir::applyFullConversion(), mlir::bufferization::BufferizationOptions::bufferizeFunctionBoundaries, mlir::createCanonicalizerPass(), mlir::createCSEPass(), mlir::bufferization::BufferizationOptions::createDeallocs, mlir::createLoopInvariantCodeMotionPass(), mlir::bufferization::OneShotBufferizationOptions::dropEquivalentFuncResults, mlir::failed(), mlir::bufferization::BufferizationOptions::fullyDynamicLayoutMaps, mlir::RewritePatternSet::getContext(), mlir::DialectRegistry::insert(), mlir::TypeConverter::isLegal(), mlir::ConversionTarget::markUnknownOpDynamicallyLegal(), options, mlir::bufferization::BufferizationOptions::printConflicts, registerAllocationOpInterfaceExternalModels(), runOneShotBufferize(), runOneShotModuleBufferize(), and mlir::bufferization::BufferizationOptions::testAnalysisOnly.
registerAllocationOpInterfaceExternalModels()
void mlir::bufferization::registerAllocationOpInterfaceExternalModels (DialectRegistry & registry)
Register external models for AllocationOpInterface.
Definition at line 691 of file BufferDeallocation.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by populateEliminateBufferizeMaterializationsPatterns(), and validateSupportedControlFlow().
replaceOpWithBufferizedValues()
void mlir::bufferization::replaceOpWithBufferizedValues (RewriterBase & rewriter, Operation * op, ValueRange values)
Replace an op with replacement values.
The op is deleted. Tensor OpResults must be replaced with memref values.
Definition at line 356 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Value::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getOpResults(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::BufferizationState::getAnalysisState(), and replaceOpWithNewBufferizedOp().
replaceOpWithNewBufferizedOp()
template<typename OpTy , typename... Args> OpTy mlir::bufferization::replaceOpWithNewBufferizedOp (RewriterBase & rewriter, Operation * op, Args &&... args)
Replace an op with a new op.
The new op must have the same number of results as the replaced op. The new op may not return any tensor values.
Definition at line 491 of file BufferizableOpInterface.h.
References mlir::OpBuilder::create(), createAllocDeallocOps(), createDealloc(), createMemCpy(), getContiguousMemRefType(), mlir::Operation::getLoc(), getMemRefType(), mlir::Operation::getResults(), hoistBufferAllocations(), and replaceOpWithBufferizedValues().
runOneShotBufferize()
LogicalResult mlir::bufferization::runOneShotBufferize (Operation * op, const OneShotBufferizationOptions & options)
Run One-Shot Bufferize on the given op: Analysis + Bufferization.
Definition at line 938 of file OneShotAnalysis.cpp.
References analyzeOp(), bufferizeOp(), mlir::failed(), mlir::failure(), mlir::success(), and mlir::bufferization::BufferizationOptions::testAnalysisOnly.
Referenced by mlir::bufferization::OneShotAnalysisState::getAliasInfo(), and populateEliminateBufferizeMaterializationsPatterns().
runOneShotModuleBufferize()
LogicalResult mlir::bufferization::runOneShotModuleBufferize (ModuleOp moduleOp, bufferization::OneShotBufferizationOptions options)
Run One-Shot Module Bufferization on the given module.
Performs a simple function call analysis to determine which function arguments are inplaceable. Then analyzes and bufferizes FuncOps one-by-one with One-Shot Bufferize.
Definition at line 418 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::OneShotBufferizationOptions::addPostAnalysisStep(), mlir::bufferization::OneShotBufferizationOptions::allowReturnAllocs, mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::FuncAnalysisState::analyzedFuncOps, analyzeOp(), annotateOpsWithBufferizationMarkers(), mlir::bufferization::BufferizationOptions::bufferizeFunctionBoundaries, bufferizeOp(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), finalizeBuffers(), foldMemRefCasts(), mlir::bufferization::func_ext::getFuncAnalysisState(), getFuncOpsOrderedByCalls(), removeBufferizationAttributes(), mlir::bufferization::func_ext::FuncAnalysisState::startFunctionAnalysis(), mlir::success(), and mlir::bufferization::BufferizationOptions::testAnalysisOnly.
Referenced by populateEliminateBufferizeMaterializationsPatterns().