MLIR: lib/Tools/PDLL/AST/Nodes.cpp File Reference
Nodes.cpp File Reference
#include "mlir/Tools/PDLL/AST/Nodes.h"
#include "mlir/Tools/PDLL/AST/Context.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static StringRef copyStringWithNull (Context &ctx, StringRef str)
Copy a string reference into the context with a null terminator.
Function Documentation
copyStringWithNull()
static StringRef copyStringWithNull (Context & ctx, StringRef str) static
Copy a string reference into the context with a null terminator.
Definition at line 18 of file Nodes.cpp.
References copy(), and mlir::pdll::ast::Context::getAllocator().
Referenced by mlir::pdll::ast::Name::create(), mlir::pdll::ast::AttributeExpr::create(), and mlir::pdll::ast::TypeExpr::create().