MLIR: lib/Dialect/Bufferization/Transforms/OneShotModuleBufferize.cpp File Reference
OneShotModuleBufferize.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/OneShotModuleBufferize.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
Typedefs
using FuncCallerMap = DenseMap< func::FuncOp, DenseSet< Operation * > >
A mapping of FuncOps to their callers.
Functions
static const FuncAnalysisState & getFuncAnalysisState (const AnalysisState &state)
Get FuncAnalysisState.
static FuncAnalysisState & getFuncAnalysisState (AnalysisState &state)
Get or create FuncAnalysisState.
static FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState &state, func::FuncOp funcOp)
Return the state (phase) of analysis of the FuncOp.
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static void removeBufferizationAttributes (BlockArgument bbArg)
Remove bufferization attributes on FuncOp arguments.
static func::FuncOp getCalledFunction (CallOpInterface callOp)
Return the func::FuncOp called by callOp.
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo &aliasInfo, FuncAnalysisState &funcState)
Gather equivalence info of CallOps.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > &orderedFuncOps, FuncCallerMap &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void annotateOpsWithBufferizationMarkers (func::FuncOp funcOp, const AnalysisState &state)
Annotate the IR with the result of the analysis. For testing/debugging only.
static void foldMemRefCasts (func::FuncOp funcOp)
Fold return values that are memref casts and update function return types.
Typedef Documentation
FuncCallerMap
using FuncCallerMap = DenseMap<func::FuncOp, DenseSet<Operation *> >
A mapping of FuncOps to their callers.
Definition at line 89 of file OneShotModuleBufferize.cpp.
Function Documentation
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (func::FuncOp funcOp, const AnalysisState & state) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 382 of file OneShotModuleBufferize.cpp.
References setInPlaceFuncArgument().
Referenced by mlir::bufferization::runOneShotModuleBufferize().
equivalenceAnalysis()
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo & aliasInfo, FuncAnalysisState & funcState) static
Gather equivalence info of CallOps.
Note: This only adds new equivalence info if the called function was already analyzed.
Definition at line 292 of file OneShotModuleBufferize.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::func_ext::FuncAnalysisState::equivalentFuncArgs, mlir::bufferization::func_ext::getCalledFunction(), mlir::WalkResult::skip(), and mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses().
Referenced by mlir::bufferization::runOneShotModuleBufferize().
foldMemRefCasts()
static void foldMemRefCasts (func::FuncOp funcOp) static
Fold return values that are memref casts and update function return types.
During FuncOp bufferization, the exact type of the returned memrefs (if any) is not known yet. Therefore, the bufferization uses memref types with the most generic layout map as function return types. After bufferizing the entire function body, a more concise memref type can potentially be used for the return type of the function.
Definition at line 397 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::getAssumedUniqueReturnOp().
Referenced by mlir::bufferization::runOneShotModuleBufferize().
getAssumedUniqueReturnOp()
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 119 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::aliasingFuncArgs, mlir::bufferization::func_ext::FuncAnalysisState::aliasingReturnVals, mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), mlir::bufferization::BufferizationAliasInfo::areAliasingBufferizedValues(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::bufferization::AnalysisState::bufferizesToMemoryWrite(), mlir::Attribute::cast(), mlir::Value::dyn_cast(), mlir::bufferization::func_ext::FuncAnalysisState::equivalentFuncArgs, mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::bufferization::func_ext::getAssumedUniqueReturnOp(), mlir::Operation::getAttr(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::bufferization::AnalysisState::getOptions(), mlir::detail::IROperandBase::getOwner(), mlir::BlockArgument::getOwner(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Value::getUses(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::bufferization::AnalysisState::isInPlace(), mlir::bufferization::AnalysisState::isValueRead(), mlir::bufferization::func_ext::NotAnalyzed, mlir::bufferization::func_ext::FuncAnalysisState::readBbArgs, mlir::Operation::setAttr(), mlir::success(), mlir::bufferization::BufferizationOptions::testAnalysisOnly, value, and mlir::bufferization::func_ext::FuncAnalysisState::writtenBbArgs.
getCalledFunction()
static func::FuncOp getCalledFunction (CallOpInterface callOp) static
Return the func::FuncOp called by callOp.
Definition at line 280 of file OneShotModuleBufferize.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
getFuncAnalysisState() [1/2]
static const FuncAnalysisState& getFuncAnalysisState (const AnalysisState & state) static
Get FuncAnalysisState.
Definition at line 93 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::AnalysisState::getDialectState().
getFuncAnalysisState() [2/2]
static FuncAnalysisState& getFuncAnalysisState (AnalysisState & state) static
Get or create FuncAnalysisState.
Definition at line 102 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::AnalysisState::getOrCreateDialectState().
getFuncOpAnalysisState()
static FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState & state, func::FuncOp funcOp) static
Return the state (phase) of analysis of the FuncOp.
Definition at line 108 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::analyzedFuncOps, mlir::bufferization::func_ext::getFuncAnalysisState(), and mlir::bufferization::func_ext::NotAnalyzed.
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > & orderedFuncOps, FuncCallerMap & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 321 of file OneShotModuleBufferize.cpp.
Referenced by mlir::bufferization::runOneShotModuleBufferize().
removeBufferizationAttributes()
static void removeBufferizationAttributes (BlockArgument bbArg) static
Remove bufferization attributes on FuncOp arguments.
Definition at line 271 of file OneShotModuleBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::bufferization::runOneShotModuleBufferize().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 374 of file OneShotModuleBufferize.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().