MLIR: lib/Dialect/PDLInterp/IR/PDLInterp.cpp File Reference
PDLInterp.cpp File Reference
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOpsDialect.cpp.inc"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
template<typename OpT >
static LogicalResult verifySwitchOp (OpT op)
static ParseResult parseCreateOperationOpAttributes (OpAsmParser &p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &attrOperands, ArrayAttr &attrNamesAttr)
static void printCreateOperationOpAttributes (OpAsmPrinter &p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames)
static ParseResult parseCreateOperationOpResults (OpAsmParser &p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &resultOperands, SmallVectorImpl< Type > &resultTypes, UnitAttr &inferredResultTypes)
static void printCreateOperationOpResults (OpAsmPrinter &p, CreateOperationOp op, OperandRange resultOperands, TypeRange resultTypes, UnitAttr inferredResultTypes)
static Type getGetValueTypeOpValueType (Type type)
Given the result type of a GetValueTypeOp, return the expected input type.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 279 of file PDLInterp.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getGetValueTypeOpValueType()
static Type getGetValueTypeOpValueType (Type type) static
Given the result type of a GetValueTypeOp, return the expected input type.
Definition at line 234 of file PDLInterp.cpp.
References mlir::Type::getContext(), mlir::Type::isa(), mlir::verify(), and verifySwitchOp().
parseCreateOperationOpAttributes()
static ParseResult parseCreateOperationOpAttributes (OpAsmParser & p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & attrOperands, ArrayAttr & attrNamesAttr) static
Definition at line 67 of file PDLInterp.cpp.
References mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), mlir::succeeded(), and mlir::success().
parseCreateOperationOpResults()
static ParseResult parseCreateOperationOpResults (OpAsmParser & p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & resultOperands, SmallVectorImpl< Type > & resultTypes, UnitAttr & inferredResultTypes) static
Definition at line 102 of file PDLInterp.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getUnitAttr(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrow(), mlir::AsmParser::parseOptionalLess(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
printCreateOperationOpAttributes()
static void printCreateOperationOpAttributes (OpAsmPrinter & p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames) static
Definition at line 90 of file PDLInterp.cpp.
printCreateOperationOpResults()
static void printCreateOperationOpResults (OpAsmPrinter & p, CreateOperationOp op, OperandRange resultOperands, TypeRange resultTypes, UnitAttr inferredResultTypes) static
Definition at line 122 of file PDLInterp.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::Builder::getFunctionType(), mlir::Value::getType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseArgument(), mlir::AsmParser::parseArrow(), mlir::function_interface_impl::parseFunctionOp(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseSuccessor(), print(), mlir::function_interface_impl::printFunctionOp(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printSuccessor(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), mlir::OpAsmParser::Argument::type, and mlir::verify().
verifySwitchOp()
template<typename OpT > static LogicalResult verifySwitchOp (OpT op) static
Definition at line 32 of file PDLInterp.cpp.
References mlir::OperationName::hasInterface(), mlir::success(), and mlir::verify().
Referenced by getGetValueTypeOpValueType().