MLIR: lib/Tools/mlir-pdll-lsp-server/PDLLServer.cpp File Reference
PDLLServer.cpp File Reference
#include "PDLLServer.h"
#include "../lsp-server-support/Logging.h"
#include "../lsp-server-support/Protocol.h"
#include "CompilationDatabase.h"
#include "mlir/Tools/PDLL/AST/Context.h"
#include "mlir/Tools/PDLL/AST/Nodes.h"
#include "mlir/Tools/PDLL/AST/Types.h"
#include "mlir/Tools/PDLL/ODS/Constraint.h"
#include "mlir/Tools/PDLL/ODS/Context.h"
#include "mlir/Tools/PDLL/ODS/Dialect.h"
#include "mlir/Tools/PDLL/ODS/Operation.h"
#include "mlir/Tools/PDLL/Parser/CodeComplete.h"
#include "mlir/Tools/PDLL/Parser/Parser.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
Classes
struct mlir::lsp::PDLLServer::Impl
Functions
static lsp::URIForFile getURIFromLoc (llvm::SourceMgr &mgr, SMRange loc, const lsp::URIForFile &mainFileURI)
Returns a language server uri for the given source location.
static bool isMainFileLoc (llvm::SourceMgr &mgr, SMRange loc)
Returns true if the given location is in the main file of the source manager.
static lsp::Location getLocationFromLoc (llvm::SourceMgr &mgr, SMRange range, const lsp::URIForFile &uri)
Returns a language server location from the given source range.
static Optional< lsp::Diagnostic > getLspDiagnoticFromDiag (llvm::SourceMgr &sourceMgr, const ast::Diagnostic &diag, const lsp::URIForFile &uri)
Convert the given MLIR diagnostic to the LSP form.
Function Documentation
getLocationFromLoc()
static lsp::Location getLocationFromLoc (llvm::SourceMgr & mgr, SMRange range, const lsp::URIForFile & uri) static
Returns a language server location from the given source range.
Definition at line 56 of file PDLLServer.cpp.
References getURIFromLoc().
Referenced by getLspDiagnoticFromDiag().
getLspDiagnoticFromDiag()
static Optional<lsp::Diagnostic> getLspDiagnoticFromDiag (llvm::SourceMgr & sourceMgr, const ast::Diagnostic & diag, const lsp::URIForFile & uri) static
Convert the given MLIR diagnostic to the LSP form.
Definition at line 63 of file PDLLServer.cpp.
References mlir::lsp::Diagnostic::category, mlir::lsp::Class, mlir::lsp::Hover::contents, mlir::lsp::CompletionItem::detail, diag(), mlir::lsp::CompletionItem::documentation, mlir::pdll::ast::Type::dyn_cast(), mlir::detail::enumerate(), mlir::lsp::Logger::error(), mlir::lsp::Error, mlir::failed(), mlir::lsp::Field, mlir::lsp::URIForFile::file(), mlir::lsp::File, mlir::lsp::CompletionItem::filterText, mlir::lsp::Folder, mlir::lsp::URIForFile::fromFile(), mlir::lsp::Function, mlir::lsp::Position::getAsSMLoc(), mlir::pdll::ods::Operation::getAttributes(), mlir::pdll::ast::PatternDecl::getBenefit(), mlir::pdll::ast::PatternDecl::getBody(), mlir::pdll::ods::OperandOrResult::getConstraint(), mlir::pdll::ods::AttributeConstraint::getCppClass(), mlir::pdll::ods::TypeConstraint::getCppClass(), mlir::pdll::ast::DeclScope::getDecls(), mlir::pdll::ods::Operation::getDescription(), mlir::pdll::ods::Context::getDialects(), mlir::pdll::ast::TupleType::getElementNames(), mlir::pdll::ast::TupleType::getElementTypes(), mlir::pdll::ast::Name::getLoc(), mlir::pdll::ods::Operation::getLoc(), mlir::pdll::ast::Node::getLoc(), mlir::pdll::ast::Diagnostic::getLocation(), getLocationFromLoc(), mlir::pdll::ast::Diagnostic::getMessage(), mlir::pdll::ast::Name::getName(), mlir::pdll::ods::OperandOrResult::getName(), mlir::pdll::ods::Operation::getName(), mlir::pdll::ast::OperationType::getName(), mlir::pdll::ast::Decl::getName(), mlir::pdll::ast::OpConstraintDecl::getName(), mlir::pdll::ast::VariableDecl::getName(), mlir::pdll::ast::Diagnostic::getNotes(), mlir::pdll::ods::Dialect::getOperations(), mlir::pdll::ast::DeclScope::getParentScope(), mlir::pdll::ods::Operation::getResults(), mlir::pdll::ast::OpRewriteStmt::getRootOpExpr(), mlir::pdll::ast::PatternDecl::getRootRewriteStmt(), mlir::pdll::ast::Diagnostic::getSeverity(), mlir::pdll::ods::Constraint::getSummary(), mlir::pdll::ods::Operation::getSummary(), mlir::pdll::ast::Expr::getType(), mlir::pdll::ast::VariableDecl::getType(), mlir::pdll::ods::OperandOrResult::getVariableLengthKind(), mlir::pdll::ast::PatternDecl::hasBoundedRewriteRecursion(), mlir::lsp::Information, mlir::lsp::CompletionItem::insertText, mlir::lsp::CompletionItem::insertTextFormat, mlir::lsp::Interface, mlir::pdll::ast::Type::isa(), isMainFileLoc(), mlir::lsp::CompletionList::items, mlir::lsp::CompletionItem::kind, mlir::lsp::CompletionItem::label, mlir::pdll::ods::Context::lookupDialect(), mlir::pdll::ods::Context::lookupOperation(), mlir::lsp::Markdown, mlir::lsp::Diagnostic::message, mlir::pdll::ods::Optional, mlir::pdll::parsePDLAST(), mlir::lsp::PlainText, mlir::lsp::Location::range, mlir::lsp::Diagnostic::range, mlir::pdll::ast::Type::refineWith(), mlir::lsp::Diagnostic::relatedInformation, rewrite(), mlir::lsp::Diagnostic::severity, mlir::pdll::ods::Single, mlir::pdll::ast::TupleType::size(), mlir::lsp::Snippet, mlir::lsp::CompletionItem::sortText, mlir::lsp::Diagnostic::source, mlir::lsp::Location::uri, mlir::lsp::MarkupContent::value, mlir::pdll::ods::Variadic, mlir::pdll::ast::Node::walk(), and mlir::lsp::Warning.
getURIFromLoc()
static lsp::URIForFile getURIFromLoc (llvm::SourceMgr & mgr, SMRange loc, const lsp::URIForFile & mainFileURI) static
Returns a language server uri for the given source location.
mainFileURI corresponds to the uri for the main file of the source manager.
Definition at line 35 of file PDLLServer.cpp.
References mlir::lsp::Logger::error(), mlir::lsp::URIForFile::fromFile(), and mlir::toString().
Referenced by getLocationFromLoc().
isMainFileLoc()
static bool isMainFileLoc (llvm::SourceMgr & mgr, SMRange loc) static
Returns true if the given location is in the main file of the source manager.
Definition at line 51 of file PDLLServer.cpp.
Referenced by getLspDiagnoticFromDiag().