MLIR: lib/Analysis/Presburger/PWMAFunction.cpp File Reference
PWMAFunction.cpp File Reference
#include "mlir/Analysis/Presburger/PWMAFunction.h"
#include "mlir/Analysis/Presburger/Simplex.h"
Functions
static SmallVector< int64_t, 8 > subtract (ArrayRef< int64_t > vecA, ArrayRef< int64_t > vecB)
Function Documentation
subtract()
static SmallVector<int64_t, 8> subtract (ArrayRef< int64_t > vecA, ArrayRef< int64_t > vecB) static
Definition at line 18 of file PWMAFunction.cpp.
Referenced by createLinalgBodyCalculationForElementwiseOp(), getConvOutputDim(), and mlir::presburger::MultiAffineFunction::isEqualWhereDomainsOverlap().