MLIR: lib/Target/LLVMIR/Dialect/ROCDL/ROCDLToLLVMIRTranslation.cpp File Reference
ROCDLToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/ROCDL/ROCDLToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/LLVMIR/ROCDLConversions.inc"
Functions
static llvm::Value * createDeviceFunctionCall (llvm::IRBuilderBase &builder, StringRef fnName, int parameter)
Function Documentation
createDeviceFunctionCall()
static llvm::Value* createDeviceFunctionCall (llvm::IRBuilderBase & builder, StringRef fnName, int parameter) static
Definition at line 31 of file ROCDLToLLVMIRTranslation.cpp.
References mlir::Attribute::dyn_cast(), mlir::failure(), mlir::NamedAttribute::getName(), mlir::NamedAttribute::getValue(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupFunction(), mlir::success(), and value.