MLIR: include/mlir/ExecutionEngine/RunnerUtils.h File Reference
RunnerUtils.h File Reference
#include <assert.h>
#include <cmath>
#include <iostream>
#include "mlir/ExecutionEngine/CRunnerUtils.h"
Classes
struct impl::StaticSizeMult< Dims >
struct impl::StaticSizeMult< N, Dims... >
struct impl::VectorDataPrinter< T, M, Dims >
struct impl::MemRefDataPrinter< T >
struct impl::MemRefDataVerifier< T >
Verify the result of two computations are equivalent up to a small numerical error and return the number of errors.
Namespaces
impl
Macros
#define MLIR_RUNNERUTILS_EXPORT __attribute__((visibility("default")))
Functions
template<typename T , typename StreamType >
void printMemRefMetaData (StreamType &os, const DynamicMemRefType< T > &v)
template<typename StreamType , typename T , int N>
void printMemRefMetaData (StreamType &os, StridedMemRefType< T, N > &v)
template<typename StreamType , typename T >
void printUnrankedMemRefMetaData (StreamType &os, UnrankedMemRefType< T > &v)
template<typename T , int M, int... Dims>
std::ostream & impl::operator<< (std::ostream &os, const Vector< T, M, Dims... > &v)
static void impl::printSpace (std::ostream &os, int count)
template<typename T , int N>
void impl::printMemRefShape (StridedMemRefType< T, N > &m)
template<typename T >
void impl::printMemRefShape (UnrankedMemRefType< T > &m)
template<typename T >
void impl::printMemRef (const DynamicMemRefType< T > &m)
template<typename T , int N>
void impl::printMemRef (StridedMemRefType< T, N > &m)
template<typename T >
void impl::printMemRef (UnrankedMemRefType< T > &m)
template<typename T >
int64_t impl::verifyMemRef (const DynamicMemRefType< T > &actual, const DynamicMemRefType< T > &expected)
Verify the equivalence of two dynamic memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
template<typename T >
int64_t impl::verifyMemRef (UnrankedMemRefType< T > &actual, UnrankedMemRefType< T > &expected)
Verify the equivalence of two unranked memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI8 (UnrankedMemRefType< int8_t > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI32 (UnrankedMemRefType< int32_t > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI64 (UnrankedMemRefType< int64_t > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeF32 (UnrankedMemRefType< float > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeF64 (UnrankedMemRefType< double > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefI8 (UnrankedMemRefType< int8_t > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefI32 (UnrankedMemRefType< int32_t > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefF32 (UnrankedMemRefType< float > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefF64 (UnrankedMemRefType< double > *m)
MLIR_RUNNERUTILS_EXPORT void printMemrefI32 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void printMemrefI64 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void printMemrefF32 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void printMemrefF64 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref0dF32 (StridedMemRefType< float, 0 > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref1dF32 (StridedMemRefType< float, 1 > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref2dF32 (StridedMemRefType< float, 2 > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref3dF32 (StridedMemRefType< float, 3 > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref4dF32 (StridedMemRefType< float, 4 > *m)
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > *m)
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefI32 (UnrankedMemRefType< int32_t > *actual, UnrankedMemRefType< int32_t > *expected)
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefF32 (UnrankedMemRefType< float > *actual, UnrankedMemRefType< float > *expected)
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefF64 (UnrankedMemRefType< double > *actual, UnrankedMemRefType< double > *expected)
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefI32 (int64_t rank, void *actualPtr, void *expectedPtr)
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefF32 (int64_t rank, void *actualPtr, void *expectedPtr)
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefF64 (int64_t rank, void *actualPtr, void *expectedPtr)
Macro Definition Documentation
MLIR_RUNNERUTILS_EXPORT
#define MLIR_RUNNERUTILS_EXPORT __attribute__((visibility("default")))
Definition at line 31 of file RunnerUtils.h.
Referenced by impl::verifyMemRef().
Function Documentation
mlirCifacePrintMemref0dF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref0dF32 (StridedMemRefType< float, 0 > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemref1dF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref1dF32 (StridedMemRefType< float, 1 > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemref2dF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref2dF32 (StridedMemRefType< float, 2 > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemref3dF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref3dF32 (StridedMemRefType< float, 3 > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemref4dF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemref4dF32 (StridedMemRefType< float, 4 > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefF32 (UnrankedMemRefType< float > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefF64()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefF64 (UnrankedMemRefType< double > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefI32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefI32 (UnrankedMemRefType< int32_t > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefI8()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefI8 (UnrankedMemRefType< int8_t > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefShapeF32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeF32 (UnrankedMemRefType< float > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefShapeF64()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeF64 (UnrankedMemRefType< double > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefShapeI32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI32 (UnrankedMemRefType< int32_t > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefShapeI64()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI64 (UnrankedMemRefType< int64_t > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefShapeI8()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefShapeI8 (UnrankedMemRefType< int8_t > * m)
Referenced by impl::verifyMemRef().
mlirCifacePrintMemrefVector4x4xf32()
MLIR_RUNNERUTILS_EXPORT void mlirCifacePrintMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > * m)
Referenced by impl::verifyMemRef().
mlirCifaceVerifyMemRefF32()
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefF32 (UnrankedMemRefType< float > * actual, UnrankedMemRefType< float > * expected)
Referenced by impl::verifyMemRef().
mlirCifaceVerifyMemRefF64()
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefF64 (UnrankedMemRefType< double > * actual, UnrankedMemRefType< double > * expected)
Referenced by impl::verifyMemRef().
mlirCifaceVerifyMemRefI32()
MLIR_RUNNERUTILS_EXPORT int64_t mlirCifaceVerifyMemRefI32 (UnrankedMemRefType< int32_t > * actual, UnrankedMemRefType< int32_t > * expected)
Referenced by impl::verifyMemRef().
printMemrefF32()
MLIR_RUNNERUTILS_EXPORT void printMemrefF32 (int64_t rank, void * ptr)
Referenced by impl::verifyMemRef().
printMemrefF64()
MLIR_RUNNERUTILS_EXPORT void printMemrefF64 (int64_t rank, void * ptr)
Referenced by impl::verifyMemRef().
printMemrefI32()
MLIR_RUNNERUTILS_EXPORT void printMemrefI32 (int64_t rank, void * ptr)
Referenced by impl::verifyMemRef().
printMemrefI64()
MLIR_RUNNERUTILS_EXPORT void printMemrefI64 (int64_t rank, void * ptr)
Referenced by impl::verifyMemRef().
printMemRefMetaData() [1/2]
template<typename T , typename StreamType > void printMemRefMetaData (StreamType & os, const DynamicMemRefType< T > & v)
Definition at line 41 of file RunnerUtils.h.
References DynamicMemRefType< T >::data, DynamicMemRefType< T >::offset, print(), DynamicMemRefType< T >::rank, DynamicMemRefType< T >::sizes, and DynamicMemRefType< T >::strides.
Referenced by _mlir_ciface_print_memref_shape_f32(), _mlir_ciface_print_memref_shape_f64(), _mlir_ciface_print_memref_shape_i32(), _mlir_ciface_print_memref_shape_i64(), _mlir_ciface_print_memref_shape_i8(), impl::printMemRef(), printMemRefMetaData(), impl::printMemRefShape(), printUnrankedMemRefMetaData(), and impl::verifyMemRef().
printMemRefMetaData() [2/2]
template<typename StreamType , typename T , int N> void printMemRefMetaData (StreamType & os, StridedMemRefType< T, N > & v)
Definition at line 59 of file RunnerUtils.h.
References printMemRefMetaData().
printUnrankedMemRefMetaData()
template<typename StreamType , typename T > void printUnrankedMemRefMetaData (StreamType & os, UnrankedMemRefType< T > & v)
Definition at line 66 of file RunnerUtils.h.
References printMemRefMetaData().
verifyMemRefF32()
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefF32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 157 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF32().
Referenced by impl::verifyMemRef().
verifyMemRefF64()
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefF64 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 164 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF64().
Referenced by impl::verifyMemRef().
verifyMemRefI32()
MLIR_RUNNERUTILS_EXPORT int64_t verifyMemRefI32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 150 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefI32().
Referenced by impl::verifyMemRef().