MLIR: lib/Conversion/SCFToSPIRV/SCFToSPIRV.cpp File Reference
SCFToSPIRV.cpp File Reference
#include "mlir/Conversion/SCFToSPIRV/SCFToSPIRV.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Transforms/DialectConversion.h"
Classes
struct mlir::ScfToSPIRVContextImpl
Namespaces
mlir
Include the generated interface declarations.
Functions
template<typename ScfOp , typename OpTy >
static void replaceSCFOutputValue (ScfOp scfOp, OpTy newOp, ConversionPatternRewriter &rewriter, ScfToSPIRVContextImpl *scfToSPIRVContext, ArrayRef< Type > returnTypes)
Helper function to replaces SCF op outputs with SPIR-V variable loads.
static Region::iterator getBlockIt (Region &region, unsigned index)
Function Documentation
getBlockIt()
static Region::iterator getBlockIt (Region & region, unsigned index) static
Definition at line 153 of file SCFToSPIRV.cpp.
References mlir::ConversionPatternRewriter::applySignatureConversion(), mlir::Region::begin(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::Block::front(), mlir::Builder::getI1Type(), mlir::OpBuilder::getInsertionBlock(), mlir::Value::getLoc(), mlir::Operation::getLoc(), mlir::Block::getNumArguments(), mlir::ConversionPatternRewriter::getRemappedValue(), mlir::ConversionPatternRewriter::getRemappedValues(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::TypeConverter::SignatureConversion::remapInput(), replaceSCFOutputValue(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
replaceSCFOutputValue()
template<typename ScfOp , typename OpTy > static void replaceSCFOutputValue (ScfOp scfOp, OpTy newOp, ConversionPatternRewriter & rewriter, ScfToSPIRVContextImpl * scfToSPIRVContext, ArrayRef< Type > returnTypes) static
Helper function to replaces SCF op outputs with SPIR-V variable loads.
We create VariableOp to handle the results value of the control flow region. spv.mlir.loop/spv.mlir.selection currently don't yield value. Right after the loop we load the value from the allocation and use it as the SCF op result.
Definition at line 127 of file SCFToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::spirv::PointerType::get(), mlir::ScfToSPIRVContextImpl::outputVars, mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by getBlockIt().