MLIR: lib/Dialect/Linalg/Transforms/SparseTensorRewriting.cpp File Reference
SparseTensorRewriting.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Support/LLVM.h"
Functions
static bool isSparseTensor (OpOperand *op)
static bool isEmptyInit (OpOperand *op)
static bool isSampling (GenericOp op)
static bool isMulChain (Value val, Value x)
static bool isSumOfMul (GenericOp op)
Function Documentation
isEmptyInit()
static bool isEmptyInit (OpOperand * op) static
Definition at line 47 of file SparseTensorRewriting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::m_AnyZeroFloat(), mlir::m_Zero(), and mlir::matchPattern().
Referenced by isSumOfMul().
isMulChain()
static bool isMulChain (Value val, Value x) static
Definition at line 69 of file SparseTensorRewriting.cpp.
References mlir::Value::dyn_cast(), and mlir::Value::getDefiningOp().
Referenced by isSumOfMul().
isSampling()
static bool isSampling (GenericOp op) static
Definition at line 54 of file SparseTensorRewriting.cpp.
Referenced by isSumOfMul().
isSparseTensor()
static bool isSparseTensor (OpOperand * op) static
Definition at line 35 of file SparseTensorRewriting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::Value::getType().
Referenced by isSumOfMul().
isSumOfMul()
static bool isSumOfMul (GenericOp op) static
Definition at line 81 of file SparseTensorRewriting.cpp.
References mlir::Block::addArgument(), mlir::Block::back(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::failure(), mlir::Block::front(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Value::getDefiningOp(), mlir::BlockArgument::getLoc(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Block::getTerminator(), mlir::Value::getType(), isEmptyInit(), isMulChain(), isSampling(), isSparseTensor(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().