MLIR: lib/Target/SPIRV/TranslateRegistration.cpp File Reference
TranslateRegistration.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/SPIRV/Deserialization.h"
#include "mlir/Target/SPIRV/Serialization.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Namespaces
mlir
Include the generated interface declarations.
Functions
static OwningOpRef< ModuleOp > deserializeModule (const llvm::MemoryBuffer *input, MLIRContext *context)
void mlir::registerFromSPIRVTranslation ()
static LogicalResult serializeModule (ModuleOp module, raw_ostream &output)
void mlir::registerToSPIRVTranslation ()
static LogicalResult roundTripModule (ModuleOp srcModule, bool emitDebugInfo, raw_ostream &output)
void mlir::registerTestRoundtripSPIRV ()
void mlir::registerTestRoundtripDebugSPIRV ()
Function Documentation
deserializeModule()
static OwningOpRef<ModuleOp> deserializeModule (const llvm::MemoryBuffer * input, MLIRContext * context) static
Definition at line 39 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::emitError(), mlir::MLIRContext::loadDialect(), and mlir::OwningOpRef< OpTy >::release().
Referenced by mlir::registerFromSPIRVTranslation().
roundTripModule()
static LogicalResult roundTripModule (ModuleOp srcModule, bool emitDebugInfo, raw_ostream & output) static
Definition at line 124 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::spirv::SerializationOptions::emitDebugInfo, mlir::failed(), mlir::failure(), mlir::MLIRContext::getDialectRegistry(), mlir::MLIRContext::loadAllAvailableDialects(), options, mlir::OwningOpRef< OpTy >::release(), mlir::spirv::serialize(), mlir::success(), and mlir::verify().
Referenced by mlir::registerTestRoundtripDebugSPIRV(), and mlir::registerTestRoundtripSPIRV().
serializeModule()
static LogicalResult serializeModule (ModuleOp module, raw_ostream & output) static
Definition at line 83 of file TranslateRegistration.cpp.
References mlir::failed(), mlir::failure(), mlir::spirv::serialize(), and mlir::success().
Referenced by mlir::registerToSPIRVTranslation().