MLIR: lib/Dialect/SPIRV/IR/SPIRVOps.cpp File Reference
SPIRVOps.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/ParserUtils.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpTraits.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/bit.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAvailability.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpAvailabilityImpl.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define GET_OP_CLASSES
Functions
static ParseResult parseOneResultSameOperandTypeOp (OpAsmParser &parser, OperationState &result)
static void printOneResultOp (Operation *op, OpAsmPrinter &p)
static bool isNestedInFunctionOpInterface (Operation *op)
Returns true if the given op is a function-like op or nested in a function-like op without a module-like op in the middle.
static bool isDirectInModuleLikeOp (Operation *op)
Returns true if the given op is an module-like op that maintains a symbol table.
static LogicalResult extractValueFromConstOp (Operation *op, int32_t &value)
template<typename Ty >
static ArrayAttr getStrArrayAttrForEnumList (Builder &builder, ArrayRef< Ty > enumValues, function_ref< StringRef(Ty)> stringifyFn)
template<typename EnumClass >
static ParseResult parseEnumStrAttr (EnumClass &value, OpAsmParser &parser, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next string attribute in parser as an enumerant of the given EnumClass.
template<typename EnumClass >
static ParseResult parseEnumStrAttr (EnumClass &value, OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next string attribute in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
template<typename EnumClass >
static ParseResult parseEnumKeywordAttr (EnumClass &value, OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next keyword in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
template<typename EnumClass >
static ParseResult parseControlAttribute (OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses Function, Selection and Loop control attributes.
static ParseResult parseMemoryAccessAttributes (OpAsmParser &parser, OperationState &state)
Parses optional memory access attributes attached to a memory access operand/pointer.
static ParseResult parseSourceMemoryAccessAttributes (OpAsmParser &parser, OperationState &state)
template<typename MemoryOpTy >
static void printMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue=None, Optional< uint32_t > alignmentAttrValue=None)
template<typename MemoryOpTy >
static void printSourceMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue=None, Optional< uint32_t > alignmentAttrValue=None)
static ParseResult parseImageOperands (OpAsmParser &parser, spirv::ImageOperandsAttr &attr)
static void printImageOperands (OpAsmPrinter &printer, Operation *imageOp, spirv::ImageOperandsAttr attr)
template<typename Op >
static LogicalResult verifyImageOperands (Op imageOp, spirv::ImageOperandsAttr attr, Operation::operand_range operands)
static LogicalResult verifyCastOp (Operation *op, bool requireSameBitWidth=true, bool skipBitWidthCheck=false)
template<typename MemoryOpTy >
static LogicalResult verifyMemoryAccessAttribute (MemoryOpTy memoryOp)
template<typename MemoryOpTy >
static LogicalResult verifySourceMemoryAccessAttribute (MemoryOpTy memoryOp)
static LogicalResult verifyMemorySemantics (Operation *op, spirv::MemorySemantics memorySemantics)
template<typename LoadStoreOpTy >
static LogicalResult verifyLoadStorePtrAndValTypes (LoadStoreOpTy op, Value ptr, Value val)
template<typename BlockReadWriteOpTy >
static LogicalResult verifyBlockReadWritePtrAndValTypes (BlockReadWriteOpTy op, Value ptr, Value val)
static ParseResult parseVariableDecorations (OpAsmParser &parser, OperationState &state)
static void printVariableDecorations (Operation *op, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs)
static unsigned getBitWidth (Type type)
static Type getElementType (Type type, ArrayRef< int32_t > indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn)
Walks the given type hierarchy with the given indices, potentially down to component granularity, to select an element type.
static Type getElementType (Type type, Attribute indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn)
static Type getElementType (Type type, Attribute indices, Location loc)
static Type getElementType (Type type, Attribute indices, OpAsmParser &parser, SMLoc loc)
static bool isMergeBlock (Block &block)
Returns true if the given block only contains one spv.mlir.merge op.
static ParseResult parseAtomicUpdateOp (OpAsmParser &parser, OperationState &state, bool hasValue)
static void printAtomicUpdateOp (Operation *op, OpAsmPrinter &printer)
template<typename T >
static StringRef stringifyTypeName ()
template<>
StringRef stringifyTypeName< IntegerType > ()
template<>
StringRef stringifyTypeName< FloatType > ()
template<typename ExpectedElementType >
static LogicalResult verifyAtomicUpdateOp (Operation *op)
static ParseResult parseGroupNonUniformArithmeticOp (OpAsmParser &parser, OperationState &state)
static void printGroupNonUniformArithmeticOp (Operation *groupOp, OpAsmPrinter &printer)
static LogicalResult verifyGroupNonUniformArithmeticOp (Operation *groupOp)
static Type getUnaryOpResultType (Type operandType)
Result of a logical op must be a scalar or vector of boolean type.
static LogicalResult verifyShiftOp (Operation *op)
static void buildLogicalBinaryOp (OpBuilder &builder, OperationState &state, Value lhs, Value rhs)
static void buildLogicalUnaryOp (OpBuilder &builder, OperationState &state, Value value)
static Type getElementPtrType (Type type, ValueRange indices, Location baseLoc)
template<typename Op >
static void printAccessChain (Op op, ValueRange indices, OpAsmPrinter &printer)
template<typename Op >
static LogicalResult verifyAccessChain (Op accessChainOp, ValueRange indices)
template<typename T >
static void printAtomicCompareExchangeImpl (T atomOp, OpAsmPrinter &printer)
static ParseResult parseAtomicCompareExchangeImpl (OpAsmParser &parser, OperationState &state)
template<typename T >
static LogicalResult verifyAtomicCompareExchangeImpl (T atomOp)
static LogicalResult verifyConstantType (spirv::ConstantOp op, Attribute value, Type opType)
static bool hasOneBranchOpTo (Block &srcBlock, Block &dstBlock)
Returns true if the given srcBlock contains only one spv.Branch to the given dstBlock.
static LogicalResult verifyPointerAndCoopMatrixType (Operation *op, Type pointer, Type coopMatrix)
static LogicalResult verifyCoopMatrixMulAdd (spirv::CooperativeMatrixMulAddNVOp op)
static ParseResult parsePtrAccessChainOpImpl (StringRef opName, OpAsmParser &parser, OperationState &state)
template<typename Op >
static auto concatElemAndIndices (Op op)
Variables
static constexpr const char kMemoryAccessAttrName [] = "memory_access"
static constexpr const char kSourceMemoryAccessAttrName []
static constexpr const char kAlignmentAttrName [] = "alignment"
static constexpr const char kSourceAlignmentAttrName [] = "source_alignment"
static constexpr const char kBranchWeightAttrName [] = "branch_weights"
static constexpr const char kCallee [] = "callee"
static constexpr const char kClusterSize [] = "cluster_size"
static constexpr const char kControl [] = "control"
static constexpr const char kDefaultValueAttrName [] = "default_value"
static constexpr const char kExecutionScopeAttrName [] = "execution_scope"
static constexpr const char kEqualSemanticsAttrName [] = "equal_semantics"
static constexpr const char kFnNameAttrName [] = "fn"
static constexpr const char kGroupOperationAttrName [] = "group_operation"
static constexpr const char kIndicesAttrName [] = "indices"
static constexpr const char kInitializerAttrName [] = "initializer"
static constexpr const char kInterfaceAttrName [] = "interface"
static constexpr const char kMemoryScopeAttrName [] = "memory_scope"
static constexpr const char kSemanticsAttrName [] = "semantics"
static constexpr const char kSpecIdAttrName [] = "spec_id"
static constexpr const char kTypeAttrName [] = "type"
static constexpr const char kUnequalSemanticsAttrName [] = "unequal_semantics"
static constexpr const char kValueAttrName [] = "value"
static constexpr const char kValuesAttrName [] = "values"
static constexpr const char kCompositeSpecConstituentsName [] = "constituents"
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4443 of file SPIRVOps.cpp.
Function Documentation
buildLogicalBinaryOp()
static void buildLogicalBinaryOp (OpBuilder & builder, OperationState & state, Value lhs, Value rhs) static
Definition at line 946 of file SPIRVOps.cpp.
buildLogicalUnaryOp()
static void buildLogicalUnaryOp (OpBuilder & builder, OperationState & state, Value value) static
Definition at line 958 of file SPIRVOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::Builder::getI1Type(), and mlir::Value::getType().
concatElemAndIndices()
template<typename Op > static auto concatElemAndIndices (Op op) static
Definition at line 4365 of file SPIRVOps.cpp.
References copy(), getElementPtrType(), getElementType(), mlir::Value::getType(), mlir::OperationState::location, parsePtrAccessChainOpImpl(), print(), printAccessChain(), mlir::success(), mlir::verify(), and verifyAccessChain().
extractValueFromConstOp()
static LogicalResult extractValueFromConstOp (Operation * op, int32_t & value) static
Definition at line 133 of file SPIRVOps.cpp.
References mlir::failure(), and mlir::success().
Referenced by getElementPtrType(), and verifyGroupNonUniformArithmeticOp().
getBitWidth()
static unsigned getBitWidth (Type type) static
Definition at line 665 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), and vectorType().
Referenced by verifyAtomicCompareExchangeImpl().
getElementPtrType()
static Type getElementPtrType (Type type, ValueRange indices, Location baseLoc) static
Definition at line 972 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::emitError(), extractValueFromConstOp(), mlir::failed(), mlir::failure(), mlir::spirv::PointerType::get(), mlir::AsmParser::getCurrentLocation(), mlir::Operation::getName(), mlir::Value::getType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseTypeList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
Referenced by concatElemAndIndices(), mlir::MemRefDescriptor::getIndexType(), isAsyncWithOneDependency(), isDefinedByCallTo(), parsePtrAccessChainOpImpl(), and verifyAccessChain().
getElementType() [1/4]
static Type getElementType (Type type, ArrayRef< int32_t > indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn) static
Walks the given type hierarchy with the given indices, potentially down to component granularity, to select an element type.
Returns null type and emits errors with the given loc on failure.
Definition at line 687 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast().
Referenced by castBoolToIntN(), mlir::pdl::PDLType::classof(), mlir::DenseFPElementsAttr::classof(), mlir::DenseIntElementsAttr::classof(), mlir::DenseElementsAttr::complex_float_value_begin(), mlir::DenseElementsAttr::complex_float_value_end(), mlir::DenseElementsAttr::complex_value_begin(), mlir::DenseElementsAttr::complex_value_end(), concatElemAndIndices(), mlir::convertMMAToLLVMType(), convertOmpAtomicRead(), convertStructType(), createLinalgBodyCalculationForElementwiseOp(), mlir::LLVM::detail::extractNDVectorTypeInfo(), mlir::DenseElementsAttr::float_value_begin(), mlir::DenseElementsAttr::float_value_end(), foldExtractStridedOpFromInsertChain(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), genLoad(), mlir::spirv::ImageType::get(), mlir::spirv::ArrayType::getCapabilities(), mlir::spirv::RuntimeArrayType::getCapabilities(), mlir::spirv::CooperativeMatrixNVType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), mlir::spirv::MatrixType::getElementType(), getElementType(), mlir::spirv::ArrayType::getExtensions(), mlir::spirv::RuntimeArrayType::getExtensions(), mlir::spirv::CooperativeMatrixNVType::getExtensions(), mlir::DenseElementsAttr::getFloatValues(), mlir::FloatType::getFPMantissaWidth(), getLocalInvocationDimSize(), getPushConstantVariable(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::spirv::ArrayType::getSizeInBytes(), getSrcVectorElementType(), mlir::getStridesAndOffset(), mlir::DenseElementsAttr::getValues(), handleMultidimensionalVectors(), hasSameBitwidthScalarType(), inferDynamicDimsForConv(), isAsyncWithOneDependency(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isComplexOfIntType(), isMatchingWidth(), mlir::DenseElementsAttr::isValidBool(), mlir::DenseElementsAttr::isValidComplex(), mlir::TensorType::isValidElementType(), mlir::DenseElementsAttr::isValidIntOrFloat(), mlir::OperandElementTypeIterator::mapElement(), mlir::ResultElementTypeIterator::mapElement(), mlir::GPUFuncOpLowering::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), mlirComplexTypeGetElementType(), mlirPDLRangeTypeGetElementType(), mlirShapedTypeGetElementType(), mlir::spirv::StructType::MemberDecorationInfo::operator<(), parseInferType(), printAtomicReductionRegion(), printGEPIndices(), printOperation(), mlir::replaceAllMemRefUsesWith(), mlir::MemRefType::Builder::setMemorySpace(), mlir::linalg::splitReduction(), mlir::DenseElementsAttr::value_begin(), mlir::DenseElementsAttr::value_end(), vectorType(), verifyAtomicCompareExchangeImpl(), verifyCastOp(), verifyConvOp(), and writeAPIntsToBuffer().
getElementType() [2/4]
static Type getElementType (Type type, Attribute indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn) static
Definition at line 713 of file SPIRVOps.cpp.
References mlir::Attribute::dyn_cast(), and getElementType().
getElementType() [3/4]
static Type getElementType (Type type, Attribute indices, Location loc) static
Definition at line 738 of file SPIRVOps.cpp.
References mlir::emitError(), and getElementType().
getElementType() [4/4]
static Type getElementType (Type type, Attribute indices, OpAsmParser & parser, SMLoc loc) static
Definition at line 745 of file SPIRVOps.cpp.
References mlir::AsmParser::emitError(), and getElementType().
getStrArrayAttrForEnumList()
template<typename Ty > static ArrayAttr getStrArrayAttrForEnumList (Builder & builder, ArrayRef< Ty > enumValues, function_ref< StringRef(Ty)> stringifyFn) static
Definition at line 154 of file SPIRVOps.cpp.
References mlir::Builder::getStrArrayAttr().
getUnaryOpResultType()
static Type getUnaryOpResultType (Type operandType) static
Result of a logical op must be a scalar or vector of boolean type.
Definition at line 928 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getContext(), and mlir::Builder::getIntegerType().
hasOneBranchOpTo()
static bool hasOneBranchOpTo (Block & srcBlock, Block & dstBlock) inline static
Returns true if the given srcBlock contains only one spv.Branch to the given dstBlock.
Definition at line 2926 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::NamedAttrList::append(), mlir::OpBuilder::atBlockEnd(), mlir::OperationState::attributes, mlir::Block::back(), bindingName(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), descriptorSetName(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::Operation::emitError(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::spirv::PointerType::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), getNumElements(), mlir::Block::getNumSuccessors(), mlir::Builder::getStringAttr(), mlir::Block::getSuccessor(), mlir::SymbolTable::getSymbolAttrName(), mlir::Block::getTerminator(), isMergeBlock(), kDefaultValueAttrName, kSpecIdAttrName, mlir::SymbolTable::lookup(), mlir::SymbolTable::lookupNearestSymbolFrom(), max(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::parseEnumKeywordAttr(), parseEnumStrAttr(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeywordType(), mlir::AsmParser::parseLParen(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalSymbolName(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), mlir::AsmParser::parseType(), parseVariableDecorations(), print(), printMemoryAccessAttribute(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), printVariableDecorations(), mlir::Region::push_back(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), value, mlir::verify(), verifyLoadStorePtrAndValTypes(), verifyMemoryAccessAttribute(), and verifyMemorySemantics().
isDirectInModuleLikeOp()
static bool isDirectInModuleLikeOp (Operation * op) static
Returns true if the given op is an module-like op that maintains a symbol table.
Definition at line 129 of file SPIRVOps.cpp.
References mlir::Operation::hasTrait().
isMergeBlock()
static bool isMergeBlock (Block & block) inline static
Returns true if the given block only contains one spv.mlir.merge op.
Definition at line 754 of file SPIRVOps.cpp.
References mlir::Block::begin(), mlir::Block::empty(), mlir::Block::end(), and mlir::Block::front().
Referenced by hasOneBranchOpTo().
isNestedInFunctionOpInterface()
static bool isNestedInFunctionOpInterface (Operation * op) static
Returns true if the given op is a function-like op or nested in a function-like op without a module-like op in the middle.
Definition at line 117 of file SPIRVOps.cpp.
References mlir::Operation::getParentOp(), and mlir::Operation::hasTrait().
parseAtomicCompareExchangeImpl()
static ParseResult parseAtomicCompareExchangeImpl (OpAsmParser & parser, OperationState & state) static
Definition at line 1142 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), kEqualSemanticsAttrName, kMemoryScopeAttrName, kUnequalSemanticsAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
Referenced by verifyAtomicCompareExchangeImpl().
parseAtomicUpdateOp()
static ParseResult parseAtomicUpdateOp (OpAsmParser & parser, OperationState & state, bool hasValue) static
Definition at line 765 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), kMemoryScopeAttrName, kSemanticsAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
Referenced by verifyAtomicCompareExchangeImpl().
parseControlAttribute()
template<typename EnumClass > static ParseResult parseControlAttribute (OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses Function, Selection and Loop control attributes.
If no control is specified, "None" is used as a default.
Definition at line 229 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), kControl, mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
parseEnumKeywordAttr()
template<typename EnumClass > static ParseResult parseEnumKeywordAttr (EnumClass & value, OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next keyword in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
Definition at line 214 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), mlir::parseEnumKeywordAttr(), and mlir::success().
parseEnumStrAttr() [1/2]
template<typename EnumClass > static ParseResult parseEnumStrAttr (EnumClass & value, OpAsmParser & parser, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next string attribute in parser as an enumerant of the given EnumClass.
Definition at line 171 of file SPIRVOps.cpp.
References mlir::Attribute::cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getNoneType(), mlir::Attribute::isa(), mlir::AsmParser::parseAttribute(), and mlir::success().
Referenced by hasOneBranchOpTo(), parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), parseEnumStrAttr(), parseGroupNonUniformArithmeticOp(), parseImageOperands(), parseMemoryAccessAttributes(), parseSourceMemoryAccessAttributes(), verifyAtomicCompareExchangeImpl(), verifyConstantType(), and verifyCoopMatrixMulAdd().
parseEnumStrAttr() [2/2]
template<typename EnumClass > static ParseResult parseEnumStrAttr (EnumClass & value, OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next string attribute in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
Definition at line 199 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), parseEnumStrAttr(), and mlir::success().
parseGroupNonUniformArithmeticOp()
static ParseResult parseGroupNonUniformArithmeticOp (OpAsmParser & parser, OperationState & state) static
Definition at line 845 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kClusterSize, kExecutionScopeAttrName, kGroupOperationAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::OperationState::types.
Referenced by verifyConstantType().
parseImageOperands()
static ParseResult parseImageOperands (OpAsmParser & parser, spirv::ImageOperandsAttr & attr) static
Definition at line 367 of file SPIRVOps.cpp.
References mlir::failure(), mlir::AsmParser::getContext(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
parseMemoryAccessAttributes()
static ParseResult parseMemoryAccessAttributes (OpAsmParser & parser, OperationState & state) static
Parses optional memory access attributes attached to a memory access operand/pointer.
Specifically, parses the following syntax: ([ memory-access ])? where: memory-access ::= "None" | "Volatile" | "Aligned", integer-literal | "NonTemporal"
Definition at line 250 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kAlignmentAttrName, kMemoryAccessAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
Referenced by hasOneBranchOpTo(), verifyConstantType(), verifyCoopMatrixMulAdd(), and verifyPointerAndCoopMatrixType().
parseOneResultSameOperandTypeOp()
static ParseResult parseOneResultSameOperandTypeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 67 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
Referenced by verifyConstantType().
parsePtrAccessChainOpImpl()
static ParseResult parsePtrAccessChainOpImpl (StringRef opName, OpAsmParser & parser, OperationState & state) static
Definition at line 4322 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), getElementPtrType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseTypeList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
Referenced by concatElemAndIndices().
parseSourceMemoryAccessAttributes()
static ParseResult parseSourceMemoryAccessAttributes (OpAsmParser & parser, OperationState & state) static
Definition at line 281 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kSourceAlignmentAttrName, kSourceMemoryAccessAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
Referenced by verifyCoopMatrixMulAdd().
parseVariableDecorations()
static ParseResult parseVariableDecorations (OpAsmParser & parser, OperationState & state) static
Definition at line 600 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, bindingName(), descriptorSetName(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by hasOneBranchOpTo(), and verifyConstantType().
printAccessChain()
template<typename Op > static void printAccessChain (Op op, ValueRange indices, OpAsmPrinter & printer) static
Definition at line 1077 of file SPIRVOps.cpp.
References mlir::ValueRange::getTypes(), and print().
Referenced by concatElemAndIndices().
printAtomicCompareExchangeImpl()
template<typename T > static void printAtomicCompareExchangeImpl (T atomOp, OpAsmPrinter & printer) static
Definition at line 1135 of file SPIRVOps.cpp.
Referenced by verifyAtomicCompareExchangeImpl().
printAtomicUpdateOp()
static void printAtomicUpdateOp (Operation * op, OpAsmPrinter & printer) static
Definition at line 794 of file SPIRVOps.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Value::getType(), kMemoryScopeAttrName, kSemanticsAttrName, and stringifyTypeName().
Referenced by verifyAtomicCompareExchangeImpl().
printGroupNonUniformArithmeticOp()
static void printGroupNonUniformArithmeticOp (Operation * groupOp, OpAsmPrinter & printer) static
Definition at line 881 of file SPIRVOps.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), kClusterSize, kExecutionScopeAttrName, and kGroupOperationAttrName.
Referenced by verifyConstantType().
printImageOperands()
static void printImageOperands (OpAsmPrinter & printer, Operation * imageOp, spirv::ImageOperandsAttr attr) static
Definition at line 382 of file SPIRVOps.cpp.
printMemoryAccessAttribute()
template<typename MemoryOpTy > static void printMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue = None, Optional< uint32_t > alignmentAttrValue = None) static
Definition at line 309 of file SPIRVOps.cpp.
References kAlignmentAttrName, and kMemoryAccessAttrName.
Referenced by hasOneBranchOpTo(), verifyConstantType(), and verifyCoopMatrixMulAdd().
printOneResultOp()
static void printOneResultOp (Operation * op, OpAsmPrinter & p) static
Definition at line 96 of file SPIRVOps.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by verifyConstantType().
printSourceMemoryAccessAttribute()
template<typename MemoryOpTy > static void printSourceMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue = None, Optional< uint32_t > alignmentAttrValue = None) static
Definition at line 339 of file SPIRVOps.cpp.
References kSourceAlignmentAttrName, and kSourceMemoryAccessAttrName.
Referenced by verifyCoopMatrixMulAdd().
printVariableDecorations()
static void printVariableDecorations (Operation * op, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs) static
Definition at line 637 of file SPIRVOps.cpp.
References bindingName(), descriptorSetName(), mlir::Operation::getAttrOfType(), mlir::Operation::getAttrs(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by hasOneBranchOpTo(), and verifyConstantType().
stringifyTypeName()
template<typename T > static StringRef stringifyTypeName () static
Referenced by printAtomicUpdateOp().
stringifyTypeName< FloatType >()
template<> StringRef stringifyTypeName< FloatType > ()
Definition at line 816 of file SPIRVOps.cpp.
stringifyTypeName< IntegerType >()
template<> StringRef stringifyTypeName< IntegerType > ()
Definition at line 811 of file SPIRVOps.cpp.
verifyAccessChain()
template<typename Op > static LogicalResult verifyAccessChain (Op accessChainOp, ValueRange indices) static
Definition at line 1087 of file SPIRVOps.cpp.
References mlir::OpState::emitOpError(), mlir::failure(), getElementPtrType(), mlir::OpState::getLoc(), mlir::SymbolTable::lookupNearestSymbolFrom(), mlir::success(), and mlir::verify().
Referenced by concatElemAndIndices().
verifyAtomicCompareExchangeImpl()
template<typename T > static LogicalResult verifyAtomicCompareExchangeImpl (T atomOp) static
Definition at line 1174 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), mlir::AsmParser::addTypesToList(), mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::emitError(), mlir::failure(), mlir::Builder::getArrayAttr(), getBitWidth(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), getElementType(), mlir::Builder::getI1Type(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Type::isa(), kBranchWeightAttrName, kIndicesAttrName, kMemoryScopeAttrName, kSemanticsAttrName, kValueAttrName, mlir::OperationState::location, mlir::OperationState::operands, parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::AsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), mlir::OpAsmParser::parseSuccessorAndUseList(), print(), printAtomicCompareExchangeImpl(), printAtomicUpdateOp(), mlir::OpAsmPrinter::printSuccessorAndUseList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), mlir::OperationState::types, value, and mlir::verify().
verifyAtomicUpdateOp()
template<typename ExpectedElementType > static LogicalResult verifyAtomicUpdateOp (Operation * op) static
Definition at line 822 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::spirv::PointerType::getPointeeType(), mlir::Value::getType(), kSemanticsAttrName, mlir::success(), and verifyMemorySemantics().
verifyBlockReadWritePtrAndValTypes()
template<typename BlockReadWriteOpTy > static LogicalResult verifyBlockReadWritePtrAndValTypes (BlockReadWriteOpTy op, Value ptr, Value val) static
Definition at line 588 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::success().
Referenced by verifyConstantType().
verifyCastOp()
static LogicalResult verifyCastOp (Operation * op, bool requireSameBitWidth = true, bool skipBitWidthCheck = false) static
Definition at line 418 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::Operation::emitOpError(), getElementType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::success(), and vectorType().
Referenced by verifyConstantType().
verifyConstantType()
static LogicalResult verifyConstantType (spirv::ConstantOp op, Attribute value, Type opType) static
Definition at line 1821 of file SPIRVOps.cpp.
References mlir::function_interface_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::WalkResult::advance(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::spirv::PointerType::get(), mlir::DenseFPElementsAttr::get(), mlir::Builder::getArrayAttr(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::spirv::getDefaultTargetEnv(), mlir::Type::getDialect(), mlir::spirv::ArrayType::getElementType(), mlir::Builder::getFloatAttr(), mlir::function_interface_impl::getFunctionType(), mlir::Builder::getFunctionType(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::spirv::ArrayType::getNumElements(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::function_interface_impl::getTypeAttrName(), mlir::OptionalParseResult::hasValue(), mlir::Attribute::isa(), mlir::Type::isa(), kCallee, kFnNameAttrName, kInitializerAttrName, kInterfaceAttrName, kTypeAttrName, kValuesAttrName, mlir::SymbolTable::lookupNearestSymbolFrom(), mlir::spirv::lookupTargetEnvOrDefault(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCommaSeparatedList(), parseEnumStrAttr(), mlir::function_interface_impl::parseFunctionSignature(), parseGroupNonUniformArithmeticOp(), mlir::AsmParser::parseLParen(), parseMemoryAccessAttributes(), parseOneResultSameOperandTypeOp(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseOptionalRegion(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), mlir::AsmParser::parseType(), parseVariableDecorations(), print(), mlir::function_interface_impl::printFunctionAttributes(), mlir::function_interface_impl::printFunctionSignature(), printGroupNonUniformArithmeticOp(), printMemoryAccessAttribute(), printOneResultOp(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), printVariableDecorations(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), value, vectorType(), mlir::verify(), verifyBlockReadWritePtrAndValTypes(), verifyCastOp(), verifyGroupNonUniformArithmeticOp(), verifyLoadStorePtrAndValTypes(), verifyMemoryAccessAttribute(), verifyMemorySemantics(), and mlir::detail::walk().
verifyCoopMatrixMulAdd()
static LogicalResult verifyCoopMatrixMulAdd (spirv::CooperativeMatrixMulAddNVOp op) static
Definition at line 3767 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Region::back(), mlir::Block::begin(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::spirv::PointerType::get(), mlir::Builder::getArrayAttr(), mlir::spirv::ImageType::getArrayedInfo(), mlir::AsmParser::getBuilder(), mlir::spirv::CooperativeMatrixNVType::getColumns(), mlir::AsmParser::getContext(), mlir::spirv::ImageType::getDim(), mlir::spirv::StructType::getElementType(), mlir::spirv::CooperativeMatrixNVType::getElementType(), mlir::spirv::MatrixType::getElementType(), mlir::spirv::SampledImageType::getImageType(), mlir::Operation::getLoc(), mlir::spirv::MatrixType::getNumColumns(), mlir::spirv::CompositeType::getNumElements(), mlir::spirv::StructType::getNumElements(), getNumElements(), mlir::spirv::MatrixType::getNumRows(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::Operation::getResult(), mlir::spirv::CooperativeMatrixNVType::getRows(), mlir::spirv::ImageType::getSamplerUseInfo(), mlir::spirv::ImageType::getSamplingInfo(), mlir::spirv::CooperativeMatrixNVType::getScope(), mlir::SymbolTable::getSymbolAttrName(), mlir::Value::getType(), mlir::Operation::hasTrait(), mlir::Type::isa(), kCompositeSpecConstituentsName, kTypeAttrName, mlir::OperationState::location, mlir::SymbolTable::lookupNearestSymbolFrom(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::OpAsmParser::parseGenericOperation(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseRParen(), parseSourceMemoryAccessAttributes(), mlir::AsmParser::parseSymbolName(), mlir::AsmParser::parseType(), print(), mlir::OpAsmPrinter::printGenericOp(), printMemoryAccessAttribute(), mlir::OpAsmPrinter::printOptionalAttrDict(), printSourceMemoryAccessAttribute(), mlir::AsmPrinter::printSymbolName(), mlir::Region::push_back(), mlir::OpAsmParser::resolveOperand(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::success(), vectorType(), mlir::verify(), verifyImageOperands(), verifyMemoryAccessAttribute(), verifyShiftOp(), and verifySourceMemoryAccessAttribute().
verifyGroupNonUniformArithmeticOp()
static LogicalResult verifyGroupNonUniformArithmeticOp (Operation * groupOp) static
Definition at line 898 of file SPIRVOps.cpp.
References mlir::Operation::emitOpError(), extractValueFromConstOp(), mlir::failed(), mlir::Operation::getAttrOfType(), mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), kExecutionScopeAttrName, kGroupOperationAttrName, and mlir::success().
Referenced by verifyConstantType().
verifyImageOperands()
template<typename Op > static LogicalResult verifyImageOperands (Op imageOp, spirv::ImageOperandsAttr attr, Operation::operand_range operands) static
Definition at line 391 of file SPIRVOps.cpp.
References mlir::OpState::emitError(), and mlir::success().
Referenced by verifyCoopMatrixMulAdd().
verifyLoadStorePtrAndValTypes()
template<typename LoadStoreOpTy > static LogicalResult verifyLoadStorePtrAndValTypes (LoadStoreOpTy op, Value ptr, Value val) static
Definition at line 573 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::success().
Referenced by hasOneBranchOpTo(), and verifyConstantType().
verifyMemoryAccessAttribute()
template<typename MemoryOpTy > static LogicalResult verifyMemoryAccessAttribute (MemoryOpTy memoryOp) static
Definition at line 465 of file SPIRVOps.cpp.
References kAlignmentAttrName, kMemoryAccessAttrName, and mlir::success().
Referenced by hasOneBranchOpTo(), verifyConstantType(), and verifyCoopMatrixMulAdd().
verifyMemorySemantics()
static LogicalResult verifyMemorySemantics (Operation * op, spirv::MemorySemantics memorySemantics) static
Definition at line 549 of file SPIRVOps.cpp.
References mlir::Operation::emitError(), and mlir::success().
Referenced by hasOneBranchOpTo(), verifyAtomicUpdateOp(), and verifyConstantType().
verifyPointerAndCoopMatrixType()
static LogicalResult verifyPointerAndCoopMatrixType (Operation * op, Type pointer, Type coopMatrix) static
Definition at line 3698 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Operation::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::Type::isa(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), print(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::verify().
verifyShiftOp()
static LogicalResult verifyShiftOp (Operation * op) static
Definition at line 936 of file SPIRVOps.cpp.
References mlir::Operation::emitError(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::success().
Referenced by verifyCoopMatrixMulAdd().
verifySourceMemoryAccessAttribute()
template<typename MemoryOpTy > static LogicalResult verifySourceMemoryAccessAttribute (MemoryOpTy memoryOp) static
Definition at line 509 of file SPIRVOps.cpp.
References kSourceAlignmentAttrName, kSourceMemoryAccessAttrName, and mlir::success().
Referenced by verifyCoopMatrixMulAdd().
Variable Documentation
kAlignmentAttrName
constexpr const char kAlignmentAttrName[] = "alignment" static
Definition at line 40 of file SPIRVOps.cpp.
Referenced by parseMemoryAccessAttributes(), printMemoryAccessAttribute(), and verifyMemoryAccessAttribute().
kBranchWeightAttrName
constexpr const char kBranchWeightAttrName[] = "branch_weights" static
Definition at line 42 of file SPIRVOps.cpp.
Referenced by verifyAtomicCompareExchangeImpl().
kCallee
constexpr const char kCallee[] = "callee" static
Definition at line 43 of file SPIRVOps.cpp.
Referenced by verifyConstantType().
kClusterSize
constexpr const char kClusterSize[] = "cluster_size" static
Definition at line 44 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), and printGroupNonUniformArithmeticOp().
kCompositeSpecConstituentsName
constexpr const char kCompositeSpecConstituentsName[] = "constituents" static
Definition at line 61 of file SPIRVOps.cpp.
Referenced by verifyCoopMatrixMulAdd().
kControl
constexpr const char kControl[] = "control" static
Definition at line 45 of file SPIRVOps.cpp.
Referenced by parseControlAttribute().
kDefaultValueAttrName
constexpr const char kDefaultValueAttrName[] = "default_value" static
Definition at line 46 of file SPIRVOps.cpp.
Referenced by hasOneBranchOpTo().
kEqualSemanticsAttrName
constexpr const char kEqualSemanticsAttrName[] = "equal_semantics" static
Definition at line 48 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl().
kExecutionScopeAttrName
constexpr const char kExecutionScopeAttrName[] = "execution_scope" static
Definition at line 47 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), printGroupNonUniformArithmeticOp(), and verifyGroupNonUniformArithmeticOp().
kFnNameAttrName
constexpr const char kFnNameAttrName[] = "fn" static
Definition at line 49 of file SPIRVOps.cpp.
Referenced by verifyConstantType().
kGroupOperationAttrName
constexpr const char kGroupOperationAttrName[] = "group_operation" static
Definition at line 50 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), printGroupNonUniformArithmeticOp(), and verifyGroupNonUniformArithmeticOp().
kIndicesAttrName
constexpr const char kIndicesAttrName[] = "indices" static
Definition at line 51 of file SPIRVOps.cpp.
Referenced by verifyAtomicCompareExchangeImpl().
kInitializerAttrName
constexpr const char kInitializerAttrName[] = "initializer" static
Definition at line 52 of file SPIRVOps.cpp.
Referenced by verifyConstantType().
kInterfaceAttrName
constexpr const char kInterfaceAttrName[] = "interface" static
Definition at line 53 of file SPIRVOps.cpp.
Referenced by verifyConstantType().
kMemoryAccessAttrName
constexpr const char kMemoryAccessAttrName[] = "memory_access" static
Definition at line 37 of file SPIRVOps.cpp.
Referenced by parseMemoryAccessAttributes(), printMemoryAccessAttribute(), and verifyMemoryAccessAttribute().
kMemoryScopeAttrName
constexpr const char kMemoryScopeAttrName[] = "memory_scope" static
Definition at line 54 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl(), parseAtomicUpdateOp(), printAtomicUpdateOp(), and verifyAtomicCompareExchangeImpl().
kSemanticsAttrName
constexpr const char kSemanticsAttrName[] = "semantics" static
Definition at line 55 of file SPIRVOps.cpp.
Referenced by parseAtomicUpdateOp(), printAtomicUpdateOp(), verifyAtomicCompareExchangeImpl(), and verifyAtomicUpdateOp().
kSourceAlignmentAttrName
constexpr const char kSourceAlignmentAttrName[] = "source_alignment" static
Definition at line 41 of file SPIRVOps.cpp.
Referenced by parseSourceMemoryAccessAttributes(), printSourceMemoryAccessAttribute(), and verifySourceMemoryAccessAttribute().
kSourceMemoryAccessAttrName
constexpr const char kSourceMemoryAccessAttrName[] static
Initial value:
=
    "source_memory_access"
Definition at line 38 of file SPIRVOps.cpp.
Referenced by parseSourceMemoryAccessAttributes(), printSourceMemoryAccessAttribute(), and verifySourceMemoryAccessAttribute().
kSpecIdAttrName
constexpr const char kSpecIdAttrName[] = "spec_id" static
Definition at line 56 of file SPIRVOps.cpp.
Referenced by hasOneBranchOpTo().
kTypeAttrName
constexpr const char kTypeAttrName[] = "type" static
Definition at line 57 of file SPIRVOps.cpp.
Referenced by verifyConstantType(), and verifyCoopMatrixMulAdd().
kUnequalSemanticsAttrName
constexpr const char kUnequalSemanticsAttrName[] = "unequal_semantics" static
Definition at line 58 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl().
kValueAttrName
constexpr const char kValueAttrName[] = "value" static
Definition at line 59 of file SPIRVOps.cpp.
Referenced by verifyAtomicCompareExchangeImpl().
kValuesAttrName
constexpr const char kValuesAttrName[] = "values" static
Definition at line 60 of file SPIRVOps.cpp.
Referenced by verifyConstantType().