MLIR: lib/Dialect/SPIRV/IR/SPIRVDialect.cpp File Reference
SPIRVDialect.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/ParserUtils.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpsDialect.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.cpp.inc"
Macros
#define GET_OP_LIST
Functions
static bool containsReturn (Region &region)
Returns true if the given region contains spv.Return or spv.ReturnValue ops.
template<typename ValTy >
static Optional< ValTy > parseAndVerify (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< Type > parseAndVerify< Type > (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< unsigned > parseAndVerify< unsigned > (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifyType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifyMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifySampledImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static LogicalResult parseOptionalArrayStride (const SPIRVDialect &dialect, DialectAsmParser &parser, unsigned &stride)
Parses an optional , stride = N assembly segment.
static Type parseArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseCooperativeMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parsePointerType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseRuntimeArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<typename IntTy >
static Optional< IntTy > parseAndVerifyInteger (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseSampledImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static ParseResult parseStructMemberDecorations (SPIRVDialect const &dialect, DialectAsmParser &parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::OffsetInfo > &offsetInfo, SmallVectorImpl< StructType::MemberDecorationInfo > &memberDecorationInfo)
static Type parseStructType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static void print (ArrayType type, DialectAsmPrinter &os)
static void print (RuntimeArrayType type, DialectAsmPrinter &os)
static void print (PointerType type, DialectAsmPrinter &os)
static void print (ImageType type, DialectAsmPrinter &os)
static void print (SampledImageType type, DialectAsmPrinter &os)
static void print (StructType type, DialectAsmPrinter &os)
static void print (CooperativeMatrixNVType type, DialectAsmPrinter &os)
static void print (MatrixType type, DialectAsmPrinter &os)
static ParseResult parseKeywordList (DialectAsmParser &parser, function_ref< LogicalResult(SMLoc, StringRef)> processKeyword)
Parses a comma-separated list of keywords, invokes processKeyword on each of the parsed keyword, and returns failure if any error occurs.
static Attribute parseInterfaceVarABIAttr (DialectAsmParser &parser)
Parses a spirv::InterfaceVarABIAttr.
static Attribute parseVerCapExtAttr (DialectAsmParser &parser)
static Attribute parseTargetEnvAttr (DialectAsmParser &parser)
Parses a spirv::TargetEnvAttr.
static void print (spirv::VerCapExtAttr triple, DialectAsmPrinter &printer)
static void print (spirv::TargetEnvAttr targetEnv, DialectAsmPrinter &printer)
static void print (spirv::InterfaceVarABIAttr interfaceVarABIAttr, DialectAsmPrinter &printer)
static LogicalResult verifyRegionAttribute (Location loc, Type valueType, NamedAttribute attribute)
Verifies the given SPIR-V attribute attached to a value of the given valueType is valid.
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
containsReturn()
static bool containsReturn (Region & region) inline static
Returns true if the given region contains spv.Return or spv.ReturnValue ops.
Definition at line 43 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create(), mlir::DialectInlinerInterface::DialectInlinerInterface(), mlir::Operation::erase(), mlir::Operation::getLoc(), mlir::Region::getParentOp(), mlir::Operation::getRegion(), mlir::Block::getTerminator(), isLegalToInline(), parseAndVerify(), parseAndVerify< Type >(), and parseAndVerify< unsigned >().
parseAndVerify()
template<typename ValTy > static Optional< ValTy > parseAndVerify (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 442 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseKeyword().
Referenced by containsReturn().
parseAndVerify< Type >()
template<> Optional< Type > parseAndVerify< Type > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 457 of file SPIRVDialect.cpp.
References parseAndVerifyType().
Referenced by containsReturn().
parseAndVerify< unsigned >()
template<> Optional< unsigned > parseAndVerify< unsigned > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 476 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::AsmParser::parseComma(), and value.
Referenced by containsReturn(), and parseOptionalArrayStride().
parseAndVerifyInteger()
template<typename IntTy > static Optional<IntTy> parseAndVerifyInteger (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 467 of file SPIRVDialect.cpp.
References max(), and mlir::AsmParser::parseInteger().
parseAndVerifyMatrixType()
static Type parseAndVerifyMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 199 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseType().
Referenced by parseMatrixType().
parseAndVerifySampledImageType()
static Type parseAndVerifySampledImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 235 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::Type::isa(), and mlir::AsmParser::parseType().
Referenced by parseSampledImageType().
parseAndVerifyType()
static Type parseAndVerifyType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 155 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::Type::getDialect(), mlir::Type::isBF16(), mlir::spirv::ScalarType::isValid(), and mlir::AsmParser::parseType().
Referenced by parseAndVerify< Type >(), parseArrayType(), parseCooperativeMatrixType(), parsePointerType(), and parseRuntimeArrayType().
parseArrayType()
static Type parseArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 285 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::ArrayType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseDimensionList(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and parseOptionalArrayStride().
Referenced by parseStructType().
parseCooperativeMatrixType()
static Type parseCooperativeMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 323 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseDimensionList(), mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseImageType()
static Type parseImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 531 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::get(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and value.
Referenced by parseStructType().
parseInterfaceVarABIAttr()
static Attribute parseInterfaceVarABIAttr (DialectAsmParser & parser) static
Parses a spirv::InterfaceVarABIAttr.
Definition at line 902 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::InterfaceVarABIAttr::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseRParen(), and mlir::succeeded().
Referenced by parseTargetEnvAttr().
parseKeywordList()
static ParseResult parseKeywordList (DialectAsmParser & parser, function_ref< LogicalResult(SMLoc, StringRef)> processKeyword) static
Parses a comma-separated list of keywords, invokes processKeyword on each of the parsed keyword, and returns failure if any error occurs.
Definition at line 876 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLSquare(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalRSquare(), mlir::AsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseVerCapExtAttr().
parseMatrixType()
static Type parseMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 406 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::MatrixType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyMatrixType(), mlir::AsmParser::parseDimensionList(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseOptionalArrayStride()
static LogicalResult parseOptionalArrayStride (const SPIRVDialect & dialect, DialectAsmParser & parser, unsigned & stride) static
Parses an optional , stride = N assembly segment.
If no parsing failure occurs, writes N to stride if existing and writes 0 to stride if missing.
Definition at line 255 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), parseAndVerify< unsigned >(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalComma(), and mlir::success().
Referenced by parseArrayType(), and parseRuntimeArrayType().
parsePointerType()
static Type parsePointerType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 360 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::PointerType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseRuntimeArrayType()
static Type parseRuntimeArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 387 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::spirv::RuntimeArrayType::get(), parseAndVerifyType(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and parseOptionalArrayStride().
Referenced by parseStructType().
parseSampledImageType()
static Type parseSampledImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 549 of file SPIRVDialect.cpp.
References mlir::spirv::SampledImageType::get(), parseAndVerifySampledImageType(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseStructMemberDecorations()
static ParseResult parseStructMemberDecorations (SPIRVDialect const & dialect, DialectAsmParser & parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::OffsetInfo > & offsetInfo, SmallVectorImpl< StructType::MemberDecorationInfo > & memberDecorationInfo) static
Definition at line 564 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OptionalParseResult::hasValue(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalEqual(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseOptionalRSquare(), mlir::AsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseStructType().
parseStructType()
static Type parseStructType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 628 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::StructType::get(), mlir::spirv::StructType::getEmpty(), mlir::spirv::StructType::getIdentified(), mlir::AsmParser::getNameLoc(), parseArrayType(), mlir::AsmParser::parseComma(), parseCooperativeMatrixType(), mlir::AsmParser::parseGreater(), parseImageType(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseLParen(), parseMatrixType(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalGreater(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseOptionalRParen(), parsePointerType(), mlir::AsmParser::parseRParen(), parseRuntimeArrayType(), parseSampledImageType(), parseStructMemberDecorations(), mlir::LLVM::detail::parseType(), mlir::AsmParser::parseType(), and mlir::succeeded().
parseTargetEnvAttr()
static Attribute parseTargetEnvAttr (DialectAsmParser & parser) static
Parses a spirv::TargetEnvAttr.
Definition at line 1045 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::TargetEnvAttr::get(), mlir::AsmParser::getCurrentLocation(), mlir::spirv::InterfaceVarABIAttr::getKindName(), mlir::spirv::VerCapExtAttr::getKindName(), mlir::spirv::TargetEnvAttr::getKindName(), mlir::AsmParser::getNameLoc(), mlir::spirv::TargetEnvAttr::kUnknownDeviceID, mlir::parseAttribute(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseInteger(), parseInterfaceVarABIAttr(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseOptionalColon(), mlir::AsmParser::parseOptionalKeyword(), parseVerCapExtAttr(), and mlir::succeeded().
parseVerCapExtAttr()
static Attribute parseVerCapExtAttr (DialectAsmParser & parser) static
Definition at line 970 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failure(), mlir::spirv::VerCapExtAttr::get(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), parseKeywordList(), mlir::AsmParser::parseLess(), and mlir::success().
Referenced by parseTargetEnvAttr().
print() [1/11]
static void print (ArrayType type, DialectAsmPrinter & os) static
Definition at line 771 of file SPIRVDialect.cpp.
References mlir::spirv::ArrayType::getArrayStride(), mlir::spirv::ArrayType::getElementType(), and mlir::spirv::ArrayType::getNumElements().
Referenced by acceptBitWidth(), mlir::Diagnostic::append(), applyTilingToAll(), mlir::Op< AffineDmaWaitOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >::attachInterface(), buildLLVMFunctionType(), mlir::pdl::PDLType::classof(), computeMemRefRankReductionMask(), concatElemAndIndices(), mlir::createLoopFusionPass(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Attribute::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::presburger::PresburgerRelation::dump(), mlir::AffineMap::dump(), mlir::Type::dump(), mlir::OperationName::dump(), mlir::Value::dump(), mlir::Operation::dump(), mlir::Block::dump(), eachHasOnlyOneOfTypes(), mlir::CallGraph::end(), foldTransferInBoundsAttribute(), mlir::TimingIdentifier::get(), mlir::python::PyOperationBase::getAsm(), mlir::tblgen::Operator::getDialect(), mlir::pdll::ods::Context::getDialects(), getGenericEffectsImpl(), mlir::OperationName::getIdentifier(), mlir::pdll::ast::Type::getImpl(), getInsertExtractValueElementType(), getLoadStoreElementType(), mlir::pdll::ast::Node::getLoc(), getOption(), mlir::scf::getParallelForInductionVarOwner(), mlir::Block::getSublistAccess(), mlir::Value::getUsers(), hasaUniqueDim(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::DynamicAttr::isa(), mlir::DynamicType::isa(), isComputeOperation(), isIntegerPtxType(), isZeroAttribute(), lookupSymbolInModule(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator*(), mlir::operator<<(), mlir::detail::PassOptions::Option< bool >::operator=(), mlir::IntegerSet::operator==(), parseGlobalMemrefOpTypeAndInitialValue(), llvm::cl::parser< mlir::OpPassManager >::parser(), impl::MemRefDataPrinter< T >::print(), mlir::Value::print(), mlir::Operation::print(), mlir::Block::print(), print(), printAccessChain(), mlir::AsmPrinter::Impl::printAttribute(), printAttributions(), printBound(), printCreateOperationOpResults(), impl::MemRefDataPrinter< T >::printFirst(), printInitializationList(), mlir::AsmPrinter::Impl::printIntegerSet(), impl::MemRefDataPrinter< T >::printLast(), printMemRefMetaData(), printMinMaxBound(), printNVVMIntrinsicOp(), mlir::detail::pass_options::printOptionValue(), mlir::raw_indented_ostream::printReindented(), printSizeAssignment(), printTransferAttrs(), printWsLoopControl(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), mlir::DynamicOpDefinition::setPrintFn(), shouldPrintElementsAttrWithHex(), verifyAllocLikeOp(), verifyAtomicCompareExchangeImpl(), verifyAttributions(), verifyConstantType(), verifyCoopMatrixMulAdd(), verifyDimAndSymbolIdentifiers(), verifyMemoryOpIndexing(), verifyMemoryOpMetadata(), verifyPointerAndCoopMatrixType(), mlir::OpState::verifyRegions(), verifySymbolAttrUse(), verifyVectorMemoryOp(), and mlir::DebugCounter::~DebugCounter().
print() [2/11]
static void print (RuntimeArrayType type, DialectAsmPrinter & os) static
Definition at line 778 of file SPIRVDialect.cpp.
References mlir::spirv::RuntimeArrayType::getArrayStride(), and mlir::spirv::RuntimeArrayType::getElementType().
print() [3/11]
static void print (PointerType type, DialectAsmPrinter & os) static
Definition at line 785 of file SPIRVDialect.cpp.
References mlir::spirv::PointerType::getPointeeType(), and mlir::spirv::PointerType::getStorageClass().
print() [4/11]
static void print (ImageType type, DialectAsmPrinter & os) static
Definition at line 790 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::getArrayedInfo(), mlir::spirv::ImageType::getDepthInfo(), mlir::spirv::ImageType::getDim(), mlir::spirv::ImageType::getElementType(), mlir::spirv::ImageType::getImageFormat(), mlir::spirv::ImageType::getSamplerUseInfo(), and mlir::spirv::ImageType::getSamplingInfo().
print() [5/11]
static void print (SampledImageType type, DialectAsmPrinter & os) static
Definition at line 799 of file SPIRVDialect.cpp.
References mlir::spirv::SampledImageType::getImageType().
print() [6/11]
static void print (StructType type, DialectAsmPrinter & os) static
Definition at line 803 of file SPIRVDialect.cpp.
References mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getIdentifier(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::StructType::getMemberOffset(), mlir::spirv::StructType::getNumElements(), mlir::spirv::StructType::hasOffset(), and mlir::spirv::StructType::isIdentified().
print() [7/11]
static void print (CooperativeMatrixNVType type, DialectAsmPrinter & os) static
Definition at line 851 of file SPIRVDialect.cpp.
References mlir::spirv::CooperativeMatrixNVType::getColumns(), mlir::spirv::CooperativeMatrixNVType::getElementType(), mlir::spirv::CooperativeMatrixNVType::getRows(), and mlir::spirv::CooperativeMatrixNVType::getScope().
print() [8/11]
static void print (MatrixType type, DialectAsmPrinter & os) static
Definition at line 857 of file SPIRVDialect.cpp.
References mlir::spirv::MatrixType::getColumnType(), mlir::spirv::MatrixType::getNumColumns(), print(), and mlir::LLVM::detail::printType().
print() [9/11]
static void print (spirv::VerCapExtAttr triple, DialectAsmPrinter & printer) static
Definition at line 1141 of file SPIRVDialect.cpp.
References mlir::spirv::VerCapExtAttr::getCapabilities(), mlir::spirv::VerCapExtAttr::getExtensionsAttr(), mlir::spirv::VerCapExtAttr::getKindName(), mlir::AsmPrinter::getStream(), and mlir::spirv::VerCapExtAttr::getVersion().
print() [10/11]
static void print (spirv::TargetEnvAttr targetEnv, DialectAsmPrinter & printer) static
Definition at line 1155 of file SPIRVDialect.cpp.
References mlir::spirv::TargetEnvAttr::getDeviceID(), mlir::spirv::TargetEnvAttr::getDeviceType(), mlir::spirv::TargetEnvAttr::getKindName(), mlir::spirv::TargetEnvAttr::getResourceLimits(), mlir::spirv::TargetEnvAttr::getTripleAttr(), mlir::spirv::TargetEnvAttr::getVendorID(), mlir::spirv::TargetEnvAttr::kUnknownDeviceID, and print().
print() [11/11]
static void print (spirv::InterfaceVarABIAttr interfaceVarABIAttr, DialectAsmPrinter & printer) static
Definition at line 1172 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Operation::emitError(), mlir::spirv::InterfaceVarABIAttr::getBinding(), mlir::spirv::InterfaceVarABIAttr::getDescriptorSet(), mlir::spirv::getEntryPointABIAttrName(), mlir::spirv::InterfaceVarABIAttr::getKindName(), mlir::NamedAttribute::getName(), mlir::spirv::InterfaceVarABIAttr::getStorageClass(), mlir::spirv::getTargetEnvAttrName(), mlir::NamedAttribute::getValue(), mlir::Attribute::isa(), materializeConstant(), print(), mlir::success(), and value.
verifyRegionAttribute()
static LogicalResult verifyRegionAttribute (Location loc, Type valueType, NamedAttribute attribute) static
Verifies the given SPIR-V attribute attached to a value of the given valueType is valid.
Definition at line 1238 of file SPIRVDialect.cpp.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::Operation::emitError(), mlir::Region::getArgument(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::Operation::getLoc(), mlir::NamedAttribute::getName(), mlir::Operation::getRegion(), mlir::Value::getType(), mlir::NamedAttribute::getValue(), mlir::Type::isIntOrIndexOrFloat(), and mlir::success().