MLIR: lib/Dialect/Linalg/Transforms/SplitReduction.cpp File Reference
SplitReduction.cpp File Reference
#include <utility>
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/PatternMatch.h"
Functions
static Optional< Attribute > getIdentity (Operation *op)
Return the identity numeric value associated to the give op.
Function Documentation
getIdentity()
static Optional<Attribute> getIdentity (Operation * op) static
Return the identity numeric value associated to the give op.
Definition at line 28 of file SplitReduction.cpp.
References mlir::Operation::getContext(), mlir::Operation::getResult(), mlir::Value::getType(), max(), and min().
Referenced by mlir::linalg::splitReduction().