MLIR: mlir::bufferization::func_ext::FuncOpInterface Struct Reference
mlir::bufferization::func_ext::FuncOpInterface Struct Reference
Public Member Functions
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, BufferizationState &state) const
Rewrite function bbArgs and return values into buffer form (using the canonical memref layout for now).
bool isWritable (Operation *op, Value value, const AnalysisState &state) const
Return true if the given function argument is writable.
bool isAllocationHoistingBarrier (Operation *op) const
Detailed Description
Definition at line 387 of file FuncBufferizableOpInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::bufferization::func_ext::FuncOpInterface::bufferize (Operation * op, RewriterBase & rewriter, BufferizationState & state) const inline
Rewrite function bbArgs and return values into buffer form (using the canonical memref layout for now).
This function bufferizes the function signature and the ReturnOp. When the entire function body has been bufferized, function return types can be switched to more concise memref types as part of foldMemRefCasts.
When a tensor function argument is known to be equivalent to a tensor result, it is dropped from the return values.
All function bbArgs are writable unless they are explicitly marked as read-only. Callers must insert copies when needed.
Note: Returning a memref is possible, but corresponding CallOp bufferizations fail unless allowReturnAllocs.
Definition at line 403 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::bufferization::createMemCpy(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::Block::front(), mlir::bufferization::BufferizationState::getAnalysisState(), mlir::Block::getArguments(), mlir::bufferization::func_ext::getAssumedUniqueReturnOp(), mlir::bufferization::BufferizationState::getBuffer(), mlir::bufferization::func_ext::getBufferizedFunctionArgType(), mlir::Operation::getContext(), mlir::bufferization::func_ext::getEquivalentFuncArgIdx(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::getMemRefType(), mlir::bufferization::BufferizationState::getOptions(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::Type::isa(), options, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
isAllocationHoistingBarrier()
bool mlir::bufferization::func_ext::FuncOpInterface::isAllocationHoistingBarrier (Operation * op) const inline
Definition at line 534 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::registerBufferizableOpInterfaceExternalModels().
isWritable()
bool mlir::bufferization::func_ext::FuncOpInterface::isWritable (Operation * op, Value value, const AnalysisState & state) const inline
Return true if the given function argument is writable.
Definition at line 518 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::Value::dyn_cast().
The documentation for this struct was generated from the following file:
lib/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.cpp