MLIR: CanonicalizeSingleResultAffineMinMaxOp< T > Struct Template Reference
CanonicalizeSingleResultAffineMinMaxOp< T > Struct Template Reference
Public Member Functions
LogicalResult matchAndRewrite (T affineOp, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< T >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< T >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (T op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (T op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
template<typename T>
struct CanonicalizeSingleResultAffineMinMaxOp< T >
Definition at line 2842 of file AffineOps.cpp.
Member Function Documentation
matchAndRewrite()
template<typename T> LogicalResult CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite (T affineOp, PatternRewriter & rewriter) const inline override virtual
Reimplemented from mlir::detail::OpOrInterfaceRewritePatternBase< T >.
Definition at line 2845 of file AffineOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::AffineValueMap::difference(), mlir::AffineExpr::dyn_cast(), mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), foldMemRefCast(), foldMinMaxOp(), mlir::Region::front(), mlir::AffineMap::get(), mlir::getAffineScope(), mlir::Builder::getArrayAttr(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getBuilder(), mlir::Builder::getConstantAffineMap(), mlir::Builder::getContext(), mlir::Builder::getI32TensorAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::bufferization::getMemRefType(), mlir::AsmParser::getNameLoc(), mlir::AffineMap::getNumDims(), getNumElements(), mlir::AffineMap::getNumInputs(), mlir::AffineValueMap::getNumResults(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getResult(), mlir::AffineMap::getResults(), isValidAffineIndexOperand(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), print(), mlir::OpAsmPrinter::printAffineMapOfSSAIds(), printAffineMinMaxOp(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), mlir::verify(), verifyAffineMinMaxOp(), and verifyDimAndSymbolIdentifiers().
The documentation for this struct was generated from the following file:
lib/Dialect/Affine/IR/AffineOps.cpp