MLIR: mlir::LowerVectorToLLVMOptions Struct Reference
mlir::LowerVectorToLLVMOptions Struct Reference
Options to control Vector to LLVM lowering.
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
Public Member Functions
LowerVectorToLLVMOptions ()
LowerVectorToLLVMOptions & enableReassociateFPReductions (bool b=true)
LowerVectorToLLVMOptions & enableIndexOptimizations (bool b=true)
LowerVectorToLLVMOptions & enableArmNeon (bool b=true)
LowerVectorToLLVMOptions & enableArmSVE (bool b=true)
LowerVectorToLLVMOptions & enableAMX (bool b=true)
LowerVectorToLLVMOptions & enableX86Vector (bool b=true)
Public Attributes
bool reassociateFPReductions {false}
bool force32BitVectorIndices {true}
bool armNeon {false}
bool armSVE {false}
bool amx {false}
bool x86Vector {false}
Detailed Description
Options to control Vector to LLVM lowering.
This should kept in sync with VectorToLLVM options defined for the ConvertVectorToLLVM pass in include/mlir/Conversion/Passes.td
Definition at line 23 of file ConvertVectorToLLVM.h.
Constructor & Destructor Documentation
LowerVectorToLLVMOptions()
mlir::LowerVectorToLLVMOptions::LowerVectorToLLVMOptions () inline
Definition at line 24 of file ConvertVectorToLLVM.h.
Member Function Documentation
enableAMX()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableAMX (bool b = true) inline
Definition at line 42 of file ConvertVectorToLLVM.h.
References amx.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
enableArmNeon()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableArmNeon (bool b = true) inline
Definition at line 34 of file ConvertVectorToLLVM.h.
References armNeon.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
enableArmSVE()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableArmSVE (bool b = true) inline
Definition at line 38 of file ConvertVectorToLLVM.h.
References armSVE.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
enableIndexOptimizations()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableIndexOptimizations (bool b = true) inline
Definition at line 30 of file ConvertVectorToLLVM.h.
References force32BitVectorIndices.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
enableReassociateFPReductions()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableReassociateFPReductions (bool b = true) inline
Definition at line 26 of file ConvertVectorToLLVM.h.
References reassociateFPReductions.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
enableX86Vector()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::enableX86Vector (bool b = true) inline
Definition at line 46 of file ConvertVectorToLLVM.h.
References x86Vector.
Referenced by mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions().
Member Data Documentation
amx
bool mlir::LowerVectorToLLVMOptions::amx {false}
Definition at line 55 of file ConvertVectorToLLVM.h.
Referenced by enableAMX().
armNeon
bool mlir::LowerVectorToLLVMOptions::armNeon {false}
Definition at line 53 of file ConvertVectorToLLVM.h.
Referenced by enableArmNeon().
armSVE
bool mlir::LowerVectorToLLVMOptions::armSVE {false}
Definition at line 54 of file ConvertVectorToLLVM.h.
Referenced by enableArmSVE().
force32BitVectorIndices
bool mlir::LowerVectorToLLVMOptions::force32BitVectorIndices {true}
Definition at line 52 of file ConvertVectorToLLVM.h.
Referenced by enableIndexOptimizations().
reassociateFPReductions
bool mlir::LowerVectorToLLVMOptions::reassociateFPReductions {false}
Definition at line 51 of file ConvertVectorToLLVM.h.
Referenced by enableReassociateFPReductions().
x86Vector
bool mlir::LowerVectorToLLVMOptions::x86Vector {false}
Definition at line 56 of file ConvertVectorToLLVM.h.
Referenced by enableX86Vector().
The documentation for this struct was generated from the following file:
include/mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h