MLIR: mlir::bufferization::BufferizationState Struct Reference
mlir::bufferization::BufferizationState Struct Reference
BufferizationState provides helper functions for performing bufferization rewrites and handling memref buffers.
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
Public Types
enum ForceInPlacability { FORCE_INPLACE, FORCE_OUT_OF_PLACE }
Public Member Functions
BufferizationState (const AnalysisState &analysisState)
FailureOr< Value > createAlloc (OpBuilder &b, Location loc, Value shapedValue, Optional< bool > dealloc=None)
Creates a memref allocation for the given shaped value.
FailureOr< Value > getBuffer (RewriterBase &rewriter, OpOperand &opOperand, Optional< ForceInPlacability > overrideInPlace=None, Optional< Operation *> customCopyInsertionPoint=None)
Return the buffer (memref) for a given OpOperand (tensor).
BaseMemRefType getBufferType (OpOperand &opOperand) const
Return the buffer type for a given OpOperand (tensor) after bufferization.
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
const AnalysisState & getAnalysisState () const
Protected Member Functions
BufferizationState (const BufferizationState &)=delete
Detailed Description
BufferizationState provides helper functions for performing bufferization rewrites and handling memref buffers.
Definition at line 420 of file BufferizableOpInterface.h.
Member Enumeration Documentation
ForceInPlacability
enum mlir::bufferization::BufferizationState::ForceInPlacability
Enumerator
FORCE_INPLACE
FORCE_OUT_OF_PLACE
Definition at line 421 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
BufferizationState() [1/2]
mlir::bufferization::BufferizationState::BufferizationState (const AnalysisState & analysisState) inline
Definition at line 423 of file BufferizableOpInterface.h.
References createAlloc(), and mlir::bufferization::None.
BufferizationState() [2/2]
mlir::bufferization::BufferizationState::BufferizationState (const BufferizationState &) protected delete
Member Function Documentation
createAlloc()
FailureOr< Value > BufferizationState::createAlloc (OpBuilder & b, Location loc, Value shapedValue, Optional< bool > dealloc = None)
Creates a memref allocation for the given shaped value.
Create an allocation after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg).
dealloc indicates whether the buffer should be deallocated or not. When dealloc is false, this would create a memory leak, unless the buffer is deallocated through some other mechanism.
dealloc is optional. By default, this function will figure out by itself if it is safe to deallocate the buffer. In essence, when returning the buffer from a block, it is not safe to deallocate the buffer. This information is queried via AnalysisState::isTensorYielded.
Note: shapedValue is typically a tensor value. However, if it is a memref value, dealloc is no longer optional and must be specified.
Definition at line 497 of file BufferizableOpInterface.cpp.
References createBufferAllocation(), mlir::bufferization::BufferizationOptions::createDeallocs, getAllocationTypeAndShape(), mlir::bufferization::AnalysisState::getOptions(), mlir::Value::getType(), and mlir::Type::isa().
getAnalysisState()
const AnalysisState& mlir::bufferization::BufferizationState::getAnalysisState () const inline
Definition at line 462 of file BufferizableOpInterface.h.
References mlir::bufferization::lookupBuffer(), options, and mlir::bufferization::replaceOpWithBufferizedValues().
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), and mlir::bufferization::func_ext::FuncOpInterface::bufferize().
getBuffer()
FailureOr< Value > BufferizationState::getBuffer (RewriterBase & rewriter, OpOperand & opOperand, Optional< ForceInPlacability > overrideInPlace = None, Optional< Operation *> customCopyInsertionPoint = None)
Return the buffer (memref) for a given OpOperand (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization was decided.
Whether a buffer is in-place or out-of-place is queried from the analysis state. Some analyses may always conservatively opt for out-of-place bufferization. Inplacability decisions can be overridden with the optional overrideInPlace parameter.
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization was decided.
Definition at line 274 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), createAlloc(), mlir::bufferization::createMemCpy(), mlir::bufferization::BufferizationOptions::dynCastBufferizableOp(), mlir::failed(), mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getLoc(), mlir::bufferization::AnalysisState::getOptions(), mlir::detail::IROperandBase::getOwner(), mlir::bufferization::lookupBuffer(), mlir::OpBuilder::setInsertionPoint(), and setInsertionPointAfter().
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), and mlir::bufferization::func_ext::FuncOpInterface::bufferize().
getBufferType()
BaseMemRefType BufferizationState::getBufferType (OpOperand & opOperand) const
Return the buffer type for a given OpOperand (tensor) after bufferization.
Definition at line 345 of file BufferizableOpInterface.cpp.
References mlir::Type::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::bufferization::getMemRefType(), mlir::bufferization::AnalysisState::getOptions(), and mlir::Value::getType().
getOptions()
const BufferizationOptions& mlir::bufferization::BufferizationState::getOptions () const inline
Return a reference to the BufferizationOptions.
Definition at line 458 of file BufferizableOpInterface.h.
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), and mlir::bufferization::bufferizeOp().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h
lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp