MLIR: mlir::sparse_tensor::SparseCompilerOptions Struct Reference
mlir::sparse_tensor::SparseCompilerOptions Struct Reference
Options for the "sparse-compiler" pipeline.
#include "mlir/Dialect/SparseTensor/Pipelines/Passes.h"
Public Member Functions
SparsificationOptions sparsificationOptions () const
Projects out the options for createSparsificationPass.
SparseTensorConversionOptions sparseTensorConversionOptions () const
Projects out the options for createSparsificationPass.
LowerVectorToLLVMOptions lowerVectorToLLVMOptions () const
Projects out the options for createConvertVectorToLLVMPass.
Public Member Functions inherited from mlir::detail::PassOptions
PassOptions ()=default
PassOptions (const PassOptions &)=delete
Delete the copy constructor to avoid copying the internal options map.
PassOptions (PassOptions &&)=delete
void copyOptionValuesFrom (const PassOptions &other)
Copy the option values from 'other' into 'this', where 'other' has the same options as 'this'.
LogicalResult parseFromString (StringRef options)
Parse options out as key=value pairs that can then be handed off to the llvm::cl command line passing infrastructure.
void print (raw_ostream &os)
Print the options held by this struct in a form that can be parsed via 'parseFromString'.
void printHelp (size_t indent, size_t descIndent) const
Print the help string for the options held by this struct.
size_t getOptionWidth () const
Return the maximum width required when printing the help string.
Public Attributes
PassOptions::Option< int32_t > parallelization
PassOptions::Option< int32_t > vectorization
PassOptions::Option< int32_t > vectorLength
PassOptions::Option< bool > enableSIMDIndex32
PassOptions::Option< bool > enableVLAVectorization
PassOptions::Option< int32_t > sparseToSparse
PassOptions::Option< bool > reassociateFPReductions
PassOptions::Option< bool > indexOptimizations
PassOptions::Option< bool > amx
PassOptions::Option< bool > armNeon
PassOptions::Option< bool > armSVE
PassOptions::Option< bool > x86Vector
Additional Inherited Members
Public Types inherited from mlir::detail::PassOptions
template<typename DataType >
using OptionParser = std::conditional_t< std::is_base_of< llvm::cl::generic_parser_base, llvm::cl::parser< DataType > >::value, GenericOptionParser< DataType >, llvm::cl::parser< DataType > >
The specific parser to use depending on llvm::cl parser used.
Static Public Member Functions inherited from mlir::PassPipelineOptions< SparseCompilerOptions >
static std::unique_ptr< SparseCompilerOptions > createFromString (StringRef options)
Factory that parses the provided options and returns a unique_ptr to the struct.
Detailed Description
Options for the "sparse-compiler" pipeline.
So far this only contains a subset of the options that can be set for the underlying passes, because it must be manually kept in sync with the tablegen files for those passes.
Definition at line 30 of file Passes.h.
Member Function Documentation
lowerVectorToLLVMOptions()
LowerVectorToLLVMOptions mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions () const inline
Projects out the options for createConvertVectorToLLVMPass.
Definition at line 97 of file Passes.h.
References mlir::sparse_tensor::buildSparseCompiler(), mlir::LowerVectorToLLVMOptions::enableAMX(), mlir::LowerVectorToLLVMOptions::enableArmNeon(), mlir::LowerVectorToLLVMOptions::enableArmSVE(), mlir::LowerVectorToLLVMOptions::enableIndexOptimizations(), mlir::LowerVectorToLLVMOptions::enableReassociateFPReductions(), mlir::LowerVectorToLLVMOptions::enableX86Vector(), options, and mlir::sparse_tensor::registerSparseTensorPipelines().
Referenced by mlir::sparse_tensor::buildSparseCompiler().
sparseTensorConversionOptions()
SparseTensorConversionOptions mlir::sparse_tensor::SparseCompilerOptions::sparseTensorConversionOptions () const inline
Projects out the options for createSparsificationPass.
Definition at line 62 of file Passes.h.
References mlir::sparseToSparseConversionStrategy().
Referenced by mlir::sparse_tensor::buildSparseCompiler().
sparsificationOptions()
SparsificationOptions mlir::sparse_tensor::SparseCompilerOptions::sparsificationOptions () const inline
Projects out the options for createSparsificationPass.
Definition at line 49 of file Passes.h.
References mlir::sparseParallelizationStrategy(), and mlir::sparseVectorizationStrategy().
Referenced by mlir::sparse_tensor::buildSparseCompiler().
Member Data Documentation
amx
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::amx
Initial value:
{
      *this, "enable-amx",
      desc("Enables the use of AMX dialect while lowering the vector dialect."),
      init(false)}
Definition at line 78 of file Passes.h.
armNeon
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::armNeon
Initial value:
{*this, "enable-arm-neon",
                                    desc("Enables the use of ArmNeon dialect "
                                         "while lowering the vector dialect."),
                                    init(false)}
Definition at line 82 of file Passes.h.
armSVE
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::armSVE
Initial value:
{*this, "enable-arm-sve",
                                   desc("Enables the use of ArmSVE dialect "
                                        "while lowering the vector dialect."),
                                   init(false)}
Definition at line 86 of file Passes.h.
enableSIMDIndex32
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::enableSIMDIndex32
Initial value:
{
      *this, "enable-simd-index32",
      desc("Enable i32 indexing into vectors (for efficiency)"), init(false)}
Definition at line 41 of file Passes.h.
enableVLAVectorization
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::enableVLAVectorization
Initial value:
{
      *this, "enable-vla-vectorization",
      desc("Enable vector length agnostic vectorization"), init(false)}
Definition at line 44 of file Passes.h.
indexOptimizations
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::indexOptimizations
Initial value:
{
      *this, "enable-index-optimizations",
      desc("Allows compiler to assume indices fit in 32-bit if that yields "
           "faster code"),
      init(true)}
Definition at line 73 of file Passes.h.
parallelization
PassOptions::Option<int32_t> mlir::sparse_tensor::SparseCompilerOptions::parallelization
Initial value:
{
      *this, "parallelization-strategy",
      desc("Set the parallelization strategy"), init(0)}
Definition at line 33 of file Passes.h.
reassociateFPReductions
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::reassociateFPReductions
Initial value:
{
      *this, "reassociate-fp-reductions",
      desc("Allows llvm to reassociate floating-point reductions for speed"),
      init(false)}
Definition at line 69 of file Passes.h.
sparseToSparse
PassOptions::Option<int32_t> mlir::sparse_tensor::SparseCompilerOptions::sparseToSparse
Initial value:
{
      *this, "s2s-strategy",
      desc("Set the strategy for sparse-to-sparse conversion"), init(0)}
Definition at line 57 of file Passes.h.
vectorization
PassOptions::Option<int32_t> mlir::sparse_tensor::SparseCompilerOptions::vectorization
Initial value:
{
      *this, "vectorization-strategy", desc("Set the vectorization strategy"),
      init(0)}
Definition at line 36 of file Passes.h.
vectorLength
PassOptions::Option<int32_t> mlir::sparse_tensor::SparseCompilerOptions::vectorLength
Initial value:
{
      *this, "vl", desc("Set the vector length"), init(1)}
Definition at line 39 of file Passes.h.
x86Vector
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::x86Vector
Initial value:
{
      *this, "enable-x86vector",
      desc("Enables the use of X86Vector dialect while lowering the vector "
           "dialect."),
      init(false)}
Definition at line 90 of file Passes.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/SparseTensor/Pipelines/Passes.h