MLIR: HoistingAnalysis Struct Reference
HoistingAnalysis Struct Reference
Analysis class to support tensor::PadOp hoisting across multiple enclosing loops.
Public Member Functions
HoistingAnalysis (tensor::PadOp padOp, int numLoops)
bool isValid ()
SmallVector< Value > getPackedTensorSizes (ImplicitLocOpBuilder &b)
Footprint of the packedTensor, computed from the packingLoops.
Public Attributes
scf::ForOp outermostEnclosingForOp
The outermost loop, determined by nLevels above which padOp will be hoisted.
SetVector< Operation * > backwardSlice
Backward slice rooted at padOp and nested under outermostEnclosingForOp.
SmallVector< scf::ForOp > packingLoops
The scf::ForOp immediately enclosing padOp such that:
Detailed Description
Analysis class to support tensor::PadOp hoisting across multiple enclosing loops.
The failure conditions are:
Pad op has a use that is not an input of a LinalgOp.
Pad op does not have a constant padding value.
There is no immediately enclosing scf::ForOp.
The backward slice from the pad op to the scf::ForOp to hoist above contains an unknown op with non index type operands, a region, or a memory effect.
The backward slice from the pad op to the scf::ForOp to hoist above is empty.
The source tensor of pad op is not defined by an extract slice op.
The source tensor of the extract slice op is not defined outside of the outermost enclosing scf::ForOp.
There is no enclosing scf::ForOp that indexes the padded data. Other cases succeed and will trigger hoisting of the pad op.
Definition at line 56 of file HoistPadding.cpp.
Constructor & Destructor Documentation
HoistingAnalysis()
HoistingAnalysis::HoistingAnalysis (tensor::PadOp padOp, int numLoops)
Definition at line 168 of file HoistPadding.cpp.
References DBGS, mlir::DominanceInfo::dominates(), mlir::failed(), mlir::failure(), getAtMostNEnclosingLoops(), mlir::getBackwardSlice(), mlir::Value::getDefiningOp(), isOnlyUsedAsInputOfLinalgOp(), and mlir::success().
Member Function Documentation
getPackedTensorSizes()
SmallVector< Value > HoistingAnalysis::getPackedTensorSizes (ImplicitLocOpBuilder & b)
Footprint of the packedTensor, computed from the packingLoops.
Definition at line 343 of file HoistPadding.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::ImplicitLocOpBuilder::createOrFold(), mlir::Builder::getContext(), and mlir::linalg::getUpperBoundForIndex().
Referenced by mlir::linalg::hoistPaddingOnTensors().
isValid()
bool HoistingAnalysis::isValid () inline
Definition at line 59 of file HoistPadding.cpp.
Referenced by mlir::linalg::hoistPaddingOnTensors().
Member Data Documentation
backwardSlice
SetVector<Operation *> HoistingAnalysis::backwardSlice
Backward slice rooted at padOp and nested under outermostEnclosingForOp.
Definition at line 70 of file HoistPadding.cpp.
Referenced by mlir::linalg::hoistPaddingOnTensors().
outermostEnclosingForOp
scf::ForOp HoistingAnalysis::outermostEnclosingForOp
The outermost loop, determined by nLevels above which padOp will be hoisted.
Definition at line 66 of file HoistPadding.cpp.
Referenced by mlir::linalg::hoistPaddingOnTensors().
packingLoops
SmallVector<scf::ForOp> HoistingAnalysis::packingLoops
The scf::ForOp immediately enclosing padOp such that:
they are nested under outermostEnclosingForOp (inclusive)
whose induction variable is used, directly or indirectly, in the computation of padOp. The span of these loops determines the footprint of the packed tensor.
Definition at line 77 of file HoistPadding.cpp.
Referenced by mlir::linalg::hoistPaddingOnTensors().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/Transforms/HoistPadding.cpp