MLIR: ConvertAddressOf Struct Reference
ConvertAddressOf Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (spirv::AddressOfOp addressOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Public Member Functions inherited from ConvertAliasResoruce< spirv::AddressOfOp >
ConvertAliasResoruce (const ResourceAliasAnalysis &analysis, MLIRContext *context, PatternBenefit benefit=1)
Additional Inherited Members
Protected Attributes inherited from ConvertAliasResoruce< spirv::AddressOfOp >
const ResourceAliasAnalysis & analysis
Detailed Description
Definition at line 285 of file UnifyAliasedResourcePass.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult ConvertAddressOf::matchAndRewrite (spirv::AddressOfOp addressOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 289 of file UnifyAliasedResourcePass.cpp.
References mlir::SymbolTable::lookupSymbolIn(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/Transforms/UnifyAliasedResourcePass.cpp