MLIR: ConvertAccessChain Struct Reference
ConvertAccessChain Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (spirv::AccessChainOp acOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Public Member Functions inherited from ConvertAliasResoruce< spirv::AccessChainOp >
ConvertAliasResoruce (const ResourceAliasAnalysis &analysis, MLIRContext *context, PatternBenefit benefit=1)
Additional Inherited Members
Protected Attributes inherited from ConvertAliasResoruce< spirv::AccessChainOp >
const ResourceAliasAnalysis & analysis
Detailed Description
Definition at line 301 of file UnifyAliasedResourcePass.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult ConvertAccessChain::matchAndRewrite (spirv::AccessChainOp acOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 305 of file UnifyAliasedResourcePass.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::spirv::SPIRVType::getSizeInBytes(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), mlir::SymbolTable::lookupSymbolIn(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/Transforms/UnifyAliasedResourcePass.cpp