MLIR: mlir::detail::StringAttrStorage Struct Reference
mlir::detail::StringAttrStorage Struct Reference
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::pair< StringRef, Type >
The hash key is a tuple of the parameter types.
Public Member Functions
StringAttrStorage (StringRef value, Type type)
bool operator== (const KeyTy &key) const
void initialize (MLIRContext *context)
Initialize the storage given an MLIRContext.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
::llvm::hash_code hashKey (const KeyTy &key)
static StringAttrStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Define a construction method for creating a new instance of this storage.
Public Attributes
StringRef value
The raw string value.
Dialect * referencedDialect
If the string value contains a dialect namespace prefix (e.g.
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type=nullptr)
Construct a new attribute storage instance with the given type.
void setType (Type newType)
Set the type of this attribute.
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 325 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::StringAttrStorage::KeyTy = std::pair<StringRef, Type>
The hash key is a tuple of the parameter types.
Definition at line 330 of file AttributeDetail.h.
Constructor & Destructor Documentation
StringAttrStorage()
mlir::detail::StringAttrStorage::StringAttrStorage (StringRef value, Type type) inline
Definition at line 326 of file AttributeDetail.h.
Member Function Documentation
construct()
static StringAttrStorage* mlir::detail::StringAttrStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Define a construction method for creating a new instance of this storage.
Definition at line 340 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), and mlir::AttributeStorage::initialize().
hashKey()
::llvm::hash_code mlir::detail::StringAttrStorage::hashKey (const KeyTy & key) inline static
Definition at line 334 of file AttributeDetail.h.
initialize()
void StringAttrStorage::initialize (MLIRContext * context)
Initialize the storage given an MLIRContext.
Definition at line 916 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::dialectReferencingStrAttrs, mlir::MLIRContextImpl::dialectRefStrAttrMutex, mlir::MLIRContextImpl::emptyStringAttr, mlir::MLIRContext::getImpl(), mlir::MLIRContext::getLoadedDialect(), and value.
operator==()
bool mlir::detail::StringAttrStorage::operator== (const KeyTy & key) const inline
Definition at line 331 of file AttributeDetail.h.
References mlir::AttributeStorage::getType(), and value.
Member Data Documentation
referencedDialect
Dialect* mlir::detail::StringAttrStorage::referencedDialect
If the string value contains a dialect namespace prefix (e.g.
dialect.blah), this is the dialect referenced.
Definition at line 353 of file AttributeDetail.h.
Referenced by mlir::MLIRContext::getOrLoadDialect().
value
StringRef mlir::detail::StringAttrStorage::value
The raw string value.
Definition at line 350 of file AttributeDetail.h.
The documentation for this struct was generated from the following files:
lib/IR/AttributeDetail.h
lib/IR/MLIRContext.cpp