MLIR: mlir::linalg::Transformation Struct Reference
mlir::linalg::Transformation Struct Reference abstract
Abstract Transformation class applied in a sequence that also handles state through markers.
#include "mlir/Dialect/Linalg/Transforms/CodegenStrategy.h"
Public Member Functions
Transformation (LinalgTransformationFilter::FilterFunction f)
virtual ~Transformation ()=default
virtual void addToPassPipeline (OpPassManager &pm, LinalgTransformationFilter m) const =0
Public Attributes
LinalgTransformationFilter::FilterFunction filter = nullptr
Detailed Description
Abstract Transformation class applied in a sequence that also handles state through markers.
Definition at line 24 of file CodegenStrategy.h.
Constructor & Destructor Documentation
Transformation()
mlir::linalg::Transformation::Transformation (LinalgTransformationFilter::FilterFunction f) inline explicit
Definition at line 25 of file CodegenStrategy.h.
References addToPassPipeline(), and ~Transformation().
~Transformation()
virtual mlir::linalg::Transformation::~Transformation () virtual default
Referenced by Transformation().
Member Function Documentation
addToPassPipeline()
virtual void mlir::linalg::Transformation::addToPassPipeline (OpPassManager & pm, LinalgTransformationFilter m) const pure virtual
Implemented in mlir::linalg::VectorLowering, mlir::linalg::Vectorize, mlir::linalg::Decompose, mlir::linalg::Interchange, mlir::linalg::Generalize, mlir::linalg::Promote, mlir::linalg::Pad, mlir::linalg::Tile, and mlir::linalg::TileAndFuse.
Referenced by Transformation().
Member Data Documentation
filter
LinalgTransformationFilter::FilterFunction mlir::linalg::Transformation::filter = nullptr
Definition at line 30 of file CodegenStrategy.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Transforms/CodegenStrategy.h