MLIR: JamBlockGatherer Struct Reference
JamBlockGatherer Struct Reference
Public Member Functions
void walk (Operation *op)
void walk (Block &block)
Public Attributes
std::vector< std::pair< Block::iterator, Block::iterator > > subBlocks
Detailed Description
Definition at line 1177 of file LoopUtils.cpp.
Member Function Documentation
walk() [1/2]
void JamBlockGatherer::walk (Operation * op) inline
Definition at line 1182 of file LoopUtils.cpp.
References mlir::Operation::getRegions(), and mlir::detail::walk().
Referenced by mlir::loopUnrollJamByFactor().
walk() [2/2]
void JamBlockGatherer::walk (Block & block) inline
Definition at line 1188 of file LoopUtils.cpp.
References mlir::Block::begin(), mlir::Block::end(), and mlir::detail::walk().
Member Data Documentation
subBlocks
std::vector<std::pair<Block::iterator, Block::iterator> > JamBlockGatherer::subBlocks
Definition at line 1179 of file LoopUtils.cpp.
Referenced by mlir::loopUnrollJamByFactor().
The documentation for this struct was generated from the following file:
lib/Dialect/Affine/Utils/LoopUtils.cpp