MLIR: mlir::linalg::LinalgTransformationFilter Struct Reference
mlir::linalg::LinalgTransformationFilter Struct Reference
Helper class to control application of linalg transformation patterns.
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Types
using FilterFunction = std::function< LogicalResult(Operation *)>
Public Member Functions
LinalgTransformationFilter (ArrayRef< StringAttr > matchDisjunction={}, Optional< StringAttr > replacement=None)
LinalgTransformationFilter (const FilterFunction &f, ArrayRef< StringAttr > matchDisjunction={}, Optional< StringAttr > replacement=None)
LinalgTransformationFilter (LinalgTransformationFilter &&)=default
LinalgTransformationFilter (const LinalgTransformationFilter &)=default
LogicalResult checkAndNotify (PatternRewriter &rewriter, Operation *op) const
void replaceLinalgTransformationFilter (PatternRewriter &rewriter, Operation *op) const
bool hasReplacementFilter (Operation *op) const
LinalgTransformationFilter & addFilter (const FilterFunction &f)
template<typename... OpTypes>
LinalgTransformationFilter & addOpFilter ()
LinalgTransformationFilter & addOpNameFilter (StringRef opName)
LinalgTransformationFilter & setMatchByDefault ()
Detailed Description
Helper class to control application of linalg transformation patterns.
Control comes in 2 forms:
attribute matching and setting behavior using the attribute named kLinalgTransformMarker. This can be used to build a state machine using attributes and incrementally applying patterns to advance states.
filter function, which is a simple lambda on the Operation* that returns a LogicalResult.
Definition at line 382 of file Transforms.h.
Member Typedef Documentation
FilterFunction
using mlir::linalg::LinalgTransformationFilter::FilterFunction = std::function<LogicalResult(Operation *)>
Definition at line 383 of file Transforms.h.
Constructor & Destructor Documentation
LinalgTransformationFilter() [1/4]
mlir::linalg::LinalgTransformationFilter::LinalgTransformationFilter (ArrayRef< StringAttr > matchDisjunction = {}, Optional< StringAttr > replacement = None) explicit
Definition at line 54 of file Transforms.cpp.
LinalgTransformationFilter() [2/4]
mlir::linalg::LinalgTransformationFilter::LinalgTransformationFilter (const FilterFunction & f, ArrayRef< StringAttr > matchDisjunction = {}, Optional< StringAttr > replacement = None) explicit
Definition at line 59 of file Transforms.cpp.
LinalgTransformationFilter() [3/4]
mlir::linalg::LinalgTransformationFilter::LinalgTransformationFilter (LinalgTransformationFilter &&) default
LinalgTransformationFilter() [4/4]
mlir::linalg::LinalgTransformationFilter::LinalgTransformationFilter (const LinalgTransformationFilter &) default
Member Function Documentation
addFilter()
LinalgTransformationFilter& mlir::linalg::LinalgTransformationFilter::addFilter (const FilterFunction & f) inline
Definition at line 400 of file Transforms.h.
addOpFilter()
template<typename... OpTypes> LinalgTransformationFilter& mlir::linalg::LinalgTransformationFilter::addOpFilter () inline
Definition at line 407 of file Transforms.h.
References mlir::success().
addOpNameFilter()
LinalgTransformationFilter& mlir::linalg::LinalgTransformationFilter::addOpNameFilter (StringRef opName) inline
Definition at line 412 of file Transforms.h.
References mlir::Operation::getName(), mlir::OperationName::getStringRef(), and mlir::success().
checkAndNotify()
LogicalResult mlir::linalg::LinalgTransformationFilter::checkAndNotify (PatternRewriter & rewriter, Operation * op) const
Definition at line 69 of file Transforms.cpp.
References diag(), mlir::failed(), mlir::failure(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::RewriterBase::notifyMatchFailure(), replaceLinalgTransformationFilter(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::linalg::LinalgVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgTilingPattern::returningMatchAndRewrite(), mlir::linalg::LinalgPaddingPattern::returningMatchAndRewrite(), mlir::linalg::LinalgTileAndFuseTensorOpsPattern::returningMatchAndRewrite(), mlir::linalg::GenericOpInterchangePattern::returningMatchAndRewrite(), mlir::linalg::LinalgGeneralizationPattern::returningMatchAndRewrite(), and mlir::linalg::splitReduction().
hasReplacementFilter()
bool mlir::linalg::LinalgTransformationFilter::hasReplacementFilter (Operation * op) const
Definition at line 113 of file Transforms.cpp.
References mlir::Attribute::dyn_cast(), mlir::Operation::getAttr(), and mlir::linalg::LinalgTransforms::kLinalgTransformMarker.
replaceLinalgTransformationFilter()
void mlir::linalg::LinalgTransformationFilter::replaceLinalgTransformationFilter (PatternRewriter & rewriter, Operation * op) const
Definition at line 103 of file Transforms.cpp.
References mlir::Builder::getStringAttr(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by checkAndNotify(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::linalg::LinalgPaddingPattern::returningMatchAndRewrite(), mlir::linalg::LinalgTileAndFuseTensorOpsPattern::returningMatchAndRewrite(), mlir::linalg::GenericOpInterchangePattern::returningMatchAndRewrite(), mlir::linalg::LinalgGeneralizationPattern::returningMatchAndRewrite(), and mlir::linalg::splitReduction().
setMatchByDefault()
LinalgTransformationFilter& mlir::linalg::LinalgTransformationFilter::setMatchByDefault () inline
Definition at line 418 of file Transforms.h.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Transforms.cpp