MLIR: mlir::linalg::CodegenStrategy Struct Reference
mlir::linalg::CodegenStrategy Struct Reference
Codegen strategy controls how a Linalg op is progressively lowered.
#include "mlir/Dialect/Linalg/Transforms/CodegenStrategy.h"
Public Member Functions
CodegenStrategy & tileAndFuse (StringRef opName, const LinalgTilingAndFusionOptions &options, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to tile the Op opName and fuse its producers with tiling and fusion options.
CodegenStrategy & tileAndFuseIf (bool b, StringRef opName, LinalgTilingAndFusionOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to tile the Op opName and fuse its producers with tiling and fusion options.
CodegenStrategy & tile (StringRef opName, const linalg::LinalgTilingOptions &options, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to add a level of tiling for Op opName with tiling options.
CodegenStrategy & tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
CodegenStrategy & pad (StringRef opName, const linalg::LinalgPaddingOptions &options, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to pad and hoist the operands of Op opName with padding options.
CodegenStrategy & padIf (bool b, StringRef opName, linalg::LinalgPaddingOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to pad and hoist the operands of Op opName with padding options.
CodegenStrategy & promote (StringRef opName, const linalg::LinalgPromotionOptions &options, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
CodegenStrategy & promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
CodegenStrategy & generalize (StringRef opName, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to generalize named operations.
CodegenStrategy & generalizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to generalize named operations.
CodegenStrategy & interchange (ArrayRef< int64_t > iteratorInterchange, const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append a pattern to interchange iterators.
CodegenStrategy & interchangeIf (bool b, ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to interchange iterators.
CodegenStrategy & decompose (const LinalgTransformationFilter::FilterFunction &f=nullptr)
Append patterns to decompose convolutions.
CodegenStrategy & decomposeIf (bool b, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append patterns to decompose convolutions.
CodegenStrategy & vectorize (StringRef opName, const LinalgTransformationFilter::FilterFunction &f=nullptr, bool vectorizePadding=false)
Append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & vectorizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr, bool vectorizePadding=false)
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & vectorLowering (LinalgVectorLoweringOptions options)
Append a pattern to lower all vector operations.
CodegenStrategy & setVectorTransferToSCFOptions (LinalgEnablingOptions options)
Configure the post staged-patterns global enabling passes options.
void configurePassPipeline (OpPassManager &pm, MLIRContext *context, bool addEnablePass=true) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Detailed Description
Codegen strategy controls how a Linalg op is progressively lowered.
Definition at line 187 of file CodegenStrategy.h.
Member Function Documentation
configurePassPipeline()
void mlir::linalg::CodegenStrategy::configurePassPipeline (OpPassManager & pm, MLIRContext * context, bool addEnablePass = true) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Definition at line 29 of file CodegenStrategy.cpp.
References mlir::OpPassManager::addPass(), mlir::createLinalgStrategyEnablePass(), and mlir::createLinalgStrategyRemoveMarkersPass().
decompose()
CodegenStrategy& mlir::linalg::CodegenStrategy::decompose (const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append patterns to decompose convolutions.
Definition at line 282 of file CodegenStrategy.h.
decomposeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::decomposeIf (bool b, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append patterns to decompose convolutions.
Definition at line 288 of file CodegenStrategy.h.
generalize()
CodegenStrategy& mlir::linalg::CodegenStrategy::generalize (StringRef opName, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to generalize named operations.
Definition at line 254 of file CodegenStrategy.h.
generalizeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::generalizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to generalize named operations.
Definition at line 262 of file CodegenStrategy.h.
interchange()
CodegenStrategy& mlir::linalg::CodegenStrategy::interchange (ArrayRef< int64_t > iteratorInterchange, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to interchange iterators.
Definition at line 268 of file CodegenStrategy.h.
interchangeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::interchangeIf (bool b, ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to interchange iterators.
Definition at line 276 of file CodegenStrategy.h.
pad()
CodegenStrategy& mlir::linalg::CodegenStrategy::pad (StringRef opName, const linalg::LinalgPaddingOptions & options, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to pad and hoist the operands of Op opName with padding options.
Definition at line 223 of file CodegenStrategy.h.
padIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::padIf (bool b, StringRef opName, linalg::LinalgPaddingOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to pad and hoist the operands of Op opName with padding options.
Definition at line 232 of file CodegenStrategy.h.
promote()
CodegenStrategy& mlir::linalg::CodegenStrategy::promote (StringRef opName, const linalg::LinalgPromotionOptions & options, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 239 of file CodegenStrategy.h.
promoteIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 248 of file CodegenStrategy.h.
setVectorTransferToSCFOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransferToSCFOptions (LinalgEnablingOptions options) inline
Configure the post staged-patterns global enabling passes options.
Definition at line 316 of file CodegenStrategy.h.
References options.
tile()
CodegenStrategy& mlir::linalg::CodegenStrategy::tile (StringRef opName, const linalg::LinalgTilingOptions & options, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to add a level of tiling for Op opName with tiling options.
Definition at line 207 of file CodegenStrategy.h.
tileAndFuse()
CodegenStrategy& mlir::linalg::CodegenStrategy::tileAndFuse (StringRef opName, const LinalgTilingAndFusionOptions & options, const LinalgTransformationFilter::FilterFunction & f = nullptr) inline
Append a pattern to tile the Op opName and fuse its producers with tiling and fusion options.
Definition at line 191 of file CodegenStrategy.h.
tileAndFuseIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::tileAndFuseIf (bool b, StringRef opName, LinalgTilingAndFusionOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to tile the Op opName and fuse its producers with tiling and fusion options.
Definition at line 200 of file CodegenStrategy.h.
tileIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 216 of file CodegenStrategy.h.
References mlir::tile().
vectorize()
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorize (StringRef opName, const LinalgTransformationFilter::FilterFunction & f = nullptr, bool vectorizePadding = false) inline
Append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 293 of file CodegenStrategy.h.
vectorizeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr, bool vectorizePadding = false) inline
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 303 of file CodegenStrategy.h.
References mlir::linalg::vectorize().
vectorLowering()
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorLowering (LinalgVectorLoweringOptions options) inline
Append a pattern to lower all vector operations.
Definition at line 309 of file CodegenStrategy.h.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/CodegenStrategy.h
lib/Dialect/Linalg/Transforms/CodegenStrategy.cpp