MLIR: lib/Dialect/Tensor/IR/TensorOps.cpp File Reference
TensorOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Arithmetic/Utils/Utils.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributeInterfaces.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "mlir/Dialect/Tensor/IR/TensorOps.cpp.inc"
Classes
struct SliceReturnTypeCanonicalizer
Return the canonical type of the result of an extract_slice op.
struct SliceCanonicalizer
A canonicalizer wrapper to replace ExtractSliceOps.
Macros
#define GET_OP_CLASSES
Functions
static TensorType joinShapes (TensorType one, TensorType two)
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
static int64_t getNumElements (ShapedType type)
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation)
Compute the RankedTensorType obtained by applying reassociation to type.
template<typename TensorReshapeOp , bool isExpansion = std::is_same< TensorReshapeOp, ExpandShapeOp>::value>
static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType)
template<typename OpTy >
static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType)
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Infer the canonical type of the result of an extract_slice op.
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType)
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp)
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
static SliceVerificationResult verifyInsertSliceOp (ShapedType srcType, ShapedType dstType, ArrayAttr staticOffsets, ArrayAttr staticSizes, ArrayAttr staticStrides, ShapedType *expectedType=nullptr)
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp)
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
void printInferType (OpAsmPrinter &printer, Operation *op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
ParseResult parseInferType (OpAsmParser &parser, Optional< OpAsmParser::UnresolvedOperand > optOperand, Type &typeToInfer, Type typeToInferFrom)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2148 of file TensorOps.cpp.
Function Documentation
computeTensorReshapeCollapsedType()
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation) static
Compute the RankedTensorType obtained by applying reassociation to type.
Definition at line 762 of file TensorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::Builder::getContext(), mlir::getReassociationAttrName(), mlir::getReassociationIndicesAttribute(), mlir::getSymbolLessAffineMaps(), mlir::Value::getType(), mlir::isReassociationValid(), and value.
Referenced by verifyTensorReshapeOp().
foldExtractAfterInsertSlice()
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp) static
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
Definition at line 1357 of file TensorOps.cpp.
References foldIdentityOffsetSizeAndStrideOpInterface(), mlir::Value::getDefiningOp(), and mlir::succeeded().
foldIdentityOffsetSizeAndStrideOpInterface()
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType) static
Definition at line 1335 of file TensorOps.cpp.
References mlir::failure(), mlir::getConstantIntValue(), and mlir::success().
Referenced by foldExtractAfterInsertSlice(), and foldInsertAfterInsertSlice().
foldInsertAfterInsertSlice()
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp) static
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
Example:
%0 = tensor.insert_slice %slice0 into %input[0, 0] [64, 64] [1, 1]
%1 = tensor.insert_slice %slice1 into %0[0, 0] [64, 64] [1, 1]
folds into:
%1 = tensor.insert_slice %slice1 into %input[0, 0] [64, 64] [1, 1]
Definition at line 1482 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::tensor::canFoldIntoConsumerOp(), mlir::canonicalizeSubViewPart(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::failure(), foldIdentityOffsetSizeAndStrideOpInterface(), mlir::getConstantIntValue(), mlir::Value::getType(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::tensor::preservesStaticInformation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), mlir::success(), mlir::Success, and verifyInsertSliceOp().
getCanonicalSliceResultType()
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Infer the canonical type of the result of an extract_slice op.
Returns a type with rank resultRank that is either the rank of the rank-reduced type, or the non-rank-reduced type.
Definition at line 1068 of file TensorOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Location::cast(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::getConstantIntValue(), mlir::getMixedSizes(), mlir::DenseElementsAttr::isSplat(), mlir::m_Constant(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by SliceReturnTypeCanonicalizer::operator()().
getNumElements()
static int64_t getNumElements (ShapedType type) static
Definition at line 704 of file TensorOps.cpp.
References mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::Type::dyn_cast(), mlir::TensorType::getElementType(), mlir::getSymbolLessAffineMaps(), mlir::Value::getType(), mlir::success(), and mlir::verify().
Referenced by mlir::DenseElementsAttr::complex_float_value_end(), mlir::DenseElementsAttr::complex_value_end(), computeMemRefRankReductionMask(), convertStructType(), mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyAffineMap::createFromCapsule(), mlir::DenseIntElementsAttr::end(), extractVector(), mlir::spirv::CompositeType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getElementTypes(), getFirstIntValue(), mlir::Sliceable< Derived, ElementTy >::getItem(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::StructType::getMemberOffset(), getPushConstantVariable(), mlir::spirv::ArrayType::getSizeInBytes(), mlir::DenseElementsAttr::getValues(), hasOneBranchOpTo(), isDefinedByCallTo(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlirElementsAttrGetNumElements(), mlir::spirv::StructType::MemberDecorationInfo::operator<(), mlir::AffineDmaStartOp::print(), mlir::AffineDmaWaitOp::print(), mlir::DenseElementsAttr::raw_int_end(), mlir::DenseElementsAttr::size(), mlir::DenseElementsAttr::value_end(), verifyCoopMatrixMulAdd(), and mlir::python::PySymbolTable::walkSymbolTables().
joinShapes()
static TensorType joinShapes (TensorType one, TensorType two) static
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
The element types need to match.
Definition at line 161 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::Region::end(), mlir::failure(), mlir::tensor::foldTensorCast(), mlir::DenseElementsAttr::get(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), mlir::TensorType::getElementType(), mlir::getElementTypeOrSelf(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::Operation::getResult(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::TensorType::hasRank(), mlir::RewriterBase::inlineRegionBefore(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::OperationState::location, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::m_ConstantInt(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::OperationState::regions, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), mlir::success(), mlir::verify(), mlir::Block::without_terminator(), and mlir::wouldOpBeTriviallyDead().
parseInferType()
ParseResult parseInferType (OpAsmParser & parser, Optional< OpAsmParser::UnresolvedOperand > optOperand, Type & typeToInfer, Type typeToInferFrom)
Definition at line 1716 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::tensor::canFoldIntoConsumerOp(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::dispatchIndexOpFoldResults(), mlir::emitError(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::Block::front(), mlir::DenseElementsAttr::get(), mlir::Block::getArgumentTypes(), mlir::getConstantIntValue(), getElementType(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexAttr(), mlir::Block::getNumArguments(), mlir::Value::getParentBlock(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Builder::getUnitAttr(), mlir::RewriterBase::inlineRegionBefore(), mlir::Type::isa(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::notifyMatchFailure(), mlir::tensor::preservesStaticInformation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::RewriterBase::updateRootInPlace(), and mlir::verify().
printInferType()
void printInferType (OpAsmPrinter & printer, Operation * op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
Definition at line 1713 of file TensorOps.cpp.
produceSliceErrorMsg()
template<typename OpTy > static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType) static
Definition at line 1035 of file TensorOps.cpp.
References mlir::Type::cast(), mlir::ElemTypeMismatch, mlir::getMixedOffsets(), mlir::getMixedSizes(), mlir::getMixedStrides(), mlir::isRankReducedType(), mlir::RankTooLarge, mlir::SizeMismatch, mlir::success(), mlir::Success, and mlir::verify().
Referenced by verifyInsertSliceOp().
verifyInsertSliceOp()
static SliceVerificationResult verifyInsertSliceOp (ShapedType srcType, ShapedType dstType, ArrayAttr staticOffsets, ArrayAttr staticSizes, ArrayAttr staticStrides, ShapedType * expectedType = nullptr) static
Definition at line 1442 of file TensorOps.cpp.
References mlir::extractFromI64ArrayAttr(), mlir::isRankReducedType(), produceSliceErrorMsg(), and mlir::verify().
Referenced by foldInsertAfterInsertSlice().
verifyTensorReshapeOp()
template<typename TensorReshapeOp , bool isExpansion = std::is_same< TensorReshapeOp, ExpandShapeOp>::value> static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType) static
Definition at line 802 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::Type::cast(), computeTensorReshapeCollapsedType(), mlir::dispatchIndexOpFoldResults(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::Builder::getI64ArrayAttr(), mlir::getPositionsOfShapeOne(), mlir::DenseElementsAttr::getRawData(), mlir::Value::getType(), mlir::DenseElementsAttr::isSplat(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::verify(), and mlir::verifyReshapeLikeTypes().