MLIR: lib/Target/Cpp/TranslateToCpp.cpp File Reference
TranslateToCpp.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/IndentedOstream.h"
#include "mlir/Target/Cpp/CppEmitter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include <utility>
Macros
#define DEBUG_TYPE "translate-to-cpp"
Functions
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Convenience functions to produce interleaved output with functions returning a LogicalResult.
template<typename Container , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (const Container &c, UnaryFunctor eachFn, NullaryFunctor betweenFn)
template<typename Container , typename UnaryFunctor >
LogicalResult interleaveCommaWithError (const Container &c, raw_ostream &os, UnaryFunctor eachFn)
static LogicalResult printConstantOp (CppEmitter &emitter, Operation *operation, Attribute value)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::VariableOp variableOp)
static LogicalResult printOperation (CppEmitter &emitter, arith::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, func::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::BranchOp branchOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::CondBranchOp condBranchOp)
static LogicalResult printOperation (CppEmitter &emitter, func::CallOp callOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CallOp callOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ApplyOp applyOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CastOp castOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::IncludeOp includeOp)
static LogicalResult printOperation (CppEmitter &emitter, scf::ForOp forOp)
static LogicalResult printOperation (CppEmitter &emitter, scf::IfOp ifOp)
static LogicalResult printOperation (CppEmitter &emitter, scf::YieldOp yieldOp)
static LogicalResult printOperation (CppEmitter &emitter, func::ReturnOp returnOp)
static LogicalResult printOperation (CppEmitter &emitter, ModuleOp moduleOp)
static LogicalResult printOperation (CppEmitter &emitter, func::FuncOp functionOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "translate-to-cpp"
Definition at line 28 of file TranslateToCpp.cpp.
Function Documentation
interleaveCommaWithError()
template<typename Container , typename UnaryFunctor > LogicalResult interleaveCommaWithError (const Container & c, raw_ostream & os, UnaryFunctor eachFn) inline
Definition at line 63 of file TranslateToCpp.cpp.
References interleaveWithError().
Referenced by printOperation().
interleaveWithError() [1/2]
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline
Convenience functions to produce interleaved output with functions returning a LogicalResult.
This is different than those in STLExtras as functions used on each element doesn't return a string.
Definition at line 40 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by interleaveCommaWithError(), interleaveWithError(), and printOperation().
interleaveWithError() [2/2]
template<typename Container , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (const Container & c, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline
Definition at line 56 of file TranslateToCpp.cpp.
References interleaveWithError().
printConstantOp()
static LogicalResult printConstantOp (CppEmitter & emitter, Operation * operation, Attribute value) static
Definition at line 185 of file TranslateToCpp.cpp.
References mlir::Attribute::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::success(), and value.
Referenced by printOperation().
printOperation() [1/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::ConstantOp constantOp) static
Definition at line 217 of file TranslateToCpp.cpp.
References printConstantOp(), and value.
Referenced by mlir::AsmPrinter::Impl::printIntegerSet(), and printOperation().
printOperation() [2/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::VariableOp variableOp) static
Definition at line 225 of file TranslateToCpp.cpp.
References printConstantOp(), and value.
printOperation() [3/17]
static LogicalResult printOperation (CppEmitter & emitter, arith::ConstantOp constantOp) static
Definition at line 233 of file TranslateToCpp.cpp.
References printConstantOp(), and value.
printOperation() [4/17]
static LogicalResult printOperation (CppEmitter & emitter, func::ConstantOp constantOp) static
Definition at line 241 of file TranslateToCpp.cpp.
References printConstantOp(), and value.
printOperation() [5/17]
static LogicalResult printOperation (CppEmitter & emitter, cf::BranchOp branchOp) static
Definition at line 249 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::Block::getSuccessor(), and mlir::success().
printOperation() [6/17]
static LogicalResult printOperation (CppEmitter & emitter, cf::CondBranchOp condBranchOp) static
Definition at line 269 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [7/17]
static LogicalResult printOperation (CppEmitter & emitter, func::CallOp callOp) static
Definition at line 315 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [8/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::CallOp callOp) static
Definition at line 327 of file TranslateToCpp.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), interleaveCommaWithError(), and mlir::success().
printOperation() [9/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::ApplyOp applyOp) static
Definition at line 373 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [10/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::CastOp castOp) static
Definition at line 386 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::success().
printOperation() [11/17]
static LogicalResult printOperation (CppEmitter & emitter, emitc::IncludeOp includeOp) static
Definition at line 401 of file TranslateToCpp.cpp.
References mlir::success().
printOperation() [12/17]
static LogicalResult printOperation (CppEmitter & emitter, scf::ForOp forOp) static
Definition at line 414 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::Region::getBlocks(), mlir::Operation::getOperands(), mlir::Region::getOps(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [13/17]
static LogicalResult printOperation (CppEmitter & emitter, scf::IfOp ifOp) static
Definition at line 492 of file TranslateToCpp.cpp.
References mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::Region::getOps(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [14/17]
static LogicalResult printOperation (CppEmitter & emitter, scf::YieldOp yieldOp) static
Definition at line 537 of file TranslateToCpp.cpp.
References mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getNumResults(), mlir::Operation::getParentOp(), mlir::Operation::getResults(), interleaveWithError(), and mlir::success().
printOperation() [15/17]
static LogicalResult printOperation (CppEmitter & emitter, func::ReturnOp returnOp) static
Definition at line 564 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [16/17]
static LogicalResult printOperation (CppEmitter & emitter, ModuleOp moduleOp) static
Definition at line 583 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [17/17]
static LogicalResult printOperation (CppEmitter & emitter, func::FuncOp functionOp) static
Definition at line 593 of file TranslateToCpp.cpp.
References mlir::WalkResult::advance(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Value::getDefiningOp(), getElementType(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::OpResult::getOwner(), mlir::Block::getParentOp(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::raw_indented_ostream::indent(), interleaveCommaWithError(), mlir::PreOrder, printOperation(), mlir::quant::QuantizationFlags::Signed, mlir::success(), mlir::raw_indented_ostream::unindent(), and mlir::WalkResult::wasInterrupted().