MLIR: lib/Dialect/Transform/IR/TransformOps.cpp File Reference
TransformOps.cpp File Reference
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Rewrite/PatternApplicator.h"
#include "llvm/ADT/ScopeExit.h"
#include "mlir/Dialect/Transform/IR/TransformOps.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static bool isValueUsePotentialConsumer (OpOperand &use)
Returns true if the given op operand may be consuming the handle value in the Transform IR.
LogicalResult checkDoubleConsume (Value value, function_ref< InFlightDiagnostic()> reportError)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 22 of file TransformOps.cpp.
Function Documentation
checkDoubleConsume()
LogicalResult checkDoubleConsume (Value value, function_ref< InFlightDiagnostic()> reportError)
Definition at line 184 of file TransformOps.cpp.
References mlir::transform::TransformState::addExtension(), mlir::transform::TransformState::applyTransform(), mlir::InFlightDiagnostic::attachNote(), diag(), mlir::failed(), mlir::failure(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::Operation::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::Block::getOperations(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getUses(), isValueUsePotentialConsumer(), mlir::transform::TransformState::make_region_scope(), mlir::transform::TransformState::removeExtension(), mlir::success(), and mlir::verify().
isValueUsePotentialConsumer()
static bool isValueUsePotentialConsumer (OpOperand & use) static
Returns true if the given op operand may be consuming the handle value in the Transform IR.
That is, if it may have a Free effect on it.
Definition at line 169 of file TransformOps.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::SideEffects::EffectInstance< EffectT >::getEffect(), mlir::detail::IROperandBase::getOwner(), and mlir::SideEffects::EffectInstance< EffectT >::getResource().
Referenced by checkDoubleConsume().