MLIR: lib/Dialect/Vector/Transforms/VectorUnrollDistribute.cpp File Reference
VectorUnrollDistribute.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Interfaces/VectorInterfaces.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "vector-unrolling"
Functions
static SmallVector< int64_t, 4 > getVectorOffset (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, int64_t index)
During unrolling from originalShape to targetShape return the offset for the slice index.
static SmallVector< Value > sliceTransferIndices (int64_t index, ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, ArrayRef< Value > indices, AffineMap permutationMap, Location loc, OpBuilder &builder)
Compute the indices of the slice index for a tranfer op.
static Operation * cloneOpWithOperandsAndTypes (OpBuilder &builder, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
static Optional< SmallVector< int64_t, 4 > > getTargetShape (const vector::UnrollVectorOptions &options, Operation *op)
Return the target shape for unrolling for the given op.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-unrolling"
Definition at line 21 of file VectorUnrollDistribute.cpp.
Function Documentation
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (OpBuilder & builder, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 69 of file VectorUnrollDistribute.cpp.
References mlir::OpBuilder::create(), mlir::Operation::getAttrs(), mlir::OperationName::getIdentifier(), and mlir::Operation::getName().
getTargetShape()
static Optional<SmallVector<int64_t, 4> > getTargetShape (const vector::UnrollVectorOptions & options, Operation * op) static
Return the target shape for unrolling for the given op.
Return llvm::None if the op shouldn't be or cannot be unrolled.
Definition at line 80 of file VectorUnrollDistribute.cpp.
References mlir::computeMaxLinearIndex(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::vector::UnrollVectorOptions::filterConstraint, mlir::Operation::getResult(), getVectorOffset(), mlir::Builder::getZeroAttr(), mlir::vector::UnrollVectorOptions::nativeShape, mlir::vector::None, options, mlir::RewriterBase::replaceOp(), mlir::shapeRatio(), sliceTransferIndices(), and mlir::success().
getVectorOffset()
static SmallVector<int64_t, 4> getVectorOffset (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, int64_t index) static
During unrolling from originalShape to targetShape return the offset for the slice index.
Definition at line 28 of file VectorUnrollDistribute.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeStrides(), and mlir::delinearize().
Referenced by getTargetShape(), and sliceTransferIndices().
sliceTransferIndices()
static SmallVector<Value> sliceTransferIndices (int64_t index, ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, ArrayRef< Value > indices, AffineMap permutationMap, Location loc, OpBuilder & builder) static
Compute the indices of the slice index for a tranfer op.
Definition at line 41 of file VectorUnrollDistribute.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getResults(), and getVectorOffset().
Referenced by getTargetShape().