MLIR: lib/Transforms/ViewOpGraph.cpp File Reference
ViewOpGraph.cpp File Reference
#include "mlir/Transforms/ViewOpGraph.h"
#include "PassDetail.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/IndentedOstream.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/GraphWriter.h"
#include <utility>
Typedefs
using AttributeMap = llvm::StringMap< std::string >
Functions
static int64_t getLargeAttributeSizeLimit ()
Return the size limits for eliding large attributes.
static std::string strFromOs (function_ref< void(raw_ostream &)> func)
Return all values printed onto a stream as a string.
static std::string escapeString (std::string str)
Escape special characters such as '
' and quotation marks.
static std::string quoteString (const std::string &str)
Put quotation marks around a given string.
static void llvmViewGraph (Region &region, const Twine &name)
Generate a CFG for a region and show it in a window.
Variables
static const StringRef kLineStyleControlFlow = "dashed"
static const StringRef kLineStyleDataFlow = "solid"
static const StringRef kShapeNode = "ellipse"
static const StringRef kShapeNone = "plain"
Typedef Documentation
AttributeMap
using AttributeMap = llvm::StringMap<std::string>
Definition at line 52 of file ViewOpGraph.cpp.
Function Documentation
escapeString()
static std::string escapeString (std::string str) static
Escape special characters such as '
' and quotation marks.
Definition at line 43 of file ViewOpGraph.cpp.
References strFromOs().
getLargeAttributeSizeLimit()
static int64_t getLargeAttributeSizeLimit () static
Return the size limits for eliding large attributes.
Definition at line 27 of file ViewOpGraph.cpp.
llvmViewGraph()
static void llvmViewGraph (Region & region, const Twine & name) static
Generate a CFG for a region and show it in a window.
Definition at line 323 of file ViewOpGraph.cpp.
Referenced by mlir::Region::viewGraph().
quoteString()
static std::string quoteString (const std::string & str) static
Put quotation marks around a given string.
Definition at line 48 of file ViewOpGraph.cpp.
strFromOs()
static std::string strFromOs (function_ref< void(raw_ostream &)> func) static
Return all values printed onto a stream as a string.
Definition at line 35 of file ViewOpGraph.cpp.
Referenced by escapeString().
Variable Documentation
kLineStyleControlFlow
const StringRef kLineStyleControlFlow = "dashed" static
Definition at line 21 of file ViewOpGraph.cpp.
kLineStyleDataFlow
const StringRef kLineStyleDataFlow = "solid" static
Definition at line 22 of file ViewOpGraph.cpp.
kShapeNode
const StringRef kShapeNode = "ellipse" static
Definition at line 23 of file ViewOpGraph.cpp.
kShapeNone
const StringRef kShapeNone = "plain" static
Definition at line 24 of file ViewOpGraph.cpp.